### ISSUE TITLE
tests: tests/drivers/counter/maxim_ds3231_api : build failure with driver

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#79868]
**Describe the bug**

drivers/counter/maxim_ds3231.c has code issue.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?
 - frdm_k64f
 - What have you tried to diagnose or workaround this issue?
 - git bisect
 - Is this a regression? If yes, have you been able to "git bisect" it to a
   specific commit?
 - this happens when tool chain upgrade to latest 0.16.9-rc2 and above

**To Reproduce**

scripts/twister -p frdm_k64f -T tests/drivers/counter/maxim_ds3231_api  --build-only

**Expected behavior**

build pass

**Impact**

maxim_ds3231

**Logs and console output**

```
/home/jenkins/agent/workspace/zephyr_downstrem_build_daily/zephyr/drivers/counter/maxim_ds3231.c: In function 'encode_alarm':
/home/jenkins/agent/workspace/zephyr_downstrem_build_daily/zephyr/drivers/counter/maxim_ds3231.c:379:15: error: implicit declaration of function 'gmtime_r'; did you mean 'gmtime'? [-Werror=implicit-function-declaration]
  379 |         (void)gmtime_r(&time, &tm);
      |               ^~~~~~~~
      |               gmtime
cc1: all warnings being treated as errors
ninja: build stopped: subcommand failed.

INFO    - /home/jenkins/agent/workspace/zephyr_downstrem_build_daily/zephyr/twister-out/frdm_k64f/tests/drivers/counter/maxim_ds3231_api/drivers.counter.maxim_ds3231/build.log
INFO    - 3130 test scenarios (2925 test instances) selected, 2004 configurations skipped (1849 by static filter, 155 at runtime).
```

**Environment (please complete the following information):**

 - OS: (e.g. Linux, )
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used: v3.7.0-4463-g03959a20f783

**Comment by dkalowsk** [comment]
@stephanosio FYI this may be a toolchain issue, raising to your attention as well.

**Comment by stephanosio** [comment]
This was fixed by https://github.com/zephyrproject-rtos/picolibc/commit/52d547fc4b3184462fbab6a7f8381fe3650c4cb1. Please try with SDK 0.17.0-rc1.
