### PR TITLE
drivers: i2c: stm32: don't manage cache aside DMA support

### PR DESCRIPTION
**Pull request by etienne-lms**
~~Commit 42c3a7814810 ("i2c: stm32: Add cache memory support") introduced a call to mem_attr_check_buf() in STM32 I2C driver i2c_ll_stm32_v2.c without adding the config dependency on CONFIG_MEM_ATTR needed. Fix STM32 I2C Kconfig accordingly.~~
~~By the way, select CONFIG_CACHE_MANAGEMENT and CONFIG_MEM_ATTR upon CONFIG_DCACHE=y instead of CONFIG_CPU_HAS_DCACHE to better relate to how STM32 I2C driver is implemented.~~

(edited)

Fix STM32 I2C driver to not call cache management related functions when DMA is not used. This change fixes an issue introduced by commit 42c3a7814810 ("i2c: stm32: Add cache memory support"). The issue makes boards embedding this driver with both `CONFIG_I2C_STM32_V2_DMA` and `CONFIG_ARCH_MPU` disabled to fail to build with an error trace message like the below:
>       .../i2c_ll_stm32_v2.c:701: undefined reference to `mem_attr_check_buf'
Fixes: 42c3a7814810a60cd23d719264695351ba5b8023

### CODE REVIEW

**Comment by etienne-lms** [comment]
@sgilbert182, could you have a look at this change. Some build currently fail on STM32 I2C driver and seem related to https://github.com/zephyrproject-rtos/zephyr/pull/81814.

**Review by JarmouniA — APPROVED** [review]

**Comment by etienne-lms** [comment]
For info, my patch was not accurate enough. I've updated it.

**Review by JarmouniA — CHANGES_REQUESTED** [review]

File: drivers/i2c/Kconfig.stm32 [hunk 1]
```diff
@@ -59,7 +60,7 @@ config I2C_STM32_V2_DMA
 	bool "DMA support"
 	depends on I2C_STM32_V2
 	select DMA
-	select CACHE_MANAGEMENT if CPU_HAS_DCACHE
+	select CACHE_MANAGEMENT if DCACHE
```
Comment (sgilbert182) [inline drivers/i2c/Kconfig.stm32:63]: possibly outside of the remit of this PR but does this suggest where #ifdef CONFIG_DCACHE is used in the i2c driver should change to #ifdef CACHE_MANAGEMENT instead?

Comment (sgilbert182) [reply drivers/i2c/Kconfig.stm32:63]: Ah ok, thanks for the link!

File: drivers/i2c/Kconfig.stm32 [hunk 2]
```diff
@@ -24,6 +24,7 @@ config I2C_STM32_V2
 	default y
 	depends on DT_HAS_ST_STM32_I2C_V2_ENABLED
 	select I2C_STM32_INTERRUPT if I2C_TARGET
+	select MEM_ATTR if DCACHE
```
[the remark this answers is not in the document]
Comment (etienne-lms) [reply drivers/i2c/Kconfig.stm32:27]: Makes sense to me, I'll post an update.

**Comment by etienne-lms** [comment]
By the way, @JarmouniA, looking at other STM32 drivers, I saw some other equivalent potential issues in *drivers/adc/adc_stm32.c*, *drivers/spi/spi_ll_stm32.c* and *drivers/serial/uart_stm32.c* that are hidden by the fact [`CONFIG_MEM_ATTR` is default enabled `CONFIG_ARM_MPU=y`](https://github.com/zephyrproject-rtos/zephyr/blob/v4.1.0/subsys/mem_mgmt/Kconfig#L6) which seems the case for the SoCs embedding these drivers. I wonder if equivalent explicit dependencies are worth being also defined in the Kconfig files relative to these drivers. What do you think?

File: drivers/i2c/Kconfig.stm32 [hunk 3]
```diff
@@ -59,7 +59,8 @@ config I2C_STM32_V2_DMA
 	bool "DMA support"
 	depends on I2C_STM32_V2
 	select DMA
-	select CACHE_MANAGEMENT if CPU_HAS_DCACHE
+	select CACHE_MANAGEMENT if DCACHE
+	select MEM_ATTR if DCACHE
```
[the remark this answers is not in the document]
Comment (etienne-lms) [reply drivers/i2c/Kconfig.stm32:63]: It seems to me if `CONFIG_DCACHE` is disabled, `CONFIG_I2C_STM32_V2_DMA` can still be enabled. Only that no cache management is needed and `CONFIG_MEM_ATTR` does not need to be enable.
@sgilbert182, may I ask your opinion?

**Comment by etienne-lms** [comment]
@erwango, may I ask your feedback on this change? It's needed to fix issues currently reported by CI tests on various P-Rs.

**Comment by etienne-lms** [comment]
> > I wonder if equivalent explicit dependencies are worth being also defined in the Kconfig files relative to these drivers. What do you think?
> 
> Maybe, to avoid potential issues later down the road.

FYI I've created https://github.com/zephyrproject-rtos/zephyr/pull/87757.

File: drivers/i2c/Kconfig.stm32 (hunk 3 above)
[the remark this answers is not in the document]
Comment (erwango) [reply drivers/i2c/Kconfig.stm32:63]: Actually, I'll split that exact change out of this PR and move to https://github.com/zephyrproject-rtos/zephyr/pull/87757.
This would give us more time to discuss and allow an easy revert if required

[the remark this answers is not in the document]
Comment (etienne-lms) [reply drivers/i2c/Kconfig.stm32:63]: My mistake.
The change in the source file fixes the CI tests issue.
The change in the Kconfig file is not strictly needed, but better be added IMHO. (maybe in a seperated P-R)

[the remark this answers is not in the document]
Comment (etienne-lms) [reply drivers/i2c/Kconfig.stm32]: P-R updated.

**Comment by etienne-lms** [comment]
As discussed above, I restricted this P-R to a change in driver source file.
Cleaning the Kconfig file is still prefer IMHO but I've moved it to #87757 so that the CI tests issue gets fixed quicker.

**Review by erwango — APPROVED** [review]
Nit: Update PR title and description

**Review by JarmouniA — APPROVED** [review]

**Review by pillo79 — APPROVED** [review]
Thanks for the hotfix!

**Review by teburd — APPROVED** [review]
