### PR TITLE
Fix `CONFIG_BT_DID` compilation error and add test

### PR DESCRIPTION
**Pull request by tchebb**
`subsys/bluetooth/host/classic/did.c` fails to compile since #101810 (cc @lylezhu2012), which added a `LOG_ERR()` invocation but didn't setup logging for the file. Fix that and add a test that builds Zephyr with `CONFIG_BT_DID=y`.

### CODE REVIEW

**Comment by lylezhu2012** [comment]
Thanks for your contribution.

I realized there's a flaw here. There are no test cases that can test the case where CONFIG_BT_DID=y.

I would like to add a test case for it, just likes as,
https://github.com/zephyrproject-rtos/zephyr/blob/7a218e5db564c1f4ddce0e84006880b0cec9d037/tests/bluetooth/shell/testcase.yaml#L62-L73

Could you help to add the following code block to testcase.yml of bluetooth shell?
```
  bluetooth.shell.shell_br.did:
    extra_configs:
      - CONFIG_UART_NATIVE_PTY_0_ON_STDINOUT=y
      - CONFIG_BT_DID=y
    extra_args: CONF_FILE="prj_br.conf"
    platform_allow:
      - qemu_cortex_m3
      - qemu_x86
      - native_sim
      - native_sim/native/64
    platform_exclude: nrf52dk/nrf52810
    tags: bluetooth
    harness: keyboard
```

**Review by lylezhu2012 — APPROVED** [review]

**Review by makeshi — APPROVED** [review]
