### PR TITLE
twister: second fix for hardware map detection

### PR DESCRIPTION
**Pull request by gchwier**
When scanning ports the manufacture field is not always filled. It must be checked before using.

After merging #66491 received error when trying to generate a new hardware map:
```
File "/home/grch/zephyrproject/zephyr/scripts/pylib/twister/twisterlib/hardwaremap.py", line 290, in scan
    if d.manufacturer.casefold() in [m.casefold() for m in self.manufacturer]:
AttributeError: 'NoneType' object has no attribute 'casefold'
```

### CODE REVIEW

**Comment by gchwier** [comment]
@michal-smola plaese review

**Review by nashif — APPROVED** [review]

**Review by PerMac — APPROVED** [review]
