### ISSUE TITLE
regression: sysbuild with encrypted image fails to build

### ISSUE THREAD

**Issue by aaron-ets** [zephyrproject-rtos/zephyr#107149]
### Describe the bug

In v4.3.0 this build succeeds:
```
west build -b reel_board samples/hello_world --sysbuild -- -DSB_CONFIG_BOOTLOADER_MCUBOOT=y -DSB_CONFIG_BOOT_ENCRYPTION=y
```

In v4.4.0-rc3 it fails to compile with missing `mbedtls/aes.h` header:
```
In file included from /home/aaron/zephyrproject/bootloader/mcuboot/boot/bootutil/include/bootutil/crypto/aes_ctr.h:21,
                 from /home/aaron/zephyrproject/bootloader/mcuboot/boot/bootutil/include/bootutil/enc_key.h:33,
                 from /home/aaron/zephyrproject/bootloader/mcuboot/boot/bootutil/src/image_validate.c:54:
/home/aaron/zephyrproject/bootloader/mcuboot/boot/bootutil/include/bootutil/crypto/aes_ctr_mbedtls.h:17:10: fatal error: mbedtls/aes.h: No such file or directory
   17 | #include <mbedtls/aes.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
```

git bisect shows commit 66ee2d2304eea0c1fa4508763f0b978d6681cea0 where it fails to build, but that was for an unrelated header file that may have been fixed.

### Regression

- [x] This is a regression.

### Steps to reproduce

west build -b reel_board samples/hello_world --sysbuild -- -DSB_CONFIG_BOOTLOADER_MCUBOOT=y -DSB_CONFIG_BOOT_ENCRYPTION=y

### Relevant log output

```shell

```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

v4.4.0-rc3
sdk 1.0.0

**Comment by henrikbrixandersen** [comment]
CC: @nordicjm

**Comment by MaureenHelm** [comment]
The release team reviewed this and agreed it's a release blocker
