### PR TITLE
Bluetooth: controller: Fix arguments unused without Extended Scanning

### LINKED ISSUE #29442: build failure w/sanitycheck for samples/bluetooth/hci_usb_h4/sample.bluetooth.hci_usb_h4
On multiple platform seeing failures if we do:

`./scripts/sanitycheck -s samples/bluetooth/hci_usb_h4/sample.bluetooth.hci_usb_h4 -l`

we get:
```
ERROR   - bl654_dvk                 samples/bluetooth/hci_usb_h4/sample.bluetooth.hci_usb_h4 FAILED: Build failure
ERROR   - see: /home/galak/git/zephyr/sanity-out/bl654_dvk/samples/bluetooth/hci_usb_h4/sample.bluetooth.hci_usb_h4/build.log
INFO    - Total complete:    1/  16   6%  skipped:    0, failed:    1
ERROR   - nrf52840dk_nrf52840       samples/bluetooth/hci_usb_h4/sample.bluetooth.hci_usb_h4 FAILED: Build failure
ERROR   - see: /home/galak/git/zephyr/sanity-out/nrf52840dk_nrf52840/samples/bluetooth/hci_usb_h4/sample.bluetooth.hci_usb_h4/build.log
INFO    - Total complete:    2/  16  12%  skipped:    0, failed:    2
ERROR   - bl653_dvk                 samples/bluetooth/hci_usb_h4/sample.bluetooth.hci_usb_h4 FAILED: Build failure
ERROR   - see: /home/galak/git/zephyr/sanity-out/bl653_dvk/samples/bluetooth/hci_usb_h4/sample.bluetooth.hci_usb_h4/build.log
INFO    - Total complete:    3/  16  18%  skipped:    0, failed:    3
ERROR   - particle_boron            samples/bluetooth/hci_usb_h4/sample.bluetooth.hci_usb_h4 FAILED: Build failure
ERROR   - see: /home/galak/git/zephyr/sanity-out/particle_boron/samples/bluetooth/hci_usb_h4/sample.bluetooth.hci_usb_h4/build.log
INFO    - Total complete:    4/  16  25%  skipped:    0, failed:    4
ERROR   - reel_board_v2             samples/bluetooth/hci_usb_h4/sample.bluetooth.hci_usb_h4 FAILED: Build failure
ERROR   - see: /home/galak/git/zephyr/sanity-out/reel_board_v2/samples/bluetooth/hci_usb_h4/sample.bluetooth.hci_usb_h4/build.log
INFO    - Total complete:    5/  16  31%  skipped:    0, failed:    5
ERROR   - nrf52833dk_nrf52833       samples/bluetooth/hci_usb_h4/sample.bluetooth.hci_usb_h4 FAILED: Build failure
ERROR   - see: /home/galak/git/zephyr/sanity-out/nrf52833dk_nrf52833/samples/bluetooth/hci_usb_h4/sample.bluetooth.hci_usb_h4/build.log
INFO    - Total complete:    6/  16  37%  skipped:    0, failed:    6
ERROR   - pinnacle_100_dvk          samples/bluetooth/hci_usb_h4/sample.bluetooth.hci_usb_h4 FAILED: Build failure
ERROR   - see: /home/galak/git/zephyr/sanity-out/pinnacle_100_dvk/samples/bluetooth/hci_usb_h4/sample.bluetooth.hci_usb_h4/build.log
INFO    - Total complete:    7/  16  43%  skipped:    0, failed:    7
ERROR   - nrf52840dongle_nrf52840   samples/bluetooth/hci_usb_h4/sample.bluetooth.hci_usb_h4 FAILED: Build failure
ERROR   - see: /home/galak/git/zephyr/sanity-out/nrf52840dongle_nrf52840/samples/bluetooth/hci_usb_h4/sample.bluetooth.hci_usb_h4/build.log
INFO    - Total complete:    8/  16  50%  skipped:    0, failed:    8
ERROR   - particle_xenon            samples/bluetooth/hci_usb_h4/sample.bluetooth.hci_usb_h4 FAILED: Build failure
ERROR   - see: /home/galak/git/zephyr/sanity-out/particle_xenon/samples/bluetooth/hci_usb_h4/sample.bluetooth.hci_usb_h4/build.log
INFO    - Total complete:    9/  16  56%  skipped:    0, failed:    9
ERROR   - nrf52840_blip             samples/bluetooth/hci_usb_h4/sample.bluetooth.hci_usb_h4 FAILED: Build failure
ERROR   - see: /home/galak/git/zephyr/sanity-out/nrf52840_blip/samples/bluetooth/hci_usb_h4/sample.bluetooth.hci_usb_h4/build.log
INFO    - Total complete:   10/  16  62%  skipped:    0, failed:   10
ERROR   - reel_board                samples/bluetooth/hci_usb_h4/sample.bluetooth.hci_usb_h4 FAILED: Build failure
ERROR   - see: /home/galak/git/zephyr/sanity-out/reel_board/samples/bluetooth/hci_usb_h4/sample.bluetooth.hci_usb_h4/build.log
INFO    - Total complete:   11/  16  68%  skipped:    0, failed:   11
ERROR   - particle_argon            samples/bluetooth/hci_usb_h4/sample.bluetooth.hci_usb_h4 FAILED: Build failure
ERROR   - see: /home/galak/git/zephyr/sanity-out/particle_argon/samples/bluetooth/hci_usb_h4/sample.bluetooth.hci_usb_h4/build.log
INFO    - Total complete:   12/  16  75%  skipped:    0, failed:   12
ERROR   - nrf52840_papyr            samples/bluetooth/hci_usb_h4/sample.bluetooth.hci_usb_h4 FAILED: Build failure
ERROR   - see: /home/galak/git/zephyr/sanity-out/nrf52840_papyr/samples/bluetooth/hci_usb_h4/sample.bluetooth.hci_usb_h4/build.log
INFO    - Total complete:   13/  16  81%  skipped:    0, failed:   13
ERROR   - nrf52840_mdk              samples/bluetooth/hci_usb_h4/sample.bluetooth.hci_usb_h4 FAILED: Build failure
ERROR   - see: /home/galak/git/zephyr/sanity-out/nrf52840_mdk/samples/bluetooth/hci_usb_h4/sample.bluetooth.hci_usb_h4/build.log
INFO    - Total complete:   14/  16  87%  skipped:    0, failed:   14
ERROR   - adafruit_feather_nrf52840 samples/bluetooth/hci_usb_h4/sample.bluetooth.hci_usb_h4 FAILED: Build failure
ERROR   - see: /home/galak/git/zephyr/sanity-out/adafruit_feather_nrf52840/samples/bluetooth/hci_usb_h4/sample.bluetooth.hci_usb_h4/build.log
INFO    - Total complete:   15/  16  93%  skipped:    0, failed:   15
ERROR   - nrf52833dk_nrf52820       samples/bluetooth/hci_usb_h4/sample.bluetooth.hci_usb_h4 FAILED: Build failure
ERROR   - see: /home/galak/git/zephyr/sanity-out/nrf52833dk_nrf52820/samples/bluetooth/hci_usb_h4/sample.bluetooth.hci_usb_h4/build.log

```

From the log:
```
/home/galak/git/zephyr/subsys/bluetooth/controller/ll_sw/ull_scan.c: In function 'll_scan_enable':
/home/galak/git/zephyr/subsys/bluetooth/controller/ll_sw/ull_scan.c:130:10: error: unused variable 'is_update_1m' [-Werror=unused-variable]
  130 |  uint8_t is_update_1m = 0U;
      |          ^~~~~~~~~~~~
/home/galak/git/zephyr/subsys/bluetooth/controller/ll_sw/ull_scan.c:127:10: error: unused variable 'is_update_coded' [-Werror=unused-variable]
  127 |  uint8_t is_update_coded = 0U;
      |          ^~~~~~~~~~~~~~~
/home/galak/git/zephyr/subsys/bluetooth/controller/ll_sw/ull_scan.c:125:22: error: unused variable 'node_rx_scan_term' [-Werror=unused-variable]
  125 |  struct node_rx_pdu *node_rx_scan_term = NULL;
      |                      ^~~~~~~~~~~~~~~~~

```

### PR DESCRIPTION
**Pull request by cvinayak**
Fix arguments unused when not enabling Extended Scanning which
was introduced in commit 0cef1e43c9

Fixes #29442.

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Comment by wopu-ot** [comment]
Wouldn't it be simpler to just guard the declaration of the respective variables with `#if defined(CONFIG_BT_CTLR_ADV_EXT)`?

**Comment by cvinayak** [comment]
> 
> 
> Wouldn't it be simpler to just guard the declaration of the respective variables with `#if defined(CONFIG_BT_CTLR_ADV_EXT)`?

I wanted to keep them close to locality of reference, but no hard opinion as to either adding ARG_UNUSED versus conditional compile.

**Review by Thalley — COMMENTED** [review]
@wopu-ot @cvinayak I tend to agree with Wolfgang here as well. I think it'll be more readable (the function is already hard enough to read with the existing `#if defined` statements).

**Review by wopu-ot — APPROVED** [review]

**Review by Thalley — APPROVED** [review]

**Review by kruithofa — APPROVED** [review]
