### PR TITLE
kernel: fix usage of KERNEL_COHERENCE macro

### LINKED ISSUE #30380: Improve the use of CONFIG_KERNEL_COHERENCE
**Describe the bug**
It seems there is a typo in the kernel where `KERNEL_COHERENCE` is used instead of `CONFIG_KERNEL_COHERENCE`.

**To Reproduce**
Search for " KERNEL_COHERENCE". Note the leading space character.
```
$ git grep " KERNEL_COHERENCE"
include/spinlock.h:# ifdef KERNEL_COHERENCE
kernel/Kconfig:config KERNEL_COHERENCE
kernel/init.c:#ifdef KERNEL_COHERENCE
kernel/sched.c:#ifdef KERNEL_COHERENCE
kernel/sched.c:#ifdef KERNEL_COHERENCE
kernel/thread.c:#ifdef KERNEL_COHERENCE
kernel/timeout.c:#ifdef KERNEL_COHERENCE
```

**Expected behavior**
```
$ git grep " KERNEL_COHERENCE"
kernel/Kconfig:config KERNEL_COHERENCE
```

**Impact**
The conditionally compiled code (asserts) is never activated by the Kconfig option.

**Environment (please complete the following information):**
 - Toolchain: zephyr-sdk-0.11.4
 - Commit SHA: Observed at `e0b35dd0d594a8af8989e3713f99d52128e08815`

**Additional context**
Introduced in f6d32ab0a45a20e27476d42f6096d8f8b0f0e6ca

### PR DESCRIPTION
**Pull request by nashif**
Add missing CONFIG_ to KERNEL_COHERENCE usage in code.

Fixes #30380

### CODE REVIEW

**Comment by martin-aberg** [comment]
Thank you @nashif for working on this.

I am afraid there are more issues with this setting. Trying it with
```
sanitycheck -x=CONFIG_KERNEL_COHERENCE=y -v -T tests/kernel
```
results in tests failing to build:
```
kernel/init.c:161:36: error: incompatible type for argument 1 of 'arch_mem_coherent'
  161 |  __ASSERT_NO_MSG(arch_mem_coherent(_kernel));

...

kernel/include/kswap.h:111:3: error: implicit declaration of function 'arch_cohere_stacks' [-Werror=implicit-function-declaration]
  111 |   arch_cohere_stacks(old_thread, NULL, new_thread);
```

**Comment by nashif** [comment]
> I am afraid there are more issues with this setting.

addressed

**Review by dcpleung — APPROVED** [review]

**Review by ghost — APPROVED** [review]
