### PR TITLE
toolchain: xt-clang: fixes issues when building picolibc from source

### LINKED ISSUE #90383: ACE: Xtensa: Build failures on ACE platforms.
**Describe the bug**
Build Failures on: `intel_adsp/ace_15_mtpm/sim, intel_adsp_ace_20_lnl/sim, intel_adsp/ace_30/ptl/sim.`

**To Reproduce**
Checkout to latest upstream ([b1f9351)](https://github.com/zephyrproject-rtos/zephyr/commit/b1f9351930f14775e90ebfb2d3d3998b6552ca1f)
Run: `twister -p intel_adsp/ace_15_mptm/sim -T tests/`

**Impact**
Affects ACE platforms

**Logs and console output**
```
In file included from <path_to>/modules/lib/picolibc/newlib/libc/stdlib/nano-free.c:29:
<path_to>/modules/lib/picolibc/newlib/libc/stdlib/nano-malloc.h:60:9: error: unknown type name 'max_align_t'
typedef max_align_t align_chunk_t;
        ^
1 error generated.
```

**Environment:**

 - OS: Linux
 - Toolchain xt-clang
 - Commit SHA or Version used ([b1f9351)](https://github.com/zephyrproject-rtos/zephyr/commit/b1f9351930f14775e90ebfb2d3d3998b6552ca1f)

**Additional context**
Bisect result:
```
843d661b820e067f28112d2ea7dd822c2ecbcba2 is the first bad commit
commit 843d661b820e067f28112d2ea7dd822c2ecbcba2
Author: Keith Packard <keithp@keithp.com>
Date:   Thu Mar 27 15:03:06 2025 -0700

    modules: Update picolibc to version 1.8.10

    Switch to latest picolib release, version 1.8.10

    Signed-off-by: Keith Packard <keithp@keithp.com>

 west.yml | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```

### PR DESCRIPTION
**Pull request by dcpleung**
Although xt-clang is based on clang, for some reason, it still lists xcc system include path as the first search path (e.g. for stddef.h), and the clang system include path as last. This creates a big issue when the code starts to use any standards past C89 (since xcc is based on GCC 4.2). We can use compiler property `nostdin_include` to add `-isystem` to compiler options. However, some modules (e.g. picolibc) somehow ignore this. So we also need to forcibly do `add_compile_options()` to make sure the clang system include path is placed before the xcc system include path.

### CODE REVIEW

**Review by nashif — APPROVED** [review]

**Comment by dcpleung** [comment]
ping? This is blocking internal CI.

**Review by teburd — APPROVED** [review]

**Comment by nashif** [comment]
@tejlmand  please review

**Review by stephanosio — APPROVED** [review]

**Review by dkalowsk — APPROVED** [review]
