### PR TITLE
fs: fcb: fix clang build error

### PR DESCRIPTION
**Pull request by fabiobaltieri**
Clang build fails since ea9ee3ee3a3 with:

/__w/zephyr/zephyr/subsys/fs/fcb/fcb.c:263:11: error: fields must have a constant size: 'variable length array in structure' extension will never be supported

Replace the union with a buffer and pointer.

### CODE REVIEW

**Review by de-nordic — COMMENTED** [review]
Can we rather do that:
https://github.com/zephyrproject-rtos/zephyr/pull/112158
I was going to do the 109, but the clang problem just rushed the work...

**Comment by fabiobaltieri** [comment]
Yeah happy with either.

**Comment by de-nordic** [comment]
> Yeah happy with either.

Thanks.
