### ISSUE TITLE
regression: Build fails after switching logging to V2

### ISSUE THREAD

**Issue by Delsian** [zephyrproject-rtos/zephyr#41915]
**Describe the bug**

Build ok with dd4035c62424b4241a5b22ec05e575c48d3fecaf
Build fail with 262cc55609b73ea61b5f999c6c6daaba20bc5240

@nordic-krch Probably you forgot to add some defines in your patch:

```
zephyr/include/sys/printk.h: In function 'vprintk':
/zephyr/include/sys/printk.h:55:8: error: 'LOG_LEVEL_INTERNAL_RAW_STRING' undeclared (first use in this function)
   55 |        LOG_LEVEL_INTERNAL_RAW_STRING, NULL, 0,
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

My file log.conf:
```
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y

# Select RTT or UART here
CONFIG_LOG_BACKEND_UART=n
CONFIG_LOG_IMMEDIATE_CLEAN_OUTPUT=y
CONFIG_LOG_BACKEND_RTT=n
#CONFIG_LOG_BACKEND_RTT_MODE_BLOCK=y
CONFIG_STDOUT_CONSOLE=n
CONFIG_UART_CONSOLE_DEBUG_SERVER_HOOKS=y
CONFIG_LOG_BACKEND_FORMAT_TIMESTAMP=n
CONFIG_LOG_CMDS=n

# SEGGER SystemView
CONFIG_THREAD_NAME=y
CONFIG_SEGGER_SYSTEMVIEW=y
CONFIG_TRACING=y
CONFIG_USE_SEGGER_RTT=y
CONFIG_SEGGER_RTT_BUFFER_SIZE_UP=8192
# enable for post-mortem tracing
CONFIG_SEGGER_SYSVIEW_POST_MORTEM_MODE=n
CONFIG_SEGGER_SYSVIEW_SECTION_DTCM=n
CONFIG_SEGGER_SYSTEMVIEW_BOOT_ENABLE=n

# Logging
CONFIG_NET_LOG=y
CONFIG_CAN_LOG_LEVEL_DBG=y
CONFIG_NET_IF_LOG_LEVEL_DBG=n
CONFIG_NET_CORE_LOG_LEVEL_DBG=n
CONFIG_NET_IPV6_LOG_LEVEL_DBG=n
CONFIG_NET_L2_ETHERNET_LOG_LEVEL_DBG=n
CONFIG_NET_UDP_LOG_LEVEL_DBG=n
CONFIG_NET_SOCKETS_LOG_LEVEL_DBG=n
CONFIG_NET_ROUTE_LOG_LEVEL_DBG=n
CONFIG_NET_TC_LOG_LEVEL_DBG=n
CONFIG_NET_PKT_LOG_LEVEL_DBG=n 
CONFIG_NET_CONN_LOG_LEVEL_DBG=n
CONFIG_NET_MGMT_EVENT_LOG_LEVEL_DBG=y
```

Changing CONFIG_TRACING to n fixes issue

**Comment by Delsian** [comment]
@nashif FYI

**Comment by nashif** [comment]
what board did you build with? what sample/test?

**Comment by nordic-krch** [comment]
Working on it.

**Comment by manoj153** [comment]
It may be related to a similar issue I am facing. The board is nucleo_h723zg. Hopefully, my test result will help.

Kconfig:
```
CONFIG_LOG=y
CONFIG_PRINTK=y
CONFIG_HEAP_MEM_POOL_SIZE=8192
CONFIG_ASSERT=y
CONFIG_GPIO=y
CONFIG_UART_ASYNC_API=y
CONFIG_LOG_BACKEND_SHOW_COLOR=y
CONFIG_NEWLIB_LIBC=y
CONFIG_LOG2_MODE_DEFERRED=y
CONFIG_SHELL=y
CONFIG_SHELL_CMDS=y
CONFIG_GPIO_SHELL=y
CONFIG_LOG_BACKEND_UART=y
CONFIG_SHELL_LOG_BACKEND=n
CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y
CONFIG_PWM=y
CONFIG_LOG_TIMESTAMP_64BIT=y
CONFIG_LOG_BACKEND_FORMAT_TIMESTAMP=n
CONFIG_SHELL_LOG_BACKEND=n
CONFIG_STM32_BACKUP_SRAM=y
CONFIG_REBOOT=y
CONFIG_LOG_MODE_OVERFLOW=y
CONFIG_LOG_BUFFER_SIZE=4096
CONFIG_LOG_SPEED=y
CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_COUNTER=y
CONFIG_COUNTER_RTC_STM32_CLOCK_LSE=y
CONFIG_COUNTER_RTC_STM32_BACKUP_DOMAIN_RESET=n
CONFIG_COUNTER_RTC_STM32_SAVE_VALUE_BETWEEN_RESETS=y
CONFIG_LOG_FUNC_NAME_PREFIX_DBG=n
CONFIG_SHELL_ARGC_MAX=16
CONFIG_NOCACHE_MEMORY=y
CONFIG_TRACING=y
CONFIG_SEGGER_SYSTEMVIEW=y
```

Crash log:
```
[946685754] <err> os: r0/a1:  0x00000004  r1/a2:  0x000000a8  r2/a3:  0x240038a8
[946685754] <err> os: r3/a4:  0x0000000f r12/ip:  0x00000000 r14/lr:  0x0801c113
[946685754] <err> os:  xpsr:  0x61000000
[946685754] <err> os: Faulting instruction address (r15/pc): 0x0803111c
[946685754] <err> os: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
[946685754] <err> os: Current thread: 0x240038a8 (logging)

```
