### PR TITLE
posix: improve header compatibility

### LINKED ISSUE #75105: ARCMWDT: Some of POSIX tests are broken
**Describe the bug**
POSIX-compatible tests are broken for ARCMWDT compiler. Some types are not presented in MW library, some types mismatch with defined in Zephyr.

**To Reproduce**
1. ``` export ZEPHYR_TOOLCHAIN_VARIANT=arcmwdt ```
2. ``` west build -p -b nsim/nsim_em tests/posix/headers/ -T portability.posix.headers.arcmwdtlib.without_posix_api ```

**Expected behavior**
Clean build with no errors

**Logs and console output**
```
/home/user/sandbox/zephyrproject/zephyr/include/zephyr/posix/posix_types.h:24:13: error: typedef redefinition with different types ('int' vs 'long')
   24 | typedef int pid_t;
      |             ^
/home/user/ARC_202406rc1/MetaWare/arc/inc/sys/types.h:63:19: note: previous definition is here
   63 |     typedef     long    pid_t;
      |                         ^
1 error generated.
```
and
```
/home/user/sandbox/zephyrproject/zephyr/include/zephyr/posix/aio.h:24:18: error: field has incomplete type 'struct sigevent'
   24 |         struct sigevent aio_sigevent;
      |                         ^
/home/user/sandbox/zephyrproject/zephyr/include/zephyr/posix/aio.h:24:9: note: forward declaration of 'struct sigevent'
   24 |         struct sigevent aio_sigevent;
      |                ^
1 error generated.
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: arcmwdt
 - Zephyr version: 3.7.0-rc1

### LINKED ISSUE #75205: multipe tests/posix & tests/lib/c_lib/thrd build failures due to missing time.h definitions
**Describe the bug**
* tests/posix/common/portability.posix.common.newlib 
* tests/posix/common/portability.posix.common.tls.newlib
* tests/posix/fs/portability.posix.fs.newlib
* tests/posix/fs/portability.posix.fs.tls.newlib
* tests/posix/headers/portability.posix.headers.newlib.with_posix_api
* tests/lib/c_lib/thrd/libraries.libc.c11_threads.newlib
* tests/lib/c_lib/thrd/libraries.libc.c11_threads.newlib_nano

build failure in the following platforms:

* circuitdojo_feather/nrf9160/ns
* actinius_icarus_bee/nrf9160/ns
* actinius_icarus@2.0.0/nrf9160/ns
* actinius_icarus@1.4.0/nrf9160/ns
* innblue21/nrf9160/ns
* innblue22/nrf9160/ns
* lpcxpresso55s69/lpc55s69/cpu0/ns
* actinius_icarus_som_dk/nrf9160/ns
* actinius_icarus_som/nrf9160/ns
* mimxrt1010_evk
* mimxrt1024_evk
* mimxrt1015_evk
* mimxrt1020_evk
* mimxrt1040_evk
* mimxrt1060_evk
* mimxrt1050_evk
* mimxrt1060_evk@hyperflash
* mimxrt1060_evkb
* mimxrt1050_evk@qspi
* mimxrt1170_evk@B/mimxrt1176/cm7
* mimxrt1062_fmurt6
* mimxrt1170_evk/mimxrt1176/cm7
* mimxrt1160_evk/mimxrt1166/cm7
* mimxrt1064_evk
* mm_feather
* mimxrt595_evk/mimxrt595s/cm33
* mm_swiftio
* mimxrt685_evk/mimxrt685s/cm33
* nrf5340dk/nrf5340/cpuapp/ns
* nrf5340_audio_dk/nrf5340/cpuapp/ns
* nrf9151dk/nrf9151/ns
* nrf9160dk/nrf9160/ns
* nrf9131ek/nrf9131/ns
* nrf9160dk@0.7.0/nrf9160/ns
* nrf9161dk/nrf9161/ns
* nrf9161dk@0.7.0/nrf9161/ns
* raytac_mdbt53_db_40/nrf5340/cpuapp/ns
* raytac_mdbt53v_db_40/nrf5340/cpuapp/ns
* sparkfun_thing_plus/nrf9160/ns
* b_u585i_iot02a/stm32u585xx/ns
* stm32l562e_dk/stm32l562xx/ns
* thingy53/nrf5340/cpuapp/ns
* vmu_rt1170/mimxrt1176/cm7
* bl5340_dvk/nrf5340/cpuapp/ns

**To Reproduce**

```
twister -i -p mimxrt1170_evk/mimxrt1176/cm7 -s portability.posix.headers.newlib.with_posix_api
```

**Expected behavior**
build PASS

**Impact**
POSIX compatible
~190 failures in weekly CI
Failures in PRs CI when these tests are triggered

**Logs and console output**

```
modules/crypto/mbedtls/library/platform_util.c
In file included from zephyr/include/zephyr/posix/time.h:116,
                 from zephyr/include/zephyr/posix/time.h:12,
                 from zephyr/include/zephyr/net/socket_select.h:22,
                 from zephyr/include/zephyr/posix/sys/select.h:10,
                 from zephyr-sdk-0.16.8/arm-zephyr-eabi/arm-zephyr-eabi/sys-include/sys/types.h:50,
                 from zephyr-sdk-0.16.8/arm-zephyr-eabi/arm-zephyr-eabi/sys-include/stdio.h:61,
                 from modules/crypto/mbedtls/include/mbedtls/platform.h:58,
                 from modules/crypto/mbedtls/library/platform_util.c:26:
zephyr-sdk-0.16.8/arm-zephyr-eabi/arm-zephyr-eabi/sys-include/time.h:56:1: error: unknown type name 'clock_t'
   56 | clock_t    clock (void);
      | ^~~~~~~
zephyr-sdk-0.16.8/arm-zephyr-eabi/arm-zephyr-eabi/sys-include/time.h:30:1: note: 'clock_t' is defined in header '<time.h>'; did you forget to '#include <time.h>'?
   29 | #include <sys/timespec.h>
  +++ |+#include <time.h>
   30 | 
In file included from zephyr/include/zephyr/posix/posix_types.h:15,
                 from zephyr/include/zephyr/posix/time.h:61:
zephyr-sdk-0.16.8/arm-zephyr-eabi/arm-zephyr-eabi/sys-include/sys/_pthreadtypes.h:182:3: error: unknown type name 'clock_t'
  182 |   clock_t  clock;             /* specifiy clock for timeouts */
      |   ^~~~~~~
zephyr/include/zephyr/posix/posix_types.h:76:9: error: unknown type name 'clockid_t'
   76 |         clockid_t clock;
      |         ^~~~~~~~~
zephyr/include/zephyr/posix/time.h:93:19: error: unknown type name 'clockid_t'; did you mean 'clock_pfd_t'?
   93 | int clock_gettime(clockid_t clock_id, struct timespec *ts);
      |                   ^~~~~~~~~
      |                   clock_pfd_t
zephyr/include/zephyr/posix/time.h:94:18: error: unknown type name 'clockid_t'; did you mean 'clock_pfd_t'?
   94 | int clock_getres(clockid_t clock_id, struct timespec *ts);
      |                  ^~~~~~~~~
      |                  clock_pfd_t
zephyr/include/zephyr/posix/time.h:95:19: error: unknown type name 'clockid_t'; did you mean 'clock_pfd_t'?
   95 | int clock_settime(clockid_t clock_id, const struct timespec *ts);
      |                   ^~~~~~~~~
      |                   clock_pfd_t
zephyr/include/zephyr/posix/time.h:96:36: error: unknown type name 'clockid_t'; did you mean 'clock_pfd_t'?
   96 | int clock_getcpuclockid(pid_t pid, clockid_t *clock_id);
      |                                    ^~~~~~~~~
      |                                    clock_pfd_t
zephyr/include/zephyr/posix/time.h:98:18: error: unknown type name 'clockid_t'; did you mean 'clock_pfd_t'?
   98 | int timer_create(clockid_t clockId, struct sigevent *evp, timer_t *timerid);
      |                  ^~~~~~~~~
      |                  clock_pfd_t
zephyr/include/zephyr/posix/time.h:105:21: error: unknown type name 'clockid_t'; did you mean 'clock_pfd_t'?
  105 | int clock_nanosleep(clockid_t clock_id, int flags,
      |                     ^~~~~~~~~
      |                     clock_pfd_t
In file included from zephyr/include/zephyr/sys/fdtable.h:13,
                 from zephyr/include/zephyr/net/socket_select.h:26:
zephyr/include/zephyr/fs/fs.h:368:1: error: unknown type name 'ssize_t'; did you mean '_ssize_t'?
  368 | ssize_t fs_read(struct fs_file_t *zfp, void *ptr, size_t size);
      | ^~~~~~~
      | _ssize_t
zephyr/include/zephyr/fs/fs.h:389:1: error: unknown type name 'ssize_t'; did you mean '_ssize_t'?
  389 | ssize_t fs_write(struct fs_file_t *zfp, const void *ptr, size_t size);
      | ^~~~~~~
      | _ssize_t
zephyr/include/zephyr/fs/fs.h:409:36: error: unknown type name 'off_t'; did you mean '_off_t'?
  409 | int fs_seek(struct fs_file_t *zfp, off_t offset, int whence);
      |                                    ^~~~~
      |                                    _off_t
zephyr/include/zephyr/fs/fs.h:425:1: error: unknown type name 'off_t'; did you mean '_off_t'?
  425 | off_t fs_tell(struct fs_file_t *zfp);
      | ^~~~~
      | _off_t
zephyr/include/zephyr/fs/fs.h:447:40: error: unknown type name 'off_t'; did you mean '_off_t'?
  447 | int fs_truncate(struct fs_file_t *zfp, off_t length);
      |                                        ^~~~~
      |                                        _off_t
zephyr/include/zephyr/sys/fdtable.h:48:17: error: expected specifier-qualifier-list before 'ssize_t'
   48 |                 ssize_t (*read)(void *obj, void *buf, size_t sz);
      |                 ^~~~~~~
zephyr/include/zephyr/sys/fdtable.h:52:17: error: expected specifier-qualifier-list before 'ssize_t'
   52 |                 ssize_t (*write)(void *obj, const void *buf, size_t sz);
      |                 ^~~~~~~
ninja: build stopped: subcommand failed.```
```

**Environment (please complete the following information):**
 - OS: (e.g. Linux)
 - Toolchain (e.g Zephyr SDK, ...) zephyr-sdk-0.16.8
 - Commit SHA or Version used: main after b82b5b0734c30490368e21627423f10036487343
 
**Additional info**
Introduced by #73978 
PR is not bisectable

Edited by @aescolar to encompass all cases of the same issue

### LINKED ISSUE #75208: posix: threads: do not blanket-define _POSIX_THREADS via cmake
**Describe the bug**

Prior to #51211, POSIX features were mostly all available all the time when `CONFIG_POSIX_API` was selected.

As part of the above ticket, POSIX features via Kconfig options that were crafted to resemble standard Options and Option Groups.

With that, we no longer need to blanket-define `-D_POSIX_THREADS`, which was originally required with external C libraries such as Newlib and Picolibc.

In fact, if `_POSIX_THREADS` is enabled, and `CONFIG_POSIX_THREADS` is not selected, it is a bug.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using? all
 - What have you tried to diagnose or workaround this issue? a lot
 - Is this a regression? no, it is a workaround that has existed in-tree for many years

**To Reproduce**

1. Select minimal Kconfig options in `prj.conf`
2. Select `CONFIG_EVENTFD=y`
3. Add a preprocessor statement of the form

```cpp
#if defined(_POSIX_THREADS)
#ifndef CONFIG_POSIX_THREADS
#error Feature _POSIX_THREADS is enabled but CONFIG_POSIX_THREADS is not selected (inconsistence)
#endif
#endif
```

**Expected behavior**
POSIX features should match the configuration

**Impact**
It introduces an element of instability / unexpected behaviour.

**Logs and console output**
```
Feature _POSIX_THREADS is enabled but CONFIG_POSIX_THREADS is not selected (inconsistence)
```

**Environment (please complete the following information):**
 - OS: any
 - Toolchain (e.g Zephyr SDK, ...): 0.16.8
 - Commit SHA or Version used: 40810983ead23c954bce113cb7ace50592451da4

**Additional context**

### PR DESCRIPTION
**Pull request by cfriedt**
* consolidate posix/time.h into time.h
* fix inconsistencies with posix and external implementations
* rename posix_features.h to sys/features.h

Fixes #75208

### CODE REVIEW

File: lib/posix/options/net.c [hunk 1]
```diff
@@ -15,6 +15,10 @@
 #include <zephyr/posix/net/if.h>
 #include <zephyr/posix/sys/socket.h>
 
+/* external libc compatibility / workaround */
+#undef snprintf
+extern int snprintf(char *ZRESTRICT buf, size_t size, const char *ZRESTRICT format, ...);
```
Comment (ycsin) [inline lib/posix/options/net.c:20]: maybe something to be fixed in picolibc/toolchain?
