### ISSUE TITLE
modules: openthread: undefined reference to `otThreadSetChildTimeout'

### ISSUE THREAD

**Issue by pdgendt** [zephyrproject-rtos/zephyr#95792]
### Describe the bug

Commit eca4dee0464bfde86fd942e22f7a8d19dd76cd56 introduced a build error for the co-processor sample.

### Regression

- [x] This is a regression.

### Steps to reproduce

```shell
$ west build -p -b nrf52840dk/nrf52840 samples/net/openthread/coprocessor -T sample.openthread.coprocessor.rcp
```

### Relevant log output

```shell
/home/pdgendt/.local/opt/zephyr-sdk-0.17.2/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: modules/openthread/libopenthread_utils.a(openthread.c.obj): in function `openthread_init':
/home/pdgendt/zephyrproject/zephyr/modules/openthread/openthread.c:359: undefined reference to `otChildSupervisionSetInterval'
/home/pdgendt/.local/opt/zephyr-sdk-0.17.2/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: /home/pdgendt/zephyrproject/zephyr/modules/openthread/openthread.c:361: undefined reference to `otChildSupervisionSetCheckTimeout'
/home/pdgendt/.local/opt/zephyr-sdk-0.17.2/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: /home/pdgendt/zephyrproject/zephyr/modules/openthread/openthread.c:363: undefined reference to `otThreadSetChildTimeout'
```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

**Comment by henrikbrixandersen** [comment]
Regression introduced in eca4dee0464bfde86fd942e22f7a8d19dd76cd56.
