### ISSUE TITLE
ci_nxp_build_failure: interrupt_controller: i.MX95 A55 links fail on undefined k_aligned_alloc

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#118431]
## Describe the bug

Network samples fail to link for `imx95_evk/mimx9596/a55` because the GICv3
and GICv3 ITS drivers reference `k_aligned_alloc`, but the symbol is undefined
at link time. The AArch64 linker also reports a truncated call relocation.

## Regression

Not confirmed. No `git bisect` has been performed.

## Steps to reproduce

1. Check out commit `434233e9751e7cca7bea82047e812bca607722d3`.
2. Build a network sample, for example `sample.net.pkt_filter`, for
   `imx95_evk/mimx9596/a55`.
3. Observe the link failure from the GICv3/GICv3 ITS driver objects.

## Relevant log output

```text
undefined reference to `k_aligned_alloc'
relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol
`k_aligned_alloc'
```

The references originate from:

```text
drivers/interrupt_controller/intc_gicv3.c
drivers/interrupt_controller/intc_gicv3_its.c
```

## Impact

Functional Limitation – multiple network samples cannot be linked for the A55
target on the i.MX95 EVK.

## Environment

- OS: Windows CI worker
- Board: `imx95_evk/mimx9596/a55`
- Toolchain: Zephyr SDK 1.0.1, GCC 14.3.0
- Zephyr version: `v4.4.0-14354-g434233e9751e`
- Commit: `434233e9751e7cca7bea82047e812bca607722d3`
- Affected samples include:
  - `sample.net.pkt_filter`
  - `sample.net.pkt_filter_priorities`
  - `sample.net.vlan`
  - `sample.net.stats`
  - `sample.net.promiscuous_mode`
  - `sample.net.virtual`
  - `sample.net.capture`

## Additional Context

No exact matching upstream issue was found for
`"k_aligned_alloc" "intc_gicv3"`. This is reported separately from the
independent i.MX95 NETC compile error (`ENETC_SI_BDR_COUNT`) seen in the same
CI build.

**Comment by hakehuang** [comment]
Bisection scope update: this is not marked as a regression. The i.MX95 A55 NETC support commit 5a56cb6fc07df4c808b67ea166e27a26b0b751fa (boards: imx95_evk: a55: add NETC support) enables GIC_V3_ITS when ETH_NXP_IMX_NETC is selected. This activates the pre-existing k_aligned_alloc references in intc_gicv3.c and intc_gicv3_its.c; the affected board configuration did not enable this path before that commit. At 434233e9751e7cca7bea82047e812bca607722d3, the newly enabled path fails to link.

**Comment by hakehuang** [comment]
﻿NXP upstream CI still reproduces this at
`a5244984a05bdad810c645aa9efe47da4f004cce`
(`v4.4.0-15083-ga5244984a05b`) with Zephyr SDK 1.0.1 / GCC 14.3.0.

Affected i.MX95 A55 samples in this run:

- `sample.net.capture`
- `sample.net.pkt_filter`
- `sample.net.pkt_filter_priorities`
- `sample.net.virtual`
- `sample.net.vlan`
- `sample.net.stats`
- `sample.net.promiscuous_mode`

The Twister summary continues to report `undefined reference to
k_aligned_alloc` for each. This is independent of the NETC compile error in
#118430, also present at the same commit.

**Comment by tpambor** [comment]
Duplicate of https://github.com/zephyrproject-rtos/zephyr/issues/118556?

**Comment by JiafeiPan** [comment]
Dupicated with https://github.com/zephyrproject-rtos/zephyr/issues/120032

**Comment by JiafeiPan** [comment]
Created a fix for this issue: https://github.com/zephyrproject-rtos/zephyr/pull/120031
