### PR TITLE
[ARM] Fix build break for ARMV8_M_BASELINE

### LINKED ISSUE #79594: tests/subsys/debug/coredump* fail to build for for ARM m33 processors
**Describe the bug**
1. Building with CONFIG_DEBUG_COREDUMP for ARM core m33 processors will result in a built failure.
2. tests/subsys/debug/coredump* fail to build for ARM core m33 processors

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=mps2/an521/cpu0 -GNinja ../tests/subsys/debug/coredump_threads/
3. ninja

OR 
1. mkdir build; cd build
2. cmake -DBOARD=mps2/an521/cpu0 -GNinja ../samples/hello_world/ -DCONFIG_DEBUG_COREDUMP=y
3. ninja

**Expected behavior**
No build failures

**Impact**
* Failing CI in  main
* Some PRs blocked

**Logs and console output**
``` 
In file included from /__w/zephyr/zephyr/arch/arm/include/kernel_arch_data.h:29,
                 from /__w/zephyr/zephyr/arch/arm/core/offsets/offsets_aarch32.c:29,
                 from /__w/zephyr/zephyr/arch/arm/core/offsets/offsets.c:9:
/__w/zephyr/zephyr/arch/arm/include/cortex_m/exception.h: In function 'z_arm_set_fault_sp':
/__w/zephyr/zephyr/arch/arm/include/cortex_m/exception.h:261:32: error: 'SCB_CCR_STKALIGN_Msk' undeclared (first use in this function); did you mean 'SCB_CCR_BFHFNMIGN_Msk'?
  261 |         if ((esf->basic.xpsr & SCB_CCR_STKALIGN_Msk) == SCB_CCR_STKALIGN_Msk) {
      |                                ^~~~~~~~~~~~~~~~~~~~
      |                                SCB_CCR_BFHFNMIGN_Msk
/__w/zephyr/zephyr/arch/arm/include/cortex_m/exception.h:261:32: note: each undeclared identifier is reported only once for each function it appears in
``` 
https://github.com/zephyrproject-rtos/zephyr/actions/runs/11250552333/job/31279885750#step:11:1033

**Environment (please complete the following information):**

 - OS: Ubuntu 22.04 CI
 - Toolchain (e.g Zephyr SDK, ...): 0.16.8
 - Commit SHA or Version used : main since ec7943bb181753c9b7dc339090a2e7f4b9d7f06e

**Additional context**
Introduced by https://github.com/zephyrproject-rtos/zephyr/pull/73189
The ARM CoreM33 SCB CCR register does not have a STKALIGN field

### PR DESCRIPTION
**Pull request by mrkhldn**
The STKALIGN mask is not present for CONFIG_ARMV8_M_BASELINE as well as CONFIG_ARMV8_M_MAINLINE. So filter out that check when setting the sp for ARM core dumps.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/79594

### CODE REVIEW

**Review by ithinuel — APPROVED** [review]

**Comment by pdgendt** [comment]
Update the commit subject to conform to the [commit message guidelines](https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-message-guidelines) and be a bit more descriptive, for example: `arch: arm: Don't use STKALIGN mask on ARMv8-M Baseline`

**Comment by mmahadevan108** [comment]
@mrkhldn , can you address the comment for @pdgendt.

**Comment by pdgendt** [comment]
The commit subject looks good, can't comment on the actual PR itself.

**Review by mmahadevan108 — APPROVED** [review]
