### PR TITLE
drivers: ethernet: stm32: Clean MAC address size assertions

### PR DESCRIPTION
**Pull request by etienne-lms**
Remove the assertion in eth_stm32_hal_v1.c recently introduce between byte array sizes storing MAC address value. It was useless since both byte array sizes are based on NET_ETH_ADDR_LEN macro. Moreover the assertion may produce a build warning as reported (and fixed) in eth_stm32_hal_v2.c by commit 0ee22dc99841 ("drivers: ethernet: stm32: fix clang error").

Factorize the 2 build assertions in eth_stm32_hal2.c with an explicit comment why it's used.

### CODE REVIEW

**Review by tpambor — DISMISSED** [review]

**Comment by etienne-lms** [comment]
My apologizes for the ugly build assertion**s** introduced in 1f2cae602baac42982146130f57362629dc48bea.

**Review by GeorgeCGV — DISMISSED** [review]

**Review by mathieuchopstm — DISMISSED** [review]

File: drivers/ethernet/eth_stm32_hal2.c [hunk 1]
```diff
@@ -49,6 +49,9 @@ LOG_MODULE_REGISTER(eth_stm32_hal, CONFIG_ETHERNET_LOG_LEVEL);
 NET_BUF_POOL_DEFINE(rx_net_buf_pool, CONFIG_ETH_STM32_HAL_RX_BUF_POOL_COUNT, ETH_STM32_RX_BUF_SIZE,
 		    0, NULL);
 
+/* Make memcpy() for MAC address array safe between the HAL structure and the Zephyr one */
+BUILD_ASSERT(sizeof(((struct hal_eth_config_t *)NULL)->mac_addr) == NET_ETH_ADDR_LEN);
```
Comment (juickar) [inline drivers/ethernet/eth_stm32_hal2.c]:
```suggestion
BUILD_ASSERT(sizeof(((hal_eth_config_t *)NULL)->mac_addr) == NET_ETH_ADDR_LEN);
```
remove struct as it is defined as a 
`typedef struct { ... } hal_eth_config_t` 
and not as a  
`struct hal_eth_config_t { ... `}.

It leads to the following error when building :

> $/zephyrproject/zephyr/drivers/ethernet/eth_stm32_hal2.c:53:54: error: invalid use of undefined type 'struct hal_eth_config_t'

**Review by juickar — CHANGES_REQUESTED** [review]

File: drivers/ethernet/eth_stm32_hal2.c (hunk 1 above)
Comment (etienne-lms) [reply drivers/ethernet/eth_stm32_hal2.c]: My bad. It seems I've build the wrong target checking this.
Thanks @juickar

**Comment by etienne-lms** [comment]
Updated.

**Review by juickar — APPROVED** [review]

**Review by GeorgeCGV — APPROVED** [review]

**Review by maass-hamburg — APPROVED** [review]

**Review by tpambor — APPROVED** [review]

**Review by erwango — APPROVED** [review]
