### PR TITLE
drivers: spi: spi_pico_pio: Implement DMA support for 4-wire operation

### PR DESCRIPTION
**Pull request by TerryGeng**
This commit largely mirrors the approach of implementing DMA in the pl022 driver.

Though https://github.com/zephyrproject-rtos/zephyr/pull/85112 is still pending, I figured out that maybe it is enough for users to only specify the DMA channels and figure out the DREQ by myself in the code. I have been working on a personal project that uses DMA with PIO so I think it is to the benefit of the community if I submit it here.

Also included here is an updated version of the spi loopback test that includes a case for PIO with DMA.

### CODE REVIEW

File: drivers/spi/spi_rpi_pico_pio.c [hunk 1]
```diff
@@ -23,20 +23,44 @@ LOG_MODULE_REGISTER(spi_pico_pio);
...
+struct spi_pico_pio_dma_config {
+	const struct device *dev;
+	uint32_t tx_channel;
+	uint32_t rx_channel;
+};
+
 struct spi_pico_pio_config {
 	const struct device *piodev;
 	const struct pinctrl_dev_config *pin_cfg;
+	const bool dma_enabled;
```
Comment (tbursztyka) [inline drivers/spi/spi_rpi_pico_pio.c:54]: Do you really need this? is dma_config.dev is non NULL it would be the same no? 
(this bool is misaligning your struct thus why there is perhaps a way to not introduce it)

Comment (TerryGeng) [reply drivers/spi/spi_rpi_pico_pio.c]: Yes, I agree with you. I was just mimicking what was done in the pl022 driver, and I think your comment will apply to the pl022 driver equally well.

File: drivers/spi/spi_rpi_pico_pio.c [hunk 2]
```diff
@@ -447,11 +669,6 @@ static void spi_pico_pio_txrx_4_wire(const struct device *dev)
 	uint32_t txrx;
 	size_t fifo_cnt = 0;
 
-	data->tx_count = 0;
-	data->rx_count = 0;
-
-	pio_sm_clear_fifos(data->pio, data->pio_sm);
-
 	while (data->rx_count < chunk_len || data->tx_count < chunk_len) {
```
Comment (ajf58) [inline drivers/spi/spi_rpi_pico_pio.c:672]:
```suggestion
	while ((data->rx_count < chunk_len) || (data->tx_count < chunk_len)) {
```

**Review by ajf58 — APPROVED** [review]
A couple of nits, but nothing that should be blocking.

File: tests/drivers/spi/spi_loopback/boards/rpi_pico_pio_dma.overlay [hunk 3]
```diff
@@ -0,0 +1,50 @@
...
+			pinmux = <PIO0_P16>;
+			input-enable;
+		};
+	};
+};
+
+&pio0 {
+	status = "okay";
+
+	pio0_spi0: pio0_spi0 {
```
[the remark this answers is not in the document]
Comment (TerryGeng) [reply tests/drivers/spi/spi_loopback/boards/rpi_pico_pio_dma.overlay]: Yes, it is doable. My original intent is to present a good snippet of code that people can just copy and paste. As you know, it is tricky to get DTS done in the right way, especially for the DMAs, since if the channel configuration is not correct, the DMA will be silently disabled.

[the remark this answers is not in the document]
Comment (TerryGeng) [reply tests/drivers/spi/spi_loopback/boards/rpi_pico_pio_dma.overlay]: I implemented what you suggested anyway. Please take a look.

**Review by ajf58 — DISMISSED** [review]

**Comment by TerryGeng** [comment]
@tbursztyka @soburi It has been quite a while since the last activity. Would you guys help with reviewing this PR?

File: tests/drivers/spi/spi_loopback/testcase.yaml [hunk 4]
```diff
@@ -217,6 +217,16 @@ tests:
...
       - EXTRA_CONF_FILE="overlay-rpi-pico-pio.conf"
     platform_allow: rpi_pico
+  drivers.spi.pio_spi_dma.loopback:
+    extra_args:
+      - DTC_OVERLAY_FILE="boards/rpi_pico_pio.overlay"
+      - EXTRA_DTC_OVERLAY_FILE="boards/rpi_pico_pio_dma.overlay"
+      - EXTRA_CONF_FILE="overlay-rpi-pico-pio.conf"
+    extra_configs:
+      - CONFIG_SPI_RPI_PICO_PIO_DMA=y
+      - CONFIG_DMA=y
```
Comment (tbursztyka) [inline tests/drivers/spi/spi_loopback/testcase.yaml:227]: Superfluous as the option one line before selects it.

**Review by tbursztyka — COMMENTED** [review]
I can't judge much on the pio side, we would need knowledgeable ppl here. But if the test passes that's already a good sign

**Comment by ajf58** [comment]
@TerryGeng it looks like this has merge conflicts due to changes on `main`. Please rebase and push an updated version of your source branch.

**Comment by TerryGeng** [comment]
Bump this PR up.

**Comment by ajf58** [comment]
The "compliance check" failed in CI, but was too long ago that appears the log has gone. Similarly there's now merge conflicts with the `main` branch. It feels like a good time to rebase, tackle the merge conflicts, and then see if there's still compliance issues.

**Comment by TerryGeng** [comment]
@ajf58 Apologize for the long absence... Let me see if there is a chance I can have a look at it today.

**Comment by TerryGeng** [comment]
@ajf58 Rebased.

File: tests/drivers/spi/spi_loopback/testcase.yaml (hunk 4 above)
Comment (tbursztyka) [reply tests/drivers/spi/spi_loopback/testcase.yaml]: please apply the suggested change, I would be happy to approve your PR

**Comment by TerryGeng** [comment]
@tbursztyka I have fixed the config files. Running the test case this time shows a bunch of failures. I believe these failed test cases are recently added in https://github.com/zephyrproject-rtos/zephyr/pull/87838. Those test cases also failed for `drivers.spi.pio_spi.loopback`. I believe this is a more general problem of the PIO SPI driver at this moment, that some unsupported SPI config wasn't being properly rejected, but that is beyond the scope of this PR.

**Comment by TerryGeng** [comment]
I opened an issue regarding the failed test cases: #94416. I might open a new PR to fix that if time permits.

**Comment by TerryGeng** [comment]
@ajf58 @tbursztyka Would you mind approving this PR again?

File: drivers/spi/spi_rpi_pico_pio.c (hunk 1 above)
Comment (tbursztyka) [reply drivers/spi/spi_rpi_pico_pio.c]: sure, but pl022 code is already in (we missed it, this would need the maintainer of the driver to fix it), not yours.

**Comment by tbursztyka** [comment]
> @tbursztyka I have fixed the config files. Running the test case this time shows a bunch of failures. I believe these failed test cases are recently added in #87838. Those test cases also failed for `drivers.spi.pio_spi.loopback`. I believe this is a more general problem of the PIO SPI driver at this moment, that some unsupported SPI config wasn't being properly rejected, but that is beyond the scope of this PR.

Sure, would be nice to see another PR addressing these failing tests

**Review by tbursztyka — DISMISSED** [review]

File: drivers/spi/spi_rpi_pico_pio.c [hunk 5]
```diff
@@ -438,6 +478,187 @@ static int spi_pico_pio_configure(const struct spi_pico_pio_config *dev_cfg,
...
+	if (MIN(data->tx_count, data->rx_count) >= chunk_len) {
+		spi_context_update_tx(&data->spi_ctx, 1, chunk_len);
+		spi_context_update_rx(&data->spi_ctx, 1, chunk_len);
+
+		if (spi_pico_pio_transfer_ongoing(data)) {
+			/* Next chunk is available, reset the count and
+			 * continue processing
+			 */
+			data->tx_count = 0;
+			data->tx_count = 0;
```
Comment (kartben) [inline drivers/spi/spi_rpi_pico_pio.c]: ?

```suggestion
			data->rx_count = 0;
```

File: drivers/spi/spi_rpi_pico_pio.c [hunk 6]
```diff
@@ -438,6 +478,187 @@ static int spi_pico_pio_configure(const struct spi_pico_pio_config *dev_cfg,
...
+		LOG_ERR("dma:%p ch:%d callback gets error: %d", dma_dev, channel, status);
+		spi_pico_pio_dma_complete(dev, status);
+
+		k_spin_unlock(&data->lock, key);
+		return;
+	}
+
+	if (dma_dev != dev_cfg->dma_config.dev) {
+		/* rpi pico has only one dma controller so far
+		 * so this is branch will never run in theory.
```
Comment (kartben) [inline drivers/spi/spi_rpi_pico_pio.c]:
```suggestion
		 * so this branch will never run in theory.
```

File: drivers/spi/spi_rpi_pico_pio.c (hunk 5 above)
Comment (TerryGeng) [reply drivers/spi/spi_rpi_pico_pio.c]: Oops.... this is the result of a recent rebase. Fixed.

**Comment by TerryGeng** [comment]
@tbursztyka @ajf58 @kartben Would you please approve again?

**Review by tbursztyka — APPROVED** [review]

**Review by kartben — APPROVED** [review]

**Comment by MagpieEmbedded** [comment]
This PR appears to have caused a regression as picked up in #94897 for the Pico W and Pico 2W boards which rely on SPI half duplex mode. As I've explained on the issue, on line 323 of `drivers/spi/spi_rpi_pico_pio.c` the `dma_config` member is referenced even though it doesn't exist as the definition on line 61 depends on `CONFIG_SPI_RPI_PICO_PIO_DMA` being defined.

This is the build error:

```
/home/tim/zephyr_workspace/zephyr/drivers/spi/spi_rpi_pico_pio.c: In function 'spi_pico_pio_configure':
/home/tim/zephyr_workspace/zephyr/drivers/spi/spi_rpi_pico_pio.c:323:28: error: 'const struct spi_pico_pio_config' has no member named 'dma_config'
  323 |                 if (dev_cfg->dma_config.dev) {
      |      
```

Making the following change gets the W variants working again:

```
diff --git a/drivers/spi/spi_rpi_pico_pio.c b/drivers/spi/spi_rpi_pico_pio.c
index 6421ec6d16e..fddfd72e136 100644
--- a/drivers/spi/spi_rpi_pico_pio.c
+++ b/drivers/spi/spi_rpi_pico_pio.c
@@ -320,10 +320,10 @@ static int spi_pico_pio_configure(const struct spi_pico_pio_config *dev_cfg,
 
 #if SPI_RPI_PICO_PIO_HALF_DUPLEX_ENABLED
        if (spi_cfg->operation & SPI_HALF_DUPLEX) {
-               if (dev_cfg->dma_config.dev) {
-                       LOG_ERR("DMA not supported in 3-wire operation");
-                       return -ENOTSUP;
-               }
+               // if (dev_cfg->dma_config.dev) {
+               //      LOG_ERR("DMA not supported in 3-wire operation");
+               //      return -ENOTSUP;
+               // }
```

There was some discussion about whether or not to include a `dma_enabled` type flag. It looks like this is a possible use case based on the pl022 driver this driver is based on? In principle, should a program should be able to use the PIO pins to have (at least) one DMA based SPI and one non-DMA SPI?

**Comment by TerryGeng** [comment]
@MagpieEmbedded Good catch. I think there is a quick fix: Would you try wrapping up this if-branch with `#if defined(CONFIG_SPI_RPI_PICO_PIO_DMA)` and `#endif`?

Here is the full patch:

```diff
diff --git a/drivers/spi/spi_rpi_pico_pio.c b/drivers/spi/spi_rpi_pico_pio.c
index 6421ec6d16e..6bd4848a00d 100644
--- a/drivers/spi/spi_rpi_pico_pio.c
+++ b/drivers/spi/spi_rpi_pico_pio.c
@@ -320,10 +320,12 @@ static int spi_pico_pio_configure(const struct spi_pico_pio_config *dev_cfg,

 #if SPI_RPI_PICO_PIO_HALF_DUPLEX_ENABLED
        if (spi_cfg->operation & SPI_HALF_DUPLEX) {
+#if defined(CONFIG_SPI_RPI_PICO_PIO_DMA)
                if (dev_cfg->dma_config.dev) {
                        LOG_ERR("DMA not supported in 3-wire operation");
                        return -ENOTSUP;
                }
+#endif

                if ((cpol != 0) || (cpha != 0)) {
                        LOG_ERR("Only mode (0, 0) supported in 3-wire SIO");
```

Upon inserting this, I can compile without any errors. I think this is the only place I invoked dma_config without checking whether DMA is enabled.

**Comment by MagpieEmbedded** [comment]
Thanks for looking at this so quickly! Yes that works for me 👍 Are you happy to raise a PR with that patch? Or I can do it if that's easier.

**Comment by TerryGeng** [comment]
No worries. I have just opened https://github.com/zephyrproject-rtos/zephyr/pull/94910 with this patch. Would you have a look? Thanks.
