### ISSUE TITLE
cmake failure when using ZEPHYR_MODULES without west

### ISSUE THREAD

**Issue by Abhishek-brcm** [zephyrproject-rtos/zephyr#26948]
**Describe the bug**
 I am getting below compilation error for  `bcm958402m2_m7` board on latest zephyr:

```
CMake Error at /home/zephyr/cmake/zephyr_module.cmake:45 (message):
  Traceback (most recent call last):
    File "/home/zephyr/scripts/zephyr_module.py", line 275, in <module>
      main()
    File "/home/zephyr/scripts/zephyr_module.py", line 201, in main
      projects += args.extra_modules
  UnboundLocalError: local variable 'projects' referenced before assignment

```
**To Reproduce**
`cmake -GNinja -B build/ -DBOARD=bcm958402m2_m7 -DZEPHYR_MODULES=<PATH TO hal/cmsis/ directory> samples/hello_world/
`

**Expected behavior**
This issue seems to be introduced in commit ef3c5e551676278ccc1f42ecb572838144c5e33a (as pointed by @nashif ).

**Comment by carlescufi** [comment]
I see the bug, I will post a fix now.
