### ISSUE TITLE
[v4.4] net: sockets: tls: `addr` may be used uninitialized

### ISSUE THREAD

**Issue by JordanYates** [zephyrproject-rtos/zephyr#108466]
### Describe the bug

TLS sockets library compiles with warnings by default on Zephyr v4.4

### Regression

- [x] This is a regression.

### Relevant log output

```shell
/home/jordan/code/workspace/zephyr/subsys/net/lib/sockets/sockets_tls.c: In function ‘dtls_client_rx’:
/home/jordan/code/workspace/zephyr/subsys/net/lib/sockets/sockets_tls.c:1038:20: error: ‘addr’ may be used uninitialized [-Werror=maybe-uninitialized]
 1038 |         received = zsock_recvfrom(tls_ctx->sock, buf, len,
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1039 |                                   ZSOCK_MSG_DONTWAIT, net_sad(&addr), &addrlen);
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/jordan/code/workspace/zephyr/include/zephyr/net/socket.h:33,
                 from /home/jordan/code/workspace/zephyr/subsys/net/lib/sockets/sockets_tls.c:16:
/home/jordan/code/workspace/zephyr/include/zephyr/net/net_ip.h:1904:36: note: by argument 1 of type ‘const struct net_sockaddr_storage *’ to ‘net_sad’ declared here
 1904 | static inline struct net_sockaddr *net_sad(const struct net_sockaddr_storage *addr)
      |                                    ^~~~~~~
/home/jordan/code/workspace/zephyr/subsys/net/lib/sockets/sockets_tls.c:1035:37: note: ‘addr’ declared here
 1035 |         struct net_sockaddr_storage addr;
      |                                     ^~~~
/home/jordan/code/workspace/zephyr/subsys/net/lib/sockets/sockets_tls.c: In function ‘dtls_server_rx’:
/home/jordan/code/workspace/zephyr/subsys/net/lib/sockets/sockets_tls.c:985:20: error: ‘addr’ may be used uninitialized [-Werror=maybe-uninitialized]
  985 |         received = zsock_recvfrom(tls_ctx->sock, &tmp_buf, sizeof(tmp_buf),
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  986 |                                   ZSOCK_MSG_DONTWAIT | ZSOCK_MSG_PEEK,
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  987 |                                   net_sad(&addr), &addrlen);
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jordan/code/workspace/zephyr/include/zephyr/net/net_ip.h:1904:36: note: by argument 1 of type ‘const struct net_sockaddr_storage *’ to ‘net_sad’ declared here
 1904 | static inline struct net_sockaddr *net_sad(const struct net_sockaddr_storage *addr)
      |                                    ^~~~~~~
/home/jordan/code/workspace/zephyr/subsys/net/lib/sockets/sockets_tls.c:979:37: note: ‘addr’ declared here
  979 |         struct net_sockaddr_storage addr;
      |                                     ^~~~
/home/jordan/code/workspace/zephyr/subsys/net/lib/sockets/sockets_tls.c: In function ‘dtls_server_switch_session_on_rx’:
/home/jordan/code/workspace/zephyr/subsys/net/lib/sockets/sockets_tls.c:1224:15: error: ‘addr’ may be used uninitialized [-Werror=maybe-uninitialized]
 1224 |         ret = zsock_recvfrom(tls_ctx->sock, &tmp_buf, sizeof(tmp_buf),
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1225 |                              ZSOCK_MSG_DONTWAIT | ZSOCK_MSG_PEEK,
      |                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1226 |                              net_sad(&addr), &addrlen);
      |                              ~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jordan/code/workspace/zephyr/include/zephyr/net/net_ip.h:1904:36: note: by argument 1 of type ‘const struct net_sockaddr_storage *’ to ‘net_sad’ declared here
 1904 | static inline struct net_sockaddr *net_sad(const struct net_sockaddr_storage *addr)
      |                                    ^~~~~~~
/home/jordan/code/workspace/zephyr/subsys/net/lib/sockets/sockets_tls.c:1219:37: note: ‘addr’ declared here
 1219 |         struct net_sockaddr_storage addr;
```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

- Zephyr v4.4.0

### Additional Context

Originally fixed in #108147, issue for backporting

**Comment by nashif** [comment]
fixed already
