### PR TITLE
drivers: uart_mux: Fix build issue

### PR DESCRIPTION
**Pull request by HrMitrev**
The build failed when CONFIG_GSM_MUX=y

Signed-off-by: Hristo Mitrev <hr.mitrev@gmail.com>

### CODE REVIEW

**Comment by HrMitrev** [comment]
This is my first pull request ever. Not sure if I signed it successfully or if I followed all the guidelines.

**Comment by ycsin** [comment]
I think I never had issues with building with `CONFIG_GSM_MUX`, do you have the log when it fails to build?

**Comment by HrMitrev** [comment]
Yes

image

-c /home/hrm/git/zephyr_sdk/zephyr/drivers/console/uart_mux.c
/home/hrm/git/zephyr_sdk/zephyr/drivers/console/uart_mux.c:76:1: error: expected ',' or ';' before 'extern'
   76 | extern struct uart_mux __uart_mux_start[];
      | ^~~~~~
/home/hrm/git/zephyr_sdk/zephyr/drivers/console/uart_mux.c: In function 'init_real_uart':
/home/hrm/git/zephyr_sdk/zephyr/drivers/console/uart_mux.c:346:19: error: '__uart_mux_start' undeclared (first use in this function); did you mean 'uart_mux_stack'?
  346 |  for (real_uart = __uart_mux_start; real_uart != __uart_mux_end;
      |                   ^~~~~~~~~~~~~~~~
      |                   uart_mux_stack
/home/hrm/git/zephyr_sdk/zephyr/drivers/console/uart_mux.c:346:19: note: each undeclared identifier is reported only once for each function it appears in

**Comment by ycsin** [comment]
Seems like it might be introduced by 47ae656cc1b9e18216a6c0e510ba3e3a37898aee

**Review by jukkar — APPROVED** [review]

**Review by rerickson1 — APPROVED** [review]

**Review by rlubos — APPROVED** [review]

**Comment by ycsin** [comment]
Would be nice if the [modem build test](https://github.com/zephyrproject-rtos/zephyr/tree/main/tests/drivers/build_all/modem) can be updated to test the gsm_mux configuration so that this is tested in the future
