### PR TITLE
tests: llext: compile architectures not supported yet

### PR DESCRIPTION
**Pull request by marc-hb**
For now llext supports a very limited number of architectures.  This restriction is enforced by add_llext_target() in CMake at configuration time.

Add a new `LOADER_BUILD_ONLY` conditional in `tests/subsys/llext/simple/` and a new `llext.simple.loader_build`, `build_only` test that does not invoke `add_llext_target()` and only compiles the llext framework code.

This helps find and fix bugs in `subsys/llext/*.c` and make it ready to be used when add_llext_target() limitations are lifted.

Note this is pure `tests/` change without any change in the actual llext framework code. The existing test is only modified to conditionally invoke add_llext_target().

### CODE REVIEW

**Comment by marc-hb** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/70000/checks?check_run_id=22476480950 show the expected `printf` failures and shift width failures that motivated this new test in the first place. Examples below.

```
__w/zephyr/zephyr/subsys/llext/llext.c:160:25: error: format '%x' expects argument of type 'unsigned int', but argument 3 has type 'elf64_off' {aka 'long long unsigned int'} [-Werror=format=]
  160 |                 LOG_DBG("section %d at %x: name %d, type %d, flags %x, addr %x, size %d",
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  161 |                         i,
  162 |                         ldr->hdr.e_shoff + i * ldr->hdr.e_shentsize,
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                          |
      |                                          elf64_off {aka long long unsigned int}
```

```
/__w/zephyr/zephyr/include/zephyr/llext/elf.h:349:29: error: right shift count >= width of type [-Werror=shift-count-overflow]
  349 | #define ELF64_R_SYM(i) ((i) >> 32)
      |                             ^~

```

**Comment by marc-hb** [comment]
Fixes submitted in #70002 and successfully tested there. Keeping this #70000 test as a draft until fixes in #70002 are merged.

**Review by pillo79 — DISMISSED** [review]
LGTM!

**Review by teburd — DISMISSED** [review]

**Comment by marc-hb** [comment]
https://github.com/zephyrproject-rtos/zephyr/actions/runs/8268746414 all green but brand new conflict with #70100

**Review by teburd — APPROVED** [review]

**Review by bjarki-andreasen — APPROVED** [review]

**Review by pillo79 — APPROVED** [review]

**Review by lyakh — APPROVED** [review]

**Review by bjarki-andreasen — APPROVED** [review]

**Comment by marc-hb** [comment]
Commit https://github.com/zephyrproject-rtos/zephyr/commit/ce243944375e46e94346bfb3dcbe8c499fc4996b ("llext: add object test case") and this commit https://github.com/zephyrproject-rtos/zephyr/commit/1408d1e5b8cefcb0f4d52c1ffb41849f70826f39 ("tests: llext: compile architectures not supported yet") conflict with each other. They were submitted concurrently, tested separately and merged around the same time. All PRs fail now :-(

Please review hotfix #70406 urgently.
