### ISSUE TITLE
gen_kobject_list.py: AttributeError: 'ConstType' object has no attribute 'size' when array member type is const-qualified

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#115618]
**Describe the bug**
The kobject generation script `scripts/build/gen_kobject_list.py` crashes with `AttributeError: 'ConstType' object has no attribute 'size'` during the build. It happens when processing an array whose member type resolves to a `ConstType` (a `const`-qualified kernel object). `ArrayType.get_kobjects()` (line 277) computes each element's address as `addr + (i * mt.size)`, but `ConstType` does not define a `size` attribute (only `ArrayType`, `AggregateType`, and `KobjectType` do).

**To Reproduce**
Build the EEPROM driver build-all test on `frdm_mcxa577`:
```
twister -p frdm_mcxa577/mcxa577 -T tests/drivers/build_all/eeprom
```

# [x] is_regression

bf871df8e3d02bdeedc69da8d86a948a35da6b88 is the first bad commit
commit bf871df8e3d02bdeedc69da8d86a948a35da6b88
Author: Peter Wang <chaoyi.wang@nxp.com>
Date:   Mon Jun 29 16:26:32 2026 +0800

    boards: arm: nxp: frdm_mcxa577: add I3C thermometer support

    Enable I3C0 on the FRDM-MCXA577 board and register the on-board
    NXP P3T1755 temperature sensor as an I3C device. The clock is
    sourced from FRO_LF_DIV with divider 1 (per the board SDK
    hardware_init reference). Pins P0_20 (SDA), P0_21 (SCL), and
    P0_2 (PUR) are configured via a new pinmux_i3c0 group (verified
    against the SDK BOARD_InitI3CPins implementation).

    Add the ambient-temp0 alias required by the thermometer sample,
    list i3c in the board's supported features, and add frdm_mcxa577
    to the sample.sensor.thermometer_i3c integration platforms.

    Tested by building samples/sensor/thermometer.

    Signed-off-by: Peter Wang <chaoyi.wang@nxp.com>

 boards/nxp/frdm_mcxa577/board.c                   |  6 ++++++
 boards/nxp/frdm_mcxa577/frdm_mcxa577-pinctrl.dtsi | 18 ++++++++++++++++++
 boards/nxp/frdm_mcxa577/frdm_mcxa577.dtsi         | 17 +++++++++++++++++
 boards/nxp/frdm_mcxa577/frdm_mcxa577.yaml         |  1 +
 samples/sensor/thermometer/sample.yaml            |  1 +
 5 files changed, 43 insertions(+)

**Expected behavior**
Build completes; the kobject list generation handles `const`-qualified array members without crashing.

**Impact**
Build failure — the affected configuration cannot be built.

**Logs and console output**
```
FAILED: zephyr/kobject_prebuilt_hash.gperf
Traceback (most recent call last):
  File ".../scripts/build/gen_kobject_list.py", line 1102, in <module>
    main()
  File ".../scripts/build/gen_kobject_list.py", line 1065, in main
    objs = find_kobjects(elf, syms)
  File ".../scripts/build/gen_kobject_list.py", line 655, in find_kobjects
    objs = type_obj.get_kobjects(addr)
  File ".../scripts/build/gen_kobject_list.py", line 329, in get_kobjects
    return type_env[self.child_type].get_kobjects(addr)
  File ".../scripts/build/gen_kobject_list.py", line 277, in get_kobjects
    objs.update(mt.get_kobjects(addr + (i * mt.size)))
AttributeError: 'ConstType' object has no attribute 'size'
ninja: build stopped: subcommand failed.
```

**Environment (please complete the following information):**
- OS: Linux (CI)
- Zephyr version: `v4.4.0-10692-g782566d7f8ba`
- Board: `frdm_mcxa577/mcxa577`
- Test: `drivers.eeprom.build` (`tests/drivers/build_all/eeprom`)

**Additional context**
`ConstType` (line 315) implements `has_kobject()` and `get_kobjects()` but has no `size` attribute, so it cannot be used as an array member type where element stride is required. A fix could add a `size` property to `ConstType` that delegates to its `child_type`, or `ArrayType.get_kobjects()` could resolve through const qualifiers before computing the stride.

**Comment by ZhaoxiangJin** [comment]
duplicate with https://github.com/zephyrproject-rtos/zephyr/issues/113105
fix: https://github.com/zephyrproject-rtos/zephyr/pull/113651
