### PR TITLE
soc: imx7d: fix CPP application building error (issue: 64784)

### PR DESCRIPTION
**Pull request by JiafeiPan**
This patch is to fix issue [64784](https://github.com/zephyrproject-rtos/zephyr/issues/64784)

For CPP application, such as samples/cpp/cpp_synchronization/, it will report the following building errors:

...
zephyrproject/modules/hal/nxp/imx/devices/MCIMX7D/./MCIMX7D_M4.h:5101:51: error:
	'reinterpret_cast<CCM_Type*>(808976384)' is not a constant expression
...

The error is caused by commit: 72312feeadcdffd6e0f5d5d0d73a75110c7109b7 " arch: arm: cortex_m: Use cmsis api instead of inline asm in arch_irq_*" This patch will cause kernel.h includes cmsis_core.h which includes soc.h, so that soc.h will be used by c++ code.

This patch make soc.h can be c++ compatible.

### CODE REVIEW

**Comment by ithinuel** [comment]
If that’s OK not to include those in the case of cpp, is it be ok not to include them at all?

**Comment by JiafeiPan** [comment]
> If that’s OK not to include those in the case of cpp, is it be ok not to include them at all from `soc.h`?

No, at least we need to include MCIMX7D_M4.h which is used by CMSIS. Commit 72312feeadcdffd6e0f5d5d0d73a75110c7109b7 changed to use CMSIS APIs in cmsis_core.h to replace  some inline APIs in asm_inline_gcc.h.

**Comment by ithinuel** [comment]
Right, I meant the includes that are gated off in [this PR](https://github.com/zephyrproject-rtos/zephyr/pull/72047/files#diff-162a092a9fefb185b2779d2beab381e993498e12f3e0a7a857db86d46874f1deR14-R22). If they are essential neither to CPP nor to C, they may as well be removed completely.

**Comment by JiafeiPan** [comment]
> Right, I meant the includes that are gated off in [this PR](https://github.com/zephyrproject-rtos/zephyr/pull/72047/files#diff-162a092a9fefb185b2779d2beab381e993498e12f3e0a7a857db86d46874f1deR14-R22). If they are essential neither to CPP nor to C, they may as well be removed completely.

These header files are essential for some C code drivers, the drivers are reused for many platforms, as we can include soc.h in the drivers but not include imx7d specific header files directly, so we need to keep these header files in soc.h.

**Comment by jlh-makeen** [comment]
@JiafeiPan Thanks for the fix, I will try it on my board as soon as possible and report back :-)

**Comment by jlh-makeen** [comment]
I confirm that this fix allows me to build my application for our cl-som-imx7d on our carrier board and the application starts normally with C++ usage !

**Review by decsny — APPROVED** [review]
thanks for handling this so quickly jiafei

**Review by jlh-makeen — APPROVED** [review]
Tested on cl-som-imx7d with c++

**Review by dleach02 — APPROVED** [review]
