### PR TITLE
util.h: Add dependency on time_units.h

### LINKED ISSUE #56006: Circular dependency between sys/util.h and sys/time_units.h
**Describe the bug**

The `WAIT_FOR` macro in `zephyr/sys/util.h` uses `k_us_to_cyc_ceil32` https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/sys/util.h#L616

This function is defined in `zephyr/sys/time_units.h`, but `time_units.h` itself includes `zephyr/sys/util.h` https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/sys/time_units.h#L11 , making a circular dependency

**How to reproduce**

Create a C file that uses `WAIT_FOR` e.g.

```
#include <zephyr/sys/util.h>
...
bool my_func() { return false; }
...
WAIT_FOR(my_func(), 1000, NULL);
```

This will fail to compile with something like

```
.../zephyr/include/zephyr/sys/util.h:551:26: error: implicit declaration of function 'k_us_to_cyc_ceil32' [-Werror=implicit-function-declaration]
  551 |   uint32_t cycle_count = k_us_to_cyc_ceil32(timeout); \
```

**Expected behavior**

Headers should be self-contained so that users can include `zephyr/sys/util.h` without knowing that they also need to include `zephyr/sys/time_units.h` with a particular include ordering.

**Impact**

Users trying to get access to `WAIT_FOR` from `util.h` will hit a confusing compiler error around `k_us_to_cyc_ceil32` if they didn't happen to transitively include `time_units.h` already.

### PR DESCRIPTION
**Pull request by yperess**
The WAIT_FOR macro uses the 'k_us_to_cyc_ceil32' function declared in zephyr/sys/time_units.h. It should have been included.

Fixes #56006

### CODE REVIEW

**Comment by yperess** [comment]
All failing tests appear to be false positives. I created https://github.com/zephyrproject-rtos/zephyr/issues/56015 to track.

**Comment by nashif** [comment]
works with sdk 0.15.2 but fails in CI which has 0.16.0:

```
nization/zephyr/zephyr.elf
Memory region         Used Size  Region Size  %age Used
             RAM:       6792 KB      2047 MB      0.32%
          LOCORE:         32 KB        60 KB     53.33%
In file included from /home/nashif/zephyrproject/zephyr/include/zephyr/toolchain.h:50,
                 from /home/nashif/zephyrproject/zephyr/include/zephyr/sys/time_units.h:10,
                 from /home/nashif/zephyrproject/zephyr/include/zephyr/sys/util.h:565,
                 from /home/nashif/zephyrproject/zephyr/arch/x86/zefi/efi.h:13,
                 from /home/nashif/zephyrproject/zephyr/arch/x86/zefi/zefi.c:9:
/home/nashif/zephyrproject/zephyr/include/zephyr/toolchain/gcc.h:558:2: error: #error processor architecture not supported
  558 | #error processor architecture not supported
      |  ^~~~~
/home/nashif/zephyrproject/zephyr/include/zephyr/sys/time_units.h: In function 'sys_clock_hw_cycles_per_sec':
/home/nashif/zephyrproject/zephyr/include/zephyr/sys/time_units.h:64:16: error: 'CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC' undeclared (first use in this function)
   64 |         return CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC;
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/nashif/zephyrproject/zephyr/include/zephyr/sys/time_units.h:64:16: note: each undeclared identifier is reported only once for each function it appears in
/home/nashif/zephyrproject/zephyr/include/zephyr/sys/time_units.h: In function 'z_tmcvt':
/home/nashif/zephyrproject/zephyr/include/zephyr/sys/time_units.h:80:28: error: 'CONFIG_SYS_CLOCK_MAX_TIMEOUT_DAYS' undeclared (first use in this function)
   80 |         ((ceiling_fraction(CONFIG_SYS_CLOCK_MAX_TIMEOUT_DAYS * 24ULL * 3600ULL * from_hz, \
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/nashif/zephyrproject/zephyr/include/zephyr/sys/util.h:251:12: note: in definition of macro 'ceiling_fraction'
  251 |         (((numerator) + ((divider) - 1)) / (divider))
      |            ^~~~~~~~~
/home/nashif/zephyrproject/zephyr/include/zephyr/sys/time_units.h:150:40: note: in expansion of macro 'Z_TMCVT_USE_FAST_ALGO'
  150 |                 } else if (const_hz && Z_TMCVT_USE_FAST_ALGO(from_hz, to_hz)) {
      |                                        ^~~~~~~~~~~~~~~~~~~~~
/home/nashif/zephyrproject/zephyr/include/zephyr/sys/time_units.h: In function 'k_ms_to_ticks_floor32':
/home/nashif/zephyrproject/zephyr/include/zephyr/sys/time_units.h:238:20: error: 'CONFIG_SYS_CLOC
```

**Comment by stephanosio** [comment]
> works with sdk 0.15.2 but fails in CI which has 0.16.0:

@nashif Funnily, this is failing locally even with Zephyr SDK 0.15.2 for me ...

**Comment by nashif** [comment]
> @nashif Funnily, this is failing locally even with Zephyr SDK 0.15.2 for me ...

you are right, it fails also on 0.15.2 for me, has a disrty environment.

**Review by stephanosio — CHANGES_REQUESTED** [review]
> All failing tests appear to be false positives. I created #56015 to track.

This is not a false positive. The failure is real and reproducible locally after the changes in this PR.

**Comment by finikorg** [comment]
Now fails with: `$ west build -p -b qemu_kvm_arm64 -T zephyr/tests/kernel/common/kernel.common`
I think it is better to remove extra includes from `util.h` then add another include chain.

**Review by dcpleung — APPROVED** [review]

**Review by stephanosio — APPROVED** [review]

**Review by teburd — APPROVED** [review]

**Review by carlescufi — APPROVED** [review]

**Comment by marc-hb** [comment]
According to @dcpleung this PR created a new conflict:
- #62464

**Comment by marc-hb** [comment]
Quoting myself in https://github.com/zephyrproject-rtos/zephyr/issues/62464#issuecomment-1714520334
> Having two .h files that each include each other directly does not make any sense to me; I think this commit should never have been merged. [...]
