### ISSUE TITLE
intel_adsp: xt-clang: unknown warning group -Wunknown-warning-option.

### ISSUE THREAD

**Issue by gbarkadiusz** [zephyrproject-rtos/zephyr#84138]
**Describe the bug**
intel_adsp/ace15_mtpm/sim
```
INFO    - 1) tests/lib/mem_alloc/libraries.libc.minimal.mem_alloc on intel_adsp/ace15_mtpm/sim error (Build failure)
INFO    - 2) tests/lib/mem_alloc/libraries.libc.minimal.mem_alloc_negative_testing on intel_adsp/ace15_mtpm/sim error (Build failure)
INFO    - 3) tests/lib/mem_alloc/libraries.libc.picolibc.mem_alloc on intel_adsp/ace15_mtpm/sim error (Build failure)
INFO    - 4) tests/kernel/mem_protect/stack_random/kernel.memory_protection.stack_random on intel_adsp/ace15_mtpm/sim error (Build failure)
```

intel_adsp/ace30/ptl/sim
```
INFO    - 1) tests/kernel/mem_protect/stack_random/kernel.memory_protection.stack_random on intel_adsp/ace30/ptl/sim error (Build failure)
INFO    - 2) tests/lib/mem_alloc/libraries.libc.minimal.mem_alloc on intel_adsp/ace30/ptl/sim error (Build failure)
INFO    - 3) tests/lib/mem_alloc/libraries.libc.minimal.mem_alloc_negative_testing on intel_adsp/ace30/ptl/sim error (Build failure)
INFO    - 4) tests/lib/mem_alloc/libraries.libc.picolibc.mem_alloc on intel_adsp/ace30/ptl/sim error (Build failure)
```

intel_adsp/ace20_lnl/sim
```
INFO    - 1) tests/lib/mem_alloc/libraries.libc.minimal.mem_alloc on intel_adsp/ace20_lnl/sim error (Build failure)
INFO    - 2) tests/lib/mem_alloc/libraries.libc.minimal.mem_alloc_negative_testing on intel_adsp/ace20_lnl/sim error (Build failure)
INFO    - 3) tests/lib/mem_alloc/libraries.libc.picolibc.mem_alloc on intel_adsp/ace20_lnl/sim error (Build failure)
INFO    - 4) tests/kernel/mem_protect/stack_random/kernel.memory_protection.stack_random on intel_adsp/ace20_lnl/sim error (Build failure)
```

**To Reproduce**
`twister -p intel_adsp/ace20_lnl/sim -T  tests/lib/mem_alloc/`

**Logs and console output**
`/tests/lib/mem_alloc/src/main.c:24:32: error: unknown warning group '-Walloc-size-larger-than=', ignored [-Werror,-Wunknown-warning-option]
#pragma GCC diagnostic ignored "-Walloc-size-larger-than="`

**Environment:**

 - OS: Linux
 - Toolchain: xt-clang
 - Commit SHA or Version used: v4.0.0-3486-g4cc76e8a9ae3

**Additional context**
b9d7b1bdae9b41d3a73070536821c481f77633f1 is the first bad commit
```
commit b9d7b1bdae9b41d3a73070536821c481f77633f1
Author: Tom Hughes <tomhughes@chromium.org>
Date:   Mon Jan 13 12:16:12 2025 -0800

    cmake clang/compiler_flags.cmake: Re-enable -Wunknown-warning-option

    All warnings in the code base have been resolved.

    Signed-off-by: Tom Hughes <tomhughes@chromium.org>
```

**Comment by gbarkadiusz** [comment]
@thughes FYI.

**Comment by thughes** [comment]
From the error, it looks like the issue is that the `xt-clang` compiler doesn't recognize the `-Walloc-size-larger-than` warning [here](https://github.com/zephyrproject-rtos/zephyr/blob/2a6e5902cc73f464c120019292f20f28940a66bf/tests/lib/mem_alloc/src/main.c#L23-L25).

I see that the warning is listed in the [GCC warning options](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html), but not [clang diagnostic flags](https://clang.llvm.org/docs/DiagnosticsReference.html).

I have a PR that makes it easier to disable warnings only for clang or only for gcc: https://github.com/zephyrproject-rtos/zephyr/pull/84063. With that change we can make this a gcc-specific warning, which should resolve this issue. (I don't have access to the `xt-clang` compiler, so I can't test myself.)
