### ISSUE TITLE
3.5.0 regression - cannot compile with -Werror -Wextra

### ISSUE THREAD

**Issue by JonSalmon-CC** [zephyrproject-rtos/zephyr#64197]
**Describe the bug**
Compiling anything including `zephyr/net/wifi.h` on zephyr 3.5.0 with `-Werror -Wextra` fails to compile. This worked on 3.4.0.

**To Reproduce**
1. Add `#include <zephyr/net/wifi.h>` to samples/net/wifi/src/wifi_test.c
2. Add `target_compile_options(app PRIVATE -Werror -Wextra)` to samples/net/wifi/CMakeLists.txt
3. Attempt to compile the sample

**Logs and console output**
```
In file included from zephyr/samples/net/wifi/src/wifi_test.c:8:
zephyr/include/zephyr/net/wifi.h:59:1: error: type qualifiers ignored on function return type [-Werror=ignored-qualifiers]
   59 | const char *const wifi_security_txt(enum wifi_security_type security);
      | ^~~~~
zephyr/include/zephyr/net/wifi.h:76:1: error: type qualifiers ignored on function return type [-Werror=ignored-qualifiers]
   76 | const char *const wifi_mfp_txt(enum wifi_mfp_options mfp);
      | ^~~~~
zephyr/include/zephyr/net/wifi.h:98:1: error: type qualifiers ignored on function return type [-Werror=ignored-qualifiers]
   98 | const char *const wifi_band_txt(enum wifi_frequency_bands band);
      | ^~~~~
zephyr/include/zephyr/net/wifi.h:142:1: error: type qualifiers ignored on function return type [-Werror=ignored-qualifiers]
  142 | const char *const wifi_state_txt(enum wifi_iface_state state);
      | ^~~~~
zephyr/include/zephyr/net/wifi.h:168:1: error: type qualifiers ignored on function return type [-Werror=ignored-qualifiers]
  168 | const char *const wifi_mode_txt(enum wifi_iface_mode mode);
      | ^~~~~
zephyr/include/zephyr/net/wifi.h:200:1: error: type qualifiers ignored on function return type [-Werror=ignored-qualifiers]
  200 | const char *const wifi_link_mode_txt(enum wifi_link_mode link_mode);
      | ^~~~~
zephyr/include/zephyr/net/wifi.h:219:1: error: type qualifiers ignored on function return type [-Werror=ignored-qualifiers]
  219 | const char *const wifi_ps_txt(enum wifi_ps ps_name);
      | ^~~~~
zephyr/include/zephyr/net/wifi.h:233:1: error: type qualifiers ignored on function return type [-Werror=ignored-qualifiers]
  233 | const char *const wifi_ps_mode_txt(enum wifi_ps_mode ps_mode);
      | ^~~~~
zephyr/include/zephyr/net/wifi.h:276:1: error: type qualifiers ignored on function return type [-Werror=ignored-qualifiers]
  276 | const char *const wifi_twt_operation_txt(enum wifi_twt_operation twt_operation);
      | ^~~~~
zephyr/include/zephyr/net/wifi.h:289:1: error: type qualifiers ignored on function return type [-Werror=ignored-qualifiers]
  289 | const char *const wifi_twt_negotiation_type_txt(enum wifi_twt_negotiation_type twt_negotiation);
      | ^~~~~
zephyr/include/zephyr/net/wifi.h:312:1: error: type qualifiers ignored on function return type [-Werror=ignored-qualifiers]
  312 | const char *const wifi_twt_setup_cmd_txt(enum wifi_twt_setup_cmd twt_setup);
      | ^~~~~
zephyr/include/zephyr/net/wifi.h:397:1: error: type qualifiers ignored on function return type [-Werror=ignored-qualifiers]
  397 | const char *const wifi_ps_wakeup_mode_txt(enum wifi_ps_wakeup_mode ps_wakeup_mode);
      | ^~~~~
cc1: all warnings being treated as errors
ninja: build stopped: subcommand failed.
FATAL ERROR: command exited with status 1: /usr/bin/cmake --build zephyr/samples/net/wifi/build
```

**Comment by dkalowsk** [comment]
I would imagine this is a compile configuration we want to always enable and support on incoming MRs as part of the safety and security WG efforts.
