### ISSUE TITLE
ACE: Xtensa: Build failures on ACE platforms.

### ISSUE THREAD

**Issue by gbarkadiusz** [zephyrproject-rtos/zephyr#90383]
**Describe the bug**
Build Failures on: `intel_adsp/ace_15_mtpm/sim, intel_adsp_ace_20_lnl/sim, intel_adsp/ace_30/ptl/sim.`

**To Reproduce**
Checkout to latest upstream ([b1f9351)](https://github.com/zephyrproject-rtos/zephyr/commit/b1f9351930f14775e90ebfb2d3d3998b6552ca1f)
Run: `twister -p intel_adsp/ace_15_mptm/sim -T tests/`

**Impact**
Affects ACE platforms

**Logs and console output**
```
In file included from <path_to>/modules/lib/picolibc/newlib/libc/stdlib/nano-free.c:29:
<path_to>/modules/lib/picolibc/newlib/libc/stdlib/nano-malloc.h:60:9: error: unknown type name 'max_align_t'
typedef max_align_t align_chunk_t;
        ^
1 error generated.
```

**Environment:**

 - OS: Linux
 - Toolchain xt-clang
 - Commit SHA or Version used ([b1f9351)](https://github.com/zephyrproject-rtos/zephyr/commit/b1f9351930f14775e90ebfb2d3d3998b6552ca1f)

**Additional context**
Bisect result:
```
843d661b820e067f28112d2ea7dd822c2ecbcba2 is the first bad commit
commit 843d661b820e067f28112d2ea7dd822c2ecbcba2
Author: Keith Packard <keithp@keithp.com>
Date:   Thu Mar 27 15:03:06 2025 -0700

    modules: Update picolibc to version 1.8.10

    Switch to latest picolib release, version 1.8.10

    Signed-off-by: Keith Packard <keithp@keithp.com>

 west.yml | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```

**Comment by dcpleung** [comment]
Part of the issue is that picolibc does not inherent `--std=` from Zephyr build system, and defaults to C11.  And xt-clang defaults to using XCC's pre-C11 headers by default, where `max_align_t` is not defined.
