### PR TITLE
mbedtls: add new Kconfig for MBEDTLS_PSA_CRYPTO_CONFIG

### LINKED ISSUE #85155: samples/net/sockets/http_server fails to build for several nrf5340/cpuapp/ns targets
**Describe the bug**
samples/net/sockets/http_server fails to build for several nrf5340/cpuapp/ns targets

**To Reproduce**
1. twister -T samples/net/sockets/http_server -s sample.net.sockets.http.server --all
2. See error

**Expected behavior**
No build failures

**Impact**
Multiple failures in weekly CI

**Logs and console output**
https://github.com/zephyrproject-rtos/zephyr/actions/runs/13095023661/job/36536314669
```
[377/451] Building C object modules/mbedtls/CMakeFiles/mbedTLSCrypto.dir/scratch/zephyrproject/modules/crypto/mbedtls/library/pk.c.obj
modules/crypto/mbedtls/library/pk.c: In function 'mbedtls_pk_get_psa_attributes':
modules/crypto/mbedtls/library/pk.c:475:17: warning: implicit declaration of function 'mbedtls_ecc_group_to_psa'; did you mean 'mbedtls_ecp_group_copy'? [-Wimplicit-function-declaration]
  475 |                 mbedtls_ecc_group_to_psa(ec->grp.id, &bits);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~
      |                 mbedtls_ecp_group_copy
modules/crypto/mbedtls/library/pk.c: In function 'copy_from_psa':
modules/crypto/mbedtls/library/pk.c:943:18: warning: implicit declaration of function 'mbedtls_ecc_group_from_psa'; did you mean 'mbedtls_pk_copy_from_psa'? [-Wimplicit-function-declaration]
  943 |         grp_id = mbedtls_ecc_group_from_psa(PSA_KEY_TYPE_ECC_GET_FAMILY(key_type), key_bits);
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                  mbedtls_pk_copy_from_psa
```
```
ERROR   - raytac_mdbt53v_db_40/nrf5340/cpuapp/ns samples/net/sockets/http_server/sample.net.sockets.http.server ERROR: Build failure
..
ERROR   - raytac_mdbt53_db_40/nrf5340/cpuapp/ns samples/net/sockets/http_server/sample.net.sockets.http.server ERROR: Build failure
..
ERROR   - thingy53/nrf5340/cpuapp/ns samples/net/sockets/http_server/sample.net.sockets.http.server ERROR: Build failure
..
INFO    - Total complete:   84/  84  100%  built (not run):   75, filtered:  846, failed:    0, error:    3
```

**Environment (please complete the following information):**

 - OS: CI Ubuntu Linux 22.04
 - Toolchain (e.g Zephyr SDK, ...): 0.17.0
 - Commit SHA or Version used: main as of now 52b8e3d3706f7503d6e4e36413c2f78a2ac95480

**Additional context**
Introduced by https://github.com/zephyrproject-rtos/zephyr/pull/82143

### PR DESCRIPTION
**Pull request by valeriosetti**
Resolves #85155

Tested with: `twister -c -T samples/net/sockets/http_server -s sample.net.sockets.http.server --all`

This PR adds a new Kconfig for `MBEDTLS_PSA_CRYPTO_CONFIG`. Previously this Mbed TLS build symbol was automatically selected when `CONFIG_MBEDTLS_PSA_CRYPTO_CLIENT` was set. This worked for most configurations, but it can create issues [^1] on TF-M based builds when the sample/test code is relying on legacy Mbed TLS implementation.
The solution proposed here is to make `CONFIG_MBEDTLS_PSA_CRYPTO_CONFIG` a new symbol [^2] so that it can be intentionally disabled in samples/tests which will to rely on legacy Mbed TLS implementation.

[^1]: link issues for missing PSA-legacy adapting functions in Mbed TLS
[^2]: still selected by `CONFIG_MBEDTLS_PSA_CRYPTO_CLIENT` as it was previously

### CODE REVIEW

**Comment by mrodgers-witekio** [comment]
Looks fine to me, but also I don't think there's any particular reason this sample needs to use the legacy mbedtls API. The following patch gets the sample building correctly again (I've only built it, not run it yet), so I think this could also be fixed on the sample app side if that is preferred. Perhaps it's better to demonstrate the most up to date way of selecting the required crypto algorithms in the sample?

```
diff --git a/samples/net/sockets/http_server/prj.conf b/samples/net/sockets/http_server/prj.conf
index 73024d1aca1..ab5833760a6 100644
--- a/samples/net/sockets/http_server/prj.conf
+++ b/samples/net/sockets/http_server/prj.conf
@@ -60,23 +60,21 @@ CONFIG_NET_CONFIG_PEER_IPV6_ADDR="2001:db8::2"
 
 # TLS configuration
 CONFIG_MBEDTLS=y
+CONFIG_MBEDTLS_PSA_CRYPTO_C=y
 CONFIG_MBEDTLS_BUILTIN=y
 CONFIG_MBEDTLS_ENABLE_HEAP=y
 CONFIG_MBEDTLS_HEAP_SIZE=60000
 CONFIG_MBEDTLS_SSL_MAX_CONTENT_LEN=2048
-CONFIG_MBEDTLS_USE_PSA_CRYPTO=n
 CONFIG_NET_SOCKETS_SOCKOPT_TLS=y
 CONFIG_NET_SOCKETS_TLS_MAX_CONTEXTS=6
 CONFIG_TLS_CREDENTIALS=y
 CONFIG_TLS_MAX_CREDENTIALS_NUMBER=5
-CONFIG_MBEDTLS_ECDH_C=y
-CONFIG_MBEDTLS_ECDSA_C=y
-CONFIG_MBEDTLS_ECP_C=y
-CONFIG_MBEDTLS_ECP_DP_SECP256R1_ENABLED=y
-CONFIG_MBEDTLS_KEY_EXCHANGE_RSA_ENABLED=n
-CONFIG_MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA_ENABLED=y
-CONFIG_MBEDTLS_CIPHER_CCM_ENABLED=y
-CONFIG_MBEDTLS_CIPHER_GCM_ENABLED=y
+CONFIG_PSA_WANT_ALG_CCM=y
+CONFIG_PSA_WANT_ALG_GCM=y
+CONFIG_PSA_WANT_ALG_ECDH=y
+CONFIG_PSA_WANT_ALG_ECDSA=y
+CONFIG_PSA_WANT_ECC_SECP_R1_256=y
+CONFIG_PSA_WANT_KEY_TYPE_ECC_PUBLIC_KEY=y
```

**Comment by valeriosetti** [comment]
> Perhaps it's better to demonstrate the most up to date way of selecting the required crypto algorithms in the sample?

Sure, that's also an option! The configuration you proposed looks mostly good to me, then only change I would propose being `CONFIG_MBEDTLS_PSA_CRYPTO_C=y` only on platforms that do not have TF-M. For those that have it, building Mbed TLS PSA Crypto core is useless. This means extending a bit the yaml file, but I can take care of it.
