### PR TITLE
drivers: counter: counter_mcux_lpc_rtc: include <zephyr/irq.h>

### LINKED ISSUE #51185: tests/drivers/counter/counter_basic_api fails to build on mimxrt685_evk_cm33
**Describe the bug**
`counter_basic_api` test fails to build on `mimxrt685_evk_cm33`. The issue appears to be related to some necessary header files no longer being included, as the failure was introduced by a6a4400b8621bc618c6056

**Logs and console output**
Snippet of build error, showing undefined macro for `IRQ_CONNECT`:
```
/home/danieldegrasse/zephyrproject/zephyr/drivers/counter/counter_mcux_lpc_rtc.c:244:17: warning: implicit declaration of function 'IRQ_CONNECT' [-Wimplicit-function-declaration]
  244 |                 IRQ_CONNECT(DT_INST_IRQN(id),
```

### PR DESCRIPTION
**Pull request by danieldegrasse**
Add include of zephyr/irq.h to mcux lpc RTC counter driver, to
provide a definition of IRQ_CONNECT.

#51185

Signed-off-by: Daniel DeGrasse <daniel.degrasse@nxp.com>

### CODE REVIEW

**Comment by danieldegrasse** [comment]
@gmarull FYI- I think this is the correct header to include here, but please let me know if there is a more granular one I should include for the `IRQ_CONNECT` macro definition

**Review by gmarull — COMMENTED** [review]
Include <zephyr/irq.h>

**Review by galak — APPROVED** [review]

**Review by gmarull — APPROVED** [review]
