### ISSUE TITLE
samples: vmu_rt1170/mimxrt1176/cm7: sample.sensor.shell build failure

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#85077]
**Describe the bug**

vmu_rt1170/mimxrt1176/cm7: sample.sensor.shell build failure

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?
 - vmu_rt1170/mimxrt1176/cm7
 - What have you tried to diagnose or workaround this issue?
 - git bisect
 - Is this a regression? If yes, have you been able to "git bisect" it to a
   specific commit?

```
4dceb0b917d3a20de0c40119801e804df33ceeff is the first bad commit
commit 4dceb0b917d3a20de0c40119801e804df33ceeff
Author: Benjamin Perseghetti <bperseghetti@rudislabs.com>
Date:   Tue Jan 28 15:43:05 2025 -0500

    samples: sensor: sensor_shell: add vmu_rt1170.

    Adds support for testing sensor shell streaming
    on the vmu_rt1170 with RTIO.

    Co-Authored-by: James Goppert <james.goppert@gmail.com>
    Signed-off-by: Benjamin Perseghetti <bperseghetti@rudislabs.com>

 .../boards/vmu_rt1170_mimxrt1176_cm7.conf          | 10 +++++++++
 .../boards/vmu_rt1170_mimxrt1176_cm7.overlay       | 26 ++++++++++++++++++++++

```

**To Reproduce**

```
west update
scripts/twister -p vmu_rt1170/mimxrt1176/cm7 -T samples/sensor/sensor_shell
```

**Expected behavior**

build pass

**Impact**

shell CI

**Logs and console output**

```
/home/jenkins/agent/workspace/zephyr_downstream_build_daily/zephyr/samples/sensor/sensor_shell/src/fake_sensor.c /home/jenkins/agent/workspace/zephyr_downstream_build_daily/zephyr/samples/sensor/sensor_shell/src/fake_sensor.c:15:12: error: 'init' defined but not used [-Werror=unused-function] 15 | static int init(const struct device *dev) | ^~~~ cc1: all warnings being treated as errors ninja: build stopped: subcommand failed.
```

**Environment (please complete the following information):**

 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used: v4.0.0-4463-g491bbcfcbd3

**Comment by bperseghetti** [comment]
Appears to be coming from this fake sensor stuff: 
https://github.com/zephyrproject-rtos/zephyr/blob/b5c5ba8c832b8ac01b03a8a26ba76a49438b6cc5/samples/sensor/sensor_shell/sample.yaml#L18-L27
@yperess you know why the test is failing for fake sensors?
