### ISSUE TITLE
zms: unable to compile with `CONFIG_ZMS_LOOKUP_CACHE=n`

### ISSUE THREAD

**Issue by JordanYates** [zephyrproject-rtos/zephyr#95614]
### Describe the bug

The ZMS subsystem no longer compiles on Zephyr v4.2 with `CONFIG_ZMS_NO_DOUBLE_WRITE=y` and `CONFIG_ZMS_LOOKUP_CACHE=n`
The `wlk_addr` variable is used but not declared under that configuration.

https://github.com/zephyrproject-rtos/zephyr/blob/663da2302b04f4afef4f4dbf48cba4566f729bc8/subsys/fs/zms/zms.c#L1487-L1495

Introduced in PR #87792 (commit 42b9b5a9d79eb38e64f0b62731ea7e513ebd7787)

### Regression

- [x] This is a regression.

### Relevant log output

```shell
/home/jordan/code/workspace/zephyr/subsys/fs/zms/zms.c: In function ‘zms_write’:
/home/jordan/code/workspace/zephyr/subsys/fs/zms/zms.c:1494:9: error: ‘wlk_addr’ undeclared (first use in this function)
 1494 |         wlk_addr = fs->ate_wra;
```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

- Zephyr v4.2, main
