### PR TITLE
arch: reorg stacktrace dependencies & add `arch_stack_walk()` for x86 & arm64

### LINKED ISSUE #74713: [Coverity CID: 392520] Same on both sides in arch/riscv/core/stacktrace.c
Static code scan issues found in file:

https://github.com/zephyrproject-rtos/zephyr/tree/dcf42917c550714d2457947538b9e29d083e872e/arch/riscv/core/stacktrace.c

Category: Incorrect expression
Function: `walk_stackframe`
Component: Architectures
CID: [392520](https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=392520)

Details:

https://github.com/zephyrproject-rtos/zephyr/blob/dcf42917c550714d2457947538b9e29d083e872e/arch/riscv/core/stacktrace.c#L191

Please fix or provide comments in coverity using the link:

https://scan9.scan.coverity.com/#/project-view/29271/12996?selectedIssue=392520

For more information about the violation, check the [Coverity Reference](https://scan9.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_CONSTANT_EXPRESSION_RESULT). ([CWE-569](http://cwe.mitre.org/data/definitions/569.html))

Note: This issue was created automatically. Priority was set based on classification
of the file affected and the impact field in coverity. Assignees were set using the MAINTAINERS file.

### LINKED ISSUE #76706: arch: riscv: unable to compile `CONFIG_KERNEL_SHELL` when `CONFIG_EXCEPTION_STACK_TRACE=n`
**Describe the bug**

unable to compile `CONFIG_KERNEL_SHELL` when `CONFIG_EXCEPTION_STACK_TRACE=n`

**To Reproduce**
Checkout `main` and build
```
west build -b qemu_riscv64 -p auto zephyr/samples/hello_world -- \
  -DCONFIG_SHELL=y \
  -DCONFIG_EXCEPTION_STACK_TRACE=n
```

**Expected behavior**
Compile successfully

**Impact**
User that would like to disable `CONFIG_EXCEPTION_STACK_TRACE` will not be able to compile kernel services

**Logs and console output**
```
(.venv) ycsin@ycsin-mba zephyrproject % west build -b qemu_riscv64 -p auto zephyr/samples/hello_world -- \
  -DCONFIG_SHELL=y \
  -DCONFIG_EXCEPTION_STACK_TRACE=n
-- west build: generating a build system
Loading Zephyr default modules (Zephyr base).
-- Application: /Users/ycsin/zephyrproject/zephyr/samples/hello_world
-- CMake version: 3.26.3
-- Found Python3: /Users/ycsin/zephyrproject/.venv/bin/python3.11 (found suitable version "3.11.3", minimum required is "3.8") found components: Interpreter
-- Cache files will be written to: /Users/ycsin/Library/Caches/zephyr
-- Zephyr version: 3.7.99 (/Users/ycsin/zephyrproject/zephyr)
-- Found west (found suitable version "1.0.0", minimum required is "0.14.0")
-- Board: qemu_riscv64, qualifiers: qemu_virt_riscv64
-- Found host-tools: zephyr 0.16.8 (/Users/ycsin/zephyr-sdk-0.16.8)
-- Found toolchain: zephyr 0.16.8 (/Users/ycsin/zephyr-sdk-0.16.8)
-- Found Dtc: /Users/ycsin/homebrew/bin/dtc (found suitable version "1.7.0", minimum required is "1.4.6")
-- Found BOARD.dts: /Users/ycsin/zephyrproject/zephyr/boards/qemu/riscv64/qemu_riscv64.dts
-- Generated zephyr.dts: /Users/ycsin/zephyrproject/build/zephyr/zephyr.dts
-- Generated devicetree_generated.h: /Users/ycsin/zephyrproject/build/zephyr/include/generated/zephyr/devicetree_generated.h
-- Including generated dts.cmake file: /Users/ycsin/zephyrproject/build/zephyr/dts.cmake
Parsing /Users/ycsin/zephyrproject/zephyr/Kconfig
Loaded configuration '/Users/ycsin/zephyrproject/build/zephyr/.config'
No change to configuration in '/Users/ycsin/zephyrproject/build/zephyr/.config'
No change to Kconfig header in '/Users/ycsin/zephyrproject/build/zephyr/include/generated/zephyr/autoconf.h'
-- Found GnuLd: /Users/ycsin/zephyr-sdk-0.16.8/riscv64-zephyr-elf/riscv64-zephyr-elf/bin/ld.bfd (found version "2.38")
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- The ASM compiler identification is GNU
-- Found assembler: /Users/ycsin/zephyr-sdk-0.16.8/riscv64-zephyr-elf/bin/riscv64-zephyr-elf-gcc
-- Using ccache: /Users/ycsin/homebrew/bin/ccache
-- Configuring done (6.9s)
-- Generating done (0.1s)
-- Build files have been written to: /Users/ycsin/zephyrproject/build
-- west build: building application
[1/121] Preparing syscall dependency handling

[3/121] Generating include/generated/zephyr/version.h
-- Zephyr version: 3.7.99 (/Users/ycsin/zephyrproject/zephyr), build: v3.7.0-510-gfb153efbff4f
[116/121] Linking C executable zephyr/zephyr_pre0.elf
FAILED: zephyr/zephyr_pre0.elf zephyr/zephyr_pre0.map /Users/ycsin/zephyrproject/build/zephyr/zephyr_pre0.map
: && ccache /Users/ycsin/zephyr-sdk-0.16.8/riscv64-zephyr-elf/bin/riscv64-zephyr-elf-gcc  -gdwarf-4 zephyr/CMakeFiles/zephyr_pre0.dir/misc/empty_file.c.obj -o zephyr/zephyr_pre0.elf  zephyr/CMakeFiles/offsets.dir/./arch/riscv/core/offsets/offsets.c.obj  -fuse-ld=bfd  -T  zephyr/linker_zephyr_pre0.cmd  -Wl,-Map=/Users/ycsin/zephyrproject/build/zephyr/zephyr_pre0.map  -Wl,--whole-archive  app/libapp.a  zephyr/libzephyr.a  zephyr/arch/common/libarch__common.a  zephyr/arch/arch/riscv/core/libarch__riscv__core.a  zephyr/lib/libc/picolibc/liblib__libc__picolibc.a  zephyr/lib/libc/common/liblib__libc__common.a  zephyr/lib/posix/options/liblib__posix__options.a  zephyr/drivers/interrupt_controller/libdrivers__interrupt_controller.a  zephyr/drivers/console/libdrivers__console.a  zephyr/drivers/serial/libdrivers__serial.a  zephyr/drivers/timer/libdrivers__timer.a  -Wl,--no-whole-archive  zephyr/kernel/libkernel.a  -L"/Users/ycsin/zephyr-sdk-0.16.8/riscv64-zephyr-elf/bin/../lib/gcc/riscv64-zephyr-elf/12.2.0/rv64imac_zicsr_zifencei/lp64/medany"  -L/Users/ycsin/zephyrproject/build/zephyr  -lgcc  zephyr/arch/common/libisr_tables.a  -mcmodel=medany  -mabi=lp64  -march=rv64imac_zicsr_zifencei  -Wl,--gc-sections  -Wl,--build-id=none  -Wl,--sort-common=descending  -Wl,--sort-section=alignment  -Wl,-u,_OffsetAbsSyms  -Wl,-u,_ConfigAbsSyms  -nostdlib  -static  -Wl,-X  -Wl,-N  -Wl,--orphan-handling=warn  -Wl,-no-pie  -DPICOLIBC_LONG_LONG_PRINTF_SCANF  --specs=picolibc.specs  -lc  -lgcc && cd /Users/ycsin/zephyrproject/build/zephyr && /Users/ycsin/homebrew/Cellar/cmake/3.26.3/bin/cmake -E true
/Users/ycsin/zephyr-sdk-0.16.8/riscv64-zephyr-elf/bin/../lib/gcc/riscv64-zephyr-elf/12.2.0/../../../../riscv64-zephyr-elf/bin/ld.bfd: zephyr/libzephyr.a(kernel_service.c.obj): in function `cmd_kernel_unwind':
/Users/ycsin/zephyrproject/zephyr/subsys/shell/modules/kernel_service.c:260: undefined reference to `arch_stack_walk'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
FATAL ERROR: command exited with status 1: /Users/ycsin/homebrew/bin/cmake --build /Users/ycsin/zephyrproject/build
```

### PR DESCRIPTION
**Pull request by ycsin**
> [!NOTE]
> Expected to conflict with #77457

Fixes #76706
Fixes #74713

Includes #76044 & #76042, obsoletes #75865

___

1. If an arch implements `arch_stack_walk()` `ARCH_HAS_STACKWALK` should be selected.
2. If the above is enabled, `ARCH_SUPPORTS_STACKWALK` indicates if the dependencies are met for arch to enable stack walking. This Kconfig replaces `<arch>_EXCEPTION_STACK_TRACE`
2. If the above is enabled, then, `ARCH_STACKWALK` determines if `arch_stack_walk()` should be compiled.
3. `EXCEPTION_STACK_TRACE` should build on top of the `ARCH_STACKWALK`, stack traces will be printed when it is enabled.
4. `EXCEPTION_STACK_TRACE_MAX_FRAMES ` will be removed as it is replaced by `ARCH_STACKWALK_MAX_FRAMES`

image

`CONFIG_EXCEPTION_STACK_TRACE_SYMTAB` is also removed in this PR, as it doesn't really make sense to save a few bytes, when a lot of bytes went into the symbol table when `CONFIG_SYMTAB=y`

### CODE REVIEW

File: arch/x86/core/fatal.c [hunk 1]
```diff
@@ -178,16 +178,57 @@ static void unwind_stack(uintptr_t base_ptr, uint16_t cs)
...
+#endif /* CONFIG_ARCH_STACKWALK */
+
+#if defined(CONFIG_EXCEPTION_STACK_TRACE)
+static bool print_trace_address(void *arg, unsigned long addr)
+{
+	int *i = arg;
+
 #ifdef CONFIG_X86_64
-		LOG_ERR("     0x%016lx", frame->ret_addr);
+	LOG_ERR("     %d: ra: 0x%016lx", (*i)++, addr);
```
Comment (dcpleung) [inline arch/x86/core/fatal.c:205]: Could you remove the `ra:` part?

Comment (ycsin) [reply arch/x86/core/fatal.c]: Removed

File: arch/x86/core/fatal.c [hunk 2]
```diff
@@ -178,16 +178,57 @@ static void unwind_stack(uintptr_t base_ptr, uint16_t cs)
...
+static bool print_trace_address(void *arg, unsigned long addr)
+{
+	int *i = arg;
+
 #ifdef CONFIG_X86_64
-		LOG_ERR("     0x%016lx", frame->ret_addr);
+	LOG_ERR("     %d: 0x%016lx", (*i)++, addr);
 #else
-		LOG_ERR("     0x%08lx (0x%lx)", frame->ret_addr, frame->args);
+	LOG_ERR("     %d: 0x%08lx", (*i)++, addr);
```
Comment (dcpleung) [inline arch/x86/core/fatal.c:207]: Would it  be possible to preserve the printing of `frame->args`?

File: arch/riscv/Kconfig [hunk 3]
```diff
@@ -383,6 +376,14 @@ config GEN_IRQ_VECTOR_TABLE
 config ARCH_HAS_SINGLE_THREAD_SUPPORT
 	default y if !SMP
 
+config ARCH_SUPPORTS_STACKWALK
```
Comment (nashif) [inline arch/riscv/Kconfig:379]: why define this per architecture? shouldn't this be in arch/Kconfig and then select it if arch supports it instead?

Comment (ycsin) [reply arch/riscv/Kconfig:379]: Because each arch seems to have different dependencies

- riscv can be done with or without fp
- x86_32 requires fp, et al
- x86_64 requires fp, `NO_OPTIMIZATIONS`, et al
- arm64 requires fp

this per-arch Kconfig indicates that the dependencies are met and stackwalk can be enabled

But I realize that `ARCH_SUPPORTS_STACKWALK` is redundant, I could have (re)used the `ARCH_HAS_STACKWALK` for the dependency checking

File: arch/x86/core/fatal.c (hunk 2 above)
Comment (ycsin) [reply arch/x86/core/fatal.c:207]: possible if reorg the `unwind_stack()` to use the `walk_stackframe()` instead of `arch_stack_walk()`.

File: arch/riscv/Kconfig (hunk 3 above)
Comment (ycsin) [reply arch/riscv/Kconfig]: > But I realize that `ARCH_SUPPORTS_STACKWALK` is redundant, I could have (re)used the `ARCH_HAS_STACKWALK` for the dependency checking, patch incoming

done

File: arch/x86/core/fatal.c (hunk 2 above)
Comment (ycsin) [reply arch/x86/core/fatal.c]: @dcpleung I've added a commit for this (the last one), PTAL

**Review by nashif — DISMISSED** [review]

**Comment by ycsin** [comment]
Squashed the x86 & arm64 's changes in this [commit](https://github.com/zephyrproject-rtos/zephyr/pull/77067#discussion_r1719251121) into where it happened, added a commit to document the API in [Architecture Interface](https://docs.zephyrproject.org/latest/doxygen/html/group__arch-interface.html)

**Comment by ycsin** [comment]
Updated release note

**Review by dcpleung — APPROVED** [review]

**Review by nashif — APPROVED** [review]
