### PR TITLE
drivers: usb: common: stm32: enable ULPI interface driver for all series

### LINKED ISSUE #107627: STM32 F4 with external USB PHY fails to build
### Describe the bug

STM32 F4 boards with an external USB PHY fail to build since #102493 was merged. The failure was observed on the `adi_sdp_k1` board, but other STM32 boards with an external USB PHY will also be affected.

git bisect points to commit 8b8321d18417b517e4230c0fb857b047858d8bfd

### Regression

- [x] This is a regression.

### Steps to reproduce

```console
$ west build -p -b adi_sdp_k1 samples/subsys/usb/console/
```

### Relevant log output

```shell
FAILED: zephyr/zephyr_pre0.elf zephyr/zephyr_pre0.map /home/mhelm/zephyrproject/zephyr/build/zephyr/zephyr_pre0.map
: && ccache /home/mhelm/.local/zephyr-sdk-1.0.0/gnu/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc  -gdwarf-4 -Os zephyr/CMakeFiles/zephyr_pre0.dir/misc/empty_file.c.obj -o zephyr/zephyr_pre0.elf  zephyr/CMakeFiles/offsets.dir/./arch/arm/core/offsets/offsets.c.obj  -T  zephyr/linker_zephyr_pre0.cmd  -Wl,-Map,/home/mhelm/zephyrproject/zephyr/build/zephyr/zephyr_pre0.map  -Wl,--whole-archive  app/libapp.a  zephyr/libzephyr.a  zephyr/arch/common/libarch__common.a  zephyr/arch/arch/arm/core/libarch__arm__core.a  zephyr/arch/arch/arm/core/cortex_m/libarch__arm__core__cortex_m.a  zephyr/arch/arch/arm/core/mpu/libarch__arm__core__mpu.a  zephyr/lib/libc/picolibc/liblib__libc__picolibc.a  zephyr/lib/libc/common/liblib__libc__common.a  zephyr/lib/posix/c_lib_ext/liblib__posix__c_lib_ext.a  zephyr/lib/net_buf/liblib__net_buf.a  zephyr/subsys/usb/device_next/libsubsys__usb__device_next.a  zephyr/drivers/interrupt_controller/libdrivers__interrupt_controller.a  zephyr/drivers/usb/udc/libdrivers__usb__udc.a  zephyr/drivers/usb/common/buf/libdrivers__usb__common__buf.a  zephyr/drivers/usb/common/stm32/libdrivers__usb__common__stm32.a  zephyr/drivers/clock_control/libdrivers__clock_control.a  zephyr/drivers/console/libdrivers__console.a  zephyr/drivers/gpio/libdrivers__gpio.a  zephyr/drivers/hwinfo/libdrivers__hwinfo.a  zephyr/drivers/pinctrl/libdrivers__pinctrl.a  zephyr/drivers/reset/libdrivers__reset.a  zephyr/drivers/serial/libdrivers__serial.a  zephyr/drivers/timer/libdrivers__timer.a  modules/hal_stm32/stm32cube/lib..__modules__hal__stm32__stm32cube.a  -Wl,--no-whole-archive  zephyr/kernel/libkernel.a  -L/home/mhelm/zephyrproject/zephyr/build/zephyr  zephyr/arch/common/libisr_tables.a  -fuse-ld=bfd  -mcpu=cortex-m4  -mthumb  -mabi=aapcs  -mfp16-format=ieee  -mtp=soft  -Wl,--gc-sections  -Wl,--build-id=none  -Wl,--sort-common=descending  -Wl,--sort-section=alignment  -Wl,-u,_OffsetAbsSyms  -Wl,-u,_ConfigAbsSyms  -nostdlib  -static  -znoexecstack  -Wl,-X  -Wl,-N  -Wl,--orphan-handling=warn  -Wl,-no-pie  -Wl,--undefined=_sw_isr_table  -Wl,--undefined=_irq_vector_table  -specs=picolibc.specs  -DPICOLIBC_LONG_LONG_PRINTF_SCANF -L"/home/mhelm/.local/zephyr-sdk-1.0.0/gnu/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/14.3.0/thumb/v7e-m/nofp/space" -lc -lgcc && cd /home/mhelm/zephyrproject/zephyr/build/zephyr && /usr/bin/cmake -E true
/home/mhelm/.local/zephyr-sdk-1.0.0/gnu/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/14.3.0/../../../../arm-zephyr-eabi/bin/ld.bfd: zephyr/drivers/usb/udc/libdrivers__usb__udc.a(udc_stm32.c.obj):(.rodata.udc173_cfg+0x1c): undefined reference to `__device_dts_ord_173__stm32_phy'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
FATAL ERROR: command exited with status 1: /usr/bin/cmake --build /home/mhelm/zephyrproject/zephyr/build
```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

- OS: Linux
- Toolchain: Zephyr SDK 1.0.0
- Version: Zephyr v4.4.0

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by MaureenHelm**
The ULPI PHY interface driver (phy_ulpi_itf.c) was only being compiled for STM32F7X and STM32H7X series, causing build failures on other series that use external ULPI PHYs, such as STM32F4X boards with ULPI PHYs.

Add CONFIG_DT_HAS_USB_ULPI_PHY_ENABLED to the build condition alongside the existing F7X/H7X series checks. This ensures the ULPI interface driver is compiled for any board that has a ULPI PHY node in its devicetree, regardless of the SOC series.

This fixes build failures like "undefined reference to __device_dts_ord_XXX__stm32_phy" when building for STM32F4 boards with external ULPI PHYs (e.g., adi_sdp_k1). The build failures were introduced in commit 8b8321d18417b517e4230c0fb857b047858d8bfd.

Signed-off-by: Maureen Helm <maureen.helm@analog.com>
Assisted-by: Claude:claude-sonnet-4-5

Fixes #107627

### CODE REVIEW

File: drivers/usb/common/stm32/CMakeLists.txt [hunk 1]
```diff
@@ -21,7 +21,7 @@ if(CONFIG_STM32_USB_COMMON)
   if(CONFIG_SOC_SERIES_STM32F4X OR CONFIG_SOC_SERIES_STM32H7X)
     zephyr_library_sources(phy_embeddedfs_ulpi_off.c)
   endif()
-  if(CONFIG_SOC_SERIES_STM32F7X OR CONFIG_SOC_SERIES_STM32H7X)
+  if(CONFIG_SOC_SERIES_STM32F7X OR CONFIG_SOC_SERIES_STM32H7X OR CONFIG_DT_HAS_USB_ULPI_PHY_ENABLED)
```
Comment (mathieuchopstm) [inline drivers/usb/common/stm32/CMakeLists.txt:24]: Might as well get rid of the series check entirely? (keep only `if(USB ULPI ENABLED)`)

**Review by mathieuchopstm — COMMENTED** [review]
Good catch. Looking back at https://github.com/zephyrproject-rtos/zephyr/commit/8b8321d18417b517e4230c0fb857b047858d8bfd, it does seem I overlooked F2/F4 can have an ULPI PHY...

Patch seems sound but I'd like to give a more thourough review; marking as DNM until then (will have to wait a few days)

File: drivers/usb/common/stm32/CMakeLists.txt (hunk 1 above)
Comment (MaureenHelm) [reply drivers/usb/common/stm32/CMakeLists.txt:24]: I was tempted to do that, but wasn't sure if it was the right fix. If you say it is, I'm happy to update accordingly.

Comment (mathieuchopstm) [reply drivers/usb/common/stm32/CMakeLists.txt]: After careful consideration, I propose adding the missing series to the list to ensure we never attempt compiling this driver for future products that would embed an ULPI interface but *may* have different clock control bits.

```suggestion
  if(CONFIG_SOC_SERIES_STM32F2X OR
     CONFIG_SOC_SERIES_STM32F4X OR
     CONFIG_SOC_SERIES_STM32F7X OR
     CONFIG_SOC_SERIES_STM32H7X)
```

As an *optimization*, we can add a check for enabled ULPI PHY as you proposed which should avoid compiling the driver unnecessarily:
```suggestion
if((CONFIG_SOC_SERIES_STM32F2X OR
    CONFIG_SOC_SERIES_STM32F4X OR
    CONFIG_SOC_SERIES_STM32F7X OR
    CONFIG_SOC_SERIES_STM32H7X) AND
    CONFIG_DT_HAS_USB_ULPI_PHY_ENABLED)
```

**Review by mathieuchopstm — COMMENTED** [review]
The old logic was (simplified - comments stripped):
```c
	/* PHY configuration */
#if DT_HAS_COMPAT_STATUS_OKAY(st_stm32_otghs)
#if defined(CONFIG_SOC_SERIES_STM32N6X)
    /* irrelevant... */
#elif DT_HAS_COMPAT_STATUS_OKAY(st_stm32u5_otghs_phy)
    /* irrelevant... */
#elif defined(CONFIG_SOC_SERIES_STM32H7X)
	if (UDC_STM32_NODE_PHY_ITFACE(DT_DRV_INST(0)) == PCD_PHY_ULPI) {
		LL_AHB1_GRP1_EnableClock(LL_AHB1_GRP1_PERIPH_USB1OTGHSULPI);
	} else {
		LL_AHB1_GRP1_DisableClockSleep(LL_AHB1_GRP1_PERIPH_USB1OTGHSULPI);
	}
#elif defined(CONFIG_SOC_SERIES_STM32F7X)
	#if UDC_STM32_NODE_PHY_ITFACE(DT_DRV_INST(0)) == PCD_PHY_ULPI
		LL_AHB1_GRP1_EnableClock(LL_AHB1_GRP1_PERIPH_OTGHSULPI);
	#elif UDC_STM32_NODE_PHY_ITFACE(DT_DRV_INST(0)) == PCD_PHY_UTMI
		LL_AHB1_GRP1_EnableClock(LL_AHB1_GRP1_PERIPH_OTGHSULPI);
		LL_APB2_GRP1_EnableClock(LL_APB2_GRP1_PERIPH_OTGPHYC);
	#endif
#else /* CONFIG_SOC_SERIES_STM32F2X || CONFIG_SOC_SERIES_STM32F4X */
	if (UDC_STM32_NODE_PHY_ITFACE(DT_DRV_INST(0)) == PCD_PHY_ULPI) {
		LL_AHB1_GRP1_EnableClock(LL_AHB1_GRP1_PERIPH_OTGHSULPI);
	} else if (UDC_STM32_NODE_SPEED(DT_DRV_INST(0)) == PCD_SPEED_HIGH_IN_FULL) {
		/*
		 * Some parts of the STM32F4 series require the OTGHSULPILPEN to be
		 * cleared if the OTG_HS is used in FS mode. Disable it on all parts
		 * since it has no nefarious effect if performed when not required.
		 */
		LL_AHB1_GRP1_DisableClockLowPower(LL_AHB1_GRP1_PERIPH_OTGHSULPI);
	}
#endif /* CONFIG_SOC_SERIES_* */
    /* #else omitted as irrelevant */
#endif /* DT_HAS_COMPAT_STATUS_OKAY(st_stm32_otghs) */
```

It is clear that the old code called `LL_AHB1_GRP1_EnableClock(LL_AHB1_GRP1_PERIPH_{USB1}OTGHSULPI)` on STM32F2, F4, F7 and H7 series - however, the new ULPI interface PHY driver is only added to build sources for F7 and H7 series.

This is an oversight of mine. Based on the following comment in the driver (and my memory), I did intend for F2 and F4 to be supported too:
https://github.com/zephyrproject-rtos/zephyr/blob/d67ec272cc6f86250e6e29eadc4590f865d76c2b/drivers/usb/common/stm32/phy_ulpi_itf.c#L44-L45

**Review by josuah — COMMENTED** [review]
This PR seems like a logical continuation of what is already there.

Though I wonder if it could be easier to maintain to have a Kconfig for it and a simple `zephyr_library_sources_ifdef(CONFIG_STM32_PHY_ULPI_ITF phy_ulpi_itf.c)`, making it pretty much like a normal driver.

For instance below:

https://github.com/zephyrproject-rtos/zephyr/blob/59dc905e80a71f99dc849637bb2ed858466ca626/drivers/usb/common/stm32/Kconfig#L12-L16

https://github.com/zephyrproject-rtos/zephyr/blob/59dc905e80a71f99dc849637bb2ed858466ca626/drivers/usb/common/stm32/CMakeLists.txt#L28-L32

This might be beyond the scope of this sole PR though which extends something already there.

**Review by mathieuchopstm — APPROVED** [review]

**Comment by mathieuchopstm** [comment]
> This PR seems like a logical continuation of what is already there.
> 
> Though I wonder if it could be easier to maintain to have a Kconfig for it and a simple `zephyr_library_sources_ifdef(CONFIG_STM32_PHY_ULPI_ITF phy_ulpi_itf.c)`, making it pretty much like a normal driver.
>
> [...]

That sounds like a good idea. In fact, my original rationale for handling everything in CMake:
https://github.com/zephyrproject-rtos/zephyr/blob/59dc905e80a71f99dc849637bb2ed858466ca626/drivers/usb/common/stm32/CMakeLists.txt#L17-L20

turns out to be incorrect: `CONFIG_DT_HAS_USB_ULPI_PHY_ENABLED` is a reliable indicator of whether the ULPI interface PHY driver ***might*** be needed, or is entirely unneeded.

However, I prefer this PR to be merged as-is because it's a smaller change, and thus fits better for backport (we definitely want this fix in v4.4.1).

I'll open a follow up PR to introduce the Kconfig option.

**Review by jfischer-no — APPROVED** [review]
