### PR TITLE
drivers: display: ssd1306: do not re-declare errno

### LINKED ISSUE #76751: ssd1306.c compile error when board is esp32_devkitc_wrover
in function ssd1306_set_iref_mode()
get compile error:
zephyrlatest/zephyr/drivers/display/ssd1306.c:207:9: error: function 'z_errno_wrap' is initialized like a variable
  207 |         int errno = 0;
      |         ^~~
fixed when changing errno variable name to another name like errnbr
code localy changed to:

============================
static inline int ssd1306_set_iref_mode(const struct device *dev)
{
	int errnbr = 0;
	const struct ssd1306_config *config = dev->config;
	uint8_t cmd_buf[] = {
		SSD1306_SET_IREF_MODE,
		SSD1306_SET_IREF_MODE_INTERNAL,
	};

	if (config->use_internal_iref) {
		errnbr = ssd1306_write_bus(dev, cmd_buf, sizeof(cmd_buf), true);
	}

	return errnbr;
}

==============================
now compiled correctly:
zephyrlatest/zephyr/samples/stepper/build/zephyr/zephyr.elf for board: esp32_devkitc_wrover
esptool.py v4.7.0
Creating esp32 image...
Image has only RAM segments visible. ROM segments are hidden and SHA256 digest is not appended.
Merged 13 ELF sections
Successfully created esp32 image.

### PR DESCRIPTION
**Pull request by kartben**
errno is a reserved macro. Use ret instead.
Fixes a bug introduced with commit bfb541ccbe811af8a0e676c472bd7a42f08b938a / PR #74885

Fixes #76751.

### CODE REVIEW

**Comment by kartben** [comment]
Not sure why this wasn't caught in CI -- maybe something that's specific to Xtensa toolchain or something, as the compilation error doesn't occur for e.g a Cortex-M target.

**Review by faxe1008 — APPROVED** [review]
Good catch 👍

**Comment by ttmut** [comment]
> Not sure why this wasn't caught in CI -- maybe something that's specific to Xtensa toolchain or something, as the compilation error doesn't occur for e.g a Cortex-M target.

I might be wrong but Xtensa does not seem to have thread local storage support (`ARCH_HAS_THREAD_LOCAL_STORAGE`). So picolibc sets `errno` to `z_errno_wrap` function and the error in the linked issue is encountered when `errno` is used like a variable.

https://github.com/zephyrproject-rtos/picolibc/blob/main/meson.build#L1343-L1347
```
elif errno_function == 'zephyr'
  if thread_local_storage
    errno_function = 'false'
  else
    errno_function = 'z_errno_wrap'
  endif
endif
```

**Comment by theob-pro** [comment]
You are doing more than fixing the issue. I only introduced `int errno` in `ssd1306_set_iref_mode`, not in `ssd1306_write_bus_spi`. I think we should not rush that and try to reproduce the issue and add a test (twister compile or something) to ensure that this doesn't happen again.

I will try to investigate a bit, in the meantime I am adding DNM. @kartben if you disagree with me or have more understanding of the issue, feel free to remove it :slightly_smiling_face:

**Review by aasinclair — APPROVED** [review]

**Comment by theob-pro** [comment]
This is a good enough fix. I am removing the DNM as the underlying issue can be investigated later.

**Review by ttmut — APPROVED** [review]

**Review by jfischer-no — APPROVED** [review]
