### ISSUE TITLE
ci_nxp_build_failure: shell: shell_tdata_dump uses removed _timeout.dticks member

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#118428]
## Describe the bug

Zephyr CI cannot build the kernel timer skiplist tests for
`vmu_rt1170/mimxrt1176/cm7`.  The shell kernel-service module accesses the
removed/private `_timeout.dticks` member:

```text
subsys/shell/modules/kernel_service/thread/list.c:85:51: error:
'struct _timeout' has no member named 'dticks'
    int64_t timeout_raw = (int64_t)thread->base.timeout.dticks;
```

The failure was observed in CI build #7301 for both
`kernel.timer.timeout.skiplist` and `kernel.timer.timeout_pending.skiplist`.

## Regression

- [x] This is a regression.

A source-level `git bisect` identified the first bad commit as
[`5a0e1f9eb7fa3efad990b89d50257296d7d85724`](https://github.com/zephyrproject-rtos/zephyr/commit/5a0e1f9eb7fa3efad990b89d50257296d7d85724),
`kernel: add Pugh skip list timeout backend`.

## Steps to reproduce

1. Check out commit `434233e9751e7cca7bea82047e812bca607722d3`.
2. Run the two timeout skiplist test configurations for
   `vmu_rt1170/mimxrt1176/cm7` with Twister.
3. Observe the build failure in `shell_tdata_dump()`.

## Relevant log output

```text
subsys/shell/modules/kernel_service/thread/list.c: In function
'shell_tdata_dump':
subsys/shell/modules/kernel_service/thread/list.c:85:51: error:
'struct _timeout' has no member named 'dticks'
    int64_t timeout_raw = (int64_t)thread->base.timeout.dticks;
                                                  ^
```

## Impact

Functional Limitation – timer skiplist test configurations do not build for
this RT1170 target.

## Environment

- OS: Windows CI worker
- Board: `vmu_rt1170/mimxrt1176/cm7`
- Toolchain: Zephyr SDK 1.0.1, GCC 14.3.0
- Zephyr version: `v4.4.0-14354-g434233e9751e`
- Commit: `434233e9751e7cca7bea82047e812bca607722d3`

## Additional Context

The failure is in the shell kernel-service code rather than in either timer
test.  No exact matching upstream issue was found when searching for
`"shell_tdata_dump" "dticks"`.

**Comment by hakehuang** [comment]
Regression confirmed by git bisect. The first bad commit is 5a0e1f9eb7fa3efad990b89d50257296d7d85724 (kernel: add Pugh skip list timeout backend). Its parent does not contain the skiplist timeout configuration; the introducing commit adds that configuration while changing struct _timeout away from dticks. shell_tdata_dump() still reads timeout.dticks, which makes the new configuration fail to build.

**Comment by hakehuang** [comment]
﻿NXP upstream CI still reproduces this at
`a5244984a05bdad810c645aa9efe47da4f004cce`
(`v4.4.0-15083-ga5244984a05b`) with Zephyr SDK 1.0.1 / GCC 14.3.0.

Both affected timeout skiplist configurations on
`vmu_rt1170/mimxrt1176/cm7` continue to fail with:

```text
subsys/shell/modules/kernel_service/thread/list.c:85:60: error:
'struct _timeout' has no member named 'dticks'
```

The failing cases remain `kernel.timer.timeout.skiplist` and
`kernel.timer.timeout_pending.skiplist`.
