### PR TITLE
tests: benchmarks: add Dhrystone benchmark

### PR DESCRIPTION
**Pull request by kelvincheung**
Add Dhrystone benchmark which is derived from
http://www.netlib.org/benchmark/dhry-c.

Signed-off-by: Keguang Zhang <keguang.zhang@unisoc.com>

### CODE REVIEW

File: samples/benchmark/CMakeLists.txt [hunk 1]
```diff
@@ -0,0 +1,6 @@
+cmake_minimum_required(VERSION 3.13.1)
+include($ENV{ZEPHYR_BASE}/cmake/app/boilerplate.cmake NO_POLICY_SCOPE)
+project(benchmark)
+
+target_sources(app PRIVATE src/main.c)
+add_subdirectory_ifdef(CONFIG_DHRYSTONE dhrystone)
```
Comment (SebastianBoe) [inline samples/benchmark/CMakeLists.txt]: samples/benchmark is a new directory, right?

I believe there is a pre-existing benchmark directory somewhere, dhyrstone would be more appropriate there.

**Review by SebastianBoe — CHANGES_REQUESTED** [review]

File: samples/benchmark/CMakeLists.txt (hunk 1 above)
Comment (kelvincheung) [reply samples/benchmark/CMakeLists.txt]: @SebastianBoe Do you mean ./tests/benchmarks?

Comment (SebastianBoe) [reply samples/benchmark/CMakeLists.txt]: yes

Comment (kelvincheung) [reply samples/benchmark/CMakeLists.txt]: OK, will do.
In addition, the dhrystone failed to build with zephyr-sdk-0.10.0-rc2.
BTW, the same code could be built successfully with zephyr-sdk-0.9.5.

[ 95%] Linking C executable zephyr_prebuilt.elf
Memory region Used Size Region Size %age Used
FLASH: 34176 B 1 MB 3.26%
SRAM: 15640 B 192 KB 7.95%
IDT_LIST: 120 B 2 KB 5.86%
/opt/zephyr-sdk/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/8.2.0/../../../../arm-zephyr-eabi/bin/ld: /opt/zephyr-sdk/arm-zephyr-eabi/arm-zephyr-eabi/lib/thumb/v7e-m/nofp/libc.a(lib_a-gettimeofdayr.o): in function _gettimeofday_r': /home/buildslave/src/github.com/zephyrproject-rtos/sdk-ng/build/build_arm/.build/arm-zephyr-eabi/src/newlib/newlib/libc/reent/gettimeofdayr.c:63: undefined reference to _gettimeofday'
collect2: error: ld returned 1 exit status
make[2]: *** [zephyr/zephyr_prebuilt.elf] Error 1
make[1]: *** [zephyr/CMakeFiles/zephyr_prebuilt.dir/all] Error 2
make: *** [all] Error 2

Steps to reproduce the behavior:

    apply #13383
    mkdir build; cd build
    cmake -DBOARD=stm32f4_disco ../samples/benchmark
    make

Environment (please complete the following information):

    OS: Ubuntu 14.04.5 LTS
    Toolchain: zephyr-sdk-0.10.0-rc2
    Commit SHA: 7077602

Any help would be greatly appreciated.

Comment (kelvincheung) [reply samples/benchmark/CMakeLists.txt]: @SebastianBoe 
The build error is gone with new zephyr-sdk-0.10.0.
Thanks for your review!

File: tests/benchmarks/dhrystone/src/dhry_2.c [hunk 2]
```diff
@@ -0,0 +1,191 @@
...
+ *  Version:    C, Version 2.1
+ *
+ *  File:       dhry_2.c (part 3 of 3)
+ *
+ *  Date:       May 25, 1988
+ *
+ *  Author:     Reinhold P. Weicker
+ *
+ ****************************************************************************
+ */
```
Comment (jukkar) [inline tests/benchmarks/dhrystone/src/dhry_2.c]: I wonder what is the original license of this piece of code.

**Review by SebastianBoe — CHANGES_REQUESTED** [review]
This test is missing a .yml file that expresses which platforms it runs on.

Also, it is missing a .rst file.

When running this test on native_posix I got this error:

```
ccache /usr/bin/gcc -DBUILD_VERSION=v1.14.0-rc3-8-g257c22e0180b -DHZ=100 -DKERNEL -DNO_PROTOTYPES=1 -D_FORTIFY_SOURCE=2 -D_POSIX_C_SOURCE=200809 -D_XOPEN_SOURCE=600 -D_XOPEN_SOURCE_EXTENDED -D__ZEPHYR__=1 -I../../../../kernel/include -I../../../../arch/posix/include -I../../../../include -I../../../../include/drivers -Izephyr/include/generated -I../../../../soc/posix/inf_clock -I../../../../boards/posix/native_posix -I/home/sebo/ncs/nrf/include -m32    -Os -g -Wall -Wformat -Wformat-security -Wno-format-zero-length -imacros /home/sebo/ncs/zephyr/tests/benchmarks/dhrystone/b/zephyr/include/generated/autoconf.h -ffreestanding -Wno-main -fno-common -fno-asynchronous-unwind-tables -fno-pie -fno-pic -fno-strict-overflow -Wno-pointer-sign -Wno-unused-but-set-variable -fno-reorder-functions -fno-defer-pop -Werror=implicit-int -Wpointer-arith -ffunction-sections -fdata-sections -fno-freestanding -m32 -MMD -MP -include /home/sebo/ncs/zephyr/arch/posix/include/posix_cheats.h -std=c11 -mfloat-abi=soft -Wno-implicit-int -Wno-implicit-function-declaration -Wno-return-type -Wno-maybe-uninitialized -MD -MT zephyr/CMakeFiles/offsets.dir/arch/posix/core/offsets/offsets.c.obj -MF zephyr/CMakeFiles/offsets.dir/arch/posix/core/offsets/offsets.c.obj.d -o zephyr/CMakeFiles/offsets.dir/arch/posix/core/offsets/offsets.c.obj   -c /home/sebo/ncs/zephyr/arch/posix/core/offsets/offsets.c
gcc: error: unrecognized command line option ‘-mfloat-abi=soft’
ninja: build stopped: subcommand failed.
sebo@mach:~/ncs/zephyr/tests/benchmarks/dhrystone$ 
```

And when running it on nrf52840_pca10056 with the gnuarmemb toolchain I get another:

```
gettimeofdayr.c:(.text._gettimeofday_r+0x10): undefined reference to `_gettimeofday'
collect2: error: ld returned 1 exit status
%
ninja: build stopped: subcommand failed.

```

When running it on nrf52840_pca10056 with the Zephyr SDK toolchain I get it to build, but I don't get any serial output indicating what the benchmark score is:

`***** Bootng Zephyr S v1.14.0-r3-8-g257c2e0180b ****
`

These issues must be addressed.

File: tests/benchmarks/dhrystone/src/dhry_2.c (hunk 2 above)
Comment (kelvincheung) [reply tests/benchmarks/dhrystone/src/dhry_2.c]: Hi Jukkar,
I'm not sure about the this.
dhrystone is an ancient program and the license is undeclared on its website.

Comment (jukkar) [reply tests/benchmarks/dhrystone/src/dhry_2.c]: I am not a lawyer, but if there is no known license for this code, then it might be a blocker for merging this code into zephyr.

**Comment by kelvincheung** [comment]
> This test is missing a .yml file that expresses which platforms it runs on.
> 
> Also, it is missing a .rst file.
> 
> When running this test on native_posix I got this error:
> 
> ```
> ccache /usr/bin/gcc -DBUILD_VERSION=v1.14.0-rc3-8-g257c22e0180b -DHZ=100 -DKERNEL -DNO_PROTOTYPES=1 -D_FORTIFY_SOURCE=2 -D_POSIX_C_SOURCE=200809 -D_XOPEN_SOURCE=600 -D_XOPEN_SOURCE_EXTENDED -D__ZEPHYR__=1 -I../../../../kernel/include -I../../../../arch/posix/include -I../../../../include -I../../../../include/drivers -Izephyr/include/generated -I../../../../soc/posix/inf_clock -I../../../../boards/posix/native_posix -I/home/sebo/ncs/nrf/include -m32    -Os -g -Wall -Wformat -Wformat-security -Wno-format-zero-length -imacros /home/sebo/ncs/zephyr/tests/benchmarks/dhrystone/b/zephyr/include/generated/autoconf.h -ffreestanding -Wno-main -fno-common -fno-asynchronous-unwind-tables -fno-pie -fno-pic -fno-strict-overflow -Wno-pointer-sign -Wno-unused-but-set-variable -fno-reorder-functions -fno-defer-pop -Werror=implicit-int -Wpointer-arith -ffunction-sections -fdata-sections -fno-freestanding -m32 -MMD -MP -include /home/sebo/ncs/zephyr/arch/posix/include/posix_cheats.h -std=c11 -mfloat-abi=soft -Wno-implicit-int -Wno-implicit-function-declaration -Wno-return-type -Wno-maybe-uninitialized -MD -MT zephyr/CMakeFiles/offsets.dir/arch/posix/core/offsets/offsets.c.obj -MF zephyr/CMakeFiles/offsets.dir/arch/posix/core/offsets/offsets.c.obj.d -o zephyr/CMakeFiles/offsets.dir/arch/posix/core/offsets/offsets.c.obj   -c /home/sebo/ncs/zephyr/arch/posix/core/offsets/offsets.c
> gcc: error: unrecognized command line option ‘-mfloat-abi=soft’
> ninja: build stopped: subcommand failed.
> sebo@mach:~/ncs/zephyr/tests/benchmarks/dhrystone$ 
> ```
> 
> And when running it on nrf52840_pca10056 with the gnuarmemb toolchain I get another:
> 
> ```
> gettimeofdayr.c:(.text._gettimeofday_r+0x10): undefined reference to `_gettimeofday'
> collect2: error: ld returned 1 exit status
> %
> ninja: build stopped: subcommand failed.
> ```
> 
> When running it on nrf52840_pca10056 with the Zephyr SDK toolchain I get it to build, but I don't get any serial output indicating what the benchmark score is:
> 
> `***** Bootng Zephyr S v1.14.0-r3-8-g257c2e0180b **** `
> 
> These issues must be addressed.

It is suggested to compile dhrystone with newlib.

**Comment by nashif** [comment]
stale
