### PR TITLE
Bluetooth: controller: split: Fix conditional compile error

### PR DESCRIPTION
**Pull request by cvinayak**
Fix conditional compilation error in building the central
only samples as all peripheral structure member accesses in
the controller where not correctly compiled out.

Regression introduced in commit 6d8b12468e95 ("Bluetooth:
controller: split: Refactor LLL conn structure").

Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

### CODE REVIEW

**Review by mtpr-ot — APPROVED** [review]
LGTM

**Review by ioannisg — APPROVED** [review]
Looks ok to me

File: subsys/bluetooth/controller/ll_sw/ull_conn.c [hunk 1]
```diff
@@ -976,8 +989,15 @@ void ull_conn_done(struct node_rx_event_done *done)
...
 			}
+#endif /* CONFIG_BT_PERIPHERAL */
+
+#if defined(CONFIG_BT_CENTRAL)
 		} else if (reason_peer) {
 			conn->master.terminate_ack = 1;
+#endif /* CONFIG_BT_CENTRAL */
+
+		} else {
+			LL_ASSERT(0);
```
Comment (mtpr-ot) [inline subsys/bluetooth/controller/ll_sw/ull_conn.c]: I think this can safely be removed

**Review by carlescufi — APPROVED** [review]

File: subsys/bluetooth/controller/ll_sw/ull_conn.c (hunk 1 above)
Comment (cvinayak) [reply subsys/bluetooth/controller/ll_sw/ull_conn.c]: Fixed.

File: subsys/bluetooth/controller/ll_sw/ull_conn.c [hunk 2]
```diff
@@ -949,7 +949,18 @@ void ull_conn_done(struct node_rx_event_done *done)
 	 * Slave received terminate ind or MIC failure
 	 */
 	reason_peer = conn->llcp_terminate.reason_peer;
-	if (reason_peer && (lll->role || conn->master.terminate_ack)) {
+	if (reason_peer && (
```
Comment (alexandru-porosanu-nxp) [inline subsys/bluetooth/controller/ll_sw/ull_conn.c]: @cvinayak , this seems a bit overly complicated to follow. I propose the following alternative:

```
tmp = 1;
#if CONFIG_BT_CENTRAL
tmp = conn->master.terminate_ack;
#endif
#if CONFIG_BT_PERIPHERAL		    
tmp ||= lll->role;
#endif

if (reason_peer && tmp) {
	...
}
```

Does this make sense?

**Review by alexandru-porosanu-nxp — COMMENTED** [review]
OK, so this fixes #20233; I need to figure out what's broken on the OpenISA SW LL, since I still see failures for central_hr.
