### PR TITLE
drivers: ptp_clock_nxp_enet: misc fixes and fixing build error due to net test disabling ethernet drivers

### LINKED ISSUE #71738: tests: net.ptp.clock: frdm_k64f:  build failure
**Describe the bug**

net.ptp.clock build failure

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?
 - frdm_k64f
 - What have you tried to diagnose or workaround this issue?
 -  no
 - Is this a regression? If yes, have you been able to "git bisect" it to a
   specific commit?
 - git bisect find this is introduced by

```

commit 537d5c310c3e9d22f1df9a6d0bd1e250c84216fb
Author: Declan Snyder <declan.snyder@nxp.com>
Date:   Mon Mar 18 18:42:55 2024 -0500

    dts: nxp: Convert ENET DT default to new binding.
    
    Convert all of the NXP SOCs with ENET to use the new
    binding scheme, which is used by the new driver.
    
```

**To Reproduce**
west build -b frdm_k64f tests/net/ptp/clock

**Expected behavior**
build pass

**Impact**
PTP function

**Logs and console output**

```
/home/shared/disk/zephyr_project/zephyr_test/zephyr/drivers/ptp_clock/ptp_clock_nxp_enet.c:19:10: fatal error: fsl_enet.h: No such file or directory
   19 | #include "fsl_enet.h"
      |          ^~~~~~~~~~~~
compilation terminated.
[118/190] Building C object zephyr/subsys/net/ip/CMakeFiles/subsys__net__ip.dir/ipv6_nbr.c.obj
ninja: build stopped: subcommand failed.
FATAL ERROR: command exited with status 1: /home/ubuntu/.local/bin/cmake --build /home/shared/disk/zephyr_project/zephyr_test/zephyr/build
```

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used:  v3.6.0-2700-ga6400b42feeb

### PR DESCRIPTION
**Pull request by decsny**
1. Correct node label in k64 overlay for ptp test
   - Not sure if this actually matters since it appears that actual hardware is no longer tested in net tests

2. Include fsl_enet with <> instead of "".

3. Build the ptp clock driver only if the ethernet driver is built
   - Technically I think the 1588 timer should be able to be used even if the ethernet mac is not used, but I would imagine this to be an extraordinarily rare, weird, and niche use case, so to fix the current CI error caused by net test disabling ethernet drivers, couple the ptp clock driver to the ethernet driver in the build configuration.

Fixes #71738

### CODE REVIEW

**Comment by jukkar** [comment]
> * Not sure if this actually matters since it appears that actual hardware is no longer tested in net tests

Note that actual Ethernet hw has or should have never been tested by net tests. The net tests are meant to be self contained and the tests use either Dummy network or simulated generic Ethernet. The reason is that the functional tests in `tests/net` are meant to test the various network APIs and libraries, and not the actual device drivers. There has been some bugs before where the hw Ethernet driver was accidentally enabled but those should be fixed atm.

**Review by jukkar — APPROVED** [review]

File: drivers/ptp_clock/Kconfig.nxp_enet [hunk 1]
```diff
@@ -5,5 +5,6 @@ config PTP_CLOCK_NXP_ENET
 	bool "NXP ENET PTP Clock driver"
 	default y
 	depends on DT_HAS_NXP_ENET_PTP_CLOCK_ENABLED && NET_L2_PTP
+	depends on ETH_NXP_ENET
```
Comment (danieldegrasse) [inline drivers/ptp_clock/Kconfig.nxp_enet:8]: I'm not familiar with the PTP testcase, but it seems that the `tests/net/ptp/clock/prj.conf` file sets `CONFIG_NET_TEST`, which in turn disables `CONFIG_ETH_DRIVER`. This causes `CONFIG_ETH_NXP_ENET` to be false as well, so the PTP driver won't be built either because of this dependency.

Is this intentional? It seems like we'd want the PTP driver to be built by this testcase.

Comment (danieldegrasse) [reply drivers/ptp_clock/Kconfig.nxp_enet:8]: It seems if I add a line like the following:

```diff
--- a/mcux/hal_nxp.cmake
+++ b/mcux/hal_nxp.cmake
@@ -160,6 +160,7 @@ include_driver_ifdef(CONFIG_ENTROPY_MCUX_RNGA               rnga            driver_rnga)
 include_driver_ifdef(CONFIG_ENTROPY_MCUX_TRNG          trng            driver_trng)
 include_driver_ifdef(CONFIG_ENTROPY_MCUX_CAAM          caam            driver_caam)
 include_driver_ifdef(CONFIG_ETH_NXP_ENET               enet            driver_enet)
+include_driver_ifdef(CONFIG_PTP_CLOCK_NXP_ENET         enet            driver_enet)
 include_driver_ifdef(CONFIG_HAS_MCUX_SMC               smc             driver_smc)
 include_driver_ifdef(CONFIG_I2C_MCUX                   i2c             driver_i2c)
 if (CONFIG_NXP_LP_FLEXCOMM)
```
to the MCUX HAL that we can build the PTP driver with this testcase

Comment (danieldegrasse) [reply drivers/ptp_clock/Kconfig.nxp_enet:8]: Based on @jukkar's comment it seems we don't want to test the PTP driver's build with this sample, so adding this dependency would make sense

Comment (decsny) [reply drivers/ptp_clock/Kconfig.nxp_enet:8]: yes the point of this change is to make it not build

**Review by danieldegrasse — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]

**Review by hakehuang — APPROVED** [review]
