### PR TITLE
tests: display: use qualified MCXA577 platform

### LINKED ISSUE #117957: display: drivers.display.check.shield link failure on FRDM-MCXA577
## Describe the bug

The `drivers.display.check.shield` Twister scenario fails at link time for the `frdm_mcxa577` targets

The link references a devicetree device ordinal from the FlexIO LCDIF MIPI DBI driver, but the corresponding device definition is absent:

- `frdm_mcxa577/mcxa577/t1s`: `undefined reference to __device_dts_ord_144`
- `frdm_mcxa577/mcxa577/ns`: `undefined reference to __device_dts_ord_151`

The failing object is `mipi_dbi_nxp_flexio_lcdif.c.obj`. The failure occurs while linking `zephyr_pre0.elf`, not while compiling the driver.

The CI test was run for PR #117331, which removes the `frdm_mcxa577:SHIELD=lcd_par_s035_8080` per-platform configuration from the display-check scenario. It appears that the scenario can still be selected for the MCXA577 board targets without the required shield/device configuration.

## Regression

- [ ] This is a regression.

No `git bisect` has been performed. The failure was observed on the PR commit identified below.

## Steps to reproduce

1. Check out `0a20a4aa1dbbc0e940c9450c99d356f18e31a9b6` from PR #117331.
2. Use Zephyr SDK 1.0.1.
3. Run the CI build command:

   ```sh
   scripts/twister --vendor nxp -j 12 -T samples/drivers/display -T tests/drivers/display --build-only --inline-logs -M all
   ```

4. Observe the link failures for `drivers.display.check.shield` on:
   - `frdm_mcxa577/mcxa577/t1s`
   - `frdm_mcxa577/mcxa577/ns`

## Relevant log output

```shell
# frdm_mcxa577/mcxa577/t1s
[187/192] Linking C executable zephyr/zephyr_pre0.elf
FAILED: zephyr/zephyr_pre0.elf zephyr/zephyr_pre0.map
.../arm-zephyr-eabi/bin/ld.bfd: zephyr/libzephyr.a(mipi_dbi_nxp_flexio_lcdif.c.obj):(.data.mcux_flexio_lcdif_config_0+0x34): undefined reference to `__device_dts_ord_144`
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

# frdm_mcxa577/mcxa577/ns
[205/210] Linking C executable zephyr/zephyr_pre0.elf
FAILED: zephyr/zephyr_pre0.elf zephyr/zephyr_pre0.map
.../arm-zephyr-eabi/bin/ld.bfd: zephyr/libzephyr.a(mipi_dbi_nxp_flexio_lcdif.c.obj):(.data.mcux_flexio_lcdif_config_0+0x34): undefined reference to `__device_dts_ord_151`
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

## Impact

Functional Limitation – the display shield test cannot be built for two `frdm_mcxa577` board targets in the NXP CI matrix.

## Environment

- OS: Linux (Jenkins CI agent)
- Toolchain: Zephyr SDK 1.0.1; `arm-zephyr-eabi` GCC 14.3.0
- Zephyr version: `v4.4.0-13612-g0a20a4aa1dbb`
- Commit SHA: `0a20a4aa1dbbc0e940c9450c99d356f18e31a9b6`
- PR under test: https://github.com/zephyrproject-rtos/zephyr/pull/117331

## Additional Context

This was observed in NXP's PR test build 117331. The associated CI log URLs are internal and cannot be shared publicly. The relevant failure output is included above.

### PR DESCRIPTION
**Pull request by hakehuang**
## Summary

Update the display-check test platform selector for the `lcd_par_s035_8080` shield to use the fully qualified `frdm_mcxa577/mcxa577` board target.

## Testing

- Confirmed the new platform entry is present and the old entry is absent.
- `git diff --check`

Fixes: #117957

### CODE REVIEW

**Review by JarmouniA — APPROVED** [review]

**Comment by hakehuang** [comment]
Superseded by #117969, which uses the required nxp-upstream fork and includes a complete signed-off commit message body.

**Review by ZhaoxiangJin — APPROVED** [review]
