### ISSUE TITLE
samples: audio: sof: compilation issue, include file not found.

### ISSUE THREAD

**Issue by ABOSTM** [zephyrproject-rtos/zephyr#31143]
**Describe the bug**
While running automatic tests on STM32 test bench,
samples/audio/sof build fails to build.
This appends on all STM32 boards but could also be seen on NON STM32 (frdm_k64f)

This is a new sample introduced by #30336

**To Reproduce**
1. scripts/twister --ninja --runtime-artifact-cleanup -b  -p nucleo_f429zi  -T samples/audio/sof/ --outdir ./log_db_audio
2. See error

**Expected behavior**
Build successful or sample not build for those boards

**Logs and console output**
```
In file included from /home/osboxes/zephyr/zephyr_project/modules/audio/sof/zephyr/../src/arch/xtensa/include/arch/drivers/timer.h:13,
                 from /home/osboxes/zephyr/zephyr_project/modules/audio/sof/zephyr/../src/include/sof/drivers/timer.h:11,
                 from /home/osboxes/zephyr/zephyr_project/modules/audio/sof/src/lib/clk.c:10:
/home/osboxes/zephyr/zephyr_project/modules/audio/sof/zephyr/../src/include/sof/drivers/interrupt.h:11:10: fatal error: platform/drivers/interrupt.h: No such file or directory
   11 | #include <platform/drivers/interrupt.h>
```

**Environment (please complete the following information):**
 - OS:  Linux
 - Toolchain Zephyr SDK
 - Commit SHA: 536f0f5acbce4c974709d5c5ce224eaac6b08022

**Additional context**
In `sample.yaml` there is:
```
    integration_platforms:
      - intel_adsp_cavs15
```
So is it normal that twister try to build for other platforms ?
(I don't catch exactly the difference between `integration_platforms `and `platform_allow`)

**Comment by ABOSTM** [comment]
^^ @nashif @andyross

**Comment by lgirdwood** [comment]
@nashif are you ok to fix this and #31153 to temp exclude the non CAVS SoC until @lyakh generic work is ready.

**Comment by galak** [comment]
@lgirdwood I think something like:

```
diff --git a/modules/Kconfig.sof b/modules/Kconfig.sof
index 17e40df34b..fb5b5c125e 100644
--- a/modules/Kconfig.sof
+++ b/modules/Kconfig.sof
@@ -3,5 +3,6 @@
 
 config SOF
        bool "Sound Open Firmware (SOF)"
+       depends on SOC_FAMILY_INTEL_ADSP
        help
          Build Sound Open Firmware (SOF) support.
diff --git a/samples/audio/sof/sample.yaml b/samples/audio/sof/sample.yaml
index 32ba0df254..c726df2fc4 100644
--- a/samples/audio/sof/sample.yaml
+++ b/samples/audio/sof/sample.yaml
@@ -7,5 +7,6 @@ tests:
   sample.audio.sof:
     tags: sof
     build_only: true
+    filter: ( CONFIG_SOF )
     integration_platforms:
       - intel_adsp_cavs15
```

as a start.

**Comment by galak** [comment]
However even when I do that, I get the following on intel_adsp_cavs15:

```
In file included from /home/galak/git/modules/audio/sof/src/platform/intel/cavs/platform.c:46:
/home/galak/git/modules/audio/sof/zephyr/../src/include/kernel/ext_manifest.h:32:10: fatal error: rimage/sof/kernel/ext_manifest.h: No such file or directory
   32 | #include <rimage/sof/kernel/ext_manifest.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by galak** [comment]
Does this require SDK 0.12.0?

**Comment by lgirdwood** [comment]
@lyakh any comment here, IIRC you have some PR pending with rimage updates for manifest (like above error) ?

**Comment by nashif** [comment]
you need to run `west sof update`

**Comment by nashif** [comment]
> depends on SOC_FAMILY_INTEL_ADSP

we should not add such dependency, the idea is to make SOF also work on non Intel SoCs...

lets just limit what platforms this can run on using explicit platform filters.

**Comment by galak** [comment]
> you need to run `west sof update`

???? what is this doing?  Why isn't this just part of the zephyr west.yml?

**Comment by nashif** [comment]
> ???? what is this doing? Why isn't this just part of the zephyr west.yml?

This is fetching git submodules needed by SOF. Tried putting those in west, but then the submodules have their own submodules....

**Comment by nashif** [comment]
> This is fetching git submodules needed by SOF. Tried putting those in west, but then the submodules have their own submodules....

same story as with espressif module with a PR pending, we really need the west support for submodules to get over this type of issues...

**Comment by galak** [comment]
So I feel like this needs more discussion as this seems to violates having modules being "copied" into zephyr github.

**Comment by galak** [comment]
@carlescufi / @ioannisg -- I think we need to discuss how zephyr as a project will handle modules w/git submodules as a general rule.

**Comment by nashif** [comment]
> So I feel like this needs more discussion as this seems to violates having modules being "copied" into zephyr github.

what is being copied in zephyr github? The modules are not in Zephyr's github.

**Comment by galak** [comment]
> > 
> 
> we should not add such dependency, the idea is to make SOF also work on non Intel SoCs...
> 
> lets just limit what platforms this can run on using explicit platform filters.

We'll the SOF code current seems limited to xtensa and maybe just the Intel SoCs at this point.  So I agree in principle this shouldn't be the case but if I enable CONFIG_SOF and another platform it's looking for xtensa code.  So feels like for right now CONFIG_SOF is only viable on the Intel xtensa SoCs.  When that changes we can remove the `depends on` that I suggest.

**Comment by nashif** [comment]
> So I agree in principle this shouldn't be the case but if I enable CONFIG_SOF and another platform it's looking for xtensa code.

NXP Platforms with audio DSP also can use SOF on top of Xtensa.
