### PR TITLE
drivers: wifi: fix simplelink driver to use ENOTSOCK

### LINKED ISSUE #29805: SimpleLink does not compile (simplelink_sockets.c)
simplelink_sockets.c does not compile as it references the symbol ENSOCK that does not seem to be defined anywhere in the Zephyr sources:

https://github.com/zephyrproject-rtos/zephyr/search?q=ENSOCK

../simplelink/simplelink_sockets.c:70:11: error: 'ENSOCK' undeclared (first use in this function); did you mean 'ENOTSOCK'?
   70 |   error = ENSOCK;
      |           ^~~~~~
      |           ENOTSOCK

### PR DESCRIPTION
**Pull request by cfriedt**
ENSOCK seems to have been a typo or possibly copy / paste error introduced in 2e15b0f6118ce0414666873bcec5ecfc2cbe5cb0.

ENOTSOCK seems to be the Zephyr equivalent.

Fixes #29805

### CODE REVIEW

**Review by galak — APPROVED** [review]

**Review by tbursztyka — APPROVED** [review]

File: drivers/wifi/simplelink/simplelink_sockets.c [hunk 1]
```diff
@@ -58,7 +58,7 @@ static int getErrno(_i32 error)
 		error = EBADF;
 		break;
 #endif
-#if ENSOCK !=  SL_ERROR_BSD_ENSOCK
+#if ENOTSOCK !=  SL_ERROR_BSD_ENSOCK
```
Comment (jukkar) [inline drivers/wifi/simplelink/simplelink_sockets.c:61]: Hmm, how this is fixing the compile issue, few lines below we try to set the `ENSOCK` to error variable?
The function seems to try to map TI HAL errno to Zephyr errno, there is also some mention of zephyr in `simplelink/source/ti/drivers/net/wifi/porting/user.h` where it introduces `ENSOCK`. So in theory the `ENSOCK` should exists at this point.
I am not sure how the code should look like but this looks just wrong to me.

**Review by jukkar — CHANGES_REQUESTED** [review]
I am giving -1 for time being until we figure out if this really is the correct thing to do.

File: drivers/wifi/simplelink/simplelink_sockets.c (hunk 1 above)
Comment (vanti) [reply drivers/wifi/simplelink/simplelink_sockets.c:61]: @cfriedt  ENSOCK is mapped to ENFILE in the hal as @jukkar mentioned, I don't think ENOTSOCK is the correct error code to use when the max number of sockets is exceeded, hence should not be used here.
