### PR TITLE
modules: mbedtls: fix pk ecc functions undefined references

### PR DESCRIPTION
**Pull request by joelguittet**
Fix undefined reference to mbedtls_pk_ecc_xxx functions following update to latest mbedtls version.

It is broken since the latest mbedtls update done in Pull Request https://github.com/zephyrproject-rtos/zephyr/pull/71118

The errors I got without this fix was the following:

```
/home/ubuntu/zephyr-sdk-0.16.1/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: modules/mbedtls/libmbedTLSCrypto.a(pkparse.c.obj): in function `pk_use_ecparams':
/home/ubuntu/zephyrproject/modules/crypto/mbedtls/library/pkparse.c:405: undefined reference to `mbedtls_pk_ecc_set_group'
/home/ubuntu/zephyr-sdk-0.16.1/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: modules/mbedtls/libmbedTLSCrypto.a(pkparse.c.obj): in function `pk_parse_key_sec1_der':
/home/ubuntu/zephyrproject/modules/crypto/mbedtls/library/pkparse.c:673: undefined reference to `mbedtls_pk_ecc_set_key'
/home/ubuntu/zephyr-sdk-0.16.1/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: /home/ubuntu/zephyrproject/modules/crypto/mbedtls/library/pkparse.c:697: undefined reference to `mbedtls_pk_ecc_set_pubkey'
/home/ubuntu/zephyr-sdk-0.16.1/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: /home/ubuntu/zephyrproject/modules/crypto/mbedtls/library/pkparse.c:714: undefined reference to `mbedtls_pk_ecc_set_pubkey_from_prv'
/home/ubuntu/zephyr-sdk-0.16.1/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: modules/mbedtls/libmbedTLSCrypto.a(pkparse.c.obj): in function `mbedtls_pk_parse_subpubkey':
/home/ubuntu/zephyrproject/modules/crypto/mbedtls/library/pkparse.c:581: undefined reference to `mbedtls_pk_ecc_set_pubkey'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

pk_ecc.c file is new, functions have been moved here by the mbedtls project recently.

### CODE REVIEW

**Review by tomi-font — APPROVED** [review]
Thanks for the fix! FYI @valeriosetti

**Review by valeriosetti — APPROVED** [review]
LGTM. Thanks!

**Comment by joelguittet** [comment]
@tomi-font @valeriosetti @d3zd3z hello! anything blocking the merge now ?

**Comment by mniestroj** [comment]
Duplcate of #72820

**Review by mniestroj — APPROVED** [review]

**Comment by joelguittet** [comment]
Correct. One of the two should be merged. This is a blocking point for severals using mbedtls!

**Comment by valeriosetti** [comment]
> @tomi-font @valeriosetti @d3zd3z hello! anything blocking the merge now ?

IMO no, this PR is absolutely OK. But I don't have the rights to merge it (actually even my review is a grey tick :sweat_smile: )

**Comment by tomi-font** [comment]
ping @carlescufi @MaureenHelm @jhedberg Can one of you merge this or the other PR and close the duplicate?

**Review by jhedberg — APPROVED** [review]
