### PR TITLE
net/pkt: Fix debug logs checking

### PR DESCRIPTION
**Pull request by tgorochowik**
The slab2str function which is used in the debug log call is not defined
unless NET_LOG_PKT_LOG_LEVEL >= LOG_LEVEL_DEBUG.

It looks like this change was accidentally introduced in #11374.

Easiest way to reproduce:
Use the `net/sockets/echo` sample with `NET_DEBUG_NET_PKT_ALLOC` enabled.

Compilation renders:

```
In file included from /path/zephyr/include/logging/log.h:11:0,
                 from /path/zephyr/subsys/net/ip/net_pkt.c:13:                   
/path/zephyr/subsys/net/ip/net_pkt.c: In function ‘net_pkt_get_reserve_data_debug’:
/path/zephyr/subsys/net/ip/net_pkt.c:399:3: warning: implicit declaration of function ‘pool2str’ [-Wimplicit-function-declaration]
   pool2str(pool), get_name(pool), get_frees(pool), 
(...)
```

### CODE REVIEW

**Review by tbursztyka — APPROVED** [review]
logging management in net_pkt is quite a mess actually.

**Review by carlescufi — APPROVED** [review]
