### PR TITLE
Revert 73978 & 74096 due to regressions

### LINKED ISSUE #75205: multipe tests/posix & tests/lib/c_lib/thrd build failures due to missing time.h definitions
**Describe the bug**
* tests/posix/common/portability.posix.common.newlib 
* tests/posix/common/portability.posix.common.tls.newlib
* tests/posix/fs/portability.posix.fs.newlib
* tests/posix/fs/portability.posix.fs.tls.newlib
* tests/posix/headers/portability.posix.headers.newlib.with_posix_api
* tests/lib/c_lib/thrd/libraries.libc.c11_threads.newlib
* tests/lib/c_lib/thrd/libraries.libc.c11_threads.newlib_nano

build failure in the following platforms:

* circuitdojo_feather/nrf9160/ns
* actinius_icarus_bee/nrf9160/ns
* actinius_icarus@2.0.0/nrf9160/ns
* actinius_icarus@1.4.0/nrf9160/ns
* innblue21/nrf9160/ns
* innblue22/nrf9160/ns
* lpcxpresso55s69/lpc55s69/cpu0/ns
* actinius_icarus_som_dk/nrf9160/ns
* actinius_icarus_som/nrf9160/ns
* mimxrt1010_evk
* mimxrt1024_evk
* mimxrt1015_evk
* mimxrt1020_evk
* mimxrt1040_evk
* mimxrt1060_evk
* mimxrt1050_evk
* mimxrt1060_evk@hyperflash
* mimxrt1060_evkb
* mimxrt1050_evk@qspi
* mimxrt1170_evk@B/mimxrt1176/cm7
* mimxrt1062_fmurt6
* mimxrt1170_evk/mimxrt1176/cm7
* mimxrt1160_evk/mimxrt1166/cm7
* mimxrt1064_evk
* mm_feather
* mimxrt595_evk/mimxrt595s/cm33
* mm_swiftio
* mimxrt685_evk/mimxrt685s/cm33
* nrf5340dk/nrf5340/cpuapp/ns
* nrf5340_audio_dk/nrf5340/cpuapp/ns
* nrf9151dk/nrf9151/ns
* nrf9160dk/nrf9160/ns
* nrf9131ek/nrf9131/ns
* nrf9160dk@0.7.0/nrf9160/ns
* nrf9161dk/nrf9161/ns
* nrf9161dk@0.7.0/nrf9161/ns
* raytac_mdbt53_db_40/nrf5340/cpuapp/ns
* raytac_mdbt53v_db_40/nrf5340/cpuapp/ns
* sparkfun_thing_plus/nrf9160/ns
* b_u585i_iot02a/stm32u585xx/ns
* stm32l562e_dk/stm32l562xx/ns
* thingy53/nrf5340/cpuapp/ns
* vmu_rt1170/mimxrt1176/cm7
* bl5340_dvk/nrf5340/cpuapp/ns

**To Reproduce**

```
twister -i -p mimxrt1170_evk/mimxrt1176/cm7 -s portability.posix.headers.newlib.with_posix_api
```

**Expected behavior**
build PASS

**Impact**
POSIX compatible
~190 failures in weekly CI
Failures in PRs CI when these tests are triggered

**Logs and console output**

```
modules/crypto/mbedtls/library/platform_util.c
In file included from zephyr/include/zephyr/posix/time.h:116,
                 from zephyr/include/zephyr/posix/time.h:12,
                 from zephyr/include/zephyr/net/socket_select.h:22,
                 from zephyr/include/zephyr/posix/sys/select.h:10,
                 from zephyr-sdk-0.16.8/arm-zephyr-eabi/arm-zephyr-eabi/sys-include/sys/types.h:50,
                 from zephyr-sdk-0.16.8/arm-zephyr-eabi/arm-zephyr-eabi/sys-include/stdio.h:61,
                 from modules/crypto/mbedtls/include/mbedtls/platform.h:58,
                 from modules/crypto/mbedtls/library/platform_util.c:26:
zephyr-sdk-0.16.8/arm-zephyr-eabi/arm-zephyr-eabi/sys-include/time.h:56:1: error: unknown type name 'clock_t'
   56 | clock_t    clock (void);
      | ^~~~~~~
zephyr-sdk-0.16.8/arm-zephyr-eabi/arm-zephyr-eabi/sys-include/time.h:30:1: note: 'clock_t' is defined in header '<time.h>'; did you forget to '#include <time.h>'?
   29 | #include <sys/timespec.h>
  +++ |+#include <time.h>
   30 | 
In file included from zephyr/include/zephyr/posix/posix_types.h:15,
                 from zephyr/include/zephyr/posix/time.h:61:
zephyr-sdk-0.16.8/arm-zephyr-eabi/arm-zephyr-eabi/sys-include/sys/_pthreadtypes.h:182:3: error: unknown type name 'clock_t'
  182 |   clock_t  clock;             /* specifiy clock for timeouts */
      |   ^~~~~~~
zephyr/include/zephyr/posix/posix_types.h:76:9: error: unknown type name 'clockid_t'
   76 |         clockid_t clock;
      |         ^~~~~~~~~
zephyr/include/zephyr/posix/time.h:93:19: error: unknown type name 'clockid_t'; did you mean 'clock_pfd_t'?
   93 | int clock_gettime(clockid_t clock_id, struct timespec *ts);
      |                   ^~~~~~~~~
      |                   clock_pfd_t
zephyr/include/zephyr/posix/time.h:94:18: error: unknown type name 'clockid_t'; did you mean 'clock_pfd_t'?
   94 | int clock_getres(clockid_t clock_id, struct timespec *ts);
      |                  ^~~~~~~~~
      |                  clock_pfd_t
zephyr/include/zephyr/posix/time.h:95:19: error: unknown type name 'clockid_t'; did you mean 'clock_pfd_t'?
   95 | int clock_settime(clockid_t clock_id, const struct timespec *ts);
      |                   ^~~~~~~~~
      |                   clock_pfd_t
zephyr/include/zephyr/posix/time.h:96:36: error: unknown type name 'clockid_t'; did you mean 'clock_pfd_t'?
   96 | int clock_getcpuclockid(pid_t pid, clockid_t *clock_id);
      |                                    ^~~~~~~~~
      |                                    clock_pfd_t
zephyr/include/zephyr/posix/time.h:98:18: error: unknown type name 'clockid_t'; did you mean 'clock_pfd_t'?
   98 | int timer_create(clockid_t clockId, struct sigevent *evp, timer_t *timerid);
      |                  ^~~~~~~~~
      |                  clock_pfd_t
zephyr/include/zephyr/posix/time.h:105:21: error: unknown type name 'clockid_t'; did you mean 'clock_pfd_t'?
  105 | int clock_nanosleep(clockid_t clock_id, int flags,
      |                     ^~~~~~~~~
      |                     clock_pfd_t
In file included from zephyr/include/zephyr/sys/fdtable.h:13,
                 from zephyr/include/zephyr/net/socket_select.h:26:
zephyr/include/zephyr/fs/fs.h:368:1: error: unknown type name 'ssize_t'; did you mean '_ssize_t'?
  368 | ssize_t fs_read(struct fs_file_t *zfp, void *ptr, size_t size);
      | ^~~~~~~
      | _ssize_t
zephyr/include/zephyr/fs/fs.h:389:1: error: unknown type name 'ssize_t'; did you mean '_ssize_t'?
  389 | ssize_t fs_write(struct fs_file_t *zfp, const void *ptr, size_t size);
      | ^~~~~~~
      | _ssize_t
zephyr/include/zephyr/fs/fs.h:409:36: error: unknown type name 'off_t'; did you mean '_off_t'?
  409 | int fs_seek(struct fs_file_t *zfp, off_t offset, int whence);
      |                                    ^~~~~
      |                                    _off_t
zephyr/include/zephyr/fs/fs.h:425:1: error: unknown type name 'off_t'; did you mean '_off_t'?
  425 | off_t fs_tell(struct fs_file_t *zfp);
      | ^~~~~
      | _off_t
zephyr/include/zephyr/fs/fs.h:447:40: error: unknown type name 'off_t'; did you mean '_off_t'?
  447 | int fs_truncate(struct fs_file_t *zfp, off_t length);
      |                                        ^~~~~
      |                                        _off_t
zephyr/include/zephyr/sys/fdtable.h:48:17: error: expected specifier-qualifier-list before 'ssize_t'
   48 |                 ssize_t (*read)(void *obj, void *buf, size_t sz);
      |                 ^~~~~~~
zephyr/include/zephyr/sys/fdtable.h:52:17: error: expected specifier-qualifier-list before 'ssize_t'
   52 |                 ssize_t (*write)(void *obj, const void *buf, size_t sz);
      |                 ^~~~~~~
ninja: build stopped: subcommand failed.```
```

**Environment (please complete the following information):**
 - OS: (e.g. Linux)
 - Toolchain (e.g Zephyr SDK, ...) zephyr-sdk-0.16.8
 - Commit SHA or Version used: main after b82b5b0734c30490368e21627423f10036487343
 
**Additional info**
Introduced by #73978 
PR is not bisectable

Edited by @aescolar to encompass all cases of the same issue

### LINKED ISSUE #75364: net: samples: poll() fails in zperf sample
**Describe the bug**
`zperf` (and possibly other samples) return an error on poll() call:

```console
TCP server started on port 5001
[00:00:09.547,000] <inf> net_zperf: Binding to 192.168.0.110
[00:00:09.547,000] <inf> net_zperf: Binding to 2001:db8::1
[00:00:09.547,000] <inf> net_zperf: Listening on port 5001
[00:00:21.146,000] <err> net_sock_svc: poll failed (-12)
```
 
It's been identified that the regression introduced with the following change:
https://github.com/zephyrproject-rtos/zephyr/commit/93973e2ead9bc1e8e1bcf05d46cc292a05b49fdd#diff-b452e7c4588832212ecb0057d4e68d34ae43827d23317b370ba7d612bbb67064R51

Samples still use `NET_SOCKETS_POLL_MAX ` in their config file, which is no longer effective in increasing maximum pollfd entires due to introduction of `ZVFS_POLL_MAX`.

**To Reproduce**
1. `west build -p -b nucleo_h723zg samples/net/zperf` (or any other board)
2. Flash/run the application
3. Start zperf TCP server: `zperf tcp download`
4. Start iperf client: `iperf -c <IP address> -p 5001 -b 100M`
5. See the error.

**Impact**
Showstopper

**Environment (please complete the following information):**
 - Linux
 - Zephyr SDK 0.16.5-1
 - a6e672f9b2368e6d011da189afd462fec599fd0d

### PR DESCRIPTION
**Pull request by aescolar**
PR #73978 introduced a regression.
Unfortunately this PR cannot be reverted without reverting also
#74096.
Let's revert both PRs to stabilize main again towards the 3.7 release.

For more details on the issue see
https://github.com/zephyrproject-rtos/zephyr/issues/75205

Note during the revert cea6bf555f6646d84ff7deb489b14f815622caac conflicted, but it was merged taking the change in cea6bf555f6646d84ff7deb489b14f815622caac

Fixes #75205
Fixes #75364

---

Note the checkpatch error "Error: lib/posix/options/fs.c:89:WARNING: Violation to rule 21.2 (Should not used a reserved identifier) - rename" is the exact same as in the orinignal PR, as the diff contains the same lines just reverted.

### CODE REVIEW

**Review by ithinuel — COMMENTED** [review]
I confirm it solves https://github.com/zephyrproject-rtos/zephyr/issues/75205 👍 but I only ran limited testing so I cannot confirm it does not break something else.

**Review by cfriedt — DISMISSED** [review]
Hard no. I have a fix in branch. Today is a public holiday in Canada so I am away from my desk at the moment.

Do not merge

**Comment by henrikbrixandersen** [comment]
> Hard no. I have a fix in branch. Today is a public holiday in Canada so I am away from my desk at the moment.

@cfriedt Did you submit a fix in another PR?

**Comment by cfriedt** [comment]
> > Hard no. I have a fix in branch. Today is a public holiday in Canada so I am away from my desk at the moment.
> 
> @cfriedt Did you submit a fix in another PR?

Yes - it's just going through CI at the moment.

**Comment by rlubos** [comment]
@cfriedt We've identified another issue, specifically with this change:
https://github.com/zephyrproject-rtos/zephyr/commit/93973e2ead9bc1e8e1bcf05d46cc292a05b49fdd#diff-b452e7c4588832212ecb0057d4e68d34ae43827d23317b370ba7d612bbb67064R51
Many samples still use `NET_SOCKETS_POLL_MAX` to increase maximum poll entries, but it's now ineffective due to this change, as   `ZVFS_POLL_MAX` should be increased instead. I think `NET_SOCKETS_POLL_MAX` should've been deprecated and no longer used by samples and in several places in the stack.

**Comment by rapopforsthaus** [comment]
Sorry if this is the wrong place to ask this. This makes `NET_SOCKETS` use the experimental feature `ZVFS`:
https://github.com/zephyrproject-rtos/zephyr/commit/93973e2ead9bc1e8e1bcf05d46cc292a05b49fdd#diff-b452e7c4588832212ecb0057d4e68d34ae43827d23317b370ba7d612bbb67064R8
Are there any guidelines about experimental features? My company has the guideline to not use experimental features and our CI asserts this.

**Comment by kartben** [comment]
> > > Hard no. I have a fix in branch. Today is a public holiday in Canada so I am away from my desk at the moment.
> > 
> > 
> > @cfriedt Did you submit a fix in another PR?
> 
> Yes - it's just going through CI at the moment.

It would be helpful to link to the PR - thanks :)

**Comment by jukkar** [comment]
> Are there any guidelines about experimental features? My company has the guideline to not use experimental features and our CI asserts this.

At least in networking code, new APIs are marked as experimental so that we can change the APIs if needed. The experimental does not really mean that the feature does not work or something like that. I would say your company is a bit too strict here.
See also https://docs.zephyrproject.org/latest/develop/api/api_lifecycle.html#experimental

**Comment by cfriedt** [comment]
> I think `NET_SOCKETS_POLL_MAX` should've been deprecated and no longer used by samples and in several places in the stack.

@rlubos - is the change you're describing in-tree only? If so, I would be happy to approve it.

**Comment by cfriedt** [comment]
> It would be helpful to link to the PR - thanks :)

@kartben - there is a link in the issue?

**Comment by rlubos** [comment]
> > I think `NET_SOCKETS_POLL_MAX` should've been deprecated and no longer used by samples and in several places in the stack.
> 
> @rlubos - is the change you're describing in-tree only? If so, I would be happy to approve it. I'm away from my desk for the next several hours.

Well, for our case we bother about in-tree only, but it would affect any out-of-tree uses as well (for instance that config is used quite a lot in nRF Connect SDK examples). I'll try to provide a fix for this.

**Comment by aescolar** [comment]
@cfriedt I would say the best approach at this point is to revert the PR that introduced this issues by merging this PR.
After the release the original PR can be resubmitted with any changes that are necessary to ensure the issues which were discovered after merge are not a problem anymore.

**Comment by cfriedt** [comment]
My big concern here is that the development, review, and approval (even at TSC level) process was followed here to the T.

The commits that are being reverted here are the result of several months of "spare time" work (spanning several development branches and split into manageable, reviewable chunks), were reviewed, tested, and rebased over, and over, and over. They all passed CI through numerous rounds and had numerous re-approvals.

Why did CI fail (and manual twister runs) fail to catch these issues? I think there will be some work required to actually understand why.

The changes will form the basis of several companies' products going forward with LTSv3.

I honestly feel that we should not take such a willy-nilly approach to reverting PRs. I.e. the release manager should have reached-out to the maintainer in this area. That's a normal part of our protocol (I don't know if it's written down per se). That did not happen.

A simple ping on discord would have helped.

Instead, I was quite surprised to have to jump back into development on a holiday? Yesterday I had 4 hours of commuting, 4 hours of sleep.

In spite of that, I came up with a hotfix that is certainly less destructive than this PR.

As mentioned last week in the TSC meeting, without these in LTS, it will be difficult to backport several bug-fixes in multiple areas.

Just some food for thought. I'm out for the day unfortunately.

**Review by henrikbrixandersen — APPROVED** [review]

**Comment by aescolar** [comment]
@cfriedt unfortunately all that you mention is circumstantial. 
The issue is that this PR has introduced regressions, and there is no evident good way to fix it now beyond reverting to the state before the PR.
It happens some times. And reverting is the default agreed approach in those cases.
We just need to unblock other people and continue stabilizing towards the 3.7 release.
In that light it does not matter what the PR in question is, or the effort that was put into it. The work is not lost anyhow.  It can be resubmitted after when the issues have been ironed out.

**Comment by nashif** [comment]
> My big concern here is that the development, review, and approval (even at TSC level) process was followed here to the T.
> 

The TSC approved an exception, the TSC did not approve the PR uncondentially. At any given time, any PR that is causing such issues would be reverted if no fix is provided in time. We are at a critical time right now and we can't be spending time on something that was not tested well enough.

> The commits that are being reverted here are the result of several months of "spare time" work (spanning several development branches and split into manageable, reviewable chunks), were reviewed, tested, and rebased over, and over, and over. They all passed CI through numerous rounds and had numerous re-approvals.

Spare time or not? Why does this make a different? Doing something on your spare time is not really my or anyone's concern. We all dedicate spare time to the project, does not mean this needs to be treated differently.

> 
> Why did CI fail (and manual twister runs) fail to catch these issues? I think there will be some work required to actually understand why.

You need to tell us why, CI did exactly what it does for all PRs, the failing tests were built/run on the default platform, so it seems there is a gap in coverage, but that is a known "issue". Lets not blame CI, something like that needs also to be verified and tested outside of CI by the developer.

> 
> The changes will form the basis of several companies' products going forward with LTSv3.
> 
Well, in that case effort should have been done to get this in the tree long before the feature freeze, if that is important enough and more time and effort should have been put into making this happen outside of "spare time" allocated.

> I honestly feel that we should not take such a willy-nilly approach to reverting PRs. I.e. the release manager should have reached-out to the maintainer in this area. That's a normal part of our protocol (I don't know if it's written down per se). That did not happen.
> 
> A simple ping on discord would have helped.

You are the assignee to this PR, a revert PR is not reverting anything yet, it still needs to go through review and last I checked, you were able to express your disagreemnt, so nothing wrong was done here.


> 
> Instead, I was quite surprised to have to jump back into development on a holiday? Yesterday I had 4 hours of commuting, 4 hours of sleep.

???

> 
> In spite of that, I came up with a hotfix that is certainly less destructive than this PR.
> 
> As mentioned last week in the TSC meeting, without these in LTS, it will be difficult to backport several bug-fixes in multiple areas.
> 
> Just some food for thought. I'm out for the day unfortunately.

We need to move on, a revert is a measure we need to take to unblock development, we do not have the luxury to experiemnt with fixes that are "half baked". You can resubmit the changes again with a proper fix and more testing.

**Review by nashif — APPROVED** [review]

**Review by rlubos — APPROVED** [review]

**Comment by cfriedt** [comment]
> The work is not lost anyhow.  It can be resubmitted after when the issues have been ironed out.

That's reassuring, although re-submitting might require fixing bugs in other code as well, and that could take time. What is the deadline for resubmitting prior to tagging v3.7.0? Will there be some flexibility?

Care to list some change requests?
e.g.
* deprecating NET_SOCKETS_POLL_MAX
* fixing type usage in inappropriate places

**Review by carlescufi — APPROVED** [review]
+1 to reverting this late in the game

**Review by fabiobaltieri — APPROVED** [review]

**Review by kartben — APPROVED** [review]

**Comment by cfriedt** [comment]
Addressed @nashif's remarks in private.

**Comment by nashif** [comment]
> Addressed @nashif's remarks in private.

There is no reason to address my remarks in private, I have seen then coming on discord but I will not read them. The place for doing this should be the PR and not private messages. Sorry.

**Comment by cfriedt** [comment]
@nashif

> The TSC approved an exception, the TSC did not approve the PR uncondentially.

The many reviewers who approved the PRs approved them without a condition attached. The TSC also approved the PRs for 3.7.0.

Due diligence was done by myself as author, tester, all of the reviewers who reviewed these PRs as well as the TSC.

> At any given time, any PR that is causing such issues would be reverted if no fix is provided in time. We are at a critical time right now and we can't be spending time on something that was not tested well enough.

"Not tested well enough"? Sorry, I don't have access to every board supported by Zephyr. However, when I run tests on platforms I have access to, and then build for all platforms with `twister`. Then I submit the PR to CI that runs for 4 hours each run, and run, and iterate.

Who knows how many hundreds of thousands of test permutations are executed.

Please define "not tested well enough". Maybe you could elaborate on what you feel proper testing is with concrete suggestions?

A fix has been provided in https://github.com/zephyrproject-rtos/zephyr/pull/75348 and is significantly less destructive than this PR.

It's quite compact. I invited @aescolar to find a test or sample that breaks. So far, nothing.

> Spare time or not, Why does this make a difference? Doing something on your spare time is not really my or anyone's concern. We all dedicate spare time to the project, does not mean this needs to be treated differently.

It makes a difference because you, the Linux Foundation, and others should probably care care about maintainer work-life balance. It really should be a concern - for all of us. We have had community members away for medical reasons recently. A friend in the LF community that does similar work died of a heart attack a few days ago. We have community members from all walks of life, in all circumstances. 🌈 

People are different. People can be treated differently. It's OK to do that 👍 

> > Why did CI fail (and manual twister runs) fail to catch these issues? I think there will be some work required to actually understand why.
> 
> You need to tell us why.

I need write the tests and run them on platforms which i have access to, and then build them for all platforms that I can build them for and then submit PRs for review.

I'm not maintainer of our CI, testsuite, or tooling. I don't pretend to know every detail about why twister is not working as expected.

> CI did exactly what it does for all PRs, the failing tests were built/run on the default platform, so it seems there is a gap in coverage, but that is a known "issue". Lets not blame CI, something like that needs also to be verified and tested outside of CI by the developer.

It was verified outside over and over by myself and others, it was verified in CI several times spanning weeks.

As mentioned yesterday in the release meeting, clearly, tests were getting skipped when they should not have been.

What `twister` invocation do you suggest I run? Because running on dozens of platforms with thousands upon thousands of permutations of tests really seems like sufficient testing to me.

I'm really not kidding; please, actually respond with the `twister` invocation / `testcase.yaml` you suggest that I use when testing manually, and I will use that diligently.

You are the maintainer of it so you should have a much better idea than me.

> > The changes will form the basis of several companies' products going forward with LTSv3.
> 
> Well, in that case effort should have been done to get this in the tree long before the feature freeze,

Again, there are only 24 hours in the day / 365 days in the year.

Patches welcome!

I've been cleaning up technical debt in the posix, C, C++, kernel, net, and other areas what - 4 years I think? If it could have been done overnight, I would have done that. However, it often takes weeks / months to get a single PR reviewed.

Please do not be so dismissive.

People have different amounts of bandwidth that they can spend working on Zephyr.

> if that is important enough and more time and effort should have been put into making this happen outside of "spare time" allocated.

You seem to have a lot of insight into how my time should be managed 🤣

> > As mentioned last week in the TSC meeting, without these in LTS, it will be difficult to backport several bug-fixes in multiple areas.
> > Just some food for thought. I'm out for the day unfortunately.

>  to unblock development, we do not have the luxury to experiment with fixes that are "half baked". You can resubmit the changes again with a proper fix and more testing.

Half-baked? 🤣 ... Wow. It's a good thing I know you don't intend to come off as dismissive.

**Comment by nashif** [comment]
> My position is that certainly if
> 
> * [x]  manual runs of twister on tier0 platforms pass
> * [x]  manual runs of twister are run in multiple test areas (posix, c, net, etc)
> * [x]  manual runs of twister for all boards pass
> * [x]  tens or hundreds of thousands of test permutations pass
> * [x]  weeks of tests running in CI that all pass
> 
> Then there is something wrong in testing.
> 
> Please feel free to suggest a test plan, and as maintainer of the testing area and twister, you should be one of the more qualified individuals to make that recommendation.

your position is flawed. You are making this about testing. The fact is, testing DID catch the issue and a bug was reported., that why we have a multi-layered test approach. 
Our CI is by design very selective depending on where CI runs. The PR being reverted introcuded something new that is not being caught by current test scenarios, you introduced the change, so probably you know better what new scenario is to be added, I do not know, and CI does know. This had nothing to do with the testing area, and if you know better, please make us all happy and make it better.

Whatever it is, the fact is that this PR is causing issues, whether caught by CI or not, the fix provided as commented by you...

> this was the "path of least resistance" change that is non-destructive. The better change would be to simply not use inappropriate types in the base OS (i.e. simply change return values from ssize_t to long). However, that would have greater repercussions as several function signatures in and out of tree would need to be corrected.

so, there is a better change, hence my comment about half-baked fix above.

**Comment by dleach02** [comment]
The importance of this from @cfriedt perspective is a general concern I have and have voiced in another forum and that is the importance of this particular release. There are consumers of Zephyr that tend to stay on an LTS to the next LTS. Given our current guidelines, this branch is now frozen for the next 2+ years with only bug/security fixes being allowed. Any other release it is easy to say "we will get it in the next release"... not such an easy thing to hear on an LTS.

Problems/lessons I see:

1. This change came in very late in this cycle. It was in the Release Plan roadmap for 3.7 (#51211) but I don't remember if we reviewed this particular ticket to determine readiness of LTS3.
2. LTS updates are very constrained.
3. CI missed the problems with this PR. Chris' own testing missed this as well. Yes, there are a lot of reviewers but we have limited time so we need CI to help identify any larger regression issues.

**Comment by cfriedt** [comment]
> > Please feel free to suggest a test plan, and as maintainer of the testing area and twister, you should be one of the more qualified individuals to make that recommendation.
> 
> your position is flawed. You are making this about testing. The fact is, testing DID catch the issue and a bug was reported., that why we have a multi-layered test approach. 

@nashif - sure after the fact



> Our CI is by design very selective depending on where CI runs.

It seems testing is a little too selective.

> this had nothing to do with the testing area, and if you know better

It really did. Why would it have passed countless iterations of manual testing, as well as many iterations of CI, even after multiple rebases?

So please, since you are the expert, tell me the manual testing to do so that I don't need to do waste twice as much of my time doing this again.

>  However, that would have greater repercussions as several function signatures in and out of tree would need to be corrected.
> 
> so, there is a better change

I can do that change too, I mean there is a clear path forward, I just want acceptance criteria to be agreed on in advance.

**Comment by kartben** [comment]
> The many reviewers who approved the PRs approved them without a condition attached. The TSC also approved the PRs for 3.7.0.

Just to clarify, the TSC approved for the PRs to be included in 3.7 *granted they are approved as per the usual review process* -- it didn't give a blanket approval to the PRs themeselves. The same goes for all the PRs/exceptions voted upon during the June 26 TSC meeting.

**Comment by andyross** [comment]
This seems kinda... energetic.  Just to jump in with an opinion where we already have too many: what's the harm of waiting a few days to stabilize and merge the fix?  Others are pointing out this stuff too, but just to summarize:

* It's a comparatively large and reasonably useful feature
* It's an LTS release that will otherwise not get it
* The bug itself is just a boring header dependency cycle.  It's not like we need to be bugging a hardware vendor for docs or working around toolchain UB or whatever.  We all agree it's a well-understood/well-constrained fix, if perhaps tedious.
* It's just a few days!

I mean, stuff breaks, people mess up.  It happens, we've all been there.   But I don't see much of an argument for ejecting the feature?

**Comment by nashif** [comment]
> I mean, stuff breaks, people mess up. It happens, we've all been there. But I don't see much of an argument for ejecting the feature?

I already said above, the reverted PR can be resubmitted again with a proper fix that addresses all issues and it will be re-considered. The exception granted by the TSC still valid, but to this needs to be done within the next few days.

**Comment by nashif** [comment]
> > your position is flawed. You are making this about testing. The fact is, testing DID catch the issue and a bug was reported., that why we have a multi-layered test approach.
> 
> @nashif - sure after the fact

yes, if you have a better way of doing this, please submit a proposal. Our CI has been operating this way for years. 

- PR (subset based on changes)-> Push (all default platforms and all tests) -> Weekly (everything is built on all platforms)
- Hardware testing is conducted by vendors (that is where the first (build) issue was caught)
- Features should be tested and verified mostly in emulation and what we define as default test platforms. 

We can't build every sample/test variant on each of the 800 platforms we have, this does not scale and each PR will take days to complete, that is where developers are tasked with picking the right coverage and defining where tests need to run.

In this particular case the build issue can be reproduced on qemu_x86 by adding `CONFIG_MBEDTLS=y`, so maybe all those posix tests need to enable more features that end up depending on posix headers and features to increase the coverage, at least the building part. 


> > Our CI is by design very selective depending on where CI runs.
> 
> It seems testing is a little too selective.

see above...

> It really did. Why would it have passed countless iterations of manual testing, as well as many iterations of CI, even after multiple rebases?

because you did not modify the tests for the new feature and additions and change in header hierachy? Of course CI will pass if there is no test coverage for something that was just introduced.

> So please, since you are the expert, tell me the manual testing to do so that I don't need to do waste twice as much of my time doing this again.

If you do not know how to test your own features, no expert (and I am not claiming to be one) will be able to help. But I want to be productive here, I already spent a few minutes to find that enabling CONFIG_MBEDTLS or any others "users"  might expose such issues in the future and would be good to have as a scenario. The socket issue I do not know, someone else need to provide their input.

**Comment by aescolar** [comment]
I only respond here because there is clearly some quite big misunderstandings driving some of the comments, and I hope that by clarifying them we can all move on and continue working on improving things.

> Why did CI fail (and manual twister runs) fail to catch these issues?
> ...
> I run tests on platforms I have access to, and then build for all platforms with twister

Fetching the PR branch and running for ex.:
`twister -T tests/posix/common/ -s portability.posix.common.newlib --all`
shows the same build errors as we saw in main.
Note that twister by default will not build for all platforms, but on the default test platforms (depending on extra settings on the tests' yaml). You need to pass it
`--all` to build for all (not filtered by the tests yaml).

Please note on top of what Anas said:
* These tests are setting **one** integration platform. That limits what they will run on PRs to just that platform. ( https://docs.zephyrproject.org/latest/develop/test/twister.html#tests )
* Ultimately it is the responsibility of a PR submitter to ensure the code is working and properly tested. And that includes that tests and CI will provide appropriate coverage. Reviews or the previous tests cannot catch it all.
* Regarding components which have too many interdependencies with other areas: The only option is to try to reduce those interdependencies and a lot of testing.


> I honestly feel that we should not take such a willy-nilly approach to reverting PRs .. A simple ping on discord would have helped.

This revert PR was submitted: 4 days after the first bug report on this issue, 2 days after @cfriedt queued a draft PR. That draft PR was failing in several ways in CI and from my review it did not seem like something we could merge for 3.7. Several more bug reports had been raised. And there had been multiple reports of PRs and developers blocked by these issues.
I had, before submitting this PR, triaged those bug reports, analyzed the extent of the issue and condensed all reports in one with all platforms and failing tests. I checked what commit introduced it, and like others realized the PR was not bisectable. I checked if an easy solution existed and there did not seem to be one.
I concluded queuing a PR with a revert was appropriate as that would ready it while @cfriedt continued investigating. There was nothing willy-nilly on this process, and it actually took a lot of time.
@cfriedt was set as assignee in this PR (so he was certainly pinged), and this revert PR was not rushed by anybody.

> In spite of that, I came up with a hotfix that is certainly less destructive than this PR.

That 2nd hotfix was rejected in its own PR as it did not seem appropriate. Other issues which the original PR had introduced and which were unrelated to the hotfix had also been raised at that point.

> the development, review, and approval.. process was followed

Please note the following (this is not to blame, but to provide pointers which hopefully will help us all):
* As the PR was not bisectable identifying the issue and doing a smaller revert was not possible. With not bisectable I mean that commits 1..N of the PR did not even build without the rest of the PR. We should always aim at submitting PRs with commits which build in separation and are as isolated and applicable on their own as possible.
* Several very related and (merge) conflicting PRs where submitted simultaneously. This means that if one PR is merged, the other need to be rebased. This slows reviews, increases the likelihood of errors, and CI not detecting issues. It also means that if one of those PRs is found to have issues which require a revert (like this one did) a revert becomes much more difficult and ends requiring reverting more code. It is best to avoid submitting PRs like this in parallel when possible.
* These PRs were submitted too late in the release cycle given their scope and size. To ensure one has proper reviews and a good chance to merge the code, and minimize disruption to others, PRs like this should be sent much earlier.

Moreover as @kartben and @nashif already mentioned, all the TSC did is approve an exception for the rule which prevents PRs with new features being merged after rc1. The TSC did not vote on the content or merit of the PRs. Moreover the TSC chair warned about the risk of merging PRs like this so late, a risk which materialized. The approval from the TSC was only thru a lack of objections. I don't recall any TSC member expressing their interest in this PRs being merged.

> The changes will form the basis of several companies' products going forward with LTSv3.

In that case those companies should have allocated resources to ensure this changes made it well in time for the release. The rc1 deadline has always been known.
This is not to say the maintainers should have worked faster. It is simply to say that not everything can make it to the release.
For this particular subsystem, all we can see relating this features is that the maintainer of this area has set his own targets for this release. That does not imply a commitment or need by anybody else.
There was many warnings about the incoming feature freeze, and a couple of discussions during release meetings with the maintainer about that plan for the subsystem and the (un)likelihood of all those changes making it in before all the way up to freeze.
Nonetheless, the release managers actively pinged the author and maintainer of these PRs when rebases were needed, and waited an extra day to allow more of these area PRs in before freeze. 
There was a public and repeated complaint from the author after freeze about one of those PRs not having been merged. That PR was not meeting the merge criteria even 1 day after the deadline due to needed rebases.
More PRs were submitted after freeze. When they were brought to the TSC to be treated as exceptions some were *not* meeting the merge criteria even though it was requested that would be the case, and one was submitted just a few hours earlier.
In my eyes, this subsystem late PRs have received a lot of preferential treatment, taking a lot of attention and time from the release managers and TSC.

Please note all subsystems have features they would like to get in. And we'd all like as many features as possible in.
But eventually we need to make a release. We cannot simply continue forever advancing an unstable main.
Our releases are time based as was agreed long ago; not feature based. Those who have an interest for having a feature in need do the work in time.
In any case, there will be more releases.


> Care to list some change requests?

@cfriedt At the very least the bugs that were reported and linked against the original PR must be fixed. Please also try to improve the test coverage.
But note it is not the role or responsibility of the release managers to tell you this. As release managers we are just trying to ensure that others can continue working on stabilizing for 3.7.

> what's the harm of waiting a few days to stabilize and merge the fix? 

@andyross Several other PRs and developers were blocked before merging this revert. We are just 1.5 weeks from final freeze. There was more than one distint regression introduced by this PR. There was no reasonable fix in sight.
We cannot just block a lot of other people which is doing necessary fixes for the release, specially when a final deadline is very close, and even more, when summer holidays will prevent some from working before that.
And as @nashif said, PRs can be resubmitted again when fixed.

Please, let's just move on and continue fixing bugs. This whole issue has taken way too much time from too many people.

**Comment by cfriedt** [comment]
> Several other PRs and developers were blocked before merging this revert. We are just 1.5 weeks from final freeze. There was more than one distint regression introduced by this PR. There was no reasonable fix in sight even after several days after the issues were reported.

@aescolar - there fully was a reasonable fix in sight (@rlubos even had a PR ready to go for the network config). You need to be willing to see the solution without dismissing it because it came from an engineer you dislike 🤷‍♂️
