### PR TITLE
net: lib: shell: dns: Fix field precission specifier type

### PR DESCRIPTION
**Pull request by aescolar**
Explicitly cast down the string width to int, as otherwise it is size_t which may have a bigger size.

Avoids the following build error when building with native_sim//64 (longs are 64, ints 32):

subsys/net/lib/shell/dns.c:496:67: error: field precision specifier ‘.*’ expects argument of type ‘int’, but argument 4 has type ‘size_t’ {aka ‘long unsigned int’}

Code introduced in 7158f33c2b00

### CODE REVIEW

**Comment by aescolar** [comment]
CC @ckhardin

**Review by rlubos — APPROVED** [review]

**Review by jukkar — APPROVED** [review]
