### PR TITLE
cmake: mwdt assembler option for imacros

### LINKED ISSUE #85854: ARC MWDT toolchain support is broken
Every attempt to build Zephyr v4.1.0-rc1 with ARC MWDT toolchain ends up with failure while building one or another assembly file, like:
```
In file included from /home/tagunil/tests2/zephyr/arch/arc/core/fast_irq.S:18:
In file included from /home/tagunil/tests2/zephyr/include/zephyr/toolchain.h:44:
In file included from /home/tagunil/tests2/zephyr/include/zephyr/toolchain/mwdt.h:18:
/home/tagunil/tests2/zephyr/include/zephyr/toolchain/common.h:101:6: error: Architecture unsupported
  101 |     #error Architecture unsupported
```
I've bisected it down to 65471a6095fd46d537dd4b7ad0667b4f1018a1c2. I'm not sure why our toolchain is the only one affected, need to look into it further.

### PR DESCRIPTION
**Pull request by bjorniuppsala**
This is an untested example of something that might fix #85854 I do not have access to the toolchain, so I cant test it personally. 

It adds the -imacros property for assembler language to compensate for changes introduced in PR #84800.

### CODE REVIEW

**Review by RobinKastberg — APPROVED** [review]

**Comment by tagunil** [comment]
> @tagunil could you test if this helps?

Yes, of course, and yes, it works.

**Review by tagunil — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

**Review by ruuddw — APPROVED** [review]
Thanks for the quick fix!

**Review by tejlmand — APPROVED** [review]
