### PR TITLE
logging: fix storage size of 'tspec' isn't known

### LINKED ISSUE #92235: `CONFIG_LOG_TIMESTAMP_USE_REALTIME` no longer works
### Describe the bug

Setting `CONFIG_LOG_TIMESTAMP_USE_REALTIME=y` no longer works because

```txt
/<path>/zephyr/subsys/logging/log_core.c: In function 'default_rt_get_timestamp':
/<path>/zephyr/subsys/logging/log_core.c:245:25: error: storage size of 'tspec' isn't known
  245 |         struct timespec tspec;
      |                         ^~~~~
/<path>/zephyr/subsys/logging/log_core.c:245:25: warning: unused variable 'tspec' [-Wunused-variable]
/<path>/zephyr/subsys/logging/log_core.c:250:1: warning: control reaches end of non-void function [-Wreturn-type]
  250 | }
      | ^
```

This was likely introduced in 7868b4d54d123fbaeccea439fa30c4ea78515648

### Regression

- [x] This is a regression.

### Steps to reproduce

1. Any project with `CONFIG_LOG=y`, add `CONFIG_LOG_TIMESTAMP_USE_REALTIME=y`
2. `west build -p --board esp32s3_devkitc/esp32s3/procpu`

### Relevant log output

```shell

```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

- OS: macOS 15.5 
- Toolchain: Zephyr SDK 0.17.0
- Zephyr codebase at d41716f63c5c86c811e06559c25a668a9beb1d5a

### Additional Context

Adding `#include <time.h>` to `subsys/logging/log_core.c` fixes it but I am unsure if this should be the case

### PR DESCRIPTION
**Pull request by maass-hamburg**
fix storage size of 'tspec' isn't known
struct timespec wasn't defined anymore.

forgotten here: #90096

### CODE REVIEW

File: subsys/logging/log_core.c [hunk 1]
```diff
@@ -23,6 +23,7 @@
 #include <zephyr/logging/log_output_dict.h>
 #include <zephyr/logging/log_output_custom.h>
 #include <zephyr/linker/utils.h>
+#include <time.h>
```
Comment (ycsin) [inline subsys/logging/log_core.c]: this should be at the top, see #41543

**Review by cfriedt — APPROVED** [review]

**Review by nashif — APPROVED** [review]

**Review by dkalowsk — APPROVED** [review]

**Review by ycsin — APPROVED** [review]
