### ISSUE TITLE
build error in http_get sample

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#4162]
```
  CC      subsys/net/lib/sockets/sockets.o
/projects/zephyr2/subsys/net/lib/sockets/sockets.c: In function ‘zsock_sendto’:
/projects/zephyr2/subsys/net/lib/sockets/sockets.c:277:11: error: ‘err’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   errno = -err;
           ^~~~
cc1: all warnings being treated as errors
make[7]: *** [/projects/zephyr2/scripts/Makefile.build:183: subsys/net/lib/sockets/sockets.o] Error 1
  CC      subsys/net/lib/sockets/getaddrinfo.o
make[7]: Target '__build' not remade because of errors.
make[6]: *** [/projects/zephyr2/scripts/Makefile.build:357: subsys/net/lib/sockets] Error 2
make[6]: Target '__build' not remade because of errors.
make[5]: *** [/projects/zephyr2/scripts/Makefile.build:357: subsys/net/lib] Error 2
```

This is when building for qemu_x86.
Not sure why CI hasn't caught this.

**Comment by andrewboie** [comment]
@pfalcon feel free to reassign as appropriate

**Comment by nashif** [comment]
introduced by 9ec60774f8cfda70fcdd3e39dc45df40eed3cb21

**Comment by pfalcon** [comment]
I'm on it.
