### PR TITLE
zbus: fix extern declaration for cpp

### LINKED ISSUE #79664: ZBus linking problem with C++ on latest main branch
I have this issue caused by C++ mangling (I believe):

`ld.bfd.exe: app/libapp.a(TemperatureEvent.cpp.obj):(._zbus_channel_observation.static.temperature_chan00_+0x4): undefined reference to 'computing_th_temp_lis'`

Here is the code:

```
ZBUS_CHAN_DEFINE(temperature_chan,
                 TemperatureEvent,
                 nullptr,
                 nullptr,
                 ZBUS_OBSERVERS(computing_th_temp_lis),
                 ZBUS_MSG_INIT()
);
```

and listender is defined in another cpp file:

`ZBUS_LISTENER_DEFINE(computing_th_temp_lis, on_zbus_temperature_callback);`

It works on 3.7 branch.

### PR DESCRIPTION
**Pull request by vChavezB**
Declaration with const keyword (subscriber, listener, message)
requires external cpp declaration, otherwise the name will be mangled.

Fixes  https://github.com/zephyrproject-rtos/zephyr/issues/79664

### CODE REVIEW

**Review by rodrigopex — APPROVED** [review]

**Comment by rodrigopex** [comment]
@vChavezB, thanks for contributing to Zephyr and zbus!

**Review by ubieda — APPROVED** [review]
