### PR TITLE
scripts: modules: Fix initialization of variable

### LINKED ISSUE #26948: cmake failure when using ZEPHYR_MODULES without west
**Describe the bug**
 I am getting below compilation error for  `bcm958402m2_m7` board on latest zephyr:

```
CMake Error at /home/zephyr/cmake/zephyr_module.cmake:45 (message):
  Traceback (most recent call last):
    File "/home/zephyr/scripts/zephyr_module.py", line 275, in <module>
      main()
    File "/home/zephyr/scripts/zephyr_module.py", line 201, in main
      projects += args.extra_modules
  UnboundLocalError: local variable 'projects' referenced before assignment

```
**To Reproduce**
`cmake -GNinja -B build/ -DBOARD=bcm958402m2_m7 -DZEPHYR_MODULES=<PATH TO hal/cmsis/ directory> samples/hello_world/
`

**Expected behavior**
This issue seems to be introduced in commit ef3c5e551676278ccc1f42ecb572838144c5e33a (as pointed by @nashif ).

### PR DESCRIPTION
**Pull request by carlescufi**
The projects variable needs to be initialized with the list of modules
provided via cmd-line arguments.

This is a regression introduced by
ef3c5e551676278ccc1f42ecb572838144c5e33a.

Fixes #26948.

Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>

### CODE REVIEW

File: scripts/zephyr_module.py [hunk 1]
```diff
@@ -197,6 +197,8 @@ def main():
             # workspace. Such setup is allowed, as west may be installed
             # but the project is not required to use west.
             projects = []
+    else:
+        projects = args.modules
```
Comment (mniestroj) [inline scripts/zephyr_module.py:201]:
```suggestion
        projects = args.modules.copy()
```
I think making a copy of list will be better, so that appending more items to `projects` does not affect `args.modules`.

**Review by nashif — APPROVED** [review]

File: scripts/zephyr_module.py (hunk 1 above)
Comment (carlescufi) [reply scripts/zephyr_module.py]: Sure, `args.modules` is not used after that, but why not. Fixed.

**Review by mbolivar-nordic — APPROVED** [review]
Thanks for this.
