### PR TITLE
cmake: Don't use -nostdinc with CXX

### LINKED ISSUE #15603: Unable to use C++ Standard Library
**Describe the bug**
C++ Standard Library cannot be used with Zephyr 1.14.0. It used to work with 1.14-rc1.

**To Reproduce**
prj.conf: `CONFIG_CPLUSPLUS=y`

main.cpp:
```
#include <zephyr.h>
#include <vector>

int main()
{
  std::vector<int> v;

  v.push_back(10); 
  
  for (int x : v) 
    printk("x: %d", x); 

  return 0;
}
```

Command line: `D:\zephyr-test>cmake -GNinja -Bbuild -H. -DBOARD=stm32f4_disco && ninja -C build`

Output:
```
Zephyr version: 1.14.0
-- Found PythonInterp: C:/Users/user/AppData/Local/Programs/Python/Python37/
python.exe (found suitable version "3.7.0", minimum required is "3.4")
-- Selected BOARD stm32f4_disco
-- Loading D:/test/zephyr-v1.14.0/boards/arm/stm32f4_disco/stm32f4_disco.dts as
base
-- Overlaying D:/test/zephyr-v1.14.0/dts/common/common.dts
Parsing Kconfig tree in D:/test/zephyr-v1.14.0/Kconfig
Loading D:/test/zephyr-v1.14.0/boards/arm/stm32f4_disco/stm32f4_disco_defconfig
as base
Merging D:/zephyr-test/prj.conf
Configuration written to 'D:/zephyr-test/build/zephyr/.config'
-- Cache files will be written to: C:\Users\user\AppData\Local/.cache/zephyr

-- The C compiler identification is GNU 8.2.1
-- The CXX compiler identification is GNU 8.2.1
-- The ASM compiler identification is GNU
-- Found assembler: C:/Program Files (x86)/GNU Tools Arm Embedded/8 2018-q4-majo
r/bin/arm-none-eabi-gcc.exe
-- Performing Test toolchain_is_ok
-- Performing Test toolchain_is_ok - Success
-- Configuring done
-- Generating done
-- Build files have been written to: D:/zephyr-test/build
ninja: Entering directory `build'
...
../src/main.cpp:2:10: fatal error: vector: No such file or directory
 #include <vector>
          ^~~~~~~~
compilation terminated.
[13/121] Building C object zephyr/arch...__arm__core__cortex_m.dir/prep_c.c.obj
ninja: build stopped: subcommand failed.
```

**Expected behavior**
It compiles, as with 1.14-rc1:
```
D:\zephyr-test>cmake -GNinja -Bbuild -H. -DBOARD=stm32f4_disco && ninja -C build

Zephyr version: 1.14.0
-- Found PythonInterp: C:/Users/user/AppData/Local/Programs/Python/Python37/
python.exe (found suitable version "3.7.0", minimum required is "3.4")
-- Selected BOARD stm32f4_disco
-- Loading D:/test/zephyr-1.14.0-rc1/boards/arm/stm32f4_disco/stm32f4_disco.dts
as base
-- Overlaying D:/test/zephyr-1.14.0-rc1/dts/common/common.dts
Parsing Kconfig tree in D:/test/zephyr-1.14.0-rc1/Kconfig
Loading D:/test/zephyr-1.14.0-rc1/boards/arm/stm32f4_disco/stm32f4_disco_defconf
ig as base
Merging D:/zephyr-test/prj.conf
Configuration written to 'D:/zephyr-test/build/zephyr/.config'
-- Cache files will be written to: C:\Users\user\AppData\Local/.cache/zephyr

-- The C compiler identification is GNU 8.2.1
-- The CXX compiler identification is GNU 8.2.1
-- The ASM compiler identification is GNU
-- Found assembler: C:/Program Files (x86)/GNU Tools Arm Embedded/8 2018-q4-majo
r/bin/arm-none-eabi-gcc.exe
-- Performing Test toolchain_is_ok
-- Performing Test toolchain_is_ok - Success
Including module(s):
-- Configuring done
-- Generating done
-- Build files have been written to: D:/zephyr-test/build
ninja: Entering directory `build'
[116/121] Linking CXX executable zephyr\zephyr_prebuilt.elf
Memory region         Used Size  Region Size  %age Used
           FLASH:       13592 B         1 MB      1.30%
            SRAM:        4348 B       192 KB      2.21%
        IDT_LIST:         120 B         2 KB      5.86%
[121/121] Linking CXX executable zephyr\zephyr.elf
```

**Impact**
Cannot update to Zephyr 1.14.0 for current development project.

**Environment (please complete the following information):**
 - OS: Windows
 - Toolchain: GNU ARM Embedded
 - Version used: Zephyr 1.14.0

### PR DESCRIPTION
**Pull request by SebastianBoe**
It is observed that the C++ standard library headers can not be found
when -nostdinc is used. To fix this we omit -nostdinc when building
for C++.

To reproduce the issue use the latest zephyr master and add

` #include <vector>`

to the list of includes in samples/cpp_synchronization.

Without this fix the sample will not build for for gnuarmemb or the
Zephyr SDK.

This fixes #15603 and uses the fix suggested here: https://github.com/zephyrproject-rtos/zephyr/issues/15603#issuecomment-486820609

### CODE REVIEW

**Review by carlescufi — APPROVED** [review]

**Comment by galak** [comment]
If we do this for C++ why wouldn't we do it for C?

**Review by pabigot — CHANGES_REQUESTED** [review]
Generally when using C++ you need CONFIG_NEWLIB_LIBC=y to access the C++ standard headers.  In that case this branch is already bypassed, so the fix doesn't work.

**Comment by SebastianBoe** [comment]
@pabigot : Could you post steps to reproduce (where this fix doesn't work) with the latest Zephyr master and SDK/gnuarmemb versions?

**Comment by SebastianBoe** [comment]
> If we do this for C++ why wouldn't we do it for C?

Using -nostdinc is inherited from the Linux kernel:
https://github.com/torvalds/linux/blob/8e61ea11c23b108c8ce062f791dfa737896da346/scripts/Makefile.lib#L162

Why the linux kernel does this I do not know. IIRC I attempted to get rid of it at some point but was unable to.

That being said, if there are some unwanted side-effects of dropping -nostdinc then I would rather find out in the C++ build than have it crop up in the more mainstream C build.

**Comment by pabigot** [comment]
Do exactly the case that works with this patch, but instead of  `#include <vector>` use `#include <array>`.

Using this PR and gcc-arm-none-eabi-8-2019-q3-update the build fails even without adding `CONFIG_NEWLIB_LIBC=y`, though the cascade of errors is different.  With `CONFIG_NEWLIB_LIBC=y` it fails to find the next `stdlib.h` as it does without this patch.

I've done some diagnostic builds and there's no difference in compiler/preprocessor invocation between the Zephyr toolchain and the ARM one except the path to the system include directory.  There's no obvious difference in the contents of the system include directory, ignoring newlib version 3.1 vs 3.0.  There must be a difference in the way gcc and newlib are configured in the Zephyr SDK that changes the behavior.

My setup is:
```
export ZEPHYR_TOOLCHAIN_VARIANT=gnuarmemb
export GNUARMEMB_TOOLCHAIN_PATH=/usr/local/gcc-arm-none-eabi
cd /mnt/devel/external/zp/zephyr
. zephyr-env.sh
```

**Comment by pabigot** [comment]
I don't see `--enable-languages=c,c++` in the SDK builds, which might explain it.

**Review by galak — CHANGES_REQUESTED** [review]
Please add a testcase as part of this for using stdlib C++ functionality.  So that way we know if this breaks in the future.

Something like:

```
void test_main(void)
{
	/* Does nothing.  This is a compile only test. */
	vector v;
	std::vector<int> v;

	v.push_back(10);
}
```

**Comment by SebastianBoe** [comment]
Closing as this was not the correct approach.
