### ISSUE TITLE
bluetooth: gatt: bluetooth.gatt.psa reports build failure

### ISSUE THREAD

**Issue by katgiadla** [zephyrproject-rtos/zephyr#109040]
### Describe the bug

Test `tests/bluetooth/gatt/bluetooth.gatt.psa` reports build failure.

Observed for `nrf5340dk/nrf5340/cpuapp/ns`.

### Regression

- [x] This is a regression.

### Steps to reproduce

1. have nrf5340dk connected
2. go to your zephyr dir
3. call `./scripts/twister -s bluetooth.gatt.psa -p nrf5340dk/nrf5340/cpuapp/ns -v --inline-logs --log-level=DEBUG`
4. See console output with error

### Relevant log output

```shell
/zephyr/tests/bluetooth/gatt/src/main.c: In function 'test_gatt_test_gatt_db_hash_psa_dynamic_register_no_leak':
/zephyr/tests/bluetooth/gatt/src/main.c:567:26: error: 'CONFIG_MBEDTLS_PSA_KEY_SLOT_COUNT' undeclared (first use in this function); did you mean 'CONFIG_MBEDTLS_PSA_CRYPTO_CLIENT'?
  567 |         int iterations = CONFIG_MBEDTLS_PSA_KEY_SLOT_COUNT + 1;
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                          CONFIG_MBEDTLS_PSA_CRYPTO_CLIENT
/zephyr/tests/bluetooth/gatt/src/main.c:567:26: note: each undeclared identifier is reported only once for each function it appears in
```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

OS: Ubuntu 20.04.1 LTS
Toolchain Zephyr SDK 1.0.1
Commit SHA or Version used: 70672265568d0afd9d79323fc81053f665feb906

### Additional Context

Introduced by a31f2d8054104d338d9944d660b0bd398e579986

**Comment by katgiadla** [comment]
fyi @m-alperen-sener

**Comment by nordic-piks** [comment]
The assignee should be @m-alperen-sener but impossible to set.

**Comment by galraifen** [comment]
The issue is that the `ns` (non-secure) configuration requires `CONFIG_BUILD_WITH_TFM`, which is expected since the application runs in the non-secure zone. However, `CONFIG_MBEDTLS_PSA_CRYPTO_C` cannot be enabled alongside `CONFIG_BUILD_WITH_TFM`, making the two configs mutually exclusive.

I think that the cleanest fix is to remove `nrf5340dk/nrf5340/cpuapp/ns` from the `platform_allow` list for this test, since the test is specifically exercising the mbedTLS-as-PSA-provider path, which is incompatible with TF-M.
Forcing `CONFIG_BUILD_WITH_TFM=n` for this test would technically work but feels hacky and works against the intent of the `/ns` target.

Happy to open a PR once the approach is agreed on.

**Comment by m-alperen-sener** [comment]
> The issue is that the `ns` (non-secure) configuration requires `CONFIG_BUILD_WITH_TFM`, which is expected since the application runs in the non-secure zone. However, `CONFIG_MBEDTLS_PSA_CRYPTO_C` cannot be enabled alongside `CONFIG_BUILD_WITH_TFM`, making the two configs mutually exclusive.
> 
> I think that the cleanest fix is to remove `nrf5340dk/nrf5340/cpuapp/ns` from the `platform_allow` list for this test, since the test is specifically exercising the mbedTLS-as-PSA-provider path, which is incompatible with TF-M. Forcing `CONFIG_BUILD_WITH_TFM=n` for this test would technically work but feels hacky and works against the intent of the `/ns` target.
> 
> Happy to open a PR once the approach is agreed on.

This make sense; and already ``filter: CONFIG_BT_GATT_CACHING and CONFIG_MBEDTLS_PSA_CRYPTO_C``  makes nrf5340 non-secure an invalid target for the test case.

**Comment by galraifen** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/109452

**Comment by m-alperen-sener** [comment]
This issue is resolved by https://github.com/zephyrproject-rtos/zephyr/pull/109452.

**Comment by katgiadla** [comment]
> This issue is resolved by [#109452](https://github.com/zephyrproject-rtos/zephyr/pull/109452).

this PR removes platforms but from another scenario. Platform can be run still on described test scenario.
