### ISSUE TITLE
Renesas rzt2m gpio driver builds with warnings

### ISSUE THREAD

**Issue by aescolar** [zephyrproject-rtos/zephyr#74890]
**Describe the bug**
The Renesas rzt2m gpio driver drivers/gpio/gpio_rzt2m.c builds with a warning which is promoted to an error in CI causing CI failures.

**To Reproduce**
1. mkdir build; cd build
2. cmake -GNinja -DBOARD=rzt2m_starter_kit ../samples/basic/blinky 
3. ninja

**Expected behavior**
No build warnings, and therefore no failures in CI

**Impact**
6 failures in weekly CI which may result in failures in PRs CI if this is board build is triggered.

**Logs and console output**
```
FAILED: zephyr/drivers/gpio/CMakeFiles/drivers__gpio.dir/gpio_rzt2m.c.obj 
...
drivers/gpio/gpio_rzt2m.c: In function 'rzt2m_gpio_pin_interrupt_configure':
drivers/gpio/gpio_rzt2m.c:354:9: error: enumeration value 'GPIO_INT_TRIG_WAKE' not handled in switch [-Werror=switch]
  354 |         switch (trig) {
      |         ^~~~~~
cc1: all warnings being treated as errors
```

**Environment (please complete the following information):**
 - OS: Linux, Ubuntu 22.04, CI
 - Toolchain (e.g Zephyr SDK, ...): 0.16.8
 - Commit SHA or Version used: Main as of now 

**Additional context**
Driver introduced in 9265d2de0cd6f72e96e609ab0adbb9e6976bb09a and e92c04cbebf7d4af50016eb63f7bc02088590240

**Comment by aescolar** [comment]
Closing as dup of #74213
