### PR TITLE
Fix samples/subsys/mgmt/mcumgr/smp_svr/sample.mcumgr.smp_svr.bt failing to compile

### PR DESCRIPTION
**Pull request by nordic-krch**
Fixing regression introduced by #63967.

### CODE REVIEW

**Review by Thalley — DISMISSED** [review]

**Review by nordicjm — CHANGES_REQUESTED** [review]
This does not work

**Review by nordicjm — APPROVED** [review]

**Review by de-nordic — APPROVED** [review]

**Comment by nordic-krch** [comment]
Added second commit with fix for failing `west build -p -b lpcxpresso55s69_cpu0 -T samples/net/wifi/sample.net.wifi.mikroe_wifi_bt_click` with
```
In file included from /w/zephyr/zephyr/include/zephyr/sys/util_macro.h:34,
                 from /w/zephyr/zephyr/include/zephyr/irq_multilevel.h:15,
                 from /w/zephyr/zephyr/include/zephyr/devicetree.h:20,
                 from /w/zephyr/zephyr/include/zephyr/device.h:12,
                 from /w/zephyr/zephyr/drivers/serial/uart_mcux_flexcomm.c:14:
/w/zephyr/zephyr/include/zephyr/device.h:85:41: error: 'device_dts_ord_DT_N_S_soc_S_peripheral_50000000_S_flexcomm_88000_P_dmas_NAME_tx_PH_ORD' undeclared here (not in a function); did you mean 'DT_N_S_soc_S_peripheral_50000000_S_flexcomm_86000_P_dmas_NAME_tx_PH'?
   85 | #define DEVICE_NAME_GET(dev_id) _CONCAT(device_, dev_id)
```

The reason for failure was that I changed shell UART backend to use asynchronous UART API by default if supported (forcing enabling of this API). On some targets additional configuration is required (e.g. DMA) so compilation fails if that setup is missing. Reverted back to use interrupt driven as the default one (unless asynchronous API is already enabled).

**Review by Thalley — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]
