### PR TITLE
sensor: Add support for INA219

### PR DESCRIPTION
**Pull request by leonardp**
This adds support and an example application for the TI INA219 zero-drift, bidirectional current/power monitor.

There already is a "quick and dirty" application example using this device [here](https://github.com/zephyrproject-rtos/zephyr/tree/main/samples/drivers/current_sensing).

Improvements over the old example application are:
- usage of the sensor API
- configuration/calibration data via devicetree
- reverse current now working
- power management
- triggered mode to save on power

Signed-off-by: Leonard Pollak leonardp@tr-host.de

### CODE REVIEW

File: dts/bindings/sensor/ti,ina219.yaml [hunk 1]
```diff
@@ -0,0 +1,107 @@
...
+
+compatible: "ti,ina219"
+
+include: i2c-device.yaml
+
+properties:
+    lsb-microamp:
+      type: int
+      required: false
+      default: 100
```
Comment (mbolivar-nordic) [inline dts/bindings/sensor/ti,ina219.yaml:14]: Justifications for all defaults must be provided; please see https://docs.zephyrproject.org/latest/guides/dts/bindings.html#default-values-for-properties for the rules.

**Review by mbolivar-nordic — CHANGES_REQUESTED** [review]
Commenting on the binding only.

File: dts/bindings/sensor/ti,ina219.yaml (hunk 1 above)
Comment (leonardp) [reply dts/bindings/sensor/ti,ina219.yaml:14]: Good catch! It doesn't seem right to have a default value for this. I will change it accordingly.

Comment (mbolivar-nordic) [reply dts/bindings/sensor/ti,ina219.yaml:14]: OK, thanks! Please note that the requirements in that link apply to all defaults in this PR

Comment (leonardp) [reply dts/bindings/sensor/ti,ina219.yaml]: I pushed the change. All other defaults correspond to the default power-up state of the config register.

Comment (mbolivar-nordic) [reply dts/bindings/sensor/ti,ina219.yaml]: > All other defaults correspond to the default power-up state of the config register.

Thanks for confirming that, but you need to explicitly document that in the binding. From the bindings link I posted (emphasis mine):

"In any case where default: is used, the property documentation should **explain why the value was selected** and any conditions that would make it necessary to provide a different value. (**This is mandatory for built-in bindings.**)"

Comment (leonardp) [reply dts/bindings/sensor/ti,ina219.yaml]: Sorry for the inconvenience but I didn't read up to that paragraph.
I have now added (what I think is) all the necessary documentation.

**Review by mbolivar-nordic — APPROVED** [review]
Thanks. The binding looks good to me now. I didn't review the rest in detail.

**Review by mbolivar-nordic — COMMENTED** [review]
While working on something else, I discovered samples/drivers/current_sensing, which is a pretty hacky example of getting this exact sensor working on a particular breakout board with a hardcoded I2C device name.

I think it's no longer necessary with this patch -- @leonardp could you please add a commit to this pull request removing the stale sample?

File: drivers/sensor/ina219/ina219.c [hunk 2]
```diff
@@ -0,0 +1,353 @@
...
+{
+	const struct ina219_config *cfg = dev->config;
+	uint8_t rx_buf[2];
+	int rc;
+
+	rc = i2c_write_read(cfg->bus, cfg->i2c_addr,
+			&reg_addr, sizeof(reg_addr),
+			rx_buf, sizeof(rx_buf));
+
+	*reg_data = ((uint16_t)rx_buf[0] << 8 | rx_buf[1]);
```
Comment (gmarull) [inline drivers/sensor/ina219/ina219.c:33]: `byteorder.h` API should be used

File: drivers/sensor/ina219/ina219.c [hunk 3]
```diff
@@ -0,0 +1,353 @@
...
+
+	return ina219_reg_write(dev, INA219_REG_CONF, reg_data);
+}
+
+static int ina219_set_calib(const struct device *dev)
+{
+	const struct ina219_config *cfg = dev->config;
+	uint16_t cal;
+
+	cal = 40960000U / ((cfg->r_shunt) * (cfg->current_lsb));
```
Comment (gmarull) [inline drivers/sensor/ina219/ina219.c:93]: constant should be defined

File: drivers/sensor/ina219/ina219.c [hunk 4]
```diff
@@ -0,0 +1,353 @@
...
+		return -EBUSY;
+	}
+#endif
+
+	/* Trigger measurement and wait for completion */
+	if ( ina219_reg_field_update(dev,
+				    INA219_REG_CONF,
+				    INA219_MODE_MASK,
+				    INA219_MODE_NORMAL) ) {
+		LOG_DBG("%s: Failed to start measurement.", dev->name);
```
Comment (gmarull) [inline drivers/sensor/ina219/ina219.c:121]: `LOG_ERR`

**Review by galak — DISMISSED** [review]
please add to tests/drivers/build_all/sensor/

File: drivers/sensor/ina219/ina219.c (hunk 2 above)
Comment (leonardp) [reply drivers/sensor/ina219/ina219.c]: I have done this for both the read and write functions.

File: drivers/sensor/ina219/ina219.c (hunk 3 above)
Comment (leonardp) [reply drivers/sensor/ina219/ina219.c]: this value is now defined as a constant

File: drivers/sensor/ina219/ina219.c (hunk 4 above)
Comment (leonardp) [reply drivers/sensor/ina219/ina219.c]: changed it to LOG_ERR

**Comment by leonardp** [comment]
> please add to tests/drivers/build_all/sensor/

Is this sufficient to do that? https://github.com/zephyrproject-rtos/zephyr/pull/35538/commits/329ace230ad629fca5c34f1de14861cee8af1ef9


@mbolivar-nordic Thanks for reviewing the bindings. I have added https://github.com/zephyrproject-rtos/zephyr/pull/35538/commits/0472698acbf06522f1468be5726405d1d6c86849 to remove the old sample code.

**Comment by mbolivar-nordic** [comment]
>  I have added [0472698](https://github.com/zephyrproject-rtos/zephyr/commit/0472698acbf06522f1468be5726405d1d6c86849) to remove the old sample code.

Thanks!

File: samples/sensor/ina219/src/main.c [hunk 5]
```diff
@@ -0,0 +1,54 @@
...
+ */
+
+#include <zephyr.h>
+#include <stdio.h>
+#include <usb/usb_device.h>
+#include <drivers/sensor/ina219.h>
+
+void main(void)
+{
+#if defined(CONFIG_USB_UART_CONSOLE)
```
Comment (jfischer-no) [inline samples/sensor/ina219/src/main.c:14]: Please remove USB device support, it is not necessary here.

**Review by jfischer-no — CHANGES_REQUESTED** [review]

File: samples/sensor/ina219/src/main.c (hunk 5 above)
Comment (leonardp) [reply samples/sensor/ina219/src/main.c:14]: There is an overlay-usb.conf that can be used to enable USB device support.
Should I remove that one as well?

Comment (jfischer-no) [reply samples/sensor/ina219/src/main.c:14]: yes, please.

Comment (leonardp) [reply samples/sensor/ina219/src/main.c]: I have removed all USB related stuff from the sample code.

**Review by jfischer-no — APPROVED** [review]

File: drivers/sensor/ina219/Kconfig [hunk 6]
```diff
@@ -0,0 +1,10 @@
+# INA219 Bidirectional Current/Power Monitor
+
+# Copyright (c) 2021 Leonard Pollak
+# SPDX-License-Identifier: Apache-2.0
+
+menuconfig INA219
```
[the remark this answers is not in the document]
Comment (leonardp) [reply drivers/sensor/ina219/Kconfig]: i've updated the Kconfig accordingly

File: samples/sensor/ina219/src/main.c [hunk 7]
```diff
@@ -0,0 +1,43 @@
...
+
+void main(void)
+{
+	const struct device *ina = device_get_binding("INA219");
+	struct sensor_value v_shunt, v_bus, power, current;
+
+	if (ina == NULL) {
+		printf("Could not get INA219 device\n");
+		return;
+	}
```
Comment (gmarull) [inline samples/sensor/ina219/src/main.c:19]: better use `DEVICE_DT_GET_ANY(ti_ina219)` (check other samples)

File: samples/sensor/ina219/src/main.c [hunk 8]
```diff
@@ -0,0 +1,43 @@
...
+		if (sensor_sample_fetch(ina)){
+			printf("Could not fetch sensor data.\n");
+		}
+
+		sensor_channel_get(ina, SENSOR_CHAN_V_SHUNT, &v_shunt);
+		sensor_channel_get(ina, SENSOR_CHAN_BUS_VOLTAGE, &v_bus);
+		sensor_channel_get(ina, SENSOR_CHAN_BUS_POWER, &power);
+		sensor_channel_get(ina, SENSOR_CHAN_BUS_CURRENT, &current);
+
+
```
Comment (gmarull) [inline samples/sensor/ina219/src/main.c:32]: nit: extra blank line

File: samples/sensor/ina219/src/main.c [hunk 9]
```diff
@@ -0,0 +1,43 @@
...
+	if (ina == NULL) {
+		printf("Could not get INA219 device\n");
+		return;
+	}
+
+	while (true) {
+
+		if (sensor_sample_fetch(ina)){
+			printf("Could not fetch sensor data.\n");
```
Comment (gmarull) [inline samples/sensor/ina219/src/main.c:24]: code will continue with `get` even if `fetch` fails

File: drivers/sensor/ina219/ina219.c [hunk 10]
```diff
@@ -0,0 +1,358 @@
...
+static int ina219_reg_field_update(const struct device *dev,
+		uint8_t addr,
+		uint16_t mask,
+		uint16_t field)
+{
+	uint16_t reg_data;
+
+	if (ina219_reg_read(dev, addr, &reg_data)) {
+		return -EIO;
+	}
```
Comment (gmarull) [inline drivers/sensor/ina219/ina219.c:61]: error code should be propagated here

File: drivers/sensor/ina219/ina219.c [hunk 11]
```diff
@@ -0,0 +1,358 @@
...
+
+static int ina219_sample_fetch(const struct device *dev,
+			       enum sensor_channel chan)
+{
+	struct ina219_data *data = dev->data;
+	int rc;
+	uint16_t status;
+	uint16_t tmp;
+
+	__ASSERT_NO_MSG(chan == SENSOR_CHAN_ALL);
```
Comment (gmarull) [inline drivers/sensor/ina219/ina219.c:112]: I'd return -ENOTSUP if given channel is not supported.

File: drivers/sensor/ina219/ina219.c [hunk 12]
```diff
@@ -0,0 +1,358 @@
...
+
+#if CONFIG_PM_DEVICE
+	if (!(data->pm_state == PM_DEVICE_STATE_ACTIVE)) {
```
Comment (gmarull) [inline drivers/sensor/ina219/ina219.c:115]: `!=`

File: drivers/sensor/ina219/ina219.c [hunk 13]
```diff
@@ -0,0 +1,358 @@
...
+#endif
+
+	/* Trigger measurement and wait for completion */
+	if (ina219_reg_field_update(dev,
+				    INA219_REG_CONF,
+				    INA219_MODE_MASK,
+				    INA219_MODE_NORMAL)) {
+		LOG_ERR("%s: Failed to start measurement.", dev->name);
+		return -EIO;
+	}
```
Comment (gmarull) [inline drivers/sensor/ina219/ina219.c:128]: error code should be propagated

File: drivers/sensor/ina219/ina219.c [hunk 14]
```diff
@@ -0,0 +1,358 @@
...
+		rc = ina219_reg_read(dev, INA219_REG_V_BUS, &status);
+		if (rc) {
+			return rc;
+		}
+		k_sleep(K_USEC(INA219_WAIT_MSR_RETRY));
+	}
+
+	/* Check for overflow */
+	if (INA219_OVF_STATUS(status)) {
+		LOG_DBG("%s: Power and/or Current calculations are out of range.", dev->name);
```
Comment (gmarull) [inline drivers/sensor/ina219/ina219.c:147]: question: is this a situation that should report error or just log?

File: drivers/sensor/ina219/ina219.c [hunk 15]
```diff
@@ -0,0 +1,358 @@
...
+static int ina219_channel_get(const struct device *dev,
+			      enum sensor_channel chan,
+			      struct sensor_value *val)
+{
+	const struct ina219_config *cfg = dev->config;
+	struct ina219_data *data = dev->data;
+	double tmp;
+	int8_t sign = 1;
+
+	switch ((int16_t)chan) {
```
Comment (gmarull) [inline drivers/sensor/ina219/ina219.c:190]: why casting to `int16_t`?

File: drivers/sensor/ina219/ina219.c [hunk 16]
```diff
@@ -0,0 +1,358 @@
...
+		LOG_DBG("%s: Channel not supported by device!", dev->name);
+		return -ENOTSUP;
+	}
+
+	return 0;
+}
+
+#ifdef CONFIG_PM_DEVICE
+static int ina219_set_power_state(const struct device *dev,
+				  uint32_t power_state)
```
Comment (gmarull) [inline drivers/sensor/ina219/ina219.c:225]: `enum pm_device_state` must be used now

File: drivers/sensor/ina219/ina219.c [hunk 17]
```diff
@@ -0,0 +1,358 @@
...
+	struct ina219_data *data = dev->data;
+	uint8_t reg_val;
+
+	if (data->pm_state == power_state) {
+		LOG_DBG("%s: Device already in requested PM_STATE.", dev->name);
+		return 0;
+	}
+
+	if (power_state == PM_DEVICE_STATE_ACTIVE) {
+		reg_val = INA219_MODE_NORMAL;
```
Comment (gmarull) [inline drivers/sensor/ina219/ina219.c:236]: this assignment is redundant here, since the function returns afterwards.

File: drivers/sensor/ina219/ina219.c [hunk 18]
```diff
@@ -0,0 +1,358 @@
...
+		return 0;
+	}
+
+	if (ina219_reg_field_update(dev,
+				INA219_REG_CONF,
+				INA219_MODE_MASK,
+				reg_val)) {
+		LOG_DBG("%s: Failed to set power state.", dev->name);
+		return -EIO;
+	}
```
Comment (gmarull) [inline drivers/sensor/ina219/ina219.c:252]: error code should be propagated

File: drivers/sensor/ina219/ina219.c [hunk 19]
```diff
@@ -0,0 +1,358 @@
...
+	struct ina219_data *data = dev->data;
+
+	*state = data->pm_state;
+
+	return 0;
+}
+
+static int ina219_pm_ctrl(const struct device *dev,
+	uint32_t ctrl_command,
+	uint32_t *state,
```
Comment (gmarull) [inline drivers/sensor/ina219/ina219.c:271]: `enum pm_device_state`

File: drivers/sensor/ina219/ina219.c [hunk 20]
```diff
@@ -0,0 +1,358 @@
...
+	if (ina219_set_calib(dev)) {
+		LOG_DBG("%s: Could not set calibration data.", dev->name);
+		return -ENODEV;
+	}
+
+	/* Set measurement delay */
+	if (ina219_set_msr_delay(dev)) {
+		LOG_ERR("%s: Could not get measurement delay.", dev->name);
+		return -EINVAL;
+	}
```
Comment (gmarull) [inline drivers/sensor/ina219/ina219.c:318]: error codes should be propagated

File: drivers/sensor/ina219/ina219.h [hunk 21]
```diff
@@ -0,0 +1,108 @@
...
+
+/* Mode fields */
+#define INA219_MODE_NORMAL	0x3 /* shunt and bus, triggered */
+#define INA219_MODE_SLEEP	0x4 /* ADC off */
+#define INA219_MODE_OFF		0x0 /* Power off */
+
+/* Others */
+#define INA219_SIGN_BIT(x)	((x) >> 15) & 0x1
+#define INA219_V_BUS_MUL	0.004
+#define INA219_SI_MUL		0.00001
```
Comment (gmarull) [inline drivers/sensor/ina219/ina219.h:45]: nit: `f` suffix

File: drivers/sensor/ina219/ina219.h [hunk 22]
```diff
@@ -0,0 +1,108 @@
...
+struct ina219_data {
+	uint16_t config;
+	uint16_t v_shunt;
+	uint16_t v_bus;
+	uint16_t power;
+	uint16_t current;
+	uint16_t calib;
+	uint32_t msr_delay;
+#ifdef CONFIG_PM_DEVICE
+	uint32_t pm_state;
```
Comment (gmarull) [inline drivers/sensor/ina219/ina219.h:72]: `enum pm_device_state`

File: include/drivers/sensor/ina219.h [hunk 23]
```diff
@@ -0,0 +1,36 @@
...
+
+enum sensor_channel_ina219 {
+	/** Shunt Voltage in V **/
+	SENSOR_CHAN_V_SHUNT = SENSOR_CHAN_PRIV_START,
+	/** Bus Voltage in V **/
+	SENSOR_CHAN_BUS_VOLTAGE,
+	/** Power **/
+	SENSOR_CHAN_BUS_POWER,
+	/** Current **/
+	SENSOR_CHAN_BUS_CURRENT,
```
Comment (gmarull) [inline include/drivers/sensor/ina219.h:29]: would probably be a good idea to namespace these channels, ie, `SENSOR_CHAN_INA219_BUS_VOLTAGE`

**Review by gmarull — CHANGES_REQUESTED** [review]

File: include/drivers/sensor/ina219.h (hunk 23 above)
Comment (leonardp) [reply include/drivers/sensor/ina219.h]: i prefixed the channels as you suggested and updated the relevant parts of the code

File: drivers/sensor/ina219/ina219.h (hunk 22 above)
Comment (leonardp) [reply drivers/sensor/ina219/ina219.h]: updated

File: drivers/sensor/ina219/ina219.h (hunk 21 above)
Comment (leonardp) [reply drivers/sensor/ina219/ina219.h]: updated

File: drivers/sensor/ina219/ina219.c (hunk 20 above)
Comment (leonardp) [reply drivers/sensor/ina219/ina219.c]: updated

File: drivers/sensor/ina219/ina219.c (hunk 19 above)
Comment (leonardp) [reply drivers/sensor/ina219/ina219.c]: updated

File: drivers/sensor/ina219/ina219.c (hunk 11 above)
Comment (leonardp) [reply drivers/sensor/ina219/ina219.c]: i have updated the ina219_sample_fetch function to also be able to only fetch a single (private) channel.
not sure if it good the way i did it...

File: drivers/sensor/ina219/ina219.c (hunk 10 above)
Comment (leonardp) [reply drivers/sensor/ina219/ina219.c]: updated

File: samples/sensor/ina219/src/main.c (hunk 9 above)
Comment (leonardp) [reply samples/sensor/ina219/src/main.c:29]: added a return

File: samples/sensor/ina219/src/main.c (hunk 8 above)
Comment (leonardp) [reply samples/sensor/ina219/src/main.c:37]: black line removed

File: samples/sensor/ina219/src/main.c (hunk 7 above)
Comment (leonardp) [reply samples/sensor/ina219/src/main.c]: updated

File: drivers/sensor/ina219/ina219.c [hunk 24]
```diff
@@ -0,0 +1,388 @@
...
+		chan_p != SENSOR_CHAN_INA219_BUS_CURRENT) {
+		return -ENOTSUP;
+	}
+
+#if CONFIG_PM_DEVICE
+	if (data->pm_state != PM_DEVICE_STATE_ACTIVE) {
+		LOG_DBG("Device inactive.");
+		return -EBUSY;
+	}
+#endif
```
Comment (gmarull) [inline drivers/sensor/ina219/ina219.c:126]: devices that need PM at runtime should implement the runtime PM API, so this is not required. There's currently ongoing work to improve the device PM state on Zephyr, ref #36125

File: drivers/sensor/ina219/ina219.c [hunk 25]
```diff
@@ -0,0 +1,388 @@
...
+		k_sleep(K_USEC(INA219_WAIT_MSR_RETRY));
+	}
+
+	/* Check for overflow */
+	if (INA219_OVF_STATUS(status)) {
+		LOG_DBG("Power and/or Current calculations are out of range.");
+	}
+
+	if (chan != SENSOR_CHAN_ALL ||
+		chan_p != SENSOR_CHAN_INA219_V_SHUNT) {
```
Comment (gmarull) [inline drivers/sensor/ina219/ina219.c:161]: I'm a bit confused here, but shouldn't that be:

```
	if (chan == SENSOR_CHAN_ALL ||
		chan_p == SENSOR_CHAN_INA219_V_SHUNT) {
```

File: drivers/sensor/ina219/ina219.c [hunk 26]
```diff
@@ -0,0 +1,388 @@
...
+			LOG_ERR("Failed to read device status.");
+			return rc;
+		}
+		k_sleep(K_USEC(INA219_WAIT_MSR_RETRY));
+	}
+
+	/* Check for overflow */
+	if (INA219_OVF_STATUS(status)) {
+		LOG_DBG("Power and/or Current calculations are out of range.");
+	}
```
Comment (gmarull) [inline drivers/sensor/ina219/ina219.c:158]: This should return an error, obtained data may be meaningless:

image

File: drivers/sensor/ina219/ina219.c (hunk 25 above)
Comment (leonardp) [reply drivers/sensor/ina219/ina219.c]: yes, i am also confused. changed it to your suggestion :+1:

File: drivers/sensor/ina219/ina219.c (hunk 24 above)
Comment (leonardp) [reply drivers/sensor/ina219/ina219.c]: removed this section. nice to see work being done to improve the PM API, really looking forward to this.

File: drivers/sensor/ina219/ina219.c (hunk 26 above)
Comment (leonardp) [reply drivers/sensor/ina219/ina219.c]: i've changed it to `LOG_ERR`, although i am not 100% sure about it being an actual error.
it's a case of: "3.6 röntgen -- not great, not terrible"...

File: drivers/sensor/ina219/ina219.c [hunk 27]
```diff
@@ -0,0 +1,381 @@
...
+		if (rc) {
+			LOG_ERR("Failed to read device status.");
+			return rc;
+		}
+		k_sleep(K_USEC(INA219_WAIT_MSR_RETRY));
+	}
+
+	/* Check for overflow */
+	if (INA219_OVF_STATUS(status)) {
+		LOG_ERR("Power and/or Current calculations are out of range.");
```
Comment (gmarull) [inline drivers/sensor/ina219/ina219.c:150]: If it's an acceptable case, then I'd change to `LOG_WRN`

**Review by gmarull — APPROVED** [review]

File: drivers/sensor/ina219/ina219.c (hunk 27 above)
Comment (leonardp) [reply drivers/sensor/ina219/ina219.c]: i did just that. i think it is fine this way.
thanks for all the reviewing

File: drivers/sensor/ina219/ina219.c [hunk 28]
```diff
@@ -0,0 +1,381 @@
...
+
+	if (ctrl_command == PM_DEVICE_STATE_SET) {
+		rc = ina219_set_power_state(dev, *state);
+	} else if (ctrl_command == PM_DEVICE_STATE_GET) {
+		rc = ina219_get_power_state(dev, state);
+	}
+
+	if (cb) {
+		cb(dev, rc, state, arg);
+	}
```
Comment (gmarull) [inline drivers/sensor/ina219/ina219.c:303]: callback has been removed, see https://github.com/zephyrproject-rtos/zephyr/pull/36757

**Review by gmarull — CHANGES_REQUESTED** [review]

File: drivers/sensor/ina219/ina219.c (hunk 28 above)
Comment (leonardp) [reply drivers/sensor/ina219/ina219.c]: i like it.
I have removed the `pm_device_cb` argument as well as the if block

File: drivers/sensor/ina219/ina219.c [hunk 29]
```diff
@@ -0,0 +1,377 @@
...
+
+	*state = data->pm_state;
+
+	return 0;
+}
+
+static int ina219_pm_ctrl(const struct device *dev,
+	uint32_t ctrl_command,
+	enum pm_device_state *state,
+	void *arg)
```
Comment (gmarull) [inline drivers/sensor/ina219/ina219.c:290]:
```suggestion
	enum pm_device_state *state)
```

File: drivers/sensor/ina219/ina219.c [hunk 30]
```diff
@@ -0,0 +1,377 @@
...
+		return 0;
+	}
+
+	if (ina219_reg_field_update(dev,
+				INA219_REG_CONF,
+				INA219_MODE_MASK,
+				reg_val)) {
+		LOG_DBG("Failed to set power state.");
+		return -EIO;
+	}
```
Comment (gmarull) [inline drivers/sensor/ina219/ina219.c:270]: error code needs to be propagated

File: drivers/sensor/ina219/ina219.c [hunk 31]
```diff
@@ -0,0 +1,377 @@
...
+
+	if (power_state == PM_DEVICE_STATE_ACTIVE) {
+		return ina219_init(dev);
+	} else if (power_state == PM_DEVICE_STATE_SUSPEND) {
+		reg_val = INA219_MODE_SLEEP;
+	} else if (power_state == PM_DEVICE_STATE_OFF) {
+		reg_val = INA219_MODE_OFF;
+	} else {
+		return 0;
```
Comment (gmarull) [inline drivers/sensor/ina219/ina219.c:261]:
```suggestion
		return -ENOTSUP;
```

File: drivers/sensor/ina219/ina219.c (hunk 16 above)
Comment (gmarull) [reply drivers/sensor/ina219/ina219.c:244]: not fixed

**Review by gmarull — CHANGES_REQUESTED** [review]

File: drivers/sensor/ina219/ina219.c (hunk 29 above)
Comment (leonardp) [reply drivers/sensor/ina219/ina219.c]: updated

File: drivers/sensor/ina219/ina219.c (hunk 30 above)
Comment (leonardp) [reply drivers/sensor/ina219/ina219.c]: updated

File: drivers/sensor/ina219/ina219.c (hunk 31 above)
Comment (leonardp) [reply drivers/sensor/ina219/ina219.c]: updated

**Review by gmarull — APPROVED** [review]

**Comment by leonardp** [comment]
The documentation build times out with:
```
Warning, treated as error:
/home/runner/work/zephyr/zephyr/doc/_build/src/samples/sensor/ina219/README.rst:16:'any' reference target not found: https://www.ti.com/product/INA219
Error: The operation was canceled.
```
however the link is working fine for me

File: samples/sensor/ina219/README.rst [hunk 32]
```diff
@@ -0,0 +1,46 @@
...
+********
+
+This sample application measures shunt voltage, bus voltage, power and current
+every 2 seconds and prints them to console.
+The calibration/configuration parameters can be set in the devicetree file.
+
+References
+**********
+
+ - `INA219 sensor <https://www.ti.com/product/INA219>`
```
Comment (gmarull) [inline samples/sensor/ina219/README.rst:16]: This is missing a trailing underscore, 
```rst
`text <url>`_
```

Comment (leonardp) [reply samples/sensor/ina219/README.rst]: thanks I've updated it. RST has a bit of a weird syntax imo.
now the tests should run fine.

**Comment by leonardp** [comment]
@galak can you please revisit?
i would like to see this merged

File: drivers/sensor/ina219/ina219.c [hunk 33]
```diff
@@ -0,0 +1,378 @@
...
+		enum pm_device_state *state)
+{
+	struct ina219_data *data = dev->data;
+
+	*state = data->pm_state;
+
+	return 0;
+}
+
+static int ina219_pm_ctrl(const struct device *dev,
```
Comment (gmarull) [inline drivers/sensor/ina219/ina219.c:289]: PM code should be adjusted following latest changes, see https://github.com/zephyrproject-rtos/zephyr/pull/36759

**Review by gmarull — CHANGES_REQUESTED** [review]

File: drivers/sensor/ina219/ina219.c (hunk 33 above)
Comment (leonardp) [reply drivers/sensor/ina219/ina219.c]: updated accordingly

**Comment by leonardp** [comment]
I have removed the private channels and replaced them with the public ones introduced by https://github.com/zephyrproject-rtos/zephyr/pull/35753
The channel for the shunt voltage was therefore removed completely.

File: samples/sensor/ina219/src/main.c [hunk 34]
```diff
@@ -0,0 +1,47 @@
...
+ */
+
+#include <zephyr.h>
+#include <stdio.h>
+#include <drivers/sensor.h>
+
+
+#if !DT_HAS_COMPAT_STATUS_OKAY(ti_ina219)
+#error "No ti,ina219 compatible node found in the device tree"
+#endif
```
Comment (gmarull) [inline samples/sensor/ina219/src/main.c:14]: better use `DEVICE_DT_GET_ONE` so that you get a compilation error if there's no device.

File: samples/sensor/ina219/src/main.c [hunk 35]
```diff
@@ -0,0 +1,47 @@
...
+	struct sensor_value v_bus, power, current;
+	int rc;
+
+	if (!device_is_ready(ina)) {
+		printf("Device %s is not ready.\n", ina->name);
+		return;
+	}
+
+	while (true) {
+
```
Comment (gmarull) [inline samples/sensor/ina219/src/main.c:28]: nit: extra blank line

File: drivers/sensor/ina219/ina219.c [hunk 36]
```diff
@@ -0,0 +1,315 @@
...
+	const struct ina219_config *cfg = dev->config;
+	uint16_t reg_data;
+
+	reg_data = (cfg->brng & INA219_BRNG_MASK) << INA219_BRNG_SHIFT |
+		(cfg->pg & INA219_PG_MASK) << INA219_PG_SHIFT |
+		(cfg->badc & INA219_ADC_MASK) << INA219_BADC_SHIFT |
+		(cfg->sadc & INA219_ADC_MASK) << INA219_SADC_SHIFT |
+		(cfg->mode & INA219_MODE_NORMAL);
+
+
```
Comment (gmarull) [inline drivers/sensor/ina219/ina219.c:89]: nit: extra blank line

File: drivers/sensor/ina219/ina219.c [hunk 37]
```diff
@@ -0,0 +1,315 @@
...
+		return -ENOTSUP;
+	}
+
+	return 0;
+}
+
+#ifdef CONFIG_PM_DEVICE
+static int ina219_pm_ctrl(const struct device *dev, enum pm_device_action action)
+{
+	int rc = 0;
```
Comment (gmarull) [inline drivers/sensor/ina219/ina219.c:223]: not used

File: drivers/sensor/ina219/ina219.c [hunk 38]
```diff
@@ -0,0 +1,315 @@
...
+	.channel_get = ina219_channel_get,
+};
+
+
+#define INA219_INIT(n)						\
+	static struct ina219_data ina219_data_##n;		\
+								\
+	static const struct ina219_config ina219_config_##n = {	\
+		.bus = DEVICE_DT_GET(DT_INST_BUS(n)),		\
+		.i2c_addr = DT_INST_REG_ADDR(n),		\
```
Comment (gmarull) [inline drivers/sensor/ina219/ina219.c:296]: use `i2c_dt_spec`: https://github.com/zephyrproject-rtos/zephyr/pull/37359

**Review by gmarull — CHANGES_REQUESTED** [review]
Some more changes requested, please check my comments. I still see that samples comes before the actual driver, can you re-order commits in proper chronological order?

File: samples/sensor/ina219/src/main.c (hunk 34 above)
Comment (leonardp) [reply samples/sensor/ina219/src/main.c]: updated.

File: drivers/sensor/ina219/ina219.c (hunk 37 above)
Comment (leonardp) [reply drivers/sensor/ina219/ina219.c]: removed

File: drivers/sensor/ina219/ina219.c (hunk 38 above)
Comment (leonardp) [reply drivers/sensor/ina219/ina219.c]: updated the driver accordingly.
I could also update the sgp40 and sht4x driver and add it to this pull request.
Would that be OK?

Comment (gmarull) [reply drivers/sensor/ina219/ina219.c]: better open another PR for that, would be a nice improvement :-)

Comment (leonardp) [reply drivers/sensor/ina219/ina219.c]: see: https://github.com/zephyrproject-rtos/zephyr/pull/37741

**Review by gmarull — APPROVED** [review]

**Review by MaureenHelm — CHANGES_REQUESTED** [review]
Please rebase and resolve the merge conflict

File: samples/sensor/ina219/CMakeLists.txt [hunk 39]
```diff
@@ -0,0 +1,8 @@
+# SPDX-License-Identifier: Apache-2.0
+
+cmake_minimum_required(VERSION 3.13.1)
```
[the remark this answers is not in the document]
Comment (leonardp) [reply samples/sensor/ina219/CMakeLists.txt]: rebased and updated

**Review by MaureenHelm — APPROVED** [review]
