### ISSUE TITLE
Espressif targets (ESP32) seem to be broken

### ISSUE THREAD

**Issue by alexpaschoaletto** [zephyrproject-rtos/zephyr#77934]
**Describe the bug**

Current Zephyr version (3.7.99) seems to have broken compilation for Espressif targets such as the regular ESP32 (xtensa) and the newer ESP32C3 (risc-v). 

**To Reproduce**
1. west build -b xiao_esp32c3 samples/hello_world --pristine
2. See error

**Expected behavior**
The project or sample should build just fine. It was working on 3.7.0-rc3.

**Impact**
It prevents Espressif builds to compile.

**Logs and console output**
The build throws many errors, but they can be reduced to the following:
```cmd
modules\hal\espressif\components\driver\gpio\include\driver\gpio.h:327:32: error: unknown type name 'gpio_num_t'; did you mean 'gpio_isr_t'?
  327 | esp_err_t gpio_isr_handler_add(gpio_num_t gpio_num, gpio_isr_t isr_handler, void *args);
...
modules/hal/espressif/components/spi_flash/esp_flash_spi_init.c:349:32: warning: implicit declaration of function 'ESP_FLASH_HOST_CONFIG_DEFAULT' [-Wimplicit-function-declaration]
  349 |     memspi_host_config_t cfg = ESP_FLASH_HOST_CONFIG_DEFAULT();
...
modules\hal\espressif\components\hal\esp32c3\include\hal\gpio_ll.h:670:28: error: 'GPIO_NUM_5' undeclared (first use in this function)
  670 |     HAL_ASSERT(gpio_num <= GPIO_NUM_5 && "gpio larger than 5 does not support deep sleep wake-up function");
```

**Environment (please complete the following information):**

 - OS: Windows 23H2
 - Zephyr 3.7.99, SDK version 0.16.8.
 - Commit SHA: ca48767be48 (HEAD -> main, origin/main, origin/HEAD) boards: byteSENSI-L: add gnss support

**Additional context**
I noticed it a week ago but decided to wait a bit for hotfixes. Those ended up not comming, hence why I'm opening this issue.
Since no one has opened an issue yet I suppose it really might be a problem on my side, but my fork has been synced today with the source.

**Comment by sylvioalves** [comment]
@alexpaschoaletto just checked with latest main, all good.

**Comment by alexpaschoaletto** [comment]
> Can you run a `west update` and verify that doesn't fix things? This sounds like a local build issue.

Indeed that was the problem. I forgot to run `west update`. Thank you for your help and sorry for the false alarm.

> @alexpaschoaletto just checked with latest main, all good.

Just out of curiosity, did you just build successfully or have you also ran on a board? The build problem has gone away here, but for the regular ESP32 (xtensa `esp32_devkitc_wroom`) now it is stuck on a reset loop with this message:

```cmd
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3ffb0000,len:6312
load:0x40080000,len:32560
entry 0x4008378c
I (29) boot: ESP Simple boot
I (29) boot: compile time Sep  3 2024 18:32:14
W (29) boot: Unicore bootloader
I (30) spi_flash: detected chip: generic
I (32) spi_flash: flash io: dio
I (35) boot: chip revision: v1.0
E (38) boot: You are using ESP32 chip revision (1) that is unsupported. While it may work, it could cause unexpected behavior or issues.
E (50) boot: Proceeding with this ESP32 chip revision is not recommended unless you fully understand the potential risk and limitations.
E (62) boot: If you choose to continue, please enable the 'CONFIG_ESP32_USE_UNSUPPORTED_REVISION' in your project configuration.
E (73) boot: HW init failed, aborting
Fatal exception (0): IllegalInstruction
epc1=0x400d139a, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000000, depc=0x00000000
```

It happened with other samples aswell. While one can obviously tell what seems to be the problem from the error, I still find it somewhat intriguing. It doesn't look like related to Zephyr but to the Espressif toolchain one, however, so I'll be closing this issue shortly if no one has anything left to say.

Thanks again for the help!

**Comment by alexpaschoaletto** [comment]
> The reason is that your ESP32 is old revision. In your prj.conf, enable this:
> `CONFIG_ESP32_USE_UNSUPPORTED_REVISION=y`.

Funny, I read the two first lines and the third one just had the answer right there.
Excuse me for a moment while I proceed to the corner of shame. And thank you once again.

**Comment by sylvioalves** [comment]
@alexpaschoaletto haha, no problem at all. The boot loop in there does not help. Will update that not to loop.

**Comment by WilliamGFish** [comment]
Just found this problem and the suggested resolution isn't working in version 4.0.99.

Ideas...?

**Comment by sylvioalves** [comment]
> Just found this problem and the suggested resolution isn't working in version 4.0.99.
> 
> Ideas...?

Can you paste the log output or provide additional info?

**Comment by WilliamGFish** [comment]
Build with: west build -b esp32_devkitc_wroom/esp32/procpu --pristine --sysbuild

I have added CONFIG_ESP32_USE_UNSUPPORTED_REVISION=y. but not change


### errors include
**MCUBoot**
> warning: BOOT_MAX_IMG_SECTORS (defined at
> /bootloader/mcuboot/boot/zephyr/Kconfig:463) was assigned the value
> '512' but got the value ''. Check these unsatisfied dependencies: (!BOOT_MAX_IMG_SECTORS_AUTO) (=n).

**Application**

> warning: MCUBOOT_UPDATE_FOOTER_SIZE (defined at subsys/dfu/Kconfig:55) was assigned the value
> '0x1000' but got the value ''. Check these unsatisfied dependencies: MCUBOOT_IMG_MANAGER (=n),
> IMG_MANAGER (=n)


> Memory region         Used Size  Region Size  %age Used
>      mcuboot_hdr:          32 B         32 B    100.00%
>         metadata:          80 B         96 B     83.33%
>            FLASH:      572484 B    4194176 B     13.65%
>      iram0_0_seg:      124160 B       224 KB     54.13%
>      dram0_0_seg:      122708 B     140452 B     87.37%
>      irom0_0_seg:      310468 B      4092 KB      7.41%
>      drom0_0_seg:         64 KB      4092 KB      1.56%
>     rtc_iram_seg:          0 GB         8 KB      0.00%
>     rtc_slow_seg:          0 GB         8 KB      0.00%
>     rtc_data_seg:          0 GB         8 KB      0.00%
>         IDT_LIST:          0 GB         8 KB      0.00%
> Generating files from /sensor_client/build/sensor_client/zephyr/zephyr.elf for board: esp32_devkitc_wroom


### **Then flash**
> esptool.py v4.7.0
> Found 1 serial ports
> Serial port COM8
> Connecting.....
> Detecting chip type... Unsupported detection protocol, switching and trying again...
> Connecting....
> Detecting chip type... ESP32
> Chip is ESP32-D0WD (revision v1.0)
> Features: WiFi, BT, Dual Core, Coding Scheme None
> Crystal is 40MHz
> MAC: 24:0a:c4:1d:54:70
> Uploading stub...
> Running stub...
> Stub running...
> Changing baud rate to 921600
> Changed.
> Configuring flash size...
> Auto-detected Flash size: 4MB
> Flash will be erased from 0x00001000 to 0x0000efff...
> SHA digest in image updated
> Wrote 65536 bytes at 0x00001000 in 1.0 seconds (544.9 kbit/s)...
> Hash of data verified.


Run Monitor

>west espressif monitor

> Serial port COM8
> Connecting.....
> Detecting chip type... Unsupported detection protocol, switching and trying again...
> Connecting....
> Detecting chip type... ESP32
> --- WARNING: GDB cannot open serial ports accessed as COMx
> --- Using \\.\COM8 instead...
> --- idf_monitor on \\.\COM8 115200 ---
> --- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
> ets Jun  8 2016 00:22:57
> rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
> configsip: 0, SPIWP:0xee
> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
> mode:DIO, clock div:2
> load:0x3ffe8000,len:10860
> ho 0 tail 12 room 4
> load:0x40078000,len:5948
> load:0x400a0000,len:37324
> entry 0x400a2c14
> I (36) soc_init: MCUboot 2nd stage bootloader
> I (36) soc_init: compile time Jan 21 2025 15:26:17
> W (36) soc_init: Unicore bootloader
> I (38) spi_flash: detected chip: generic
> I (41) spi_flash: flash io: dio
> I (44) soc_init: chip revision: v1.0
> E (47) soc_init: You are using ESP32 chip revision (1) that is unsupported. While it may work, it could cause unexpected behavior or issues.
> E (60) soc_init: Proceeding with this ESP32 chip revision is not recommended unless you fully understand the potential risk and limitations.
> E (72) soc_init: If you choose to continue, please enable the 'CONFIG_ESP32_USE_UNSUPPORTED_REVISION' in your project configuration.
> E (84) boot: HW init failed, aborting
> abort()
> Fatal exception (0): IllegalInstruction
> epc1=0x400781e3, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000000, depc=0x00000000
