### ISSUE TITLE
Build with CONFIG_POSIX_API=y fails on `main`

### ISSUE THREAD

**Issue by dkouba-atym** [zephyrproject-rtos/zephyr#96886]
### Describe the bug

I switched an existing project from `v4.2-branch` to `main` today and my application now fails to build. I was able to narrow the issue down to the config value `CONFIG_POSIX_API=y` using a freshly checked out version of Zephyr and the hello_world sample.

### Regression

- [ ] This is a regression.

### Steps to reproduce

This can be replicated with a fresh project and the following build command:

```
west build -b rpi_pico2/rp2350a/m33/w zephyr/samples/hello_world -- -DCONFIG_POSIX_API=y
```

The failure is not board specific from what I can tell. I have also tried:
- `pico_plus2/rp2350b/m33`
- `rpi_pico2/rp2350a/m33`

### Relevant log output

```shell
/Users/dankouba/zephyrproject/zephyr/lib/posix/options/timer.c: In function 'zephyr_timer_wrapper':
/Users/dankouba/zephyrproject/zephyr/lib/posix/options/timer.c:57:23: error: 'struct sigevent' has no member named 'sigev_notify_function'
   57 |         if (timer->evp.sigev_notify_function == NULL) {
      |
```

### Impact

Major – Severely degrades functionality; workaround is difficult or unavailable.

### Environment

OS: Mac OSX

**Comment by dkouba-atym** [comment]
Upon investigation, this appears to be a regression from https://github.com/zephyrproject-rtos/zephyr/pull/96589

I reverted those changes and I am able to build again.

**Comment by cfriedt** [comment]
No issues building here. Maybe try with `-p`?

```cpp
west build -p -b rpi_pico2/rp2350a/m33/w samples/hello_world -- -DCONFIG_POSIX_API=y
-- west build: generating a build system
Loading Zephyr default modules (Zephyr base).
-- Application: /home/cfriedt/zephyrproject/zephyr/samples/hello_world
-- CMake version: 4.1.0
-- Found Python3: /opt/zephyr/venv/20250910/bin/python3.10 (found suitable version "3.10.18", minimum required is "3.10") found components: Interpreter
-- Cache files will be written to: /home/cfriedt/.cache/zephyr
-- Zephyr version: 4.2.99 (/home/cfriedt/zephyrproject/zephyr)
-- Found west (found suitable version "1.4.0", minimum required is "0.14.0")
-- Board: rpi_pico2, qualifiers: rp2350a/m33/w
-- Found host-tools: zephyr 0.17.2 (/opt/zephyr/zephyr-sdk-0.17.2)
-- Found toolchain: zephyr 0.17.2 (/opt/zephyr/zephyr-sdk-0.17.2)
-- Found Dtc: /opt/zephyr/zephyr-sdk-0.17.2/sysroots/x86_64-pokysdk-linux/usr/bin/dtc (found suitable version "1.7.0", minimum required is "1.4.6")
-- Found BOARD.dts: /home/cfriedt/zephyrproject/zephyr/boards/raspberrypi/rpi_pico2/rpi_pico2_rp2350a_m33_w.dts
-- Generated zephyr.dts: /home/cfriedt/zephyrproject/zephyr/build/zephyr/zephyr.dts
-- Generated pickled edt: /home/cfriedt/zephyrproject/zephyr/build/zephyr/edt.pickle
-- Generated devicetree_generated.h: /home/cfriedt/zephyrproject/zephyr/build/zephyr/include/generated/zephyr/devicetree_generated.h
Parsing /home/cfriedt/zephyrproject/zephyr/Kconfig
Loaded configuration '/home/cfriedt/zephyrproject/zephyr/boards/raspberrypi/rpi_pico2/rpi_pico2_rp2350a_m33_w_defconfig'
Merged configuration '/home/cfriedt/zephyrproject/zephyr/samples/hello_world/prj.conf'
Merged configuration '/home/cfriedt/zephyrproject/zephyr/build/zephyr/misc/generated/extra_kconfig_options.conf'
Configuration saved to '/home/cfriedt/zephyrproject/zephyr/build/zephyr/.config'
Kconfig header saved to '/home/cfriedt/zephyrproject/zephyr/build/zephyr/include/generated/zephyr/autoconf.h'
-- Found GnuLd: /opt/zephyr/zephyr-sdk-0.17.2/arm-zephyr-eabi/arm-zephyr-eabi/bin/ld.bfd (found version "2.38")
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- The ASM compiler identification is GNU
-- Found assembler: /opt/zephyr/zephyr-sdk-0.17.2/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc
-- Using ccache: /usr/bin/ccache
-- Found gen_kobject_list: /home/cfriedt/zephyrproject/zephyr/scripts/build/gen_kobject_list.py
-- Configuring done (4.6s)
-- Generating done (0.2s)
-- Build files have been written to: /home/cfriedt/zephyrproject/zephyr/build
-- west build: building application
[1/200] Preparing syscall dependency handling

[2/200] Generating include/generated/zephyr/version.h
-- Zephyr version: 4.2.99 (/home/cfriedt/zephyrproject/zephyr), build: v4.2.0-4845-g0ab40913c2de
[200/200] Linking C executable zephyr/zephyr.elf
Memory region         Used Size  Region Size  %age Used
           FLASH:       19252 B         4 MB      0.46%
             RAM:        6984 B       520 KB      1.31%
        IDT_LIST:          0 GB        32 KB      0.00%
Generating files from /home/cfriedt/zephyrproject/zephyr/build/zephyr/zephyr.elf for board: rpi_pico2
Converted to uf2, output size: 38912, start address: 0x10000000
Wrote 38912 bytes to zephyr.uf2
```

**Comment by cfriedt** [comment]
@dkouba-atym - are you able to provide any additional reproducibility information? I also cannot reproduce with the v0.17.4 SDK.

Feel free to reach out on Discord as well. Perhaps there are some additional details specific to your application?

**Comment by dkouba-atym** [comment]
I am using the 16.8 SDK, apologies I should have mentioned that — is there a possible incompatibility with prior versions?

```
dankouba ➜ ~ $ echo $ZEPHYR_SDK_INSTALL_DIR
/Users/dankouba/zephyr-sdk-0.16.8
```

**Comment by dkouba-atym** [comment]
Apologies, I now see [this guide](https://github.com/zephyrproject-rtos/sdk-ng/wiki/Zephyr-Version-Compatibility#zephyr-sdk-version-compatibility-matrix). I have upgraded my SDK to 17.4 and can build successfully.

**Comment by shiftee** [comment]
I was not able to get much from the link in the previous post.
In any case the following command installed the newer SDK for me: ```west sdk install```

Should this be added to the [Keeping Zephyr Updated](https://docs.zephyrproject.org/latest/develop/beyond-GSG.html#keeping-zephyr-updated) documentation?
