### ISSUE TITLE
tests/posix/common/portability.posix.common.picolibc broken on main on some platforms

### ISSUE THREAD

**Issue by aescolar** [zephyrproject-rtos/zephyr#62819]
**Describe the bug**
tests/posix/common/portability.posix.common.picolibc fails to build on some platforms

**To Reproduce**
1. mkdir build; cd build
2. cmake ../tests/posix/common/ -DBOARD=native_sim -GNinja -DCONFIG_PICOLIBC=y
3. ninja

**Expected behavior**
No build errors

**Impact**
CI blocked when these tests are triggered

**Logs and console output**
1. https://github.com/zephyrproject-rtos/zephyr/actions/runs/6235662389/job/16925534892#step:13:1650
2. 
```
 in function `get_posix_cond': lib/posix/cond.c:54: undefined reference to `log_const_pthread_cond'
 in function `to_posix_cond': lib/posix/cond.c:79: undefined reference to `log_const_pthread_cond'
 in function `cond_wait': lib/posix/cond.c:105: undefined reference to `log_const_pthread_cond'
/usr/bin/ld: lib/posix/cond.c:108: undefined reference to `log_const_pthread_cond'
 in function `pthread_cond_signal': lib/posix/cond.c:131: undefined reference to `log_const_pthread_cond'
lib/posix/cond.c:153: more undefined references to `log_const_pthread_cond' follow
 in function `to_posix_mutex': lib/posix/mutex.c:91: undefined reference to `log_const_pthread_mutex'
 in function `get_posix_mutex': lib/posix/mutex.c:66: undefined reference to `log_const_pthread_mutex'
 in function `acquire_mutex': lib/posix/mutex.c:131: undefined reference to `log_const_pthread_mutex'
/usr/bin/ld: lib/posix/mutex.c:136: undefined reference to `log_const_pthread_mutex'
/usr/bin/ld: lib/posix/mutex.c:144: undefined reference to `log_const_pthread_mutex'
lib/posix/mutex.c:149: more undefined references to `log_const_pthread_mutex' follow
 in function `is_posix_policy_prio_valid': lib/posix/pthread.c:145: undefined reference to `log_const_pthread'
 in function `to_posix_thread': lib/posix/pthread.c:102: undefined reference to `log_const_pthread'
 in function `pthread_attr_setschedparam': lib/posix/pthread.c:195: undefined reference to `log_const_pthread'
 in function `pthread_attr_setstack': lib/posix/pthread.c:213: undefined reference to `log_const_pthread'
 in function `pthread_attr_is_valid': lib/posix/pthread.c:237: undefined reference to `log_const_pthread'
lib/posix/pthread.c:416: more undefined references to `log_const_pthread' follow 
collect2: error: ld returned 1 exit status
```

**Environment (please complete the following information):**
 - OS: Linux CI, or Ubuntu 22.04
 - Toolchain gcc 11 or 12
 - Commit SHA or Version used: main after https://github.com/zephyrproject-rtos/zephyr/pull/62771 

**Additional context**
Introduced by https://github.com/zephyrproject-rtos/zephyr/pull/62771

**Comment by cfriedt** [comment]
This particular configuration is probably filtered-out in `testcase.yaml`, since it's passing CI for all other platforms.

**Comment by cfriedt** [comment]
I'll take a quick look to see if I can fix it.

**Comment by aescolar** [comment]
> This particular configuration is probably filtered-out in testcase.yaml, since it's passing CI for all other platforms.

Nope. Note the linked CI failure.

> I'll take a quick look to see if I can fix it.

Thanks :)

**Comment by cfriedt** [comment]
Ah, it was an easy fix. Will make a PR.

**Comment by cfriedt** [comment]
> > This particular configuration is probably filtered-out in testcase.yaml, since it's passing CI for all other platforms.
> 
> Nope. Note the linked CI failure.

right - .. well it passed CI for code that was already merged. I can't make CI run with the ability to predict what future code might be merged.

https://github.com/zephyrproject-rtos/zephyr/pull/62771/checks
