### ISSUE TITLE
samples: gsm_modem: Compilation failed, likely related to logging changes

### ISSUE THREAD

**Issue by ycsin** [zephyrproject-rtos/zephyr#35329]
**Describe the bug**
On the latest zephyr master, after added `CONFIG_GSM_MUX=y` to the `prj.conf` of the `samples/net/gsm_modem` and build that with:
```shell
west build -t ram_report --pristine -b frdm_k22f -- -DDTC_OVERLAY_FILE="boards/frdm_uart2_dts.overlay"
```
will result in massive compilation error related to log/uart_mux/struct gsm_mux.

It worked on master v2.5ish @ commit 365145aa97. Likely related to logging changes according to @jukkar on Slack

**To Reproduce**
Build the `gsm_modem` sample with the command written above.

**Expected behavior**
The sample should compiles fine, but for now it results in very long compilation error related to log/uart_mux/struct gsm_mux.

**Impact**
Unable to progress with anything that requires `CONFIG_GSM_MUX=y`

**Logs and console output**
Similar to this: [compile_log.txt](https://github.com/zephyrproject-rtos/zephyr/files/6492052/compile_log.txt)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Toolchain: gnuarmembi
 - Commit SHA or Version used: Latest master
