### PR TITLE
Replace diagnostic pragmas with `TOOLCHAIN_*` macros

### LINKED ISSUE #84138: intel_adsp: xt-clang: unknown warning group -Wunknown-warning-option.
**Describe the bug**
intel_adsp/ace15_mtpm/sim
```
INFO    - 1) tests/lib/mem_alloc/libraries.libc.minimal.mem_alloc on intel_adsp/ace15_mtpm/sim error (Build failure)
INFO    - 2) tests/lib/mem_alloc/libraries.libc.minimal.mem_alloc_negative_testing on intel_adsp/ace15_mtpm/sim error (Build failure)
INFO    - 3) tests/lib/mem_alloc/libraries.libc.picolibc.mem_alloc on intel_adsp/ace15_mtpm/sim error (Build failure)
INFO    - 4) tests/kernel/mem_protect/stack_random/kernel.memory_protection.stack_random on intel_adsp/ace15_mtpm/sim error (Build failure)
```

intel_adsp/ace30/ptl/sim
```
INFO    - 1) tests/kernel/mem_protect/stack_random/kernel.memory_protection.stack_random on intel_adsp/ace30/ptl/sim error (Build failure)
INFO    - 2) tests/lib/mem_alloc/libraries.libc.minimal.mem_alloc on intel_adsp/ace30/ptl/sim error (Build failure)
INFO    - 3) tests/lib/mem_alloc/libraries.libc.minimal.mem_alloc_negative_testing on intel_adsp/ace30/ptl/sim error (Build failure)
INFO    - 4) tests/lib/mem_alloc/libraries.libc.picolibc.mem_alloc on intel_adsp/ace30/ptl/sim error (Build failure)
```

intel_adsp/ace20_lnl/sim
```
INFO    - 1) tests/lib/mem_alloc/libraries.libc.minimal.mem_alloc on intel_adsp/ace20_lnl/sim error (Build failure)
INFO    - 2) tests/lib/mem_alloc/libraries.libc.minimal.mem_alloc_negative_testing on intel_adsp/ace20_lnl/sim error (Build failure)
INFO    - 3) tests/lib/mem_alloc/libraries.libc.picolibc.mem_alloc on intel_adsp/ace20_lnl/sim error (Build failure)
INFO    - 4) tests/kernel/mem_protect/stack_random/kernel.memory_protection.stack_random on intel_adsp/ace20_lnl/sim error (Build failure)
```

**To Reproduce**
`twister -p intel_adsp/ace20_lnl/sim -T  tests/lib/mem_alloc/`

**Logs and console output**
`/tests/lib/mem_alloc/src/main.c:24:32: error: unknown warning group '-Walloc-size-larger-than=', ignored [-Werror,-Wunknown-warning-option]
#pragma GCC diagnostic ignored "-Walloc-size-larger-than="`

**Environment:**

 - OS: Linux
 - Toolchain: xt-clang
 - Commit SHA or Version used: v4.0.0-3486-g4cc76e8a9ae3

**Additional context**
b9d7b1bdae9b41d3a73070536821c481f77633f1 is the first bad commit
```
commit b9d7b1bdae9b41d3a73070536821c481f77633f1
Author: Tom Hughes <tomhughes@chromium.org>
Date:   Mon Jan 13 12:16:12 2025 -0800

    cmake clang/compiler_flags.cmake: Re-enable -Wunknown-warning-option

    All warnings in the code base have been resolved.

    Signed-off-by: Tom Hughes <tomhughes@chromium.org>
```

### PR DESCRIPTION
**Pull request by thughes**
The `TOOLCHAIN_DISABLE_WARNING`/`TOOLCHAIN_ENABLE_WARNING` macros are easier to read and compiler agnostic.

Depends on https://github.com/zephyrproject-rtos/zephyr/pull/84063

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/84138

### CODE REVIEW

**Comment by cfriedt** [comment]
signal.h looks fine.

I suspect @nordic-krch should also review

**Review by nordic-krch — COMMENTED** [review]
logging and cbrprintf changes look ok.

**Review by tejlmand — COMMENTED** [review]
I do know that this PR just change existing use of pragma into a macro use, but I would like this opportunity to open a discussion regarding the use of macros / pragmas for disabling warnings.

In general pragmas are less portable between toolchains, and when adding support for a new toolchain, being it arc mwdt, IAR, etc, then the use of pragmas / macros in many files can result in a need to update a lot of files, especially when the warning may not be disabled in the same way.

For C files, like here:https://github.com/zephyrproject-rtos/zephyr/blob/f345a376445e5a8672d55b54250fe093d672a75e/arch/arm/core/cortex_a_r/reboot.c#L37
https://github.com/zephyrproject-rtos/zephyr/blob/f345a376445e5a8672d55b54250fe093d672a75e/drivers/dma/dma_xilinx_axi_dma.c#L362

it would be better to disable the warning in the CMake code, either for the C file or the library using the compiler target properties, https://github.com/zephyrproject-rtos/zephyr/blob/main/cmake/compiler/compiler_flags_template.cmake, especially because that will allow other toolchains (compilers) to define their own flag for disabling the corresponding warning.

For header files, then I agree the pragma / macro approach is needed, as I don't believe it's feasible to handle this in all the sources which includes the header.

My main concern with introducing macros, is the risk of misuse because it can become to easy to just disable a given warning using the macro, instead of doing this in the build system code (CMake).

**Comment by thughes** [comment]
> it would be better to disable the warning in the CMake code, either for the C file or the library using the compiler target properties, https://github.com/zephyrproject-rtos/zephyr/blob/main/cmake/compiler/compiler_flags_template.cmake, especially because that will allow other toolchains (compilers) to define their own flag for disabling the corresponding warning.

The problem with this approach is that it disables warnings in an overly broad fashion. We don't really want to disable warnings for an entire C file, library, or globally if we don't have to. Instead, we should prefer to disable the warning in an isolated manner as possible, so that the warning still applies to the rest of the code in the file or library.

> For header files, then I agree the pragma / macro approach is needed, as I don't believe it's feasible to handle this in all the sources which includes the header.

Correct. You can't do this in CMake. 

> In general pragmas are less portable between toolchains, and when adding support for a new toolchain, being it arc mwdt, IAR, etc, then the use of pragmas / macros in many files can result in a need to update a lot of files, especially when the warning may not be disabled in the same way.
> My main concern with introducing macros, is the risk of misuse because it can become to easy to just disable a given warning using the macro, instead of doing this in the build system code (CMake).

I think you have the same problem if you add the warnings in the cmake code. For example, let's say you add some code that triggers the hypothetical new `-Wfoo` warning added in the latest version clang. Let's say this warning only triggers on one function (or macro) in Zephyr. With these new macros we'd disable it with `TOOLCHAIN_DISABLE_CLANG_WARNING("-Wfoo")` and keep it isolated to the single macro or function that was affected. Alternatively, we could add it to the clang compiler cmake file and just disable it across all of the Zephyr code. 

Now, consider the case where we want to add the IAR toolchain. The IAR compiler has the `-Wfoo` warning, but refers to it by a different name [like `FOO123`](https://stackoverflow.com/questions/51969604/get-rid-of-iar-compile-warning-pa039-use-of-address-of-unaligned-structure-me). Even if we had added `-Wno-foo` to the clang compiler cmake file, it would not be used for the IAR toolchain. We would still need to add the IAR equivalent (`--diag_suppress FOO123`) to the IAR toolchain cmake file.

So with the cmake approach you still have the same problem with new toolchains, but you also the ability to disable the warning in an isolated manner that the macro approach provides (and which is required for disabling warnings in headers).

If we wanted to make the macro approach more flexible for new toolchains, one option would be to remove the generic `TOOLCHAIN_DISABLE_WARNING` macro and leave the compiler-specific ones (`TOOLCHAIN_DISABLE_GCC_WARNING`, `TOOLCHAIN_DISABLE_CLANG_WARNING`). Then if you want to disable a warning for all compilers, you'd create a new macro for indirection: `TOOLCHAIN_DISABLE_SHADOW_WARNING`:

(pseudocode)
```
#ifdef clang 
#define TOOLCHAIN_DISABLE_SHADOW_WARNING TOOLCHAIN_DISABLE_CLANG_WARNING("-Wshadow")
#elif gcc
#define TOOLCHAIN_DISABLE_SHADOW_WARNING TOOLCHAIN_DISABLE_GCC_WARNING("-Wshadow")
#elif iar
#define TOOLCHAIN_DISABLE_SHADOW_WARNING TOOLCHAIN_DISABLE_IAR_WARNING("FOO123")
#endif
```

The downside is that it adds a lot of boilerplate every time you want to disable a new warning for all the currently supported compilers, so it seems like it might make more sense to delay doing it until actually needed. It wouldn't be that hard to do a search and replace of all `TOOLCHAIN_DISABLE_WARNING` and then implement this behavior when needed.

**Comment by tejlmand** [comment]
> We don't really want to disable warnings for an entire C file, library, or globally if we don't have to.

Correct, the more specific the warning disabling is, the better.
I didn't pay close enough attention to the fact that in the C-files, the warnings was only disabled for specific functions.

> Now, consider the case where we want to add the IAR toolchain. The IAR compiler has the -Wfoo warning, but refers to it by a different name [like FOO123](https://stackoverflow.com/questions/51969604/get-rid-of-iar-compile-warning-pa039-use-of-address-of-unaligned-structure-me). Even if we had added -Wno-foo to the clang compiler cmake file, it would not be used for the IAR toolchain.

but that's exactly the beauty of the toolchain infrastructure.
You don't need to know the flag in order to use it, as you can do:
```
set_source_files_properties(file.c PROPERTIES COMPILE_OPTIONS "$<TARGET_PROPERTY:compiler,foo_warning>")
```

and then the compiler implementation, like here:
https://github.com/zephyrproject-rtos/zephyr/blob/main/cmake/compiler/gcc/compiler_flags.cmake
https://github.com/zephyrproject-rtos/zephyr/blob/main/cmake/compiler/arcmwdt/compiler_flags.cmake
https://github.com/zephyrproject-rtos/zephyr/blob/main/cmake/compiler/armclang/compiler_flags.cmake

decides which compiler flag corresponds to the `foo_warning` property.

This also means that out-of-tree toolchains can provide their own properties and there will be no need for adjusting C source code when having to support another toolchain, such as iar.
IAR can then do: `set_compiler_property(PROPERTY foo_warning --diag_suppress FOO123)` and code will still work.

> So with the cmake approach you still have the same problem with new toolchains, 

No, because you can adjust this without changing / patching the source code, which again means much more flexible to downstream users having out-of-tree toolchains or special requirements.


But based on the fact that the warning disabling in the C-code itself is as localized as it can be, then I think current solution is quite well.

@thughes Thanks the discussion, it's a good references for others looking at the PR / code in future.

**Review by tejlmand — APPROVED** [review]
LGTM, thanks for this and all the other cleanups :+1:

**Comment by thughes** [comment]
I need another approver for this to be merged.

@dcpleung @cfriedt @nordic-krch Would any of you be able to take a look? Thanks!

**Review by cfriedt — APPROVED** [review]
