### ISSUE TITLE
benchmark.memory_allocators fails on imx8mp_evk/mimx8ml8/adsp due to missing _ztest_benchmark_list_start

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#109885]
### Describe the bug

`tests/benchmarks/memory_allocators` fails to link for `imx8mp_evk/mimx8ml8/adsp` in downstream daily testing.

The failure happens while linking `zephyr/zephyr_pre0.elf` and reports a missing ztest benchmark linker symbol:
- `undefined reference to '_ztest_benchmark_list_start'`

Observed details:
- target platform: `imx8mp_evk/mimx8ml8/adsp`
- test case: `benchmark.memory_allocators`
- result: build failure
- downstream observed upstream SHA: `af72f3ca6382`

I did not find an existing open Zephyr issue matching:
- `_ztest_benchmark_list_start`
- `benchmark.memory_allocators`
- `imx8mp` + `adsp`

### Regression

- [x] This is a regression.

bad commit
commit 667c3184d6e8cbcbd1885a1f7c99a39d1cc99c56
Author: Krzysztof Chruściński <krzysztof.chruscinski@nordicsemi.no>
Date:   Mon Dec 8 08:27:59 2025 +0100

    logging: log_output: Fix formatting of function prefix
    
    When function prefix is used then formatting is expected to be
    <source_name>.<func_name> but it was as if function prefix was
    not used <source_name>: <func_name>.
    
    Signed-off-by: Krzysztof Chruściński <krzysztof.chruscinski@nordicsemi.no>

 subsys/logging/log_output.c | 16 ++++++++++++++--
 1 file changed, 14 insertions(+), 2 deletions(-)

### Steps to reproduce

1. Run twister for `tests/benchmarks/memory_allocators`
2. Use board `imx8mp_evk/mimx8ml8/adsp`
3. Build with Zephyr SDK / GNU Xtensa toolchain
4. Observe the link failure while creating `zephyr/zephyr_pre0.elf`

Representative twister target:
- `tests/benchmarks/memory_allocators`
- board: `imx8mp_evk/mimx8ml8/adsp`

### Relevant log output

[173/179] Linking C executable zephyr/zephyr_pre0.elf
FAILED: zephyr/zephyr_pre0.elf zephyr/zephyr_pre0.map
...
libsubsys__testsuite__ztest.a(benchmark.c.obj):(.literal.benchmark_main+0x4): undefined reference to `_ztest_benchmark_list_start'

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

- OS: Linux (observed in CI)
- Toolchain: Zephyr SDK / GNU Xtensa toolchain
- Commit SHA or Version used: `af72f3ca6382`

### Additional Context

The failure is specific to:
- `benchmark.memory_allocators`
- `imx8mp_evk/mimx8ml8/adsp`

Representative failure path from CI:
- `tests/benchmarks/memory_allocators/benchmark.memory_allocators`

If needed, I can provide the longer linker command excerpt as a follow-up comment.

**Comment by Mattemagikern** [comment]
Are you sure that commit (667c318) actually causes this?
That commit only changes log_output and has nothing to do with iterable sections or ztest.

The linker error undefined reference to `_ztest_benchmark_list_start` means the ztest_benchmark iterable section was never emitted to the linker.

The benchmark subsys registers its section via:
```CMake
zephyr_linker_sources(DATA_SECTIONS benchmark.ld)
zephyr_iterable_section(NAME ztest_benchmark GROUP DATA_REGION ${XIP_ALIGN_WITH_INPUT})
zephyr_iterable_section(NAME ztest_benchmark_timed GROUP DATA_REGION ${XIP_ALIGN_WITH_INPUT})
zephyr_iterable_section(NAME ztest_benchmark_suite GROUP DATA_REGION ${XIP_ALIGN_WITH_INPUT})
```

As it works for other targets, I would infer that the targets linker backend is missing an include or a section definition.

**Comment by hakehuang** [comment]
> Are you sure that commit ([667c318](https://github.com/zephyrproject-rtos/zephyr/commit/667c3184d6e8cbcbd1885a1f7c99a39d1cc99c56)) actually causes this? That commit only changes log_output and has nothing to do with iterable sections or ztest.
> 
> The linker error undefined reference to `_ztest_benchmark_list_start` means the ztest_benchmark iterable section was never emitted to the linker.
> 
> The benchmark subsys registers its section via:
> 
> zephyr_linker_sources(DATA_SECTIONS benchmark.ld)
> zephyr_iterable_section(NAME ztest_benchmark GROUP DATA_REGION ${XIP_ALIGN_WITH_INPUT})
> zephyr_iterable_section(NAME ztest_benchmark_timed GROUP DATA_REGION ${XIP_ALIGN_WITH_INPUT})
> zephyr_iterable_section(NAME ztest_benchmark_suite GROUP DATA_REGION ${XIP_ALIGN_WITH_INPUT})
> As it works for other targets, I would infer that the targets linker backend is missing an include or a section definition.

@Mattemagikern git bisect told me this commit, it may not be the rootcause. as you said this platform need some updates
