### ISSUE TITLE
Bluetooth sample app 'peripheral' failing to build for nRF52840

### ISSUE THREAD

**Issue by thedjnK** [zephyrproject-rtos/zephyr#16054]
The sample application bluetooth/peripheral is failing to build for the nRF52840 (using nrf52840_pca10056) with these errors:

    ../src/main.c:190:32: error: expected ')' before '{' token
     BT_GATT_SERVICE_DEFINE(vnd_svc,
                                    ^
                                    )
    ../src/main.c: In function 'main':
    ../src/main.c:331:23: error: 'vnd_svc' undeclared (first use in this function);
    did you mean 'vnd_uuid'?
        ind_params.attr = &vnd_svc.attrs[2];
                           ^~~~~~~
                           vnd_uuid

This seems to be due to the previous way of declaring GATT services changing from:
static struct bt_gatt_attr vnd_attrs[] = {
    	/* Vendor Primary Service Declaration */
    	BT_GATT_PRIMARY_SERVICE(&vnd_uuid),

To:
    BT_GATT_SERVICE_DEFINE(vnd_svc,
    	BT_GATT_PRIMARY_SERVICE(&vnd_uuid),
    	BT_GATT_CHARACTERISTIC(&vnd_enc_uuid.uuid,

This change was introduced in https://github.com/zephyrproject-rtos/zephyr/commit/c42707c2d3fea5b2524b345cc9909263532c0cc8

**To Reproduce**
1. cd samples/bluetooth/peripheral
2. mkdir build; cd build
2. cmake -GNinja -DBOARD=nrf52840_pca10056 ..
3. make

**Expected behavior**
The sample app to build

**Impact**
Was trying to reproduce a bug in the bluetooth code whereby it wrongly returns a reserved for future use error code in an older version of zephyr to see if it has been fixed so in regards to that this is a show stopper. If the code wasn't compiling it shouldn't have been pushed in the first place.

**Environment (please complete the following information):**
 - OS: Windows 7 64-bit
 - Toolchain: GCC 8
 - Commit SHA: latest, a93fcb10fd8b1dee7fbafff2dd8cf34901dc3068 at time of submission

**Comment by thedjnK** [comment]
Seems this was caused by building the old style without west, building with west builds a working image.
