### ISSUE TITLE
posix: undefined reference with --no-gc-sections

### ISSUE THREAD

**Issue by masz-nordic** [zephyrproject-rtos/zephyr#20137]
**Describe the bug**
When building with `--no-gc-sections` option to ld, reference to `clock_gettime` is undefined.
This is because its implementation is only included when `CONFIG_POSIX_CLOCK` is enabled, even though the function is called disregarding that config.

**To Reproduce**
1. Add:
```diff
--- a/samples/basic/blinky/CMakeLists.txt
+++ b/samples/basic/blinky/CMakeLists.txt
@@ -3,5 +3,6 @@
 cmake_minimum_required(VERSION 3.13.1)
 include($ENV{ZEPHYR_BASE}/cmake/app/boilerplate.cmake NO_POLICY_SCOPE)
 project(blinky)
-
+zephyr_ld_options(-Wl,--no-gc-sections)
+zephyr_ld_options(-Wl,--orphan-handling=place)
 target_sources(app PRIVATE src/main.c)
```
2. Build blinky:

```
west build -b nrf52840_pca10056
```

**Expected behavior**
Sample builds.

**Impact**
Annoyance.

**Screenshots or console output**
```
zephyr/lib/posix/liblib__posix.a(pthread_common.c.obj): in function `timespec_to_timeoutms':
/home/marcin/zephyr/zephyr/lib/posix/pthread_common.c:21: undefined reference to `clock_gettime'
```

**Environment:**
 - OS: Linux 5.2.21-1-MANJARO
 - Toolchain: Zephyr SDK 0.10.3
 - 55471982f68fed13671353585609507d2096bade with modification above

**Comment by pabigot** [comment]
There are a couple failures with these options on this sample.

For timespec I think the cause is that lib/posix is being built and linked in, and though most of the source files there are conditional on some posix-related Kconfig symbol `pthread_common.c` is not, and it wants to access the clock.

Potential solutions are:
* in `lib/posix/CMakeLists.txt' make `pthread_common.c` conditional on `CONFIG_POSIX_API`
* in `lib/CMakeLists.txt` make the recursion to `posix` conditional on `CONFIG_POSIX_API`

I would think the latter would make sense, but need information from @pfalcon to answer the question of why lib/posix is being included when `CONFIG_POSIX_API` is not enabled.

When I tested the reproducing case I also found an undefined reference to `sys_rand32_get()` coming from `kernel/init.c`.  That seems to have been introduced in 394f66b77e94af24325ffae49b791115486044b0 for which the commit message mentions nothing about the change, so assigning @ceolin to provide insight.

On the whole I don't think Zephyr's prepared to be built without discarding unreachable symbols.

**Comment by andrewboie** [comment]
I'd like to understand what your use-cases are for disabling gc-sections before we put work into addressing this configuration.

**Comment by masz-nordic** [comment]
@pabigot 
>When I tested the reproducing case I also found an undefined reference to sys_rand32_get() coming from kernel/init.c. That seems to have been introduced in 394f66b for which the commit message mentions nothing about the change, so assigning @ceolin to provide insight.

I have created a separate issue for kernel here: #20136

**Comment by ceolin** [comment]
> There are a couple failures with these options on this sample.
> 
> For timespec I think the cause is that lib/posix is being built and linked in, and though most of the source files there are conditional on some posix-related Kconfig symbol `pthread_common.c` is not, and it wants to access the clock.
> 
> Potential solutions are:
> 
> * in `lib/posix/CMakeLists.txt` make `pthread_common.c` conditional on `CONFIG_POSIX_API`
> * in `lib/CMakeLists.txt` make the recursion to `posix` conditional on `CONFIG_POSIX_API`
> 
> I would think the latter would make sense, but need information from @pfalcon to answer the question of why lib/posix is being included when `CONFIG_POSIX_API` is not enabled.
> 
> When I tested the reproducing case I also found an undefined reference to `sys_rand32_get()` coming from `kernel/init.c`. That seems to have been introduced in [394f66b](https://github.com/zephyrproject-rtos/zephyr/commit/394f66b77e94af24325ffae49b791115486044b0) for which the commit message mentions nothing about the change, so assigning @ceolin to provide insight.
> 
> On the whole I don't think Zephyr's prepared to be built without discarding unreachable symbols.

the problem with `sys_rand32_get` was there before the referenced commit, though there is a problem indeed. Have assigned #20136 to myself.

**Comment by pfalcon** [comment]
> I'd like to understand what your use-cases are for disabling gc-sections before we put work into addressing this configuration.

+1. Actually, I'd suggest to start with the assumption that Zephyr *requires* --gc-sections as part of the design.

**Comment by pfalcon** [comment]
> but need information from @pfalcon to answer the question of why lib/posix is being included when CONFIG_POSIX_API is not enabled.

As a quick generic answer (i.e. how-it-supposed-to-be) before I'll be able to dig into details, CONFIG_POSIX_API is the "master switch" for enabling all of the individual POSIX sub-APIs. They still can be enabled individually, because there're usecases for that. E.g. CONFIG_POSIX_MQUEUE enables just mq_*().

Beyond that, generic, underlying parts truly reusable w/o posix APIs, shouldn't be in lib/os/ instead of lib/posix/. E.g., it was the reason why fdtable.c was migrated from lib/posix/ to lib/os/.
