### ISSUE TITLE
twister: twister quit error when build with samples/subsys/ipc/openamp when use --prep-artifacts-for-testing

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#87163]
**Describe the bug**

```
2025-03-16 08:07:00,911 - __main__ -zephyr_ci_build_deploy_test.py : 189 - INFO - File "/home/jenkins/agent/workspace/zephyr_test_pipe/zephyr/scripts/pylib/twister/twisterlib/runner.py", line 1395, in _get_binaries
2025-03-16 08:07:00,911 - __main__ -zephyr_ci_build_deploy_test.py : 189 - INFO - for domain in self.instance.domains.get_domains():
2025-03-16 08:07:00,911 - __main__ -zephyr_ci_build_deploy_test.py : 189 - INFO - AttributeError: 'NoneType' object has no attribute 'get_domains'
```

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?
 - all NXP platforms
 - What have you tried to diagnose or workaround this issue?
 - git bisect
 - Is this a regression? If yes, have you been able to "git bisect" it to a
   specific commit?

the issue is exposed by below commit

9d7ee123a54a920455322fa42a094c53e45e06d4

**To Reproduce**

```
scripts/twister -p mimxrt1040_evk -j 12 -T samples/subsys/ipc/openamp  --prep-artifacts-for-testing --package-artifacts mimxrt1040_evk_twister_test_only.tar.gz --inline-logs -W
```

**Expected behavior**

build pass

**Impact**

CI

**Logs and console output**

**Environment (please complete the following information):**

 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used: b80526658cc0e6ec5719f09cd8fff65d4e50525c

**Comment by hakehuang** [comment]
samples/subsys/logging/syst has the same issue
