### ISSUE TITLE
ci_nxp_build_failure: soc: nxp: rw: RW612 builds fail on undefined RTC wakeup-count APIs

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#117797]
# Zephyr Upstream Issue Draft

## Summary
Zephyr main fails to build many unrelated tests and samples for both RW612 board targets because `soc/nxp/rw/power.c` calls `RTC_GetWakeupCount()` and `RTC_SetWakeupCount()` without declarations in the selected MCUX headers.

## Environment
- Tree: Zephyr main / NXP `zephyr_test_pipe` CI
- Zephyr version: `v4.4.0-13528-gf80761e49401`
- Commit: `f80761e49401497b5ee64ee9732dc2791055ec52`
- Toolchain: Zephyr SDK 1.0.1 (`arm-zephyr-eabi` GCC 14.3.0)
- Affected platforms:
  - `frdm_rw612/rw612` — Jenkins build [#7194](https://jenkins.nxp.com/zephyr-ci/job/zephyr_test_pipe/7194/), 40 failures
  - `rd_rw612_bga/rw612` — Jenkins build [#7253](https://jenkins.nxp.com/zephyr-ci/job/zephyr_test_pipe/7253/), 28 failures
  - `rd_rw612_bga/rw612/ethernet` — Jenkins build [#7249](https://jenkins.nxp.com/zephyr-ci/job/zephyr_test_pipe/7249/), 28 failures

## Steps to reproduce
```sh
west twister -p frdm_rw612 -T tests -T samples --build-only --inline-logs -M all
# or
west twister -p rd_rw612_bga -T tests -T samples --build-only --inline-logs -M all
```

## Actual Behavior
Compilation of `soc/nxp/rw/power.c` stops with:

```text
soc/nxp/rw/power.c:248:17: error: implicit declaration of function
'RTC_GetWakeupCount' [-Wimplicit-function-declaration]
  248 | uint16_t wake = RTC_GetWakeupCount(RTC);

soc/nxp/rw/power.c:253:49: error: implicit declaration of function
'RTC_SetWakeupCount' [-Wimplicit-function-declaration]
  253 | RTC_SetWakeupCount(RTC, wake - latency_ticks);
```

This common compilation unit prevents numerous unrelated scenarios from building, including `benchmark.kernel.footprints.pm`, multiple `cpp.main.*` variants, and `drivers.counter.basic_api`.

## Expected Behavior
RW612 power-management code should use APIs present in the selected MCUX RTC headers (and include the correct declarations), allowing unrelated applications and tests to build.

## Additional Context
All three affected targets fail at the same source lines and API names. This looks like a SoC/MCUX RTC API integration issue rather than failures in the individual tests.

A GitHub duplicate search for `RTC_GetWakeupCount` and `RTC_SetWakeupCount` returned no matching Zephyr issue as of 2026-08-31.

**Comment by hakehuang** [comment]
## Regression bisection

I reproduced the build failure locally with the Zephyr SDK 1.0.0 toolchain (GCC 14.3.0) and the `hal_nxp` revision pinned by each tested Zephyr revision.

**First bad commit:** [`fc9e4177aa6e6ef00731ce76722e639b05fd3d7e`](https://github.com/zephyrproject-rtos/zephyr/commit/fc9e4177aa6e6ef00731ce76722e639b05fd3d7e) — `drivers: timer: mcux_os_timer: fix PM3 exit drift`

| Revision | Result |
|---|---|
| parent [`77c6b14c4ba`](https://github.com/zephyrproject-rtos/zephyr/commit/77c6b14c4ba) | Builds successfully |
| `fc9e4177aa6e6ef00731ce76722e639b05fd3d7e` | Fails with undeclared `RTC_GetWakeupCount` and `RTC_SetWakeupCount` |
| reported CI revision `f80761e49401497b5ee64ee9732dc2791055ec52` | Same failure |

The reproducer was `samples/hello_world` for `frdm_rw612`, with `CONFIG_PM=y` supplied as an extra configuration fragment. PM is required because `soc/nxp/rw/power.c` is only compiled when `CONFIG_PM=y`.

```powershell
'CONFIG_PM=y' | Set-Content C:\Temp\pm.conf
west build -p always -b frdm_rw612 samples\hello_world -- `
  -DEXTRA_CONF_FILE=C:\Temp\pm.conf
```

The first-bad change adds the failing calls in `soc/nxp/rw/power.c`:

```c
uint16_t wake = RTC_GetWakeupCount(RTC);
...
RTC_SetWakeupCount(RTC, wake - latency_ticks);
```

The manifest-pinned `hal_nxp` revision contains the similarly named LPC RTC declarations under `drivers/lpc_rtc/fsl_rtc.h`, but that header is not in the RW612 compilation include set. This confirms the failure is introduced by the above Zephyr commit, rather than by a later `hal_nxp` revision.

**Comment by jacob-wienecke-nxp** [comment]
@hakehuang 
```
#if DT_NODE_HAS_STATUS_OKAY(DT_NODELABEL(standby))
#include <fsl_rtc.h>
#endif
```
Inclusion of fsl_rtc.h is contingent on the standby node being present. Which is the way that #105784 was tested, as it only applies to PM3. However, that doesn't stop the compiler from complaining about the unguarded call sites. So, the fix appears to be guarding the call sites in the same way.

PR incoming
