### ISSUE TITLE
tests: net.ptp.clock: frdm_k64f:  build failure

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#71738]
**Describe the bug**

net.ptp.clock build failure

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?
 - frdm_k64f
 - What have you tried to diagnose or workaround this issue?
 -  no
 - Is this a regression? If yes, have you been able to "git bisect" it to a
   specific commit?
 - git bisect find this is introduced by

```

commit 537d5c310c3e9d22f1df9a6d0bd1e250c84216fb
Author: Declan Snyder <declan.snyder@nxp.com>
Date:   Mon Mar 18 18:42:55 2024 -0500

    dts: nxp: Convert ENET DT default to new binding.
    
    Convert all of the NXP SOCs with ENET to use the new
    binding scheme, which is used by the new driver.
    
```

**To Reproduce**
west build -b frdm_k64f tests/net/ptp/clock

**Expected behavior**
build pass

**Impact**
PTP function

**Logs and console output**

```
/home/shared/disk/zephyr_project/zephyr_test/zephyr/drivers/ptp_clock/ptp_clock_nxp_enet.c:19:10: fatal error: fsl_enet.h: No such file or directory
   19 | #include "fsl_enet.h"
      |          ^~~~~~~~~~~~
compilation terminated.
[118/190] Building C object zephyr/subsys/net/ip/CMakeFiles/subsys__net__ip.dir/ipv6_nbr.c.obj
ninja: build stopped: subcommand failed.
FATAL ERROR: command exited with status 1: /home/ubuntu/.local/bin/cmake --build /home/shared/disk/zephyr_project/zephyr_test/zephyr/build
```

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used:  v3.6.0-2700-ga6400b42feeb

**Comment by hakehuang** [comment]
@decsny
