### ISSUE TITLE
Compile error building SNTP library for native_posix while NET_SOCKETS_POSIX_NAMES=n

### ISSUE THREAD

**Issue by heinwessels** [zephyrproject-rtos/zephyr#57133]
**Describe the bug**
It's not possible to build an application with the SNTP library using the `native_posix` board when `CONFIG_NET_SOCKETS_POSIX_NAMES=n` and `CONFIG_POSIX_API=n`. The error shown is

```
In file included from /home/hein/zephyrproject/zephyr/include/zephyr/posix/unistd.h:10,
                 from /home/hein/zephyrproject/zephyr/include/zephyr/net/sntp.h:15,
                 from /home/hein/zephyrproject/zephyr/samples/net/sockets/sntp_client/src/main.c:11:
/home/hein/zephyrproject/zephyr/include/zephyr/posix/sys/stat.h:40:10: fatal error: sys/_timespec.h: No such file or directory
   40 | #include <sys/_timespec.h>
      |          ^~~~~~~~~~~~~~~~~
```
A previous PR #50805 was merged by a member of our team to allow building SNTP for the same scenario, but I'm relatively confident that this functionality was broken again with a necessary change in https://github.com/zephyrproject-rtos/zephyr/commit/6f4e96bc2482e868590f3f72cfed92d14dcd6de1. 

After conferring with @cfriedt he mentioned that this could be fixed by changing the headers in `sntp.h`, something like:
```
#ifdef CONFIG_ARCH_POSIX
#include <sys/socket.h>
#include <unistd.h>
#include <poll.h>
#else
#include <zephyr/posix/sys/socket.h>
#include <zephyr/posix/unistd.h>
#include <zephyr/posix/poll.h>
#endif
```

I could get it to work, but it turned into a little oil spill where it required fixing a few files named below. I'm not sure what is the right way to fix it, and the fix seemed quite messy. If no one else is willing I will create a draft PR with these fixes soon.
```
include/zephyr/net/sntp.h
include/zephyr/net/socketutils.h
subsys/net/lib/sntp/sntp.c
subsys/net/lib/sntp/sntp_simple.c
subsys/net/lib/utils/addr_utils.c
```

**To Reproduce**
1. In `zephyr/samples/net/sockets/sntp_client/prj.conf` change to `CONFIG_NET_SOCKETS_POSIX_NAMES=n`.
2. `west build -p always -b native_posix samples/net/sockets/sntp_client`
4. Witness the mentioned compiler error

**Expected behavior**
For the application to build without warnings.

**Impact**
This is currently a showstopper in our attempt to migrate from Zephyr 2.6 to the upcoming Zephyr 3.4.

**Environment (please complete the following information):**
 - Linux
 - Zephyr SDK 0.16
 - Zephyr commit: 3707014f20f7c9fcb71e4f13fd23cf897b1dcbdc

**Comment by cfriedt** [comment]
@heinwessels - are you able to open a PR?

**Comment by heinwessels** [comment]
> Also major kudos making the leap from v2.6.0 to v3.4.0

Thanks! It's definitely not been easy, but this is the last hurdle I believe. Want to jump onto the next LTS where most of our functionality is in upstream Zephyr.

And I created the PR. Added you as co-author since you gave me the starting code. Not sure if that's the correct etiquette, so please feel to tell me if I should remove your name from the commit.

**Comment by cfriedt** [comment]
> > Also major kudos making the leap from v2.6.0 to v3.4.0
> 
> Thanks! It's definitely not been easy, but this is the last hurdle I believe. Want to jump onto the next LTS where most of our functionality is in upstream Zephyr.

Would be great if you had a few notes to share about that experience. An LTSv2 to LTSv3 migration guide is still very much in the planning stages cc @kartben

**Comment by heinwessels** [comment]
> > > Also major kudos making the leap from v2.6.0 to v3.4.0
> > 
> > 
> > Thanks! It's definitely not been easy, but this is the last hurdle I believe. Want to jump onto the next LTS where most of our functionality is in upstream Zephyr.
> 
> Would be great if you had a few notes to share about that experience. An LTSv2 to LTSv3 migration guide is still very much in the planning stages cc @kartben

I don't mind sharing if there's an existing document and everything, but don't currently have the time create such a migration guide. Most of our time was only spent moving our changes from our fork into upstream though, so also don't know how helpful that would be. :)
