### PR TITLE
manifest: hal_nxp: update revision for __aeabi_memcpy fix

### LINKED ISSUE #111367: [llext] rd_rw612_bga/rw612 link failures after aa31c8a69a1a (multiple definition of memcpy)
## Describe the bug

On `rd_rw612_bga/rw612`, multiple `tests/subsys/llext` builds started failing after commit `aa31c8a69a1a136dd9827845ce6ab3892d9b44be` (`llext: export ARM EABI mem helper functions`).

In NXP CI, a main-branch twister run at commit `dc0256972a7c7d70624bbcebc8dd0f1eb3ab02ce` reports 119 failures on `rd_rw612_bga/rw612`, concentrated in LLEXT test variants such as:

- `llext.loader_build.llext.inter_ext`
- `llext.loader_build.llext.inspect`
- `llext.loader_build.llext.printk_exported`
- `llext.readonly.llext.inter_ext`
- `llext.readonly.memblk.llext.inter_ext`
- `llext.readonly_mpu.llext.inter_ext`

The failures are link-time errors caused by a duplicate `memcpy` definition after the ARM EABI mem helper export change.

Representative error from the CI log:

```text
FAILED: zephyr/zephyr_pre0.elf zephyr/zephyr_pre0.map
...
multiple definition of `memcpy'; modules/hal_nxp/libmodules__hal_nxp.a(fsl_memcpy.S.obj):/home/jenkins/agent/workspace/zephyr_test_pipe/modules/hal/nxp/mcux/mcux-sdk-ng/components/misc_utilities/fsl_memcpy.S:198: first defined here
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

`git bisect` identified `aa31c8a69a1a136dd9827845ce6ab3892d9b44be` as the first bad commit.

## Regression

- [x] This is a regression.

`git bisect` points to:

- `aa31c8a69a1a136dd9827845ce6ab3892d9b44be` - `llext: export ARM EABI mem helper functions`
- Author: Anas Nashif <anas.nashif@intel.com>
- Date: Wed Jun 10 17:14:01 2026 -0400

## Steps to reproduce

1. Clone Zephyr main.
2. Check out commit `dc0256972a7c7d70624bbcebc8dd0f1eb3ab02ce` (or a revision containing `aa31c8a69a1a136dd9827845ce6ab3892d9b44be`).
3. Run twister for `rd_rw612_bga`:

   ```sh
   scripts/twister -j 10 --prep-artifacts-for-testing --package-artifacts default/rd_rw612_bga_twister_test_only.tar.gz --inline-logs --detailed-test-id -T tests -T samples -p rd_rw612_bga -W
   ```

4. Observe link failures in multiple `tests/subsys/llext` cases.

## Relevant log output

```text
CASE_NAME                                 RESULT         PLATFORM
llext.loader_build.llext.inter_ext        Build failure  rd_rw612_bga/rw612
llext.loader_build.llext.inspect          Build failure  rd_rw612_bga/rw612
llext.loader_build.llext.printk_exported  Build failure  rd_rw612_bga/rw612
...

FAILED: zephyr/zephyr_pre0.elf zephyr/zephyr_pre0.map
...
multiple definition of `memcpy'; modules/hal_nxp/libmodules__hal_nxp.a(fsl_memcpy.S.obj):/home/jenkins/agent/workspace/zephyr_test_pipe/modules/hal/nxp/mcux/mcux-sdk-ng/components/misc_utilities/fsl_memcpy.S:198: first defined here
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

## Impact

Functional Limitation - multiple LLEXT test builds fail on `rd_rw612_bga/rw612` on current main after the cited commit.

## Environment

- OS: Linux-based Jenkins CI environment (`/home/jenkins/...` paths in log)
- Toolchain: reported by the CI email as `zephyr`
- Commit SHA used in failing run: `dc0256972a7c7d70624bbcebc8dd0f1eb3ab02ce`
- First bad commit from `git bisect`: `aa31c8a69a1a136dd9827845ce6ab3892d9b44be`
- Platform: `rd_rw612_bga/rw612`

## Additional Context

The regressing commit adds ARM EABI exports in `subsys/llext/llext_export.c`, including `__aeabi_memcpy*`, `__aeabi_memmove*`, `__aeabi_memset*`, and `__aeabi_memclr*`.

This appears to interact badly with the NXP HAL implementation of `memcpy` from `modules/hal/nxp/mcux/mcux-sdk-ng/components/misc_utilities/fsl_memcpy.S`, resulting in duplicate symbol resolution during linking.

Related merged PR: #111004 (`llext: fixes for ARM with LLVM (zephyr/llvm)`).

### PR DESCRIPTION
**Pull request by zejiang0jason**
## Summary

- Update hal_nxp manifest revision to include `__aeabi_memcpy` aliases in `fsl_memcpy.S`
- Fixes "multiple definition of `memcpy'" link error when `CONFIG_LLEXT=y` on NXP Cortex-M platforms

## Root Cause

Zephyr commit aa31c8a69a1a added `EXPORT_GROUP_SYMBOL` for `__aeabi_memcpy*` in `llext_export.c`. NXP's optimized `fsl_memcpy.S` only defines `memcpy` without `__aeabi_memcpy` aliases, so the linker pulls in picolibc's `memcpy.c.o` (which provides `__aeabi_memcpy` as weak but also carries a strong `memcpy`), causing a multiple definition conflict.

## Fix

hal_nxp PR: https://github.com/zephyrproject-rtos/hal_nxp/pull/753

Adds `.thumb_set` aliases so `__aeabi_memcpy`, `__aeabi_memcpy4`, `__aeabi_memcpy8` resolve to the NXP optimized `memcpy`. Same calling convention — simple alias is correct.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/111367

## Test plan

- [x] `west build -p always tests/subsys/llext/ -b rd_rw612_bga` — passes
- [x] `west build -p always samples/hello_world/ -b mimxrt1180_evk/mimxrt1189/cm33` — passes
- [x] Verified `__aeabi_memcpy*` symbols point to NXP optimized implementation via `nm`

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Review by iuliana-prodan — DISMISSED** [review]

**Comment by hakehuang** [comment]
build test pass with this fixes.

**Review by hakehuang — DISMISSED** [review]

**Review by ZhaoxiangJin — DISMISSED** [review]

**Comment by zejiang0jason** [comment]
update to use SHA instead of PR id.

**Review by ZhaoxiangJin — APPROVED** [review]

**Review by MaochenWang1 — APPROVED** [review]
