### PR TITLE
arch: arm: fix extended frame check compilation for Cortex-A/R

### PR DESCRIPTION
**Pull request by aescolar**
Fix a compilation error when CONFIG_EXTRA_EXCEPTION_INFO is enabled on platforms that do not define EXC_RETURN_STACK_FRAME_TYPE_Msk (which is only defined for Cortex-M).

For Cortex-A/R devices we just default to the same code path as before [bce6f0de636fb248bef3f135a2bdc119beb29556](https://github.com/zephyrproject-rtos/zephyr/commit/bce6f0de636fb248bef3f135a2bdc119beb29556?w=1)

Issue introduced in https://github.com/zephyrproject-rtos/zephyr/pull/111949 / bce6f0de636fb248bef3f135a2bdc119beb29556
Can be reproduced with
``
cmake -GNinja -DBOARD=qemu_cortex_a9/xc7z007s ../tests/subsys/debug/gdbstub
ninja
``
Failure in main can be seen here:
https://github.com/zephyrproject-rtos/zephyr/actions/runs/29233319541/job/86763059718#step:12:716

### CODE REVIEW

**Review by wearyzen — APPROVED** [review]

File: arch/arm/core/fatal.c [hunk 1]
```diff
@@ -30,7 +30,7 @@ static void esf_dump(const struct arch_esf *esf)
 	EXCEPTION_DUMP(" xpsr:  0x%08x", esf->basic.xpsr);
 #if defined(CONFIG_FPU) && defined(CONFIG_FPU_SHARING)
 	bool extended_frame;
-#if defined(CONFIG_EXTRA_EXCEPTION_INFO)
+#if defined(CONFIG_EXTRA_EXCEPTION_INFO) && defined(EXC_RETURN_STACK_FRAME_TYPE_Msk)
```
Comment (Thalley) [inline arch/arm/core/fatal.c:33]: I don't understand this fix. When is this not defined? 

```c
#define EXC_RETURN_STACK_FRAME_TYPE_Pos        4
#define EXC_RETURN_STACK_FRAME_TYPE_Msk        BIT(EXC_RETURN_STACK_FRAME_TYPE_Pos)
```

The only path I see, is that the macro is only defined for `CONFIG_CPU_CORTEX_M`, and in that case shouldn't this be

```suggestion
#if defined(CONFIG_EXTRA_EXCEPTION_INFO) && defined(CONFIG_CPU_CORTEX_M)
```

Instead?

**Review by fabiobaltieri — APPROVED** [review]

File: arch/arm/core/fatal.c (hunk 1 above)
Comment (aescolar) [reply arch/arm/core/fatal.c:33]: > The only path I see, is that the macro is only defined for CONFIG_CPU_CORTEX_M

I'm just playing it safe here. It either is defined and the code below compiles, or it isn't and we fall back to the previous code path.

**Review by fkokosinski — APPROVED** [review]
Thanks for the hotfix!
