### PR TITLE
Xtensa asm2 and SMP series, full

### PR DESCRIPTION
**Pull request by andyross**
Rebased, should be ready for merge unless I missed some test failures

### CODE REVIEW

**Comment by nashif** [comment]
can you please all other open PRs that are obsolete now?

File: arch/xtensa/core/window_vectors.S [hunk 1]
```diff
@@ -0,0 +1,239 @@
+/*
+ * Copyright (c) 2016 Cadence Design Systems, Inc.
```
Comment (ramakrishnapallala) [inline arch/xtensa/core/window_vectors.S]: 2018?

File: arch/xtensa/core/thread.c [hunk 2]
```diff
@@ -12,6 +12,7 @@
 #include <kernel_structs.h>
 #include <wait_q.h>
 #include <xtensa_config.h>
+#include <nano_internal.h>
```
Comment (ramakrishnapallala) [inline arch/xtensa/core/thread.c]: we changed this name to kernel_internal.h

is it still existing?

File: arch/xtensa/include/kernel_arch_data.h [hunk 3]
```diff
@@ -57,6 +57,10 @@ typedef struct _kernel_arch _kernel_arch_t;
 
 #endif /*! _ASMLANGUAGE && ! __ASSEMBLER__ */
 
+#ifdef CONFIG_USE_SWITCH
```
Comment (ramakrishnapallala) [inline arch/xtensa/include/kernel_arch_data.h]: can we change the config name to CONFIG_USE_ARCH_SWITCH?

File: kernel/include/ksched.h [hunk 4]
```diff
@@ -32,6 +32,13 @@ extern s32_t _ms_to_ticks(s32_t ms);
 #endif
 extern void idle(void *, void *, void *);
 
+/* find which one is the next thread to run */
+/* must be called with interrupts locked */
+static ALWAYS_INLINE struct k_thread *_get_next_ready_thread(void)
```
Comment (ramakrishnapallala) [inline kernel/include/ksched.h]: this change was removed earlier commit and added now again!!

File: arch/xtensa/core/xtensa-asm2.c [hunk 5]
```diff
@@ -9,6 +9,7 @@
 #include <kernel.h>
 #include <ksched.h>
 #include <kernel_structs.h>
+#include <nano_internal.h>
```
Comment (ramakrishnapallala) [inline arch/xtensa/core/xtensa-asm2.c]: kernel_internal.h?

File: tests/kernel/mp/src/main.c [hunk 6]
```diff
@@ -0,0 +1,48 @@
...
+
+	while (1) {
+	}
+}
+
+void test_mp_start(void)
+{
+	cpu_arg = 12345;
+
+	_arch_start_cpu(1, cpu1_stack, CPU1_STACK_SIZE, cpu1_fn, &cpu_arg);
```
Comment (ramakrishnapallala) [inline tests/kernel/mp/src/main.c]: does cpu1_fn() will be called from a new thread context?

File: kernel/include/kernel_structs.h [hunk 7]
```diff
@@ -89,6 +88,30 @@ struct _kernel {
...
+
+typedef struct _cpu _cpu_t;
+
+struct _kernel {
+	/* For compatibility with pre-SMP code, union the first CPU
+	 * record with the legacy fields so code can continue to use
+	 * the "_kernel.XXX" expressions and assembly offsets.
+	 */
+	union {
+		struct _cpu cpus[CONFIG_MP_NUM_CPUS];
```
Comment (ramakrishnapallala) [inline kernel/include/kernel_structs.h]: strcut _cpu should be under #ifdef CONFIG_SMP right?

File: kernel/init.c [hunk 8]
```diff
@@ -302,11 +340,19 @@ static void prepare_multithreading(struct k_thread *dummy_thread)
...
+	init_idle_thread(_idle_thread1, _idle_stack1);
+#endif
+
+#if defined(CONFIG_SMP) && CONFIG_MP_NUM_CPUS > 2
+	init_idle_thread(_idle_thread2, _idle_stack2);
+#endif
+
+#if defined(CONFIG_SMP) && CONFIG_MP_NUM_CPUS > 3
+	init_idle_thread(_idle_thread3, _idle_stack3);
 #endif
```
Comment (ramakrishnapallala) [inline kernel/init.c]: all the #if should be under the CONFIG_MULTITHREADING

File: kernel/smp.c [hunk 9]
```diff
@@ -48,3 +50,56 @@ void _smp_global_unlock(unsigned int key)
...
+
+	CODE_UNREACHABLE;
+}
+#endif
+
+void smp_init(void)
+{
+	atomic_t start_flag;
+
+	atomic_clear(&start_flag);
```
Comment (ramakrishnapallala) [inline kernel/smp.c]: Just for my understanding, why we need atomic here?

File: kernel/include/ksched.h [hunk 10]
```diff
@@ -46,7 +53,11 @@ static inline int _is_idle_thread(void *entry_point)
 
 static inline int _is_idle_thread_ptr(k_tid_t thread)
 {
+#ifdef CONFIG_SMP
+	return thread->base.is_idle;
```
Comment (ramakrishnapallala) [inline kernel/include/ksched.h]: if we are checking idle thread ptr based on 'is_idle' then any thread which sets this filed becomes idle thread, do we want this ? idle thread is something which should be run at the system level and should be created early init right?

File: kernel/sched.c [hunk 11]
```diff
@@ -489,3 +497,44 @@ int _impl_k_is_preempt_thread(void)
...
+
+	for (p = 0; p < ARRAY_SIZE(_ready_q.q); p++) {
+		sys_dlist_t *list = &_ready_q.q[p];
+		sys_dnode_t *node;
+
+		for (node = list->tail; node != list; node = node->prev) {
+			struct k_thread *th = (struct k_thread *)node;
+
+			/* Skip threads that are already running elsewhere! */
+			if (th->base.active && th->base.cpu != mycpu) {
```
Comment (ramakrishnapallala) [inline kernel/sched.c]: what does active flag indicate? does it mean thread has run at least once? also when are we assigning the cpu? is it during thread create?

File: kernel/idle.c [hunk 12]
```diff
@@ -164,6 +164,20 @@ void idle(void *unused1, void *unused2, void *unused3)
...
+	/* Simplified idle for non-default SMP CPUs pending driver
+	 * support.  The busy waiting is needed to prevent lock
+	 * contention.  Long term we need to wake up idle CPUs with an
+	 * IPI.
+	 */
+	if (_arch_curr_cpu()->id > 0) {
+		while (1) {
+			k_busy_wait(100);
+			k_yield();
+		}
```
Comment (ramakrishnapallala) [inline kernel/idle.c]: this means, scheduler code always run on main cpu? also as per the current logic other cpu's don't don't enter sleep states?

File: kernel/thread_abort.c [hunk 13]
```diff
@@ -37,13 +37,17 @@ void _impl_k_thread_abort(k_tid_t thread)
 	_k_thread_single_abort(thread);
 	_thread_monitor_exit(thread);
 
-	if (_current == thread) {
-		_Swap(key);
-		CODE_UNREACHABLE;
-	}
+	if (_is_in_isr()) {
+		irq_unlock(key);
```
Comment (ramakrishnapallala) [inline kernel/thread_abort.c]: we are just unlocking here and returning, where is reschedule is being called?

the earlier logic is now moved to ela=se part (non isr), so how this call will behave in case of ISR?

File: arch/xtensa/core/thread.c (hunk 2 above)
Comment (ramakrishnapallala) [reply arch/xtensa/core/thread.c]: saw the change in the following commit, igonre it

**Comment by ramakrishnapallala** [comment]
@andy I think it's better to add the documentation as you have written detailed commit messages  :)

File: kernel/include/kernel_structs.h (hunk 7 above)
Comment (andyross) [reply kernel/include/kernel_structs.h]: No, this is the official API now.  When there is only one CPU, the array is of length one but otherwise shares the same offsets as the legacy fields in the union (which will eventually go away).  There's no particular benefit to having a separate API beyond making migration easier.

File: kernel/init.c (hunk 8 above)
Comment (andyross) [reply kernel/init.c]: CONFIG_SMP presumes CONFIG_MULTITHREADING.  It doesn't make sense otherwise.  Not sure if the kconfig makes that explicit or not.

File: kernel/smp.c (hunk 9 above)
Comment (andyross) [reply kernel/smp.c]: We don't on ESP-32 or x86.  In theory on some architecture we might if there are cache coherence rules..  Beyond that it's just form adherence.  Spinning on a raw int from a separate CPU just feels wrong.

File: kernel/include/ksched.h (hunk 10 above)
Comment (andyross) [reply kernel/include/ksched.h]: Nothing sets this field at runtime, and threads do not "become idle".  An "idle thread" is a specific thread created at system startup.  There used to be one, so you would test it with "tid == _idle_thread".  Now there needs to be one per CPU so it needs a bit somewhere in the struct to tell us.

File: kernel/sched.c (hunk 11 above)
Comment (andyross) [reply kernel/sched.c]: Documented in the struct as "Non-zero when actively running on a CPU".  This indicates that another CPU is actively running this thread.

And we don't assign threads to CPUs.  The "S" in SMP means that every CPU can run every process.  They select the next process from the scheduler in this code when they are about to context switch (i.e. someone has called k_yield(), or we are returning from handling an interrupt of a preemptible thread, etc...).

File: kernel/idle.c (hunk 12 above)
Comment (andyross) [reply kernel/idle.c]: Timeout code always runs on the main CPU, yes.  Right now it's based on counting ticks instead of finer-grained timeouts, so there's no easy way to translate that to a different CPU's interrupts, which happen at a different phase.   Scheduler code runs on every CPU, it's SMP :)

And yes: right now auxiliary CPUs can't enter a low power state because there is nothing to wake them up appropriately when a new thread enters the scheduler.  We have to choose either bad latency (i.e. have them wake up at their next timer tick interrupt, which can be millions of cycles late) or bad power behavior (spin on the scheduler looking for updates), and I picked the latter.

In the intermediate term we need an architecture where adding a schedulable thread to the run queue where there are idle CPUs will produce an IPI to wake up the others CPUs.

File: kernel/thread_abort.c (hunk 13 above)
Comment (andyross) [reply kernel/thread_abort.c]: The reschedule doesn't get called.  That's the whole point: in an ISR, you can't _Swap() on xtensa (and ARM too) because you then won't get to the interrupt exit code, which will then inspect the scheduler and return into whatever the next thread should be.  This is all explained in the commit message detailing that change.

**Comment by andyross** [comment]
Just series cleanup in this last revision, no code change.  Ram found an embarassing spot where I'd independently written both a patch and its precise revision (moving a function out of a header, then right back in) without realizing it.  Remove those two patches.

File: kernel/thread_abort.c (hunk 13 above)
Comment (ramakrishnapallala) [reply kernel/thread_abort.c]: got it :), the reschedule will happen anyways after servicing the interrupt.

File: kernel/idle.c (hunk 12 above)
Comment (ramakrishnapallala) [reply kernel/idle.c]: got it. Thanks.

**Comment by rgundi** [comment]
Andy, in the current form, this still breaks Intel S1000 compilation (due to missing _soc_inthandlers.h). Is it not possible to make the changes explicitly under the "XTENSA_ASM2" macro? Meaning, if this macro is undefined, the compilation should continue in the old style (where it doesn't look for _soc_inthandlers.h).

**Review by SebastianBoe — APPROVED** [review]
CMake-related changes are OK

**Comment by andyross** [comment]
Yes, older platforms are absolutely supposed to be still supported as-is.  You're right that the xtensa-asm2.c file needs a header that doesn't exist though, which is a bug.  I can move the asm2 sources (which are supposed to build on their own) into a zephyr_sources_ifdef(), though I can't test out of tree stuff well.  It might be simpler to do this in the S1000 patch series.

**Comment by andyross** [comment]
@rgundi : Might be simpler to just have you test.  This should resolve the missing header build failure:

``diff --git a/arch/xtensa/core/CMakeLists.txt b/arch/xtensa/core/CMakeLists.txt
index 9b2ae4e..672d897 100644
--- a/arch/xtensa/core/CMakeLists.txt
+++ b/arch/xtensa/core/CMakeLists.txt
@@ -3,6 +3,9 @@ zephyr_sources(
        cpu_idle.c
        fatal.c
        window_vectors.S
+       )
+
+zephyr_sources_ifdef(CONFIG_XTENSA_ASM2
        xtensa-asm2-util.S
        xtensa-asm2.c
        )

**Comment by andyross** [comment]
Nah, that's silly.  I can trivially validate that patch even if I can't build S1000.  Included.

**Comment by rgundi** [comment]
The compilation passed that stage but failed later with the below message.
kernel_arch_func.h: Assembler messages:
kernel_arch_func.h:35: Error: unknown opcode or format name 'rsr.misc0'

So, I see the code "_arch_curr_cpu()" gets included even in case where XTENSA_ASM2 is not enabled. I tried excluding it but it threw other errors as it is referenced elsewhere. So, as discussed earlier, guess it's better to replace MISC0 with EXCSAVE2 which is present in all Xtensa SoCs

**Comment by andyross** [comment]
@rgundi: Yeah, let's take this offline and deal with the stuff specific to out-of-tree patches separately.  Until I get a working toolchain here (and ideally hardware that matches) we're constantly going to be bumping into issues like this.

FWIW: it should absolutely be possible to disable compilation of that function and whatever else depends on it when ASM2 is unset.

**Comment by andyross** [comment]
Heh, same deal.  Said "let's do this later", then went in to see if I could synthesize the error locally, and it turned out to be trivial.  Patch included.

File: arch/xtensa/soc/esp32/esp32-mp.c [hunk 14]
```diff
@@ -0,0 +1,192 @@
...
+ *
+ * SPDX-License-Identifier: Apache-2.0
+ */
+#include <zephyr.h>
+#include <kernel_structs.h>
+#include <soc.h>
+
+#define _REG(base, off) (*(volatile u32_t *)((base) + (off)))
+
+#define RTC_CNTL_BASE             0x3ff48000
```
Comment (lpereira) [inline arch/xtensa/soc/esp32/esp32-mp.c]: Please use the register macros from esp-idf. All ESP32 drivers are using them; I'd like to keep the consistency.

File: arch/xtensa/soc/esp32/linker.ld [hunk 15]
```diff
@@ -30,6 +30,9 @@ PROVIDE ( esp32_rom_uart_attach = 0x40008fd0 );
 PROVIDE ( esp32_rom_intr_matrix_set = 0x4000681c );
 PROVIDE ( esp32_rom_gpio_matrix_in = 0x40009edc );
 PROVIDE ( esp32_rom_gpio_matrix_out = 0x40009f0c );
+PROVIDE ( esp32_rom_Cache_Flush = 0x40009a14 );
```
Comment (lpereira) [inline arch/xtensa/soc/esp32/linker.ld]: Nitpick: lower case names, please.

File: arch/xtensa/soc/esp32/esp32-mp.c [hunk 16]
```diff
@@ -0,0 +1,192 @@
...
+	sr.vecbase = vb;
+	sr.alive = &alive_flag;
+
+	appcpu_top = K_THREAD_STACK_BUFFER(stack) + sz;
+
+	start_rec = &sr;
+
+	appcpu_start();
+
+	while (!alive_flag) {
```
Comment (lpereira) [inline arch/xtensa/soc/esp32/esp32-mp.c]: Are there any error conditions we should check while waiting for the CPU to be brought up? Do we need to panic on timeout?

File: include/spinlock.h [hunk 17]
```diff
@@ -0,0 +1,69 @@
...
+	 * implementation.  The "irq_lock()" API in SMP context is
+	 * actually a wrapper for a global spinlock!
+	 */
+	k.key = _arch_irq_lock();
+
+#ifdef CONFIG_SMP
+# ifdef CONFIG_DEBUG
+	l->saved_key = k.key;
+# endif
+	while (!atomic_cas(&l->locked, 0, 1)) {
```
Comment (lpereira) [inline include/spinlock.h]: I'm not sure if it would be an issue in the systems Zephyr runs on (esp. on ESP32, where this makes sense now), but it's often a good thing to perform the locking primitive of a spinlock like this in order to reduce cache contention:

```C
while (!atomic_cas(&l->locked, 0, 1)) {
     while (l->locked != 0) {
     }
}
```

Note that `atomic_get()` is not used here on purpose: the generic implementation using GCC atomic builtins will enforce total ordering, which isn't needed because `atomic_cas()` will do that for us if the value ever changes.

File: kernel/init.c [hunk 18]
```diff
@@ -373,6 +436,10 @@ FUNC_NORETURN void _Cstart(void)
 	__stack_chk_guard = (void *)sys_rand32_get();
 #endif
 
+#ifdef CONFIG_SMP
+	smp_init();
+#endif
+
 	/* display boot banner */
```
Comment (lpereira) [inline kernel/init.c]: Minor: It would be nice to have "SMP" somewhere in the boot banner.

File: include/kernel.h [hunk 19]
```diff
@@ -391,6 +391,17 @@ struct _thread_base {
 		u16_t preempt;
 	};
 
+#ifdef CONFIG_SMP
+	/* True for the per-CPU idle threads */
+	u8_t is_idle;
+
+	/* Non-zero when actively running on a CPU */
+	u8_t active;
```
Comment (lpereira) [inline include/kernel.h]: Do we need both `active` and `cpu`? Could `active` be a bitmap, where the nth-bit tells us this thread is running on the nth CPU? This would simplify the thread skipping logic in the scheduler a little bit.

File: kernel/init.c (hunk 18 above)
Comment (andrewboie) [reply kernel/init.c]: Good idea.

File: arch/xtensa/include/kernel_arch_data.h (hunk 3 above)
Comment (andrewboie) [reply arch/xtensa/include/kernel_arch_data.h]: why is that necessary?

File: kernel/Kconfig [hunk 20]
```diff
@@ -549,6 +549,18 @@ config MAX_DOMAIN_PARTITIONS
...
+config USE_SWITCH
+	bool
+	prompt "Use new-style _arch_switch instead of __swap"
+	default n
+	help
+	The _arch_switch() API is a lower level context switching
+	primitive than the original __swap mechanism.  It is required
+	for an SMP-aware scheduler, or if the architecture does not
+	provide __swap.  In uniprocess situations where the
+	architecture provides both, _arch_switch incurs more somewhat
```
Comment (andrewboie) [inline kernel/Kconfig]: " _arch_switch incurs more somewhat overhead and may be slower"

Nitpick: awkward English.
Suggest: "_arch_switch incurs somewhat more overhead."

File: kernel/include/kernel_internal.h [hunk 21]
```diff
@@ -51,30 +52,61 @@ extern void _setup_new_thread(struct k_thread *new_thread,
...
+ * don't want to have to do in per-architecture assembly.
+ */
 static inline unsigned int _Swap(unsigned int key)
 {
+	struct k_thread *new_thread, *old_thread;
+
+	old_thread = _kernel.current;
 
-#ifdef CONFIG_STACK_SENTINEL
 	_check_stack_sentinel();
```
Comment (andrewboie) [inline kernel/include/kernel_internal.h]: Me personally, I always preferred explicit ifdefs rather than defining various functions to empty macros, as I think it makes it clearer that this call site doesn't do anything.

I used to lose arguments with Dirk all the time about this.

Carry on, I'm just whining.

File: arch/xtensa/soc/esp32/linker.ld (hunk 15 above)
Comment (andyross) [reply arch/xtensa/soc/esp32/linker.ld]: That's the name in the Espressif header though, even though we don't use it from there.

File: arch/xtensa/soc/esp32/esp32-mp.c (hunk 14 above)
Comment (andyross) [reply arch/xtensa/soc/esp32/esp32-mp.c]: Sorry, my reply must have been in the other PR.  The problem is that the existing API for these registers is sort of a mess, it doesn't express the register as an lvalue and wants to use a whole bunch of setter/getter macroness, and IIRC I had trouble making that work.  But I'll investigate again.

File: arch/xtensa/soc/esp32/esp32-mp.c (hunk 16 above)
Comment (andyross) [reply arch/xtensa/soc/esp32/esp32-mp.c]: ...maybe?  There are no errors reported by the existing API and the FreeRTOS integration didn't check IIRC.   I guess my feeling here would be "don't test for fatal errors, failure is OK if recovery is impossible".  A hung boot if the second CPU fails seems.... sort of OK to me?

File: drivers/timer/xtensa_sys_timer.c [hunk 22]
```diff
@@ -465,6 +479,18 @@ void _xt_tick_divisor_init(void)
...
+
+#ifdef CONFIG_XTENSA_ASM2
+	/* FIXME: the legacy xtensa code did this in the assembly
+	 * hook, and was a little more sophisticated.  We should track
+	 * the delta from the last set time, not the current time.
+	 * And the earlier code was even prepared to handle missed
+	 * ticks by calling the handler function multiple times if the
+	 * delta was more than one _xt_tick_divisor.
+	 */
+	SET_TIMER_FIRE_TIME(GET_TIMER_CURRENT_TIME() + _xt_tick_divisor);
```
Comment (andrewboie) [inline drivers/timer/xtensa_sys_timer.c]: I had a fever dream that one day this driver was fixed up to use IRQ_CONNECT() and all the custom asm stuff for it was nuked from orbit. I should file a bug on that.

File: include/spinlock.h (hunk 17 above)
Comment (andyross) [reply include/spinlock.h]: Even on x86, the resulting lock cmpxchg is safe from cache spamming.  The line goes into a S(hared) state in L1D the first time through the loop and the core hits L2/L3 only if it snoops someone else's change to that cache line.

But really long term if we care about performance what we'll do is to have each architecture code its own spinlock implementation with inlines instead of calling out to the generic atomic API.

File: arch/xtensa/core/xtensa_intgen.py [hunk 23]
```diff
@@ -0,0 +1,129 @@
+#!/usr/bin/env python3
+import re
+import fileinput
+
+# Pass an Xtensa core-isa.h file on stdin or the command line, emits a
+# C file on output containing optimized interrupt dispatch routines.
+
```
Comment (andrewboie) [inline arch/xtensa/core/xtensa_intgen.py]: Suggest filing a user story to have someone with CMake chops make this part of the build.
I have no idea on how to do it either.

File: arch/xtensa/core/xtensa-asm2.c [hunk 24]
```diff
@@ -27,23 +28,23 @@ void *xtensa_init_stack(int *stack_top,
 
 	memset(bsa, 0, bsasz);
 
-	bsa[BSA_PC_OFF/4] = entry;
+	bsa[BSA_PC_OFF/4] = _thread_entry;
```
Comment (andrewboie) [inline arch/xtensa/core/xtensa-asm2.c]: Oh jeez. I missed this in the initial implementation.
I'm a little amazed our test cases pass, one of the essential things _thread_entry does is call k_thread_abort() after main() returns.
Good stuff.

File: include/kernel.h (hunk 19 above)
Comment (andyross) [reply include/kernel.h]: That's clever.  Yes, I think.  The "cpu" field might in principle be needed (by a fancier scheduler) to tell the kernel the CPU that a non-active thread was "last" scheduled on, but it isn't right now.

File: arch/xtensa/core/xtensa-asm2-util.S [hunk 25]
```diff
@@ -265,6 +265,30 @@ DEF_EXCINT 6, _handle_excint, xtensa_int6_c
...
 #endif
 
+/* The user exception vector is defined here, as we need to handle
+ * MOVSP exceptions in assembly (the result has to be to unspill the
+ * caller function of the code that took the exception, and that can't
+ * be done in C).  A prototype exists which mucks with the stack frame
+ * from the C handler instead, but that would add a LARGE overhead to
+ * some alloca() calls (those whent he caller has been spilled) just
+ * to save these five cycles during other exceptions and L1
+ * interrupts.  Maybe revisit at some point, with better benchmarking.
```
Comment (andrewboie) [inline arch/xtensa/core/xtensa-asm2-util.S]: In commit message you mention some possible future optimizations. I suggest filing a low-priority user story about it so we don't forget. We could give it to a junior engineer or something.

File: kernel/smp.c [hunk 26]
```diff
@@ -48,3 +50,56 @@ void _smp_global_unlock(unsigned int key)
 	recursive_count = 0;
 	k_spin_unlock(&global_spinlock, sk);
 }
+
+extern k_thread_stack_t _interrupt_stack1[];
```
Comment (andrewboie) [inline kernel/smp.c]: I'd really like to see these interrupt stacks and idle thread objects, etc. expressed as an array sized by some Kconfig, rather than hard-coded in this way.
We can punt to a future enhancement if needed.

File: include/spinlock.h [hunk 27]
```diff
@@ -0,0 +1,69 @@
...
+	 * add a nesting count or something...
+	 */
+	__ASSERT(l->saved_key == key.key, "Mismatched spin lock/unlock");
+# endif
+	/* Strictly we don't need atomic_clear() here (which is an
+	 * exchange operation that returns the old value).  We are always
+	 * setting a zero and (because we hold the lock) know the existing
+	 * state won't change due to a race.  But some architectures need
+	 * a memory barrier when used like this, and we don't have a
+	 * Zephyr framework for that.
```
Comment (andrewboie) [inline include/spinlock.h]: We have a memory barrier macro which should enforce ordering of memory access:

```
include/toolchain/gcc.h
331-#endif
332-
333:#define compiler_barrier() do { \
334-	__asm__ __volatile__ ("" ::: "memory"); \
335-} while ((0))
```

Or do you need something more like an instruction barrier?

File: include/spinlock.h [hunk 28]
```diff
@@ -0,0 +1,69 @@
...
+
+static inline k_spinlock_key_t k_spin_lock(struct k_spinlock *l)
+{
+	k_spinlock_key_t k;
+
+	/* Note that we need to use the underlying arch-specific lock
+	 * implementation.  The "irq_lock()" API in SMP context is
+	 * actually a wrapper for a global spinlock!
+	 */
+	k.key = _arch_irq_lock();
```
Comment (andrewboie) [inline include/spinlock.h]: Just for my own understanding: this locks interrupts just on the current CPU or all of them in this context?
If this is global I might be being thick but I am unsure how this works.

File: arch/xtensa/soc/esp32/esp32-mp.c [hunk 29]
```diff
@@ -66,6 +68,13 @@ static void appcpu_entry2(void)
 	__asm__ volatile("wsr.VECBASE %0" : : "r"(start_rec->vecbase));
 	__asm__ volatile("rsync");
 
+	/* Set up the CPU pointer.  Really this should be xtensa arch
+	 * code, not in the ESP-32 layer
```
Comment (andrewboie) [inline arch/xtensa/soc/esp32/esp32-mp.c]: Was there some difficulty implementing it there?

File: kernel/idle.c [hunk 30]
```diff
@@ -164,6 +164,20 @@ void idle(void *unused1, void *unused2, void *unused3)
 	__idle_time_stamp = (u64_t)k_cycle_get_32();
 #endif
 
+#ifdef CONFIG_SMP
+	/* Simplified idle for non-default SMP CPUs pending driver
+	 * support.  The busy waiting is needed to prevent lock
+	 * contention.  Long term we need to wake up idle CPUs with an
+	 * IPI.
```
Comment (andrewboie) [inline kernel/idle.c]: suggest filing a user story about this and other future improvements, possibly for others to work on as the team has bandwidth.

File: include/misc/__assert.h [hunk 31]
```diff
@@ -67,6 +67,11 @@
 #endif
 #endif
 
+#ifdef CONFIG_FORCE_NO_ASSERT
+#undef __ASSERT_ON
```
Comment (andrewboie) [inline include/misc/__assert.h]: Nasty. I can only imagine how much time was sunk tracking this down.
Suggest an upstream report to gcc team if you haven't already.

File: samples/mpu/mpu_stack_guard_test/sample.yaml [hunk 32]
```diff
@@ -5,7 +5,7 @@ tests:
     tags: apps
     harness: console
     # We do not handle segfaults here
-    arch_exclude: posix riscv32 nios2
+    arch_exclude: posix riscv32 nios2 xtensa
```
Comment (andrewboie) [inline samples/mpu/mpu_stack_guard_test/sample.yaml]: This change is fine. I need to fix this filter so that it instead filters on whether the CPU has stack protection features.

File: arch/xtensa/soc/esp32/linker.ld (hunk 15 above)
Comment (andrewboie) [reply arch/xtensa/soc/esp32/linker.ld]: nothing like mixing up hump notation/CamelCase and underscore notation.
I say leave it to be consistent with the HAL.

**Review by tyrantlizard77 — APPROVED** [review]
I think we can ship this. Just some questions/suggestions.

File: kernel/Kconfig (hunk 20 above)
Comment (andyross) [reply kernel/Kconfig]: I... don't know why that ifdef is there anymore.  At a guess: because it used to hold an inline function that relied on other stuff under USE_SWTICH and is now just a vestigial function declaration.

Will fix that and the phrasing.

File: include/spinlock.h (hunk 28 above)
Comment (andyross) [reply include/spinlock.h]: Only on the current CPU, because it's in a critical section while the spinlock is held.  The other CPUs can do their own thing until/unless they want to contend for the same lock.

File: include/spinlock.h (hunk 27 above)
Comment (andyross) [reply include/spinlock.h]: That comment was sort of obtuse.  I mean a hardware barrier.  Architectures with relaxed cache coherence rules (none of ours, I'm told that older NUMA systems in the 80's did this) wouldn't expose a C assignment (i.e." locked = 0;") to the cache in such a way that other CPUs would see the lock released, so another could come along and get an inconsistent result.  Using the atomic API guarantees that we're using a correct primitive as long as the architecture does it right.

**Review by nashif — APPROVED** [review]
