### PR TITLE
drivers: mfd: infineon_mxcrypto: fix build without a child driver

### PR DESCRIPTION
**Pull request by kartben**
Lining this up as a an alternative to reverting #117103 as proposed in #117440. Will live it at the discretion of fellow release engineers which hotfix is preferred.

Also would appreciate @lauracarlesso @teburd @mcatee-infineon input here.

## Problem

Five `kit_pse84_eval` tests fail to link on main:

```
undefined reference to `Cy_Crypto_Core_Enable'
```

- `kit_pse84_eval/pse846gps2dbzc4a/m55:sample.boards.infineon.autanalog_fir_fifo`
- `kit_pse84_eval/pse846gps2dbzc4a/m55:sample.driver.adc_stream.pse84`
- `kit_pse84_eval/pse846gps2dbzc4a/m33:drivers.comparator.build.build`
- `kit_pse84_eval/pse846gps2dbzc4a/m55:drivers.comparator.build.build`
- `kit_pse84_eval/pse846gps2dbzc4a/m55:drivers.comparator.gpio_loopback.infineon_ptcomp`

## Cause

The MXCRYPTO MFD init hook calls `Cy_Crypto_Core_Enable()`, but the driver never selected the PDL sources that provide it — `cy_crypto_core_hw.c` and friends are only built when a child function driver selects one of the `USE_INFINEON_MXCRYPTO_*` symbols. On top of that, `MFD_INFINEON_MXCRYPTO` is `default y` whenever `DT_HAS_INFINEON_MXCRYPTO_ENABLED`, which on PSE84 is always (the `crypto0` node has no `status` property).

So any build that pulls in MFD for another Infineon function driver (autanalog, HPPASS, PTCOMP) while leaving crypto and entropy off gets the MFD with no PDL behind it. That has been true since the driver landed in #108439; it only became visible when #117103 dropped crypto and entropy from the board defconfigs.

## Fix

Add a hidden `USE_INFINEON_MXCRYPTO_CORE` symbol for the PDL sources shared by the TRNG, AES and SHA accelerators, selected by all three and by the MFD driver itself, so the MFD builds on its own — a driver should select the HAL sources it calls.

Then default the MFD to `y` only when a child function driver is enabled, so it is no longer instantiated (and the crypto block no longer powered up at `PRE_KERNEL_1`) in builds that have no use for it. Unlike `depends on`, this keeps `CONFIG_MFD_INFINEON_MXCRYPTO=y` working if someone enables it explicitly.

No change for configurations that already use the TRNG or the crypto driver: they select `USE_INFINEON_MXCRYPTO_CORE` through the same PDL symbols as before, and still get the MFD by default.

> [!NOTE]
> **Alternative:** #117440 reverts #117103 instead. Turns main back to green but re-hides the driver bug rather than fixing it: the MFD has been unbuildable without crypto or entropy since #108439.

### CODE REVIEW

**Comment by lauracarlesso** [comment]
First of all thanks for the prompt identification of the issue and the proposed fix. 
I clearly need to learn more about MFDs and their interconnections. I'm reviewing the proposal and running some more in depth testing on the HW.

**Comment by lauracarlesso** [comment]
Reran HW testing and confirmed this is a solid solution. 

Once this goes in the original https://github.com/zephyrproject-rtos/zephyr/pull/117103 should be reapplied once more

**Review by lauracarlesso — APPROVED** [review]

**Review by teburd — APPROVED** [review]
changes made sense when I saw them, seeing Laura has tested it out +1 from me

**Review by parthitce — APPROVED** [review]
LGTM
