### PR TITLE
USB STM32: correct compilation error for USB clean speed configuration

### PR DESCRIPTION
**Pull request by kbidani**
This pull request fix the USB speed configuration by leveraging the device tree's status, ensuring the correct full-speed setting is applied dynamically.

### CODE REVIEW

**Review by etienne-lms — COMMENTED** [review]
For commit "drivers: usb: udc_stm32: fix maximum speed for usb_fs":
~~Note the CI test failing on commit message containing line > 74 chars.~~ **-> addressed**
Since this fix**es** a previous commit, could you add a ` Fixes:` tag in the commit message: 
`Fixes: ba1ad38f998d02d624e9d2f6d1605a5fbbdf44f1`

For commit "drivers: usb: device_stm32: fix maximum speed for usb_f":
`Fixes: 01ddccdf626a2d767d4b76b648fc9e520c35ded5`

**Review by henrikbrixandersen — APPROVED** [review]

**Review by fabiobaltieri — APPROVED** [review]

File: drivers/usb/udc/udc_stm32.c [hunk 1]
```diff
@@ -50,7 +50,11 @@ LOG_MODULE_REGISTER(udc_stm32, CONFIG_UDC_DRIVER_LOG_LEVEL);
 #define HIGH_SPEED             USB_OTG_SPEED_HIGH
 #endif
 
+#if DT_HAS_COMPAT_STATUS_OKAY(st_stm32_usb)
+#define FULL_SPEED             PCD_SPEED_FULL
+#else
 #define FULL_SPEED             USB_OTG_SPEED_FULL
+#endif
```
Comment (jfischer-no) [inline drivers/usb/udc/udc_stm32.c:57]: HIGH_SPEED/FULL_SPEED is a very bad choice. I see this was introduced in https://github.com/zephyrproject-rtos/zephyr/commit/01ddccdf626a2d767d4b76b648fc9e520c35ded5. No idea how this could get enough approvals and be merged. Not that there are no macros that are already prefixed correctly with `UDC_STM32_`.

**Review by jfischer-no — CHANGES_REQUESTED** [review]

File: drivers/usb/udc/udc_stm32.c (hunk 1 above)
Comment (fabiobaltieri) [reply drivers/usb/udc/udc_stm32.c:57]: @jfischer-no so you are suggesting these should be renamed to `UDC_STM32_FULL_SPEED` and `UDC_STM32_FULL_SPEED`? Not super clear to me from your comment, trying to land this to an approvable state with few turnarounds since it break the build for load of platforms.

Comment (jfischer-no) [reply drivers/usb/udc/udc_stm32.c:57]: Yes.

> it break the build for load of platforms.

Just revert https://github.com/zephyrproject-rtos/zephyr/pull/86922

Comment (fabiobaltieri) [reply drivers/usb/udc/udc_stm32.c:57]: Thanks, I think it's fine to wait for a fix forward no need to rush a revert, just wanted to go straight to the right fix.

**Review by jfischer-no — COMMENTED** [review]
>drivers: usb: udc_stm32: fix maximum speed for usb_fs

What is `usb_fs`?

>update the definition of FULL_SPEED based on the presence of USB
and USB_DRD_FS.

What does "presence of USB" mean?

File: drivers/usb/udc/udc_stm32.c (hunk 1 above)
Comment (henrikbrixandersen) [reply drivers/usb/udc/udc_stm32.c:57]: > Just revert #86922

Given that there's still no progress on this, I suggest we perform a revert. This is breaking downstream users/CI.

Comment (jfischer-no) [reply drivers/usb/udc/udc_stm32.c:57]: Outdated, should be fixed by https://github.com/zephyrproject-rtos/zephyr/pull/88244
