### PR TITLE
Bluetooth: Host: Fix build error with observer-only config

### PR DESCRIPTION
**Pull request by jhedberg**
When building an observer-only build the check_pending_conn label would result in CI warnings/errors due to this only being a C23 feature:

scan.c:692:1: error: label at end of compound statement is a C23 extension

Turns out the #ifdefs are completely unnecessary, and the code can simply take advantage of IS_ENABLED(), which should get rid of the warning.

### CODE REVIEW

**Comment by jhedberg** [comment]
This should fix a CI build error introduced by #98411: https://github.com/zephyrproject-rtos/zephyr/actions/runs/19072848093/job/54480145733

**Review by cfriedt — APPROVED** [review]

**Review by Thalley — APPROVED** [review]

**Review by PavelVPV — APPROVED** [review]

**Review by aescolar — APPROVED** [review]
Just for info: Note adding a `;` after the label would have also done it.
