### PR TITLE
drivers: udc_stm32: only check for HS_SPEED if defined

### LINKED ISSUE #75307: udc_stm32 build failure on stm32f1 and stm32f3 (and possibly others)
**Describe the bug**

drivers/usb/udc/udc_stm32.c fails to build on f1 families since https://github.com/zephyrproject-rtos/zephyr/pull/75129 got merged:

```
zephyrproject/zephyr/drivers/usb/udc/udc_stm32.c:792:37: error: 'USBD_HS_SPEED' undeclared (first use in this function); did you mean 'USBD_FS_SPEED'?
  792 |         if (priv->pcd.Init.speed == USBD_HS_SPEED) {
      |                                     ^~~~~~~~~~~~~
      |                                     USBD_FS_SPEED
```

https://github.com/zephyrproject-rtos/zephyr/pull/75306 out with a proposed fix

**To Reproduce**
`west build -p -b stm32_min_dev@blue samples/subsys/usb/hid-keyboard`

**Expected behavior**
No build errors.

**Impact**
Somewhat of an annoyance if you want to actually use the driver, not a problem at all if you don't.

**Environment (please complete the following information):**
Linux, Zephyr SDK, the commit above

### PR DESCRIPTION
**Pull request by fabiobaltieri**
Seems like not all stm32 devices define USBD_HS_SPEED in the HAL, only check for USBD_HS_SPEED if defined. Fixes a build failure with the new stack on F1 MCUs.

Fixes https://github.com/zephyrproject-rtos/zephyr/issues/75307

### CODE REVIEW

**Review by henrikbrixandersen — APPROVED** [review]

**Comment by henrikbrixandersen** [comment]
Could you open a bug report for getting this into v3.7.0?

**Comment by fabiobaltieri** [comment]
> Could you open a bug report for getting this into v3.7.0?

Sure https://github.com/zephyrproject-rtos/zephyr/issues/75307

**Review by FRASTM — APPROVED** [review]

**Review by erwango — APPROVED** [review]

**Review by tmon-nordic — APPROVED** [review]

**Comment by jfischer-no** [comment]
@fabiobaltieri  I think this controller variant is not built by the CI. Can you add test feature `usbd` to one of these ST boards, like https://github.com/zephyrproject-rtos/zephyr/pull/74987?

**Comment by fabiobaltieri** [comment]
> @fabiobaltieri I think this controller variant is not built by the CI. Can you add test feature `usbd` to one of these ST boards, like #74987?

Sure I'll send a separate PR for that, this is fixing a build breakage would rather not hold it further.

**Review by jfischer-no — APPROVED** [review]
