### PR TITLE
cmake: compiler/xt-clang: add -Wno-unknown-warning-option

### LINKED ISSUE #84138: intel_adsp: xt-clang: unknown warning group -Wunknown-warning-option.
**Describe the bug**
intel_adsp/ace15_mtpm/sim
```
INFO    - 1) tests/lib/mem_alloc/libraries.libc.minimal.mem_alloc on intel_adsp/ace15_mtpm/sim error (Build failure)
INFO    - 2) tests/lib/mem_alloc/libraries.libc.minimal.mem_alloc_negative_testing on intel_adsp/ace15_mtpm/sim error (Build failure)
INFO    - 3) tests/lib/mem_alloc/libraries.libc.picolibc.mem_alloc on intel_adsp/ace15_mtpm/sim error (Build failure)
INFO    - 4) tests/kernel/mem_protect/stack_random/kernel.memory_protection.stack_random on intel_adsp/ace15_mtpm/sim error (Build failure)
```

intel_adsp/ace30/ptl/sim
```
INFO    - 1) tests/kernel/mem_protect/stack_random/kernel.memory_protection.stack_random on intel_adsp/ace30/ptl/sim error (Build failure)
INFO    - 2) tests/lib/mem_alloc/libraries.libc.minimal.mem_alloc on intel_adsp/ace30/ptl/sim error (Build failure)
INFO    - 3) tests/lib/mem_alloc/libraries.libc.minimal.mem_alloc_negative_testing on intel_adsp/ace30/ptl/sim error (Build failure)
INFO    - 4) tests/lib/mem_alloc/libraries.libc.picolibc.mem_alloc on intel_adsp/ace30/ptl/sim error (Build failure)
```

intel_adsp/ace20_lnl/sim
```
INFO    - 1) tests/lib/mem_alloc/libraries.libc.minimal.mem_alloc on intel_adsp/ace20_lnl/sim error (Build failure)
INFO    - 2) tests/lib/mem_alloc/libraries.libc.minimal.mem_alloc_negative_testing on intel_adsp/ace20_lnl/sim error (Build failure)
INFO    - 3) tests/lib/mem_alloc/libraries.libc.picolibc.mem_alloc on intel_adsp/ace20_lnl/sim error (Build failure)
INFO    - 4) tests/kernel/mem_protect/stack_random/kernel.memory_protection.stack_random on intel_adsp/ace20_lnl/sim error (Build failure)
```

**To Reproduce**
`twister -p intel_adsp/ace20_lnl/sim -T  tests/lib/mem_alloc/`

**Logs and console output**
`/tests/lib/mem_alloc/src/main.c:24:32: error: unknown warning group '-Walloc-size-larger-than=', ignored [-Werror,-Wunknown-warning-option]
#pragma GCC diagnostic ignored "-Walloc-size-larger-than="`

**Environment:**

 - OS: Linux
 - Toolchain: xt-clang
 - Commit SHA or Version used: v4.0.0-3486-g4cc76e8a9ae3

**Additional context**
b9d7b1bdae9b41d3a73070536821c481f77633f1 is the first bad commit
```
commit b9d7b1bdae9b41d3a73070536821c481f77633f1
Author: Tom Hughes <tomhughes@chromium.org>
Date:   Mon Jan 13 12:16:12 2025 -0800

    cmake clang/compiler_flags.cmake: Re-enable -Wunknown-warning-option

    All warnings in the code base have been resolved.

    Signed-off-by: Tom Hughes <tomhughes@chromium.org>
```

### PR DESCRIPTION
**Pull request by dcpleung**
xt-clang is usually based on older version of clang, and Zephyr main targets more recent versions. Because of this, some newer compiler flags may cause warnings where twister would mark as test being failed. To workaround that, add -Wno-unknown-warning-option to suppress those warnings.

Fixes #84138

### CODE REVIEW

**Comment by thughes** [comment]
> some newer compiler flags may cause warnings where twister would mark as test being failed.

I don't have access to `xt-clang`, but note that upstream clang doesn't have the warning that is failing in https://github.com/zephyrproject-rtos/zephyr/issues/84138. If that's the only warning, it will be fixed by https://github.com/thughes/zephyr/commit/67c43905be165b1f91e7044f8c93a2b62957195f in https://github.com/zephyrproject-rtos/zephyr/pull/84065.

**Comment by dcpleung** [comment]
In that case, I will wait a bit to see if the other PR is going forward. However, the compiler warning is blocking our internal CI and preventing us from testing on latest Zephyr.

**Review by nashif — APPROVED** [review]

**Review by tejlmand — APPROVED** [review]
