### ISSUE TITLE
ci_nxp_build_failure: twister build for frdm_mcxa577/mcxa577 fails in gen_kobject_list.py with "ConstType" object has no attribute "size"

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#113105]
### Describe the bug

`west twister` build-only runs for `tests/drivers/build_all/eeprom` fail on `frdm_mcxa577/mcxa577` on Zephyr `main` at commit `8409c1339bc491cb94ce7f7835c4fb8903a96e56`.

Both `drivers.eeprom.build` and `drivers.eeprom.emul.build` fail while generating `kobject_prebuilt_hash.gperf`. The failure comes from `scripts/build/gen_kobject_list.py` with:

`AttributeError: 'ConstType' object has no attribute 'size'`

### Regression

- [x] This is a regression.

commit bf871df8e3d02bdeedc69da8d86a948a35da6b88
Author: Peter Wang <chaoyi.wang@nxp.com>
Date:   Mon Jun 29 16:26:32 2026 +0800

    boards: arm: nxp: frdm_mcxa577: add I3C thermometer support

    Enable I3C0 on the FRDM-MCXA577 board and register the on-board
    NXP P3T1755 temperature sensor as an I3C device. The clock is
    sourced from FRO_LF_DIV with divider 1 (per the board SDK
    hardware_init reference). Pins P0_20 (SDA), P0_21 (SCL), and
    P0_2 (PUR) are configured via a new pinmux_i3c0 group (verified
    against the SDK BOARD_InitI3CPins implementation).

    Add the ambient-temp0 alias required by the thermometer sample,
    list i3c in the board's supported features, and add frdm_mcxa577
    to the sample.sensor.thermometer_i3c integration platforms.

    Tested by building samples/sensor/thermometer.

    Signed-off-by: Peter Wang <chaoyi.wang@nxp.com>

 boards/nxp/frdm_mcxa577/board.c                   |  6 ++++++
 boards/nxp/frdm_mcxa577/frdm_mcxa577-pinctrl.dtsi | 18 ++++++++++++++++++
 boards/nxp/frdm_mcxa577/frdm_mcxa577.dtsi         | 17 +++++++++++++++++
 boards/nxp/frdm_mcxa577/frdm_mcxa577.yaml         |  1 +
 samples/sensor/thermometer/sample.yaml            |  1 +

### Steps to reproduce

 ```sh
   git clone https://github.com/zephyrproject-rtos/zephyr -b main
   cd zephyr
   git checkout 8409c1339bc491cb94ce7f7835c4fb8903a96e56
   west twister -p frdm_mcxa577/mcxa577 -T tests/drivers/build_all/eeprom --build-only --inline-logs -j 12 -M all
```

### Relevant log output

```shell
FAILED: zephyr/kobject_prebuilt_hash.gperf
...
Traceback (most recent call last):
  File "/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/scripts/build/gen_kobject_list.py", line 1102, in <module>
    main()
  File "/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/scripts/build/gen_kobject_list.py", line 1065, in main
    objs = find_kobjects(elf, syms)
  File "/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/scripts/build/gen_kobject_list.py", line 655, in find_kobjects
    objs = type_obj.get_kobjects(addr)
  File "/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/scripts/build/gen_kobject_list.py", line 329, in get_kobjects
    return type_env[self.child_type].get_kobjects(addr)
  File "/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/scripts/build/gen_kobject_list.py", line 277, in get_kobjects
    objs.update(mt.get_kobjects(addr + (i * mt.size)))
AttributeError: 'ConstType' object has no attribute 'size'
ninja: build stopped: subcommand failed.
```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

OS: Linux (Jenkins)
Zephyr revision: 8409c1339bc491cb94ce7f7835c4fb8903a96e56
Zephyr version: v4.4.0-7823-g8409c1339bc4
Toolchain variant: zephyr/gnu
Zephyr SDK: 1.0.1
Python: 3.12.3
CMake: 3.28.3
West: 1.5.0
Board/target: frdm_mcxa577/mcxa577
Test path: tests/drivers/build_all/eeprom

**Comment by hakehuang** [comment]
I dug into the regression a bit more.

`git bisect` points to:

- `bf871df8e3d02bdeedc69da8d86a948a35da6b88`
- `boards: arm: nxp: frdm_mcxa577: add I3C thermometer support`

From the diff, the most likely triggering part is the new `&i3c0` block in `boards/nxp/frdm_mcxa577/frdm_mcxa577.dtsi`, especially the new child node:

```dts
&i3c0 {
	status = "okay";
	pinctrl-0 = <&pinmux_i3c0>;
	pinctrl-names = "default";

	i2c-scl-hz = <DT_FREQ_K(400)>;
	i3c-scl-hz = <DT_FREQ_M(4)>;
	i3c-od-scl-hz = <DT_FREQ_K(1500)>;

	p3t1755: p3t1755@4800000236152a0090 {
		compatible = "nxp,p3t1755";
		reg = <0x48 0x0236 0x152a0090>;
		status = "okay";
	};
};
```


My current hypothesis is:

This commit enables i3c0 and adds the p3t1755 I3C child.
The MCUX I3C driver now emits a static struct i3c_device_desc[] from DT children.
In DWARF, one of the array/member types is represented as a const-qualified type.
scripts/build/gen_kobject_list.py walks that array and hits:

objs.update(mt.get_kobjects(addr + (i * mt.size)))
where mt is ConstType.
ConstType forwards has_kobject() and get_kobjects(), but it does not expose .size, so the script crashes with:

AttributeError: 'ConstType' object has no attribute 'size'
So I think bf871df8e3d... is the first bad commit for this board, but it likely exposed an older latent bug in gen_kobject_list.py.

A minimal fix seems to be to make ConstType forward size to its wrapped child type, e.g.:

```
class ConstType:
    def __init__(self, child_type):
        self.child_type = child_type

    def __repr__(self):
        return f"<const {self.child_type}>"

    @property
    def size(self):
        return type_env[self.child_type].size

    def has_kobject(self):
        if self.child_type not in type_env:
            return False

        return type_env[self.child_type].has_kobject()

    def get_kobjects(self, addr):
        return type_env[self.child_type].get_kobjects(addr)
```
That seems consistent with the existing delegation pattern already used by ConstType.

**Comment by hakehuang** [comment]
﻿Latest occurrence from the analyzed upstream CI set:

- release: `v4.4.0-9486-gc2805ec5324d`
- platform: `frdm_mcxa577/mcxa577`
- build number: `6121`
- failing cases:
  - `tests/drivers/build_all/eeprom/drivers.eeprom.build` â€” `Build failure`
  - `tests/drivers/build_all/eeprom/drivers.eeprom.emul.build` â€” `Build failure`

**Comment by hakehuang** [comment]
Additional occurrence in retained upstream-CI results:

At `v4.4.0-11847-gc5dffcb7c9da` (commit `c5dffcb7c9da`), both
`drivers.eeprom.build` and `drivers.eeprom.emul.build` were again reported
as generic build failures on `frdm_mcxa577/mcxa577`.

The retained structured summary does not include the compiler traceback, so
this comment cannot confirm that the same `ConstType.size` failure remains.
It does show that the two affected configurations were still failing at this
later revision.
