### ISSUE TITLE
numaker_m2l31ki is currently broken

### ISSUE THREAD

**Issue by carlescufi** [zephyrproject-rtos/zephyr#70929]
The board, introduced in #70357, currently fails when building like so:
`west build -b numaker_m2l31ki samples/subsys/shell/shell_module/`

```
 /Users/carles/src/zephyr/zephyr/arch/arm/include/cortex_m/dwt.h:82:29: error: 'CoreDebug_DEMCR_TRCENA_Msk' undeclared (first use in this function); did you mean 'CoreDebug_DEMCR_DWTENA_Msk'?
   82 |         CoreDebug->DEMCR |= CoreDebug_DEMCR_TRCENA_Msk;
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                             CoreDebug_DEMCR_DWTENA_Msk
/Users/carles/src/zephyr/zephyr/arch/arm/include/cortex_m/dwt.h:82:29: note: each undeclared identifier is reported only once for each function it appears in
/Users/carles/src/zephyr/zephyr/arch/arm/include/cortex_m/dwt.h: In function 'z_arm_dwt_init_cycle_counter':
/Users/carles/src/zephyr/zephyr/arch/arm/include/cortex_m/dwt.h:100:12: error: 'DWT_Type' has no member named 'CYCCNT'
  100 |         DWT->CYCCNT = 0;

...
```
