### PR TITLE
modules: openthread: Fix alarm counter compilation

### PR DESCRIPTION
**Pull request by db00lean**
Add missing header and ifdefs to fix compilation of alarm counter for counter drivers.

### CODE REVIEW

**Comment by pdgendt** [comment]
> Add missing header and ifdefs to fix compilation of alarm counter for counter drivers.

Could you provide details of when it currently fails to compile? Ideally in a bug report, so we can backport the fix.

**Comment by db00lean** [comment]
> > Add missing header and ifdefs to fix compilation of alarm counter for counter drivers.
> 
> Could you provide details of when it currently fails to compile? Ideally in a bug report, so we can backport the fix.

```
~/zephyrproject/zephyr/modules/openthread/platform/alarm_counter.c: In function 'otPlatTimeGetXtalAccuracy':
~/zephyrproject/zephyr/modules/openthread/platform/alarm_counter.c:177:16: error: implicit declaration of function 'otPlatRadioGetCslAccuracy'; did you mean 'otPlatTimeGetXtalAccuracy'? [-Wimplicit-function-declaration]
  177 |         return otPlatRadioGetCslAccuracy(NULL);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                otPlatTimeGetXtalAccuracy
~/zephyrproject/zephyr/modules/openthread/platform/alarm_counter.c: At top level:
~/zephyrproject/zephyr/modules/openthread/platform/alarm_counter.c:31:16: warning: 'time_offset_us' defined but not used [-Wunused-variable]
   31 | static int32_t time_offset_us;
      |                ^~~~~~~~~~~~~~
```
I am working on a 802.15.4 Radio driver to enable Thread operations on Silicon Labs EFR32 chipset. I encountered the above error when attempting to build an OpenThread shell application with OPENTHREAD_CSL_RECEIVER. Both the Radio Driver and the CSL support are coming in later PRs, but I figured I would fix this first.

**Review by pdgendt — APPROVED** [review]

**Review by rlubos — APPROVED** [review]
