### PR TITLE
boards: arm: nrf52840dongle_nrf52840: Use USB CDC as default UART

### LINKED ISSUE #1599: nrf52840dongle build failure in zephyr
The `nRF52840dongle_nrf52840` board fails to build in the current 3.3 main of zephyr with the following error:

```
 file included from /tmp/aa/zephyr/include/zephyr/sys/util_macro.h:34,
                 from /tmp/aa/zephyr/include/zephyr/sys/util.h:17,
                 from /tmp/aa/zephyr/include/zephyr/devicetree.h:21,
                 from /tmp/aa/zephyr/include/zephyr/device.h:12,
                 from /tmp/aa/zephyr/include/zephyr/drivers/uart.h:26,
                 from /tmp/aa/bootloader/mcuboot/boot/zephyr/serial_adapter.c:18:
/tmp/aa/bootloader/mcuboot/boot/zephyr/serial_adapter.c: In function 'boot_uart_fifo_init':
/tmp/aa/zephyr/include/zephyr/sys/util.h:88:55: error: size of unnamed array is negative
   88 | #define ZERO_OR_COMPILE_ERROR(cond) ((int) sizeof(char[1 - 2 * !(cond)]) - 1)
      |                                                       ^
/tmp/aa/zephyr/include/zephyr/sys/util_internal.h:72:26: note: in definition of macro '__DEBRACKET'
   72 | #define __DEBRACKET(...) __VA_ARGS__
      |                          ^~~~~~~~~~~
/tmp/aa/zephyr/include/zephyr/sys/util_internal.h:64:9: note: in expansion of macro '__GET_ARG2_DEBRACKET'
   64 |         __GET_ARG2_DEBRACKET(one_or_two_args _if_code, _else_code)
      |         ^~~~~~~~~~~~~~~~~~~~
/tmp/aa/zephyr/include/zephyr/sys/util_internal.h:59:9: note: in expansion of macro '__COND_CODE'
   59 |         __COND_CODE(_XXXX##_flag, _if_1_code, _else_code)
      |         ^~~~~~~~~~~
/tmp/aa/zephyr/include/zephyr/sys/util_macro.h:177:9: note: in expansion of macro 'Z_COND_CODE_1'
  177 |         Z_COND_CODE_1(_flag, _if_1_code, _else_code)
      |         ^~~~~~~~~~~~~
/tmp/aa/zephyr/include/zephyr/device.h:277:9: note: in expansion of macro 'COND_CODE_1'
  277 |         COND_CODE_1(DT_HAS_COMPAT_STATUS_OKAY(compat),                         \
      |         ^~~~~~~~~~~
/tmp/aa/zephyr/include/zephyr/device.h:279:22: note: in expansion of macro 'ZERO_OR_COMPILE_ERROR'
  279 |                     (ZERO_OR_COMPILE_ERROR(0)))
      |                      ^~~~~~~~~~~~~~~~~~~~~
/tmp/aa/bootloader/mcuboot/boot/zephyr/serial_adapter.c:197:20: note: in expansion of macro 'DEVICE_DT_GET_ONE'
  197 |         uart_dev = DEVICE_DT_GET_ONE(zephyr_cdc_acm_uart);
      |                    ^~~~~~~~~~~~~~~~~
[75/300] Building C object zephyr/CMakeFiles/zephyr.dir/subsys/usb/device/usb_device.c.obj
ninja: build stopped: subcommand failed.
```

### LINKED ISSUE #54659: boards: arm: nrf52840dongle_nrf52840: Defaults to UART which is not connected (and mcuboot build fails)
**Describe the bug**
The `nrf52840dongle_nrf52840` board is a USB dongle, it is expected that this board communicates with a host via CDC ACM, but the default board configuration is to use the UART - there is nothing connected to the UART pins. Therefore, this should be fixed to use USB CDC as the default UART port. This is also causing the default mcuboot configuration for the board to cause a compilation failure.

**To Reproduce**
Build mcuboot for the board, observe error

**Expected behavior**
Build should work, and UART should also be visible for people using the board

**Impact**
Showstopper

**Environment (please complete the following information):**
 - Commit SHA or Version used: d56ed39e209d63f95593218f95fd04ea97d5bea6

### PR DESCRIPTION
**Pull request by nordicjm**
Enables use of the USB CDC port as the default UART for this board, as it is a USB dongle and makes more sense to use the on-board USB port instead of a disconnected/floating UART interface.

Fixes #54659
Also fixes https://github.com/mcu-tools/mcuboot/issues/1599

### CODE REVIEW

**Review by tmon-nordic — DISMISSED** [review]

**Review by anangl — DISMISSED** [review]

**Review by fabiobaltieri — DISMISSED** [review]

File: boards/arm/nrf52840dongle_nrf52840/Kconfig.defconfig [hunk 1]
```diff
@@ -24,6 +24,42 @@ config FLASH_LOAD_OFFSET
...
+	default CONSOLE
+
+config USB_DEVICE_INITIALIZE_AT_BOOT
+	default y if !MCUBOOT
+
+config SHELL_BACKEND_SERIAL_CHECK_DTR
+	default SHELL
+
+config USB_DEVICE_REMOTE_WAKEUP
+	default n
```
Comment (fabiobaltieri) [inline boards/arm/nrf52840dongle_nrf52840/Kconfig.defconfig:45]: More of a curiosity: why default this to false? The application only uses it if enabled, it's a cool demo to show that the driver has wakeup support.

Comment (nordicjm) [reply boards/arm/nrf52840dongle_nrf52840/Kconfig.defconfig]: Have removed it, might need to reintroduce it if it causes problems (was introduced on thingy53 because if the application does not use the API then it can get into a state whereby the device locks up)

**Review by fabiobaltieri — DISMISSED** [review]

**Review by anangl — DISMISSED** [review]

File: boards/arm/nrf52840dongle_nrf52840/Kconfig.defconfig (hunk 1 above)
Comment (tmon-nordic) [reply boards/arm/nrf52840dongle_nrf52840/Kconfig.defconfig]: Driver supports remote wakeup, but CDC ACM implementation does not seem to issue remote wakeup on its own. Therefore, if host suspends the device (Linux does so if there is no outgoing traffic and no incoming traffic) then the data device wants to write won't be ever picked up (it only will be picked up if host wants to send something).

At this point I would simply continue to use to workaround which is to not advertise remote wakeup (i.e. set `USB_DEVICE_REMOTE_WAKEUP` to `n`).

Comment (nordicjm) [reply boards/arm/nrf52840dongle_nrf52840/Kconfig.defconfig:45]: Have added it back in :)

**Review by tmon-nordic — APPROVED** [review]

**Review by anangl — APPROVED** [review]

File: boards/arm/nrf52840dongle_nrf52840/Kconfig.defconfig (hunk 1 above)
Comment (fabiobaltieri) [reply boards/arm/nrf52840dongle_nrf52840/Kconfig.defconfig:45]: Interesting, thanks for clarifying. Sounds like there's space for for something like a Kconfig dependency or a conditional `#warning` in the affected class drivers.

Comment (nordicjm) [reply boards/arm/nrf52840dongle_nrf52840/Kconfig.defconfig:45]: Possibly room for improvement in the USB CDC class to add support for it also I assume

**Review by fabiobaltieri — APPROVED** [review]

**Comment by stephanosio** [comment]
Is there any reason why this must go into v3.3? This is not fixing a bug and is an more of an enhancement than a stabilisation change.

**Comment by nordicjm** [comment]
The bug is that this board is useless without this change, there is no UART wired up, the reason it was ever left like this goes back to a battle I had to fight strongly for with another board

**Comment by stephanosio** [comment]
> The bug is that this board is useless without this change, there is no UART wired up,

I still think this is an enhancement because a user may wire up the UART and use it, or override the defaults to enable CDC and use it as the primary console (i.e. the board is not really _useless_ without this change; it just takes an extra step to use it).

Nevertheless, it is indeed not very sane to have something other than the USB as the default console for a _USB dongle_ and, on second thought, the benefits of merging this and having sane defaults outweigh the risk of breaking something, which I am sure is going to get fixed very promptly without much effort.

**Review by stephanosio — APPROVED** [review]
