### PR TITLE
fs: zms: fix no-cache + no-double-write

### LINKED ISSUE #95614: zms: unable to compile with `CONFIG_ZMS_LOOKUP_CACHE=n`
### Describe the bug

The ZMS subsystem no longer compiles on Zephyr v4.2 with `CONFIG_ZMS_NO_DOUBLE_WRITE=y` and `CONFIG_ZMS_LOOKUP_CACHE=n`
The `wlk_addr` variable is used but not declared under that configuration.

https://github.com/zephyrproject-rtos/zephyr/blob/663da2302b04f4afef4f4dbf48cba4566f729bc8/subsys/fs/zms/zms.c#L1487-L1495

Introduced in PR #87792 (commit 42b9b5a9d79eb38e64f0b62731ea7e513ebd7787)

### Regression

- [x] This is a regression.

### Steps to reproduce

_No response_

### Relevant log output

```shell
/home/jordan/code/workspace/zephyr/subsys/fs/zms/zms.c: In function ‘zms_write’:
/home/jordan/code/workspace/zephyr/subsys/fs/zms/zms.c:1494:9: error: ‘wlk_addr’ undeclared (first use in this function)
 1494 |         wlk_addr = fs->ate_wra;
```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

- Zephyr v4.2, main

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by JordanYates**
Fix a compiler error when `CONFIG_ZMS_NO_DOUBLE_WRITE=y` and `CONFIG_ZMS_LOOKUP_CACHE=n`.

Fixes #95614

### CODE REVIEW

File: subsys/fs/zms/zms.c [hunk 1]
```diff
@@ -1498,12 +1498,19 @@ ssize_t zms_write(struct zms_fs *fs, uint32_t id, const void *data, size_t len)
...
-	uint64_t wlk_addr = fs->lookup_cache[zms_lookup_cache_pos(id)];
+	wlk_addr = fs->lookup_cache[zms_lookup_cache_pos(id)];
 
 	if (wlk_addr == ZMS_LOOKUP_CACHE_NO_ADDR) {
-		goto no_cached_entry;
+		if (len > 0) {
+			goto no_cached_entry;
+		} else {
+			/* skip delete entry for non-existing entry */
+			return 0;
```
Comment (JordanYates) [inline subsys/fs/zms/zms.c:1512]: In my head this is not correct, since I assume it is possible for an entry to not be in the cache when the delete is requested.
However I have been unable to create a test-case that generates that behaviour, and in any case I assume that would mean the larger `wlk_addr == ZMS_LOOKUP_CACHE_NO_ADDR` conditional is also incorrect, since we couldn't assume that the entry doesn't exist just because its not in the cache.

Comment (rghaddab) [reply subsys/fs/zms/zms.c:1512]: @JordanYates this commit is incorrect since like you said, an entry could be not present in cache but exists in the storage. In this case, the delete should be written.
we can get ZMS_LOOKUP_CACHE_NO_ADDR if the cache entry has been invalidated after a sector erase.
Note that in the same cache index multiple addresses can collide, that's why even if we get ZMS_LOOKUP_CACHE_NO_ADDR, this doesn't mean that the entry doesn't exist in the storage.

Comment (JordanYates) [reply subsys/fs/zms/zms.c:1512]: Ok, the problem is that without this change, the existing implementation fails the current test suite when `CONFIG_ZMS_NO_DOUBLE_WRITES=y` and `CONFIG_ZMS_CACHE=y`. It passes with this change, which implies there is a pretty big set of potential implementation problems not being tested when caching is enabled.

Comment (rghaddab) [reply subsys/fs/zms/zms.c:1512]: @JordanYates which test is failing ?
Is it the test_zms_cache_collision ?
I will test locally to verify this

Comment (JordanYates) [reply subsys/fs/zms/zms.c:1512]: The failure is in `test_delete` on the last check. Deleting a non-existent entry makes the file system grow.
I have pushed the PR without this incorrect change, it should show the failure in CI.

File: subsys/fs/zms/zms.c [hunk 2]
```diff
@@ -1498,9 +1498,11 @@ ssize_t zms_write(struct zms_fs *fs, uint32_t id, const void *data, size_t len)
...
 #ifdef CONFIG_ZMS_NO_DOUBLE_WRITE
+	uint64_t wlk_addr;
+
 	/* find latest entry with same id */
 #ifdef CONFIG_ZMS_LOOKUP_CACHE
-	uint64_t wlk_addr = fs->lookup_cache[zms_lookup_cache_pos(id)];
+	wlk_addr = fs->lookup_cache[zms_lookup_cache_pos(id)];
 
 	if (wlk_addr == ZMS_LOOKUP_CACHE_NO_ADDR) {
 		goto no_cached_entry;
```
Comment (rghaddab) [inline subsys/fs/zms/zms.c]: @JordanYates add a commit with this fix :
```suggestion
		if (len) {
 			goto no_cached_entry;
		} else {
			/* skip delete entry for non-existing entry */
			return 0;
		}
```

File: subsys/fs/zms/zms.c (hunk 1 above)
Comment (rghaddab) [reply subsys/fs/zms/zms.c:1512]: See my comment here:
https://github.com/zephyrproject-rtos/zephyr/pull/95615/files#r2339441867

File: subsys/fs/zms/zms.c (hunk 2 above)
Comment (JordanYates) [reply subsys/fs/zms/zms.c]: Isn't that the same change you rejected in https://github.com/zephyrproject-rtos/zephyr/pull/95615#discussion_r2329563705?

Comment (rghaddab) [reply subsys/fs/zms/zms.c]: @JordanYates I tried to find that old commit but couldn't find it.
If this is the same change that you did then sorry for the confusion.
ZMS_LOOKUP_CACHE_NO_ADDR means that this cache line has never been used, which means that the ID has never been written before.

File: subsys/fs/zms/zms.c [hunk 3]
```diff
@@ -1498,12 +1498,19 @@ ssize_t zms_write(struct zms_fs *fs, uint32_t id, const void *data, size_t len)
...
+	uint64_t wlk_addr;
+
 	/* find latest entry with same id */
 #ifdef CONFIG_ZMS_LOOKUP_CACHE
-	uint64_t wlk_addr = fs->lookup_cache[zms_lookup_cache_pos(id)];
+	wlk_addr = fs->lookup_cache[zms_lookup_cache_pos(id)];
 
 	if (wlk_addr == ZMS_LOOKUP_CACHE_NO_ADDR) {
-		goto no_cached_entry;
+		if (len == 0) {
```
Comment (rghaddab) [inline subsys/fs/zms/zms.c]: Actually this is the opposite.
we should continue to no_cached_entry when it is an entry with some data to write.
Otherwise we return
```suggestion
		if (len) {
```

**Review by rghaddab — APPROVED** [review]

**Comment by rghaddab** [comment]
@de-nordic can you have a quick look at this

**Review by de-nordic — APPROVED** [review]
