### ISSUE TITLE
drivers.gpio.build: mimx93_evk_a55 : build failure

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#68399]
**Describe the bug**
drivers.gpio.builduild failure in mimx93_evk_a55

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?
 mimx93_evk_a55
 - What have you tried to diagnose or workaround this issue?
 - Is this a regression? If yes, have you been able to "git bisect" it to a
   specific commit?
twister add float point check

**To Reproduce**
tests/drivers/build_all/gpio
1. west build -b mimx93_evk_a55 

**Expected behavior**
build pass

**Impact**
CI

**Logs and console output**

```

zephyr/drivers/gpio/gpio_bd8lb600fs.c:79:25: error: format '%i' expects argument of type 'int', but argument 3 has type 'size_t' {aka 'long unsigned int'} [-Werror=format=]
   79 |                 LOG_DBG("%s: configuration for instance %i: %04X (position %i)",
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   80 |                         dev->name,
   81 |                         j,
      |                         ~
      |                         |
      |                         size_t {aka long unsigned int}
/home/jenkins/agent/workspace/github_zephyr_build_ci_imx-a/zephyr/include/zephyr/logging/log_core.h:275:42: note: in definition of macro 'Z_LOG2'
  275 |                 z_log_printf_arg_checker(__VA_ARGS__); \
      |                                          ^~~~~~~~~~~
/home/jenkins/agent/workspace/github_zephyr_build_ci_imx-a/zephyr/include/zephyr/logging/log.h:73:25: note: in expansion of macro 'Z_LOG'
   73 | #define LOG_DBG(...)    Z_LOG(LOG_LEVEL_DBG, __VA_ARGS__)
      |                         ^~~~~
/home/jenkins/agent/workspace/github_zephyr_build_ci_imx-a/zephyr/drivers/gpio/gpio_bd8lb600fs.c:79:17: note: in expansion of macro 'LOG_DBG'
   79 |                 LOG_DBG("%s: configuration for instance %i: %04X (position %i)",
      |                 ^~~~~~~
/home/jenkins/agent/workspace/github_zephyr_build_ci_imx-a/zephyr/drivers/gpio/gpio_bd8lb600fs.c:79:58: note: format string is defined here
   79 |                 LOG_DBG("%s: configuration for instance %i: %04X (position %i)",
      |                                                         ~^
      |                                                          |
      |                                                          int
      |                                                         %li
cc1: all warnings being treated as errors
```

**Environment (please complete the following information):**
 - OS: (e.g. Linux,, )
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used: 6cb98162b7b40041a9f9a5cb638faf371fcdfa7e
