### PR TITLE
riscv: fix compilation error when building OOT SoC with custom `__soc_is_irq`

### PR DESCRIPTION
**Pull request by ycsin**
Fixes the following compilation error when building OOT RISCV SOC on v3.7.0 (update from v3.5.0):

```
/data/users/ycsin/firmware/zephyr/modules/soc_latest/soc/meta/common/soc_irq.S: Assembler messages:
/data/users/ycsin/firmware/zephyr/modules/soc_latest/soc/meta/common/soc_irq.S:36: Error: illegal operands `li t1,BIT64(63U)'
```

This is likely due to changes introduced in #67829

### CODE REVIEW

File: include/zephyr/sys/util_macro.h [hunk 1]
```diff
@@ -43,10 +43,16 @@ extern "C" {
  */
 #define BIT(n)  (1UL << (n))
 #endif
-#endif
+#endif /* BIT */
 
+#ifndef BIT64
```
Comment (gmarull) [inline include/zephyr/sys/util_macro.h:48]: why is extra ifdeffery needed?

Comment (ycsin) [reply include/zephyr/sys/util_macro.h:48]: So that it is same as `BIT()`, but this commit doesn't seem necessary, will drop it.

Comment (gmarull) [reply include/zephyr/sys/util_macro.h]: I guess it exists for BIT due to some HALs polluting the namespace. However, the version without `ULL` prefix is likely needed for asm?

Comment (ycsin) [reply include/zephyr/sys/util_macro.h]: > I guess it exists for BIT due to some HALs polluting the namespace. However, the version without `ULL` prefix is likely needed for asm?

Had that impression as well, but my application continue to build without the `ULL` prefix

**Review by gmarull — APPROVED** [review]

**Review by fkokosinski — APPROVED** [review]

**Comment by aescolar** [comment]
@ycsin Please note that priority labels do not apply to pull requests. Neither does the regression label.
There is also no point of adding the size:XS label by hand.
If you want the PR to be related to a bug with regression and priority information, please create a bug report and link it to the PR.
