### ISSUE TITLE
tests/drivers/counter/counter_basic_api fails to build on mimxrt685_evk_cm33

### ISSUE THREAD

**Issue by danieldegrasse** [zephyrproject-rtos/zephyr#51185]
**Describe the bug**
`counter_basic_api` test fails to build on `mimxrt685_evk_cm33`. The issue appears to be related to some necessary header files no longer being included, as the failure was introduced by a6a4400b8621bc618c6056

**Logs and console output**
Snippet of build error, showing undefined macro for `IRQ_CONNECT`:
```
/home/danieldegrasse/zephyrproject/zephyr/drivers/counter/counter_mcux_lpc_rtc.c:244:17: warning: implicit declaration of function 'IRQ_CONNECT' [-Wimplicit-function-declaration]
  244 |                 IRQ_CONNECT(DT_INST_IRQN(id),
```

**Comment by laurenmurphyx64** [comment]
Hi! This may have been fixed by #51325 recently merged into the tree; try rebasing and let us know if the issue is resolved.
