### ISSUE TITLE
drivers: hwinfo: Compile fails on STM32 platforms with dual-core variants

### ISSUE THREAD

**Issue by KloudJack** [zephyrproject-rtos/zephyr#56375]
### Describe the bug

Since #55993 has been merged, the `hwinfo` driver fails to compile on STM32 platforms with dual-core variants.

Specifically this occurs on the following platforms:

- STM32H7
- STM32MP1
- STM32WB
- STM32WL

As the HAL for these platforms have separate per-core  `LL_PWR_IsActiveFlag_SB` and `LL_PWR_ClearFlag_SB` methods.
(named `_C1SB`/`_C2SB`, respectively)

### To Reproduce

1. Run the `hwinfo` unit tests for a board based on one of the 4 platforms listed above, e.g.:

    ```sh
    west twister -p nucleo_wb55rg -s tests/drivers/hwinfo/api/drivers.hwinfo.api
    ```
2. Observe unit test failure

### Expected behavior

Unit tests pass.

### Impact

`hwinfo` driver fails to compile on the mentioned platforms.

PRs for these platforms will fail their workflows due to this issue. [Example](https://github.com/zephyrproject-rtos/zephyr/pull/56330/checks?check_run_id=12397402575).

### Logs and console output

```c
zephyr/drivers/hwinfo/hwinfo_stm32.c: In function 'z_impl_hwinfo_get_reset_cause':
zephyr/drivers/hwinfo/hwinfo_stm32.c:117:13: warning: implicit declaration of function 'LL_PWR_IsActiveFlag_SB'; did you mean 'LL_PWR_IsActiveFlag_C1SB'? [-Wimplicit-function-declaration]
  117 |         if (LL_PWR_IsActiveFlag_SB()) {
      |             ^~~~~~~~~~~~~~~~~~~~~~
      |             LL_PWR_IsActiveFlag_C1SB
zephyr/drivers/hwinfo/hwinfo_stm32.c: In function 'z_impl_hwinfo_clear_reset_cause':
zephyr/drivers/hwinfo/hwinfo_stm32.c:131:9: warning: implicit declaration of function 'LL_PWR_ClearFlag_SB'; did you mean 'LL_PWR_ClearFlag_WU'? [-Wimplicit-function-declaration]
  131 |         LL_PWR_ClearFlag_SB();
      |         ^~~~~~~~~~~~~~~~~~~
      |         LL_PWR_ClearFlag_WU
```

### Environment:
 - OS: Arch Linux, kernel 6.2.8-arch1-1
 - Toolchain: Zephyr-SDK 0.16.0
 - Commit: 70f9acd9269b61b7311f9f8050d3b88832e8020f

**Comment by KloudJack** [comment]
@Desvauxm-st @FRASTM @gautierg-st 

Unfortunately I'm not familiar enough with the integration of the STM32 HALs in Zephyr to devise a fix to this issue. 
I'd glady create a PR with some guidance though.

I suppose `#ifdef` directives excluding 4 platforms would be too hackish :wink:

Perhaps the mentioned PR should be reverted until the appropriate methods have been created for the affected platforms and that change has found its way into [hal_stm32](https://github.com/zephyrproject-rtos/hal_stm32)?

**Comment by KloudJack** [comment]
After further investigation into the STM32 HALs affected, I've noticed that the `LL_PWR_IsActiveFlag` and `LL_PWR_ClearFlag` methods for standby and stop states are only omitted on platforms with dual-core variants, as each core will have its own standby/stop status and reset register.

IMHO the usage of these methods introduced in #55993 needs to be reworked to consider platforms with more than one core, and discern which core is currently running said code.
Additionally the appropriate `LL_PWR` methods for per-core standby and stop state retrieval/reset will need to be added to the respective STM32CubeXX codebases and downstreamed to [hal_stm32](https://github.com/zephyrproject-rtos/hal_stm32).

I'm creating a PR to revert #55993 until this is implemented.
