### ISSUE TITLE
tests: sample.net.pkt_filter: build error with undefined reference to npf_eth_vlan_type_match

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#88752]
**Describe the bug**

sample.net.pkt_filter build failure

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using
```
  - imx95_evk/mimx9596/m7
  - mimxrt1180_evk/mimxrt1189/cm33
 ```
 - What have you tried to diagnose or workaround this issue?
    git bisect
 - Is this a regression? If yes, have you been able to "git bisect" it to a
   specific commit?

```
3064c7b11dcde3052ad54af3462eca4f4fe31d34
samples: net: pkt_filter: Add a sample to demo packet filtering

Add a network packet filtering sample to show how the packet
filtering can be used.

Signed-off-by: Jukka Rissanen <jukka.rissanen@nordicsemi.no>
```

**To Reproduce**

```
scripts/twister -p mimxrt1180_evk/mimxrt1189/cm33  -T samples/net/pkt_filter --build-only
```

**Expected behavior**

build pass

**Impact**

net_pkg filter

**Logs and console output**

```
[235/249] Building C object zephyr/kernel/CMakeFiles/kernel.dir/timer.c.obj[236/249] Building C object zephyr/kernel/CMakeFiles/kernel.dir/timeout.c.obj[237/249] Building C object zephyr/kernel/CMakeFiles/kernel.dir/mempool.c.obj[238/249] Building C object zephyr/kernel/CMakeFiles/kernel.dir/poll.c.obj[239/249] Building C object zephyr/kernel/CMakeFiles/kernel.dir/sched.c.obj[240/249] Building C object zephyr/subsys/net/ip/CMakeFiles/subsys__net__ip.dir/tcp.c.obj[241/249] Building C object zephyr/kernel/CMakeFiles/kernel.dir/dynamic_disabled.c.obj[242/249] Linking C static library zephyr/subsys/net/ip/libsubsys__net__ip.a[243/249] Linking C static library zephyr/kernel/libkernel.a[244/249] Linking C executable zephyr/zephyr_pre0.elfFAILED: zephyr/zephyr_pre0.elf zephyr/zephyr_pre0.map /home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/twister-out/mimxrt1180_evk_mimxrt1189_cm33/zephyr/samples/net/pkt_filter/sample.net.pkt_filter/zephyr/zephyr_pre0.map l_nxp/libmodules__hal_nxp.a -Wl,--no-whole-archive zephyr/kernel/libkernel.a -L/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/twister-out/mimxrt1180_evk_mimxrt1189_cm33/zephyr/samples/net/pkt_filter/sample.net.pkt_filter/zephyr zephyr/arch/common/libisr_tables.a -Wl,--fatal-warnings -mcpu=cortex-m33 -mthumb -mabi=aapcs -mfp16-format=ieee -mtp=soft -fuse-ld=bfd -Wl,--gc-sections -Wl,--build-id=none -Wl,--sort-common=descending -Wl,--sort-section=alignment -Wl,-u,_OffsetAbsSyms -Wl,-u,_ConfigAbsSyms -nostdlib -static -Wl,-X -Wl,-N -Wl,--orphan-handling=warn -Wl,-no-pie -specs=picolibc.specs -DPICOLIBC_DOUBLE_PRINTF_SCANF -L"/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/thumb/v8-m.main/nofp" -lc -lgcc && cd /home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/twister-out/mimxrt1180_evk_mimxrt1189_cm33/zephyr/samples/net/pkt_filter/sample.net.pkt_filter/zephyr && /usr/bin/cmake -E true/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: app/libapp.a(main.c.obj): in function `init_app':/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/samples/net/pkt_filter/src/main.c:127: undefined reference to `_net_l2_ETHERNET'/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: app/libapp.a(main.c.obj):(.data.arp_packet+0x0): undefined reference to `npf_eth_vlan_type_match'/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: app/libapp.a(main.c.obj):(.data.ipv4_packet2+0x0): undefined reference to `npf_eth_vlan_type_match'/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd: app/libapp.a(main.c.obj):(.data.ipv4_packet1+0x0): undefined reference to `npf_eth_vlan_type_match'collect2: error: ld returned 1 exit statusninja: build stopped: subcommand failed.
```

**Environment (please complete the following information):**

 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used: v4.1.0-2563-g90cd350c5a4a
