### PR TITLE
soc: nxp: lpc55xxx: fix dependencies for SOC_FLASH_MCUX

### LINKED ISSUE #79576: Dependencies for `SOC_FLASH_MCUX` are incorrect on LPC55xxx platforms
**Describe the bug**
Samples enabling `CONFIG_FLASH` fail to build on the LPC55S69 CPU1 target, due to the IAP flash driver being enabled when it should not be.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?
   ` lpcxpresso55s69/lpc55s69/cpu1`
 - Is this a regression? If yes, have you been able to "git bisect" it to a
   specific commit?
   Yes, the introduction of HWMv2

**To Reproduce**

**Expected behavior**
Build should pass

**Impact**
Blocking CI on #72102

**Logs and console output**
```
 /__w/zephyr/zephyr/drivers/flash/soc_flash_mcux.c:41:2: error: #error No matching compatible for soc_flash_mcux.c
   41 | #error No matching compatible for soc_flash_mcux.c
      |  ^~~~~
/__w/zephyr/zephyr/drivers/flash/soc_flash_mcux.c:53:10: fatal error: fsl_flash.h: No such file or directory
   53 | #include "fsl_flash.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
```
**Environment (please complete the following information):**

 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA or Version used: d7ab4f25e13f975a9c3 (main)

### PR DESCRIPTION
**Pull request by danieldegrasse**
SOC_FLASH_MCUX has additional dependencies for LPC55xxx CPUs, due to the fact that the flash should be disabled when executing in nonsecure mode.

Since the merge of HWMv2, this dependency has been set incorrectly at the SOC level, resulting in the IAP flash driver being enabled when targeting CPU1, which is incorrect. Fix the Kconfig dependency to resolve this issue.

Fixes #79576

### CODE REVIEW

**Review by decsny — APPROVED** [review]
commit message could be more clear about why it isn't meant to be enabled for cpu1

File: soc/nxp/lpc/lpc55xxx/Kconfig.defconfig [hunk 1]
```diff
@@ -53,7 +53,7 @@ config CAN_MCUX_MCAN
 
 endif # SOC_LPC55S16
 
-if SOC_LPC55S69
+if SOC_LPC55S69_CPU0
```
Comment (butok) [inline soc/nxp/lpc/lpc55xxx/Kconfig.defconfig:56]: Should CPU0 support the flash in multicore applications?

**Comment by butok** [comment]
> due to the fact that the flash should be disabled when executing in nonsecure mode.
Fine for TFM/ns case. 
But for a multicore use case (without TFM/ns) both CPU0 and CPU1 should have access the Flash ROM API. Right?

**Comment by danieldegrasse** [comment]
> But for a multicore use case (without TFM/ns) both CPU0 and CPU1 should have access the Flash ROM API. Right?

I believe so. As far as I know, this isn't a technical restriction, we just don't have flash support enabled for CPU1 right now, so the Kconfig dependency here was incorrect.

**Review by EmilioCBen — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]
