### PR TITLE
Typecheck objects passed to K_POLL_EVENT_INITIALIZER

### PR DESCRIPTION
**Pull request by arbrauns**
Too many times have I accidentally passed a `struct k_sem **` or similar. Thankfully modern C can help us here.

### CODE REVIEW

File: include/zephyr/toolchain/common.h [hunk 1]
```diff
@@ -175,6 +175,10 @@
 	}
 #endif
 
+// Same as BUILD_ASSERT(), but evaluates to an expression of value 0. Useful in macros.
+#define BUILD_ASSERT_EXPR(EXPR, MSG...) \
+	(0 * sizeof(struct { BUILD_ASSERT(EXPR, MSG); int dummy; }))
```
Comment (andyross) [inline include/zephyr/toolchain/common.h:180]: As mentioned elsewhere, it's probably even more useful for this to take a parameter to which it will evaluate if it doesn't blow up.

**Review by andyross — COMMENTED** [review]
Some notes.  Seems clever.

File: include/zephyr/kernel.h [hunk 2]
```diff
@@ -5698,13 +5698,35 @@ struct k_poll_event {
 	};
 };
 
+#define K_POLL_ASSERT_VALID_OBJECT(_event_type, _event_obj) BUILD_ASSERT_EXPR( \
+	(_event_type) == K_POLL_TYPE_IGNORE || (\
+		(_event_type) == K_POLL_TYPE_SIGNAL && \
+		__builtin_types_compatible_p(__typeof__(_event_obj), struct k_poll_signal *)\
```
[the remark this answers is not in the document]
Comment (andyross) [reply include/zephyr/kernel.h:5704]: Heh, actually it looks like we already have it, see SAME_TYPE(): https://github.com/zephyrproject-rtos/zephyr/blob/main/include/zephyr/sys/util.h#L233

(Which is actually a poor name for this, as it accepts promotions and automatic conversions too)

[the remark this answers is not in the document]
Comment (arbrauns) [reply include/zephyr/kernel.h]: Now uses `SAME_TYPE()` and guards against C++.

File: include/zephyr/kernel.h [hunk 3]
```diff
@@ -5698,13 +5698,35 @@ struct k_poll_event {
...
+	"Invalid object for k_poll")
+
 #define K_POLL_EVENT_INITIALIZER(_event_type, _event_mode, _event_obj) \
 	{ \
 	.poller = NULL, \
 	.type = _event_type, \
 	.state = K_POLL_STATE_NOT_READY, \
 	.mode = _event_mode, \
-	.unused = 0, \
+	.unused = 0 + K_POLL_ASSERT_VALID_OBJECT(_event_type, _event_obj), \
```
[the remark this answers is not in the document]
Comment (andyross) [reply include/zephyr/kernel.h]: GCC statement expressions[1] are the normal tool for that.  `({ STATEMENT_A; STATEMENT_B; })` executes A and then B, but then evaluates syntactically as the result of B.

[1] An extension we do allow, because it's so pervasively supported and incredibly useful.  See https://gcc.gnu.org/onlinedocs/gcc/Statement-Exprs.html

**Comment by npitre** [comment]
You are missing `K_POLL_TYPE_FIFO_DATA_AVAILABLE` and have
`K_POLL_TYPE_DATA_AVAILABLE` twice.

I think this can be made much simpler while fully leveraging the compiler's
type checking ability, and also be C++ compatible. Consider this:

```
diff --git a/include/zephyr/kernel.h b/include/zephyr/kernel.h
index 32c554c159d..f4fb7765933 100644
--- a/include/zephyr/kernel.h
+++ b/include/zephyr/kernel.h
@@ -5686,14 +5686,14 @@ struct k_poll_event {
 
 	/** per-type data */
 	union {
-		void *obj;
-		struct k_poll_signal *signal;
-		struct k_sem *sem;
-		struct k_fifo *fifo;
-		struct k_queue *queue;
-		struct k_msgq *msgq;
+		void *obj, *typed_K_POLL_TYPE_IGNORE;
+		struct k_poll_signal *signal, *typed_K_POLL_TYPE_SIGNAL;
+		struct k_sem *sem, *typed_K_POLL_TYPE_SEM_AVAILABLE;
+		struct k_fifo *fifo, *typed_K_POLL_TYPE_FIFO_DATA_AVAILABLE;
+		struct k_queue *queue, *typed_K_POLL_TYPE_DATA_AVAILABLE;
+		struct k_msgq *msgq, *typed_K_POLL_TYPE_MSGQ_DATA_AVAILABLE;
 #ifdef CONFIG_PIPES
-		struct k_pipe *pipe;
+		struct k_pipe *pipe, *typed_K_POLL_TYPE_PIPE_DATA_AVAILABLE;
 #endif
 	};
 };
@@ -5706,7 +5706,7 @@ struct k_poll_event {
 	.mode = _event_mode, \
 	.unused = 0, \
 	{ \
-		.obj = _event_obj, \
+		.typed_##_event_type = _event_obj, \
 	}, \
 	}
 
@@ -5719,7 +5719,7 @@ struct k_poll_event {
 	.mode = _event_mode, \
 	.unused = 0, \
 	{ \
-		.obj = _event_obj, \
+		.typed_##_event_type = _event_obj, \
 	}, \
 	}
 
```

This even trips an existing test that does this:

```
        struct k_poll_event bad_events2[] = {
                K_POLL_EVENT_INITIALIZER(0xFU,
                                         K_POLL_MODE_NOTIFY_ONLY,
                                         &no_wait_sem),
        };
```

And I think that's a good thing. Initializers shouldn't be used with random
literals. The test could simply be modified to work around the initializer
in this particular case.

**Comment by cfriedt** [comment]
Sort of leaning toward Nico's solution and allowing the compiler to better do its job.

File: include/zephyr/kernel.h (hunk 3 above)
[the remark this answers is not in the document]
Comment (arbrauns) [reply include/zephyr/kernel.h]: Those aren't allowed outside of function scopes, which would be a weird restriction to impose.

**Comment by arbrauns** [comment]
> You are missing K_POLL_TYPE_FIFO_DATA_AVAILABLE and have
K_POLL_TYPE_DATA_AVAILABLE twice.

Those are the same thing.

Anyway, I've adopted your solution, it is nicer indeed.

**Review by npitre — DISMISSED** [review]

File: include/zephyr/kernel.h [hunk 4]
```diff
@@ -5686,14 +5686,14 @@ struct k_poll_event {
...
-		struct k_sem *sem;
-		struct k_fifo *fifo;
-		struct k_queue *queue;
-		struct k_msgq *msgq;
+		void *obj, *typed_K_POLL_TYPE_IGNORE;
+		struct k_poll_signal *signal, *typed_K_POLL_TYPE_SIGNAL;
+		struct k_sem *sem, *typed_K_POLL_TYPE_SEM_AVAILABLE;
+		struct k_fifo *fifo, *typed_K_POLL_TYPE_FIFO_DATA_AVAILABLE;
+		struct k_queue *queue, *typed_K_POLL_TYPE_DATA_AVAILABLE;
+		struct k_msgq *msgq, *typed_K_POLL_TYPE_MSGQ_DATA_AVAILABLE;
```
Comment (andyross) [inline include/zephyr/kernel.h:5694]: Might not be the worst thing to have a comment here to the effect of  " the 'typed_' fields exist for the benefit of the initializers below that take the type symbols as an argument" or whatever.

**Review by andyross — DISMISSED** [review]
Very clean

**Review by cfriedt — APPROVED** [review]

**Review by npitre — APPROVED** [review]

**Comment by kartben** [comment]
@andyross need you to re-approve (I know you love this :)) thanks!

**Review by andyross — APPROVED** [review]
Fell behind on reviews, but still +1

**Comment by evgeniy-paltsev** [comment]
This breaks existing Zephyr tests.


For example`tests/kernel/poll`:
How to reproduce:

```
west build -b qemu_x86 tests/kernel/poll -T kernel.poll
```

```
FAILED: CMakeFiles/app.dir/src/test_poll.c.obj 
In file included from /zephyr/subsys/testsuite/ztest/include/zephyr/ztest.h:40,
                 from /zephyr/tests/kernel/poll/src/test_poll.c:7:
/zephyr/tests/kernel/poll/src/test_poll.c: In function 'poll_api_1cpu_test_poll_no_wait':
/zephyr/include/zephyr/kernel.h:5757:18: error: 'union <anonymous>' has no member named 'typed_0xFU'
 5757 |                 .typed_##_event_type = _event_obj, \
      |                  ^~~~~~
/zephyr/tests/kernel/poll/src/test_poll.c:119:17: note: in expansion of macro 'K_POLL_EVENT_INITIALIZER'
  119 |                 K_POLL_EVENT_INITIALIZER(0xFU,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~
[23/144] Building C object zephyr/CMakeFiles/zephyr.dir/lib/os/cbprintf_packaged.c.obj
```

@jhedberg can we revert it?

**Comment by npitre** [comment]
Better yet, let's fix the test instead.
The test is definitively wrong.

**Comment by npitre** [comment]
Failing test fixed in PR #74126.
