### PR TITLE
kernel: ensure System Power Managment enables Tickless Idle.

### PR DESCRIPTION
**Pull request by mnkp**
Zephyr's Power Management documentation is ambiguous on the issue however, enabling the power management system seems to makes sense only if kernel operates in Tickless Idle mode. That's also how the source code was written. 

Currently enabling SYS_POWER_MANAGEMENT without enabling TICKLESS_IDLE results in a linker error:
```
zephyr/kernel/libkernel.a(idle.c.obj): In function `_sys_power_save_idle_exit':
zephyr/kernel/idle.c:115: undefined reference to `z_clock_idle_exit'
collect2: error: ld returned 1 exit status
```
The z_clock_idle_exit function is compiled only if TICKLESS_IDLE Kconfig option is enabled. The example was generated for ARM architecture but remaining architectures are also affected.

This patch selects TICKLESS_IDLE option whenever SYS_POWER_MANAGEMENT is enabled. Also, it removes a dependency between DEVICE_POWER_MANAGEMENT and SYS_POWER_MANAGEMENT as both features are completely independent. This ensures that device power management can be used without tickles idle mode.

The `CONFIG_TICKLESS_IDLE=y` was removed from all the *.conf files where SYS_POWER_MANAGEMENT is already enabled.

Fixes: #11046

### CODE REVIEW

**Review by andyross — APPROVED** [review]
Makes sense.  Long term we probably want to remove TICKLESS_IDLE as a configurable.  Really this is a feature of the driver now, the kernel doesn't care whether it's happening or not.  And in fact all of the new drivers support it always, even if you don't ask for it.

File: kernel/Kconfig.power_mgmt [hunk 1]
```diff
@@ -59,6 +60,8 @@ config SYS_POWER_DEEP_SLEEP
 	  from the reset vector same as cold boot. The interface allows
 	  restoration of states that were saved at the time of suspend.
 
+endif # SYS_POWER_MANAGEMENT
```
Comment (nashif) [inline kernel/Kconfig.power_mgmt]: Moving this up here is unrelated to the commit, what is the reasoning? device pm can now work on its own without system power management?

**Review by nashif — CHANGES_REQUESTED** [review]

**Review by nniranjhana — COMMENTED** [review]
LGTM, although we probably want to modify the doc to reflect these changes as well.

File: kernel/Kconfig.power_mgmt (hunk 1 above)
Comment (mnkp) [reply kernel/Kconfig.power_mgmt]: > Moving this up here is unrelated to the commit, what is the reasoning?

Without the change any project using device power management would automatically be configured in tickles idle mode. That's because enabling device power management would only be possible if system power management is enabled. Since these two features are independent we allow projects to use device power management without tickles idle as it was the case before.

> device pm can now work on its own without system power management?

As far as I can tell looking at the source code device power management is independent from system power management. If it is not the case then this change should not be performed.

**Comment by mnkp** [comment]
I'll add changes to the documentation in this commit.

**Review by spoorthik — APPROVED** [review]

File: doc/subsystems/power_management.rst [hunk 2]
```diff
@@ -92,9 +92,11 @@ System Power Management
 
 This consists of the hook functions that the power management subsystem calls
 when the kernel enters and exits the idle state, in other words, when the kernel
-has nothing to schedule. This section provides a general overview of the hook
-functions. Refer to :ref:`power_management_api` for the detailed description of
-the APIs.
+has nothing to schedule. Enabling system power management compels Zephyr kernel
+scheduler to work in tickless idle mode.
```
Comment (dbkinder) [inline doc/subsystems/power_management.rst]:
```suggestion
scheduler to work in tickless idle mode (see :option:`CONFIG_TICKLESS_IDLE`).
```

**Review by dbkinder — DISMISSED** [review]

**Comment by mnkp** [comment]
I have a quick question: now that I've added the requested change should I mark the relevant conversation/change request as resolved or wait for the request's author to mark it as resolved? Should I add a short comment like "Fixed" to let the request's author know that this particular issue was taken care of? We are using force push and it's not always easy to see what the changes in a new version are. I couldn't find anything in "Contribution Guidelines" and somehow never heard what the recommended flow is.

**Review by nashif — APPROVED** [review]
