### ISSUE TITLE
Build regression for intel_ish_5_8_0/intel_ish_5_8_0 and others and posix

### ISSUE THREAD

**Issue by fabiobaltieri** [zephyrproject-rtos/zephyr#85500]
**Describe the bug**

This is for a build regression for intel ISH platforms:

```
$ west build -p -b intel_ish_5_8_0/intel_ish_5_8_0 samples/posix/env
...
zephyr/arch/x86/core/prep_c.c:40: undefined reference to `z_x86_mmu_init'
zephyr/subsys/demand_paging/eviction/nru.c:39: undefined reference to `arch_page_info_get'
zephyr/subsys/demand_paging/eviction/nru.c:70: undefined reference to `arch_page_info_get'
...few more...
```

and more. Seems like the regression has been introduced in 0ac931b38647d875693a8b881fae0319692562a6 (@cfriedt), reverting the commit fixex the problem.

Not sure how to move forward, enabling X86_MMU causes a different build failure, those options are "select" so they can't be unselected.

Could you folks take a look?

**To Reproduce**
See above

**Expected behavior**
The build builds

**Impact**
Broken tests in the weekly run Probably POSIX can't be used for the board?

**Environment (please complete the following information):**
Zephyr SDK 0.16.8, Linux, baced6d315f

**Comment by nashif** [comment]
duplicate of #85305
