### PR TITLE
logging: Improve handling of long packages

### PR DESCRIPTION
**Pull request by nordic-krch**
Package length in a message was stored on 10 bits which limited packages to 1023 bytes. If longer package was used (e.g. `LOG_INF("%s", extremely_long_string);`) application was asserting.

Added warning message in that case with message dropping (to prevent assert).

Additionally, increased field to 11 bits since there was one spare bit in 32 bit long log message descriptor.

### CODE REVIEW

**Review by dcpleung — DISMISSED** [review]

**Review by dcpleung — DISMISSED** [review]

File: subsys/logging/log_msg.c [hunk 1]
```diff
@@ -63,10 +63,12 @@ void z_impl_z_log_msg_static_create(const void *source,
...
 
-		if (len > Z_LOG_MSG_MAX_PACKAGE)
-		{
-			LOG_WRN("Log message dropped because it exceeds current limitation (%u)",
-				(uint32_t)Z_LOG_MSG_MAX_PACKAGE);
+		if (len > Z_LOG_MSG_MAX_PACKAGE) {
+			struct cbprintf_package_hdr_ext *pkg =
+				(struct cbprintf_package_hdr_ext *)package;
+
+			LOG_WRN("Message (\"%s\") dropped because it exceeds size limitation (%u)",
```
Comment (mbolivar-nordic) [inline subsys/logging/log_msg.c:70]: Is it possible that the format string itself is too long? If so, what would happen here?

Comment (nordic-krch) [reply subsys/logging/log_msg.c:70]: Format string is in rodata so it is not included in the package.

**Review by dcpleung — DISMISSED** [review]

File: subsys/logging/log_msg.c (hunk 1 above)
Comment (mbolivar-nordic) [reply subsys/logging/log_msg.c:70]: OK, thanks for clarifying

**Comment by mbolivar-nordic** [comment]
Rebased to see if the documentation build failure was temporary

**Review by mbolivar-nordic — DISMISSED** [review]

**Comment by mbolivar-nordic** [comment]
@nordic-krch have a look to see if you can reproduce the doc failure locally

File: subsys/logging/log_msg.c (hunk 1 above)
Comment (tmon-nordic) [reply subsys/logging/log_msg.c:70]: @nordic-krch But how does being in rodata is changing anything? What am I missing? The `%s` formatter is being used here and thus if the `pkg->fmt` is larger than the limit, would it trigger the issue? Could this lead to endless recursive call?

**Comment by nordic-krch** [comment]
@mbolivar-nordic i tried `make html` locally and it gives same result for `main` and PR. Is there some python post-processing going there since there was some regex failure?

**Comment by mbolivar-nordic** [comment]
@nordic-krch

> i tried `make html` locally and it gives same result for `main` and PR.

Are you sure? Try reproducing with exactly the build steps used in CI:

```
cd zephyr/doc
cmake -GNinja -B_build -S. -DDOC_TAG=development -DSPHINXOPTS="-q -W -t publish" -DLATEXMKOPTS="-halt-on-error -no-shell-escape" -DDT_TURBO_MODE=1
cmake --build _build --target html
```

When I did that on my machine, I did not reproduce the error on `main`, but it does fail on your PR.

I'm attaching the full error traceback, which seems to be confused about something near the "Descriptor must fit ..." build assertion message.

[sphinx-err-g5yedm4u.log](https://github.com/zephyrproject-rtos/zephyr/files/10900967/sphinx-err-g5yedm4u.log)

```
  51   │ sphinx.util.cfamily.DefinitionError: Invalid C declaration: Expected end of definition. [error at 16]
  52   │   Descriptor must fit in bits
  53   │   ----------------^
```

**Comment by nordic-krch** [comment]
@mbolivar-nordic I tried to run command you pasted but i'm getting different error (same on `main`):
```
[0/2] Generating Devicetree bindings documentation...
[1/2] Running Sphinx HTML build...

Warning, treated as error:
/home/krch/work/zephyr/include/zephyr/bluetooth/audio/lc3.h:336: argument 'em' of command @param is not found in the argument list of BT_CODEC_LC3_CONFIG(_freq, _duration, _loc, _len, _frames_per_sdu, _stream_context)
FAILED: CMakeFiles/html /home/krch/work/zephyr/doc/_build/CMakeFiles/html
cd /home/krch/work/zephyr/doc/_build && /usr/bin/cmake -E env DOXYGEN_EXECUTABLE=/usr/bin/doxygen DOT_EXECUTABLE=/usr/bin/dot /home/krch/.local/bin/sphinx-build -b html -c /home/krch/work/zephyr/doc -d /home/krch/work/zephyr/doc/_build/doctrees -w /home/krch/work/zephyr/doc/_build/html.log -t development -q -W -t publish /home/krch/work/zephyr/doc/_build/src /home/krch/work/zephyr/doc/_build/html
ninja: build stopped: subcommand failed.
```

**Comment by mbolivar-nordic** [comment]
You're not using doxygen 1.9.1, are you? That's the version that comes with ubuntu 22.04 and it has some known issues. I build with doxygen 1.9.7

**Comment by nordic-krch** [comment]
Yes, i was using doxygen 1.9.1. When updated to `1.9.7 (5b5f1534ab4d5885c6f9537910831a6489f33af2)` build is passing without any errors.
I was using:
- sphinx 5.3.0
- doxygen 1.9.1
- west 1.0.0
- python 3.10.6

**Comment by nordic-krch** [comment]
One more thing:
Initially I had west 0.14.0 and got following error:
`AttributeError: type object 'WestCommand' has no attribute 'add_pre_run_hook'`
When updated west error got fixed.

When doc is built it states: `-- Found west (found suitable version "0.14.0", minimum required is "0.7.1")`
Shouldn't minimum required be updated?

**Comment by nordic-krch** [comment]
Yesterday i got too much into tools versions that i eventually forgot to switch from `main` to PR. It was passing on main but failing on PR.
It was complaining about `BUILD_ASSERT` in the header for reason unknown. I just moved the check to the c file.

**Review by dcpleung — APPROVED** [review]

**Review by mbolivar-nordic — APPROVED** [review]
