### PR TITLE
bluetooth: CTS: Fix includes to avoid build error with some libCs

### LINKED ISSUE #81416: BT CTS fails to build with some libCs
**Describe the bug**
The BT CTS service fails to build with some libCs

**To Reproduce**
1. mkdir build; cd build
2. cmake -GNinja -DBOARD=nrf52_bsim ../samples/bluetooth/peripheral/ 
3. ninja

**Expected behavior**
No build failures

**Impact**
Samples fails to build for some targets or with some libCs

**Logs and console output**
```
[97/247] Building C object zephyr/CMakeFiles/zephyr.dir/subsys/bluetooth/services/cts.c.obj
FAILED: zephyr/CMakeFiles/zephyr.dir/subsys/bluetooth/services/cts.c.obj
[..]
zephyr.dir/subsys/bluetooth/services/cts.c.obj -c subsys/bluetooth/services/cts.c
In file included from /usr/include/sys/types.h:130,
                 from include/zephyr/bluetooth/gatt.h:23,
                 from subsys/bluetooth/services/cts.c:15:
/usr/include/bits/types/timer_t.h:7:19: error: conflicting types for ‘timer_t’; have ‘__timer_t’ {aka ‘void *’}
    7 | typedef __timer_t timer_t;
      |                   ^~~~~~~
In file included from include/zephyr/posix/time.h:61,
                 from subsys/bluetooth/services/cts.c:12:
include/zephyr/posix/posix_types.h:93:23: note: previous declaration of ‘timer_t’ with type ‘timer_t’ {aka ‘long unsigned int’}
   93 | typedef unsigned long timer_t;
      |                       ^~~~~~~
subsys/bluetooth/services/cts.c: In function ‘bt_cts_time_from_unix_ms’:
subsys/bluetooth/services/cts.c:74:13: warning: implicit declaration of function ‘gmtime_r’; did you mean ‘gmtime’? [-Wimplicit-function-declaration]
   74 |         if (gmtime_r(&unix_ts, &date_time) == NULL) {
      |             ^~~~~~~~
      |             gmtime
subsys/bluetooth/services/cts.c:74:44: warning: comparison between pointer and integer
   74 |         if (gmtime_r(&unix_ts, &date_time) == NULL) {
      |                                            ^~
``` 

**Environment (please complete the following information):**

 - OS: Ubuntu Linux 24.04
 - Toolchain (e.g Zephyr SDK, ...): 0.17 or host gcc 14.2
 - Commit SHA or Version used: 8dc3f856229ce083c956aa301c31a23e65bd8cd8

**Additional context**
Related to #81412
Service introduced in 957d59814b29b9ba3e9dcd707c474393baab639b

### PR DESCRIPTION
**Pull request by aescolar**
Remove unnecessary include in header and source file which causes conflicting type definitions with some libCs.

gmtime_r() is an extension to the C library, and therefore one needs to explicitly ask for its prototype to have it exposed. This is done by defining _POSIX_C_SOURCE so let's do so.

These two changes fix build errors with some libCs. Tested with pico, newlib, minimal and the host glibc with CONFIG_BT_CTS_HELPER_API set to `n` and `y`

Related to #81412
Fixes #81416

### CODE REVIEW

File: subsys/bluetooth/services/cts.c [hunk 1]
```diff
@@ -7,9 +7,16 @@
  *
  * SPDX-License-Identifier: Apache-2.0
  */
+
+#ifdef CONFIG_BT_CTS_HELPER_API
+#undef _POSIX_C_SOURCE
+#define _POSIX_C_SOURCE 200809L
```
Comment (jhedberg) [inline subsys/bluetooth/services/cts.c:13]: Maybe add a code comment here explaining why you're doing this (i.e. which libc API needs this)

Comment (aescolar) [reply subsys/bluetooth/services/cts.c]: Done

**Review by jhedberg — DISMISSED** [review]

**Review by Thalley — DISMISSED** [review]

File: subsys/bluetooth/services/cts.c [hunk 2]
```diff
@@ -7,9 +7,16 @@
  *
  * SPDX-License-Identifier: Apache-2.0
  */
+
+#ifdef CONFIG_BT_CTS_HELPER_API
+#undef _POSIX_C_SOURCE
+#define _POSIX_C_SOURCE 200809L /* To get gmtime_r()'s prototype */
```
Comment (alwa-nordic) [inline subsys/bluetooth/services/cts.c:13]: It would be simpler to put the feature test macros outside the ifdef. Outside the ifdef, it has potentially better test coverage, so it's safer too.

Comment (alwa-nordic) [reply subsys/bluetooth/services/cts.c:13]: Is there a reason for putting it inside the ifdef?

Comment (aescolar) [reply subsys/bluetooth/services/cts.c:13]: Just that it is only needed in that case. It can be outside.

Comment (alwa-nordic) [reply subsys/bluetooth/services/cts.c:13]: I prefer it's outside as then the file is always compatible with the same standard. This reduces complexity.

If it's inside the ifdef, someone could make a change somewhere else in the file, incompatible with `_POSIX_C_SOURCE 200809L`. At best the ifdef is enabled in a CI test and gives a compile error, but even that feedback is unnecessarily late.

Comment (aescolar) [reply subsys/bluetooth/services/cts.c:12]: Changed

**Comment by aescolar** [comment]
1st push is @alwa-nordic requested change
2nd push is just a rebase

**Review by Thalley — APPROVED** [review]

**Review by jhedberg — APPROVED** [review]
