### PR TITLE
drivers: mcux: fix compilation error for board without otrig

### LINKED ISSUE #58376: tests: drivers: dma: build failure for mimxrt595_evk_cm33 and mimxrt685_evk_cm33
**Describe the bug**
Multiple DMA testsuites were failing to build in CI for the `mimxrt595_evk_cm33` and `mimxrt685_evk_cm33` boards.

The failures were determined to be unrelated to the changes in https://github.com/zephyrproject-rtos/zephyr/pull/58375.

the problem you're facing:
 - What target platform are you using? CI Only
 - What have you tried to diagnose or workaround this issue? Read the logs at the linked PR
 - Is this a regression? Presumably, yes, but I have not bisected it.
 - ...

**To Reproduce**
* `west build -b mimxrt595_evk_cm33  tests/drivers/dma/loop_transfer`
* `west build -b mimxrt595_evk_cm33  tests/drivers/dma/chan_blen_transfer`
* `west build -b mimxrt685_evk_cm33  tests/drivers/dma/loop_transfer`
* `west build -b mimxrt685_evk_cm33  tests/drivers/dma/chan_blen_transfer`

**Expected behavior**
CI shouldn't fail

**Impact**
Currently breaking CI

**Logs and console output**
See https://github.com/zephyrproject-rtos/zephyr/actions/runs/5106587709/jobs/9178887624

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows): CI (Linux)
 - Toolchain (e.g Zephyr SDK, ...): Zephyr SDK v0.16.1 
 - Commit SHA or Version used: 86d63c5cff11654088db423c6d419aa8c0304c6c

**Additional context**

### PR DESCRIPTION
**Pull request by ycsin**
#57049 introduced channel chaining support for LPC55S69 which added new dt properties & made the dma driver dependant on those properties unconditionally, however, existing board that uses the same dma aren't updated accordingly and therefore building these board with the dma will lead to [compilation errors](https://github.com/zephyrproject-rtos/zephyr/pull/58375/checks?check_run_id=13834062173).

This PR fixes the compilation error by checking if the dts of the target board has the required prop to declare and init those config structs, tested with:
- `west build -b mimxrt595_evk_cm33  tests/drivers/dma/loop_transfer`
- `west build -b mimxrt595_evk_cm33  tests/drivers/dma/chan_blen_transfer`
- `west build -b mimxrt685_evk_cm33  tests/drivers/dma/loop_transfer`
- `west build -b mimxrt685_evk_cm33  tests/drivers/dma/chan_blen_transfer`

⚠️ However I'm not sure about the runtime.

See also https://github.com/zephyrproject-rtos/zephyr/issues/58376#issuecomment-1567706640

Fixes #58376

### CODE REVIEW

**Comment by ycsin** [comment]
Closed in favor of #58431

**Comment by decsny** [comment]
> > Hello @ycsin, thank you for the pull request, however I have an alternate fix at #58431 that involves less code changes. Let me know if I am missing something
> 
> At some point I did try `DT_INST_PROP_OR` at L754 but I got compilation error and I thought that probably array cant have a size of 0, turns out 0 sized array actually works 🤯, I just needed to change L733 as well.
> 
> Closed in favor of #58431, it's a much cleaner fix

Yes, and this driver initializes that whole array to -1's anyways so that `= {0}` could be removed
