### ISSUE TITLE
tests: drivers: memc: ram: build error on hifive_unmatched

### ISSUE THREAD

**Issue by mars-low** [zephyrproject-rtos/zephyr#99002]
### Describe the bug

Test `tests/drivers/memc/ram` fails to build for `hifive_unmatched` platform. 

It is a regression caused by https://github.com/zephyrproject-rtos/zephyr/commit/569a4ab8a7f9bb5d3230925b5af8c625c03804f0.

### Regression

- [x] This is a regression.

### Steps to reproduce

```
west build -p -b hifive_unmatched/fu740/s7 tests/drivers/memc/ram -T drivers.memc
```

### Relevant log output

```shell
/zephyrproject/zephyr/tests/drivers/memc/ram/src/main.c: In function 'test_ram_test_ram0':
/zephyrproject/zephyr/tests/drivers/memc/ram/src/main.c:74:31: error: 'RAM_SIZE_SRAM' undeclared (first use in this function); did you mean 'BUF_SIZE_SRAM'?
   74 |         test_ram_rw(buf_ram0, RAM_SIZE_SRAM);
      |                               ^~~~~~~~~~~~~
      |                               BUF_SIZE_SRAM
/zephyrproject/zephyr/tests/drivers/memc/ram/src/main.c:74:31: note: each undeclared identifier is reported only once for each function it appears in
```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

- OS: Ubuntu 24.04.3 LTS
- Toolchain: https://github.com/zephyrproject-rtos/sdk-ng/releases/tag/v0.17.4
- SHA: 8b2c75a2fbe4eef38a99f0a050d9d1d268d1bb69
