### ISSUE TITLE
samples: usb_c: sink: fails to link on stm32g081b_eval (undefined reference to __device_dts_ord_53)

### ISSUE THREAD

**Issue by ncadieux** [zephyrproject-rtos/zephyr#117678]
## Describe the bug

The `samples/subsys/usb_c/sink` sample does not link for `stm32g081b_eval` on current `main`. The build fails at the `zephyr_pre0.elf` link step with an undefined reference to a devicetree device ordinal, which resolves to the `gpiob` controller:

    undefined reference to `__device_dts_ord_53'

`__device_dts_ord_53` is `/soc/pin-controller@50000000/gpio@50000400`, i.e. `gpiob`.

The sample's board overlay declares a VBUS discharge pin:

```dts
/* samples/subsys/usb_c/sink/boards/stm32g081b_eval.overlay */
discharge-gpios = <&gpiob 13 GPIO_ACTIVE_HIGH>;
```

and the `zephyr,usb-c-vbus-adc` driver bakes that reference into its device config unconditionally:

```c
/* drivers/usb_c/vbus/usbc_vbus_adc.c */
.discharge_gpios = GPIO_DT_SPEC_INST_GET_OR(inst, discharge_gpios, {}),
```

However `samples/subsys/usb_c/sink/prj.conf` does not set `CONFIG_GPIO`. The sample was implicitly relying on `CONFIG_GPIO=y` coming from the board's `_defconfig`. That line was removed in commit 90b9c954f00, so the GPIO driver is no longer built, `gpiob` never gets a device definition, and the link fails.

### Suggested fix

Add `CONFIG_GPIO=y` to `samples/subsys/usb_c/sink/boards/stm32g081b_eval.conf`:

```diff
+CONFIG_GPIO=y
```

Bisected to: 90b9c954f00

### Regression

- [x] This is a regression.

### Steps to reproduce

```
west build -p always -b stm32g081b_eval samples/subsys/usb_c/sink
```

Fails at the link step. Adding `CONFIG_GPIO=y` to the sample's `prj.conf` (or building with `-DCONFIG_GPIO=y`) makes it link.

### Relevant log output

```shell
[173/178] Linking C executable zephyr/zephyr_pre0.elf
FAILED: zephyr/zephyr_pre0.elf zephyr/zephyr_pre0.map
/home/user/zephyr-sdk-1.0.1/gnu/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/14.3.0/../../../../arm-zephyr-eabi/bin/ld.bfd: zephyr/drivers/usb_c/vbus/libdrivers__usb_c__vbus.a(usbc_vbus_adc.c.obj):(.rodata.drv_config_0+0x20): undefined reference to `__device_dts_ord_53'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
FATAL ERROR: command exited with status 1
```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

- OS: Ubuntu 24.04.2 LTS (WSL2, kernel 5.15.167.4-microsoft-standard-WSL2)
- Toolchain: Zephyr SDK 1.0.1 (arm-zephyr-eabi gcc 14.3.0)
- Zephyr version: 4.4.99, build `v4.4.0-13404-gceb28342befb`
- Commit SHA: `ceb28342befb91553340bec6079c1fc9370b8598`
- west 1.5.0, CMake 3.28.3, Python 3.12.3
- Board: `stm32g081b_eval`
