### PR TITLE
update hal_nxp to mcux sdk 25.09.00

### PR DESCRIPTION
**Pull request by ZhaoxiangJin**
update hal_nxp to mcux sdk 25.09.00

### CODE REVIEW

**Comment by dleach02** [comment]
@ZhaoxiangJin I think your commits probably need to be squashed into one. Because the HAL change pulls in a part number change it likely causes a bisect problem if you have a separate commit to change the part numbers in the Zephyr side.

**Comment by ZhaoxiangJin** [comment]
> @ZhaoxiangJin I think your commits probably need to be squashed into one. Because the HAL change pulls in a part number change it likely causes a bisect problem if you have a separate commit to change the part numbers in the Zephyr side.

yes, i will squash them

**Comment by ZhaoxiangJin** [comment]
Hi @hakehuang, there is a CI issue unrelated to this PR. This issue also occurs in https://github.com/zephyrproject-rtos/zephyr/pull/95630. Other than that, all other tests are passing. Could you please help with regression testing? Thanks.

**Comment by hakehuang** [comment]
> Hi @hakehuang, there is a CI issue unrelated to this PR. This issue also occurs in #95630. Other than that, all other tests are passing. Could you please help with regression testing? Thanks.

@ZhaoxiangJin , I kick a regression on this PR, and is it possible to provide a hal updating notes? It will be helpful to check the test   plan.

**Comment by ZhaoxiangJin** [comment]
> > Hi @hakehuang, there is a CI issue unrelated to this PR. This issue also occurs in #95630. Other than that, all other tests are passing. Could you please help with regression testing? Thanks.
> 
> @ZhaoxiangJin , I kick a regression on this PR, and is it possible to provide a hal updating notes? It will be helpful to check the test plan.

Hi @hakehuang, each time update brings a lot of changes to HAL NXP, such as large-scale device and driver updates. Some information will be recorded in [README](https://github.com/zephyrproject-rtos/hal_nxp/pull/612/commits/2ebc2de31efd11d987c3937d0440a77e334b38e3), however, it seems difficult to use notes to record the specific driver/device updates.

**Comment by dleach02** [comment]
@ZhaoxiangJin, @hakehuang  the README is not intended for recording what changes have occurred. Since our HAL is constructed from multiple sources, it is meant to record where the update is coming from. We also list any patches we maintain on top of those sources.

**Comment by ZhaoxiangJin** [comment]
> @ZhaoxiangJin, @hakehuang the README is not intended for recording what changes have occurred. Since our HAL is constructed from multiple sources, it is meant to record where the update is coming from. We also list any patches we maintain on top of those sources.

Yes, I know. What I don't know is what Hake needs. I just pointed out that Hake can get some information from the README. I have no intention of adding more information to the README. If Hake needs, we can further discuss how to add update notes to improve the test plan.

**Comment by hakehuang** [comment]
board regression test pass, no issues found on v4.2.0-5336-g2a90804d52ce

**Comment by hakehuang** [comment]
> Yes, I know. What I don't know is what Hake needs. I just pointed out that Hake can get some information from the README. I have no intention of adding more information to the README. If Hake needs, we can further discuss how to add update notes to improve the test plan.

HAL changes shall be limited and clearly documented. and I need judge the test plan based on this.

**Comment by ZhaoxiangJin** [comment]
Update:
No code change, just rebase to the latest main

**Comment by ZhaoxiangJin** [comment]
Update:
Rebased to the latest main to fix the CI issue, no code change.

**Comment by hakehuang** [comment]
> Update:
> Rebased to the latest main to fix the CI issue, no code change.

regression tests PASS on v4.2.0-5746-g0495de1af84e

**Comment by ZhaoxiangJin** [comment]
> > Update:
> > Rebased to the latest main to fix the CI issue, no code change.
> 
> regression tests PASS on v4.2.0-5746-g0495de1af84e

Good, hello @dleach02, @mmahadevan108, maybe we can merge hal_nxp side PR now.

**Review by hakehuang — DISMISSED** [review]
regression test pass

**Comment by dleach02** [comment]
We will sequence the HAL PR with the others in the queue. When we do the merge we will update this PR with the new SHA

**Review by mmahadevan108 — APPROVED** [review]

**Review by hakehuang — APPROVED** [review]

**Review by mmahadevan108 — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]

**Comment by jhedberg** [comment]
Looks like this may have broken `main`:
```
In file included from /__w/zephyr/modules/hal/nxp/mcux/middleware/mcux-sdk-middleware-connectivity-framework/platform/kw47_mcxw72/configs/fwk_config.h:10,
                 from /__w/zephyr/modules/hal/nxp/mcux/middleware/mcux-sdk-middleware-connectivity-framework/platform/wireless_mcu/fwk_platform.c:11:
/__w/zephyr/modules/hal/nxp/mcux/middleware/mcux-sdk-middleware-connectivity-framework/platform/kw47_mcxw72/fwk_platform_definitions.h:140: error: "PLATFORM_BANK_IS_ECC" redefined [-Werror]
  140 | #define PLATFORM_BANK_IS_ECC TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE
      | 
In file included from /__w/zephyr/modules/hal/nxp/mcux/mcux-sdk-ng/devices/MCX/MCXW/periph3/PERI_ADC.h:50,
                 from /__w/zephyr/modules/hal/nxp/mcux/mcux-sdk-ng/devices/MCX/MCXW/MCXW727C/MCXW727C_cm33_core0.h:46,
                 from /__w/zephyr/modules/hal/nxp/mcux/mcux-sdk-ng/devices/MCX/MCXW/MCXW727C/fsl_device_registers.h:17,
                 from /__w/zephyr/modules/hal/nxp/mcux/middleware/mcux-sdk-middleware-connectivity-framework/platform/kw47_mcxw72/fwk_platform_definitions.h:10:
/__w/zephyr/modules/hal/nxp/mcux/mcux-sdk-ng/devices/MCX/MCXW/MCXW727C/MCXW727C_cm33_core0_COMMON.h:2493: note: this is the location of the previous definition
 2493 | #define PLATFORM_BANK_IS_ECC TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE
```

I'm not 100% it was this specific PR, but it looks like the likeliest culprit. Is someone looking at fixing it? The full CI run is here:
https://github.com/zephyrproject-rtos/zephyr/actions/runs/18580734508/job/52974881248

**Comment by ZhaoxiangJin** [comment]
> Looks like this may have broken `main`:
> 
> ```
> In file included from /__w/zephyr/modules/hal/nxp/mcux/middleware/mcux-sdk-middleware-connectivity-framework/platform/kw47_mcxw72/configs/fwk_config.h:10,
>                  from /__w/zephyr/modules/hal/nxp/mcux/middleware/mcux-sdk-middleware-connectivity-framework/platform/wireless_mcu/fwk_platform.c:11:
> /__w/zephyr/modules/hal/nxp/mcux/middleware/mcux-sdk-middleware-connectivity-framework/platform/kw47_mcxw72/fwk_platform_definitions.h:140: error: "PLATFORM_BANK_IS_ECC" redefined [-Werror]
>   140 | #define PLATFORM_BANK_IS_ECC TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE
>       | 
> In file included from /__w/zephyr/modules/hal/nxp/mcux/mcux-sdk-ng/devices/MCX/MCXW/periph3/PERI_ADC.h:50,
>                  from /__w/zephyr/modules/hal/nxp/mcux/mcux-sdk-ng/devices/MCX/MCXW/MCXW727C/MCXW727C_cm33_core0.h:46,
>                  from /__w/zephyr/modules/hal/nxp/mcux/mcux-sdk-ng/devices/MCX/MCXW/MCXW727C/fsl_device_registers.h:17,
>                  from /__w/zephyr/modules/hal/nxp/mcux/middleware/mcux-sdk-middleware-connectivity-framework/platform/kw47_mcxw72/fwk_platform_definitions.h:10:
> /__w/zephyr/modules/hal/nxp/mcux/mcux-sdk-ng/devices/MCX/MCXW/MCXW727C/MCXW727C_cm33_core0_COMMON.h:2493: note: this is the location of the previous definition
>  2493 | #define PLATFORM_BANK_IS_ECC TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE
> ```
> 
> I'm not 100% it was this specific PR, but it looks like the likeliest culprit. Is someone looking at fixing it? The full CI run is here: https://github.com/zephyrproject-rtos/zephyr/actions/runs/18580734508/job/52974881248

Hello @jhedberg, I will look into this, will fix it ASAP.

**Comment by hakehuang** [comment]
commit b6c66b78582138078222a1525a2bbab82b4e10c1 is the first bad commit, but  v4.2.0-5746-g0495de1af84e is OK, what do you changed in between? @ZhaoxiangJin

**Comment by hakehuang** [comment]
> I'm not 100% it was this specific PR, but it looks like the likeliest culprit. Is someone looking at fixing it? The full CI run is here:
> https://github.com/zephyrproject-rtos/zephyr/actions/runs/18580734508/job/52974881248

sorry, it is my bad, I did not involve net samples in my regression test scope, will enhance afterwards @jhedberg

**Comment by axelnxp** [comment]
@jhedberg @hakehuang @ZhaoxiangJin I opened a PR to fix it.
https://github.com/zephyrproject-rtos/zephyr/pull/97782
