### PR TITLE
drivers: stepper: adi_tmc: Fix read_actual_position() calls

### LINKED ISSUE #107773: Stepper: adi_tmc: Build fails with unresolved function read_actual_position()
### Describe the bug

When using either of the two stepper motor drivers for Analog Devices, TMC50xxx or TMC51xx, and with CONFIG_STEPPER_ADI_TMC524X_RAMPSTAT_POLL_STALLGUARD_LOG enabled, compilation fails. The function `read_actual_position()` cannot be resolved.

This is caused by the renaming of these function implementations in issue #8395626, without updating the caller.

### Regression

- [x] This is a regression.

### Steps to reproduce

Activate usage of tmc50xx or tmc51xx driver in DTS.
Activate CONFIG_STEPPER_ADI_TMC524X_RAMPSTAT_POLL_STALLGUARD_LOG
west build

### Relevant log output

```shell

```

### Impact

Annoyance – Minor irritation; no significant impact on usability or functionality.

### Environment

Any platform that uses the TMC50XX or TMC51XX driver and wants to use stallguard logging.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by schweigstill**
Commit [8395626](83956260f77e6138ca56614e004ee891d27e80ff) renamed the identically named functions implemented in `tmc50xx.c` and `tmc51xx.c` from `read_actual_position()` to `tmc50xx_read_actual_position()` and `tmc51xx_read_actual_position()`, respectively. However, the corresponding call sites were not updated.

When `CONFIG_STEPPER_ADI_TMC524X_RAMPSTAT_POLL_STALLGUARD_LOG` is enabled, this results in a compilation error.

This PR fixes the issue by updating the affected call sites accordingly.

Fixes #107773

### CODE REVIEW

**Review by jilaypandya — APPROVED** [review]

**Review by dipakgmx — APPROVED** [review]

**Comment by dipakgmx** [comment]
@schweigstill The commit message needs to be fixed as per the [guidelines](https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-guidelines).

**Comment by jilaypandya** [comment]
The bug got introduced in https://github.com/zephyrproject-rtos/zephyr/commit/83956260f77e6138ca56614e004ee891d27e80ff
Thanks for fixing it :-)

**Comment by jilaypandya** [comment]
Hi @schweigstill, could you adjust the commit title as follows:
```
drivers: stepper: adi_tmc: fix read_actual_position calls
```
