### PR TITLE
dfu: mcuboot: define boot_img_magic when FLASH_AREA_IMAGE_SECONDARY

### LINKED ISSUE #30075: dfu: mcuboot: fail to build with CONFIG_BOOTLOADER_MCUBOOT=n and CONFIG_IMG_MANAGER=y
**Describe the bug**
Using CONFIG_IMG_MANAGER without CONFIG_BOOTLOADER_MCUBOOT is not longer possible. This is most likely introduced with 5cfafb041b2ab3d63e73c9f800b1174ba8ad57aa.

**To Reproduce**
1. west build -b nrf52840dk_nrf52840 samples/hello_world/ -- -DCONFIG_IMG_MANAGER=y -DCONFIG_FLASH=y
2. See error

**Expected behavior**
It is possible to use functionality provided by IMG_MANAGER without building firmware for chain-loading with mcuboot.

**Impact**
Annoyance.

**Logs and console output**
```
zephyr/subsys/dfu/boot/mcuboot.c: In function 'boot_magic_write':
zephyr/subsys/dfu/boot/mcuboot.c:390:34: error: 'boot_img_magic' undeclared (first use in this function)
  390 |  rc = flash_area_write(fa, offs, boot_img_magic, BOOT_MAGIC_SZ);
      |                                  ^~~~~~~~~~~~~~
zephyr/subsys/dfu/boot/mcuboot.c:390:34: note: each undeclared identifier is reported only once for each function it appears in
```

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: Zephyr SDK v0.12.0-beta-1
 - Commit SHA: 4d930057d6d667634752e3d0d0dbd677761714e2 (tip of master)

**Additional context**

### PR DESCRIPTION
**Pull request by mniestroj**
boot_img_magic[] is needed for boot_magic_write() function, which is
defined if FLASH_AREA_IMAGE_SECONDARY is defined as well.

Make sure boot_img_magic[] is defined when FLASH_AREA_IMAGE_SECONDARY.

Fixes: #30075

### CODE REVIEW

**Comment by de-nordic** [comment]
According to the description of the problem (https://github.com/zephyrproject-rtos/zephyr/issues/30075), the desired result is to be able to use `CONFIG_IMG_MANAGER=y`  without support for MCUBOOT:

> It is possible to use functionality provided by IMG_MANAGER without building firmware for chain-loading with mcuboot.

Shouldn't then the solution be to make a compilation of `mcuboot.c` optional within CMakeList.txt ?

**Review by nvlsianpu — COMMENTED** [review]
We decided not to use not in zephyr tree defined Kconfig properties here.
Then fastest patch is to add `|| defined(CONFIG_IMG_MANAGER)` or `&& !defined(CONFIG_IMG_MANAGER)`  where needed.
Also want to emphasize that  I will work on #29963 soon

**Comment by mniestroj** [comment]
>We decided not to use not in zephyr tree defined Kconfig properties here.

But still decided to make a logic based on "not in zephyr tree" code, its public functions etc. IMO it doesn't seem any better, because dependency is still there. The only thing is that Compliance check is satisfied, which is kind of artificial gain.

>Then fastest patch is to add || defined(CONFIG_IMG_MANAGER) or || !defined(CONFIG_IMG_MANAGER) where needed.

Unfortunately `defined(CONFIG_IMG_MANAGER)` still doesn't tell us if we are building within mcuboot or not.

>Also want to emphasize that I will work on #29963 soon

Seems like a very good idea, we really need that! Any estimates on that already?

What about adding a helper macro `#define WITHIN_MCUBOOT (whatever_magic_needs_to_be_here)` and then use `#if WITHIN_MCUBOOT` and `#if !WITHIN_MCUBOOT` statements all across the codebase? This will at least show what logic we are relying on, while `defined(CONFIG_BOOTLOADER_MCUBOOT)` doesn't tell anything for now. Personally I think that we should use `CONFIG_MCUBOOT`, but if that is really not desirable then at least:
```
#if !defined(CONFIG_BOOTLOADER_MCUBOOT) && !defined(CONFIG_IMG_MANAGER) && !defined(CONFIG_ZTEST)
#define WITHIN_MCUBOOT 1
#endif
```

**Comment by nvlsianpu** [comment]
`WITHIN_MCUBOOT` sound ok to me.

**Comment by mniestroj** [comment]
I am not sure that adding a check around `CONFIG_IMG_MANAGER` (when defining `WITH_MCUBOOT`) makes sense, because then we will run into function name conflicts with MCUboot once again, because `mcuboot.c` is compiled **only** when `CONFIG_IMG_MANAGER=y`. @nvlsianpu could you confirm?

**Comment by nvlsianpu** [comment]
@mniestroj ^^ obviously you are right.
looks like need to find another way - new kconfig or so

**Comment by nvlsianpu** [comment]
I started working on https://github.com/zephyrproject-rtos/zephyr/issues/29963

**Comment by nvlsianpu** [comment]
@mniestroj shall we close this?

**Comment by mniestroj** [comment]
This has been superseded with #30370.
