### ISSUE TITLE
tests: net.mqtt_sn.packet : build failure for multiply NXP platfroms

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#81809]
**Describe the bug**

net.mqtt_sn.packet build failure for 

- ls1046ardb/ls1046a/smp/4cores
- ls1046ardb/ls1046a
- imx95_evk/mimx9596/a55/smp
- imx93_evk/mimx9352/a55
- imx8mp_evk/mimx8ml8/a53/smp
- imx8mp_evk/mimx8ml8/a53
- imx8mn_evk/mimx8mn6/a53
- imx8mm_evk/mimx8mm6/a53/smp 
- imx8mm_evk/mimx8mm6/a53

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?
 - list above
 - What have you tried to diagnose or workaround this issue?
 - git bisect
 - Is this a regression? If yes, have you been able to "git bisect" it to a
   specific commit?
 
```
aa9c9228d48a0e4041138cf264a26fc5edd7c03c is the first bad commit
commit aa9c9228d48a0e4041138cf264a26fc5edd7c03c
Author: Kenneth Witham <kennywitham4@gmail.com>
Date:   Mon Oct 28 08:09:49 2024 -0700

    net: mqtt-sn: Add Gateway Advertisement and Discovery process support
    
    Fixes: #78010
    This commit implements the "Gateway Advertisement and Discovery" process
    defined in section 6.1 of the MQTT-SN specification.
    This includes breaking changes to the transport interface and the default
    included UDP interface implementation as support for UDP multicast
    messages is added as implemented by the Paho MQTT-SN Gateway.
    
    Signed-off-by: Kenneth Witham <kennywitham4@gmail.com>

 doc/connectivity/networking/api/mqtt_sn.rst    |  51 ++--
 include/zephyr/net/mqtt_sn.h                   |  88 ++++--
 subsys/net/lib/mqtt_sn/Kconfig                 |  41 +++
 subsys/net/lib/mqtt_sn/mqtt_sn.c               | 396 ++++++++++++++++++++++---
 subsys/net/lib/mqtt_sn/mqtt_sn_decoder.c       |  15 +
 subsys/net/lib/mqtt_sn/mqtt_sn_transport_udp.c | 146 +++++++--
 6 files changed, 638 insertions(+), 99 deletions(-)
```

**To Reproduce**

```
west build -p -b imx8mm_evk/mimx8mm6/a53 tests/net/lib/mqtt_sn_packet -T net.mqtt_sn.packet
```

**Expected behavior**

Build PASS

**Impact**

MQTT applications

**Logs and console output**

```
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/subsys/net/lib/mqtt_sn/mqtt_sn.c:187:33: error: format '%hu' expects argument of type 'int', but argument 2 has type 'size_t' {aka 'long unsigned int'} [-Werror=format=]
  187 |                         LOG_ERR("Can't create PUB: Too much data (%" PRIu16 ")", data->size);
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~             ~~~~~~~~~~
      |                                                                                      |
      |                                                                                      size_t {aka long unsigned int}
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/include/zephyr/logging/log_core.h:315:50: note: in definition of macro 'Z_LOG2'
  315 |                         z_log_printf_arg_checker(__VA_ARGS__);                                     \
      |                                                  ^~~~~~~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/include/zephyr/logging/log.h:44:25: note: in expansion of macro 'Z_LOG'
   44 | #define LOG_ERR(...)    Z_LOG(LOG_LEVEL_ERR, __VA_ARGS__)
      |                         ^~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/subsys/net/lib/mqtt_sn/mqtt_sn.c:187:25: note: in expansion of macro 'LOG_ERR'
  187 |                         LOG_ERR("Can't create PUB: Too much data (%" PRIu16 ")", data->size);
      |                         ^~~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/subsys/net/lib/mqtt_sn/mqtt_sn.c: In function 'mqtt_sn_topic_create':
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/subsys/net/lib/mqtt_sn/mqtt_sn.c:245:25: error: format '%hu' expects argument of type 'int', but argument 2 has type 'size_t' {aka 'long unsigned int'} [-Werror=format=]
  245 |                 LOG_ERR("Can't create topic: name too long (%" PRIu16 ")", name->size);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~             ~~~~~~~~~~
      |                                                                                |
      |                                                                                size_t {aka long unsigned int}
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/include/zephyr/logging/log_core.h:315:50: note: in definition of macro 'Z_LOG2'
  315 |                         z_log_printf_arg_checker(__VA_ARGS__);                                     \
      |                                                  ^~~~~~~~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/include/zephyr/logging/log.h:44:25: note: in expansion of macro 'Z_LOG'
   44 | #define LOG_ERR(...)    Z_LOG(LOG_LEVEL_ERR, __VA_ARGS__)
      |                         ^~~~~
/home/jenkins/agent/workspace/bitbucket_build_platform/zephyr/subsys/net/lib/mqtt_sn/mqtt_sn.c:245:17: note: in expansion of macro 'LOG_ERR'
  245 |                 LOG_ERR("Can't create topic: name too long (%" PRIu16 ")", name->size);
      |                 ^~~~~~~
cc1: all warnings being treated as errors
ninja: build stopped: subcommand failed.

```

**Environment (please complete the following information):**

 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used: v4.0.0-697-g78c1def4db53

**Comment by jukkar** [comment]
Fixed by #81803
