### ISSUE TITLE
CI build fails for tests due to thread function signature changes

### ISSUE THREAD

**Issue by benediktibk** [zephyrproject-rtos/zephyr#64578]
Build failures:

    ccache /opt/toolchains/zephyr-sdk-0.16.3/x86_64-zephyr-elf/bin/x86_64-zephyr-elf-gcc -DKERNEL -DPICOLIBC_INTEGER_PRINTF_SCANF -DTC_RUNID=aa27f2621db6b33dd47811b2391bc39b -D_FORTIFY_SOURCE=1 -D_POSIX_C_SOURCE=200809 -D__LINUX_ERRNO_EXTENSIONS__ -D__ZEPHYR__=1 -I/__w/zephyr/zephyr/include -I/__w/zephyr/zephyr/twister-out/qemu_x86_64/tests/kernel/mem_protect/stackprot/kernel.memory_protection.stackprot_tls/zephyr/include/generated -I/__w/zephyr/zephyr/soc/x86/ia32 -I/__w/zephyr/zephyr/subsys/testsuite/include -I/__w/zephyr/zephyr/subsys/testsuite/ztest/include -m64  -fno-strict-aliasing -Werror -fstack-protector-all -mstack-protector-guard=tls -Os -imacros /__w/zephyr/zephyr/twister-out/qemu_x86_64/tests/kernel/mem_protect/stackprot/kernel.memory_protection.stackprot_tls/zephyr/include/generated/autoconf.h -fno-printf-return-value -fno-common -g -gdwarf-4 -fdiagnostics-color=always -m64 -Wa,--divide --sysroot=/opt/toolchains/zephyr-sdk-0.16.3/x86_64-zephyr-elf/x86_64-zephyr-elf -imacros /__w/zephyr/zephyr/include/zephyr/toolchain/zephyr_stdint.h -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wno-pointer-sign -Wpointer-arith -Wexpansion-to-defined -Wno-unused-but-set-variable -Werror=implicit-int -fno-pic -fno-pie -fno-asynchronous-unwind-tables -ftls-model=local-exec -fno-reorder-functions --param=min-pagesize=0 -fno-defer-pop -fmacro-prefix-map=/__w/zephyr/zephyr/tests/kernel/mem_protect/stackprot=CMAKE_SOURCE_DIR -fmacro-prefix-map=/__w/zephyr/zephyr=ZEPHYR_BASE -fmacro-prefix-map=/__w/zephyr=WEST_TOPDIR -ffunction-sections -fdata-sections -mno-sse3 -mno-ssse3 -mno-sse4.1 -mno-sse4.2 -mno-sse4a --specs=picolibc.specs -std=c99 -MD -MT CMakeFiles/app.dir/src/main.c.obj -MF CMakeFiles/app.dir/src/main.c.obj.d -o CMakeFiles/app.dir/src/main.c.obj -c /__w/zephyr/zephyr/tests/kernel/mem_protect/stackprot/src/main.c
    /__w/zephyr/zephyr/tests/kernel/mem_protect/stackprot/src/main.c: In function 'stackprot_test_create_alt_thread':
    /__w/zephyr/zephyr/tests/kernel/mem_protect/stackprot/src/main.c:132:25: error: passing argument 4 of 'k_thread_create' from incompatible pointer type [-Werror=incompatible-pointer-types]
      132 |                         alternate_thread, NULL, NULL, NULL,
          |                         ^~~~~~~~~~~~~~~~
          |                         |
          |                         void (*)(void)
    In file included from /__w/zephyr/zephyr/include/zephyr/kernel.h:6102,
                     from /__w/zephyr/zephyr/tests/kernel/mem_protect/stackprot/src/main.c:9:
    /__w/zephyr/zephyr/twister-out/qemu_x86_64/tests/kernel/mem_protect/stackprot/kernel.memory_protection.stackprot_tls/zephyr/include/generated/syscalls/kernel.h:59:131: note: expected 'k_thread_entry_t' {aka 'void (*)(void *, void *, void *)'} but argument is of type 'void (*)(void)'
       59 | static inline k_tid_t k_thread_create(struct k_thread * new_thread, k_thread_stack_t * stack, size_t stack_size, k_thread_entry_t entry, void * p1, void * p2, void * p3, int prio, uint32_t options, k_timeout_t delay)
          |                                                                                                                  ~~~~~~~~~~~~~~~~~^~~~~
    cc1: all warnings being treated as errors
    
    /__w/zephyr/zephyr/tests/kernel/mutex/sys_mutex/src/main.c:91:25: error: passing argument 4 of 'k_thread_create' from incompatible pointer type [-Werror=incompatible-pointer-types]
       91 |                         thread_##id,                                                       \
          |                         ^~~~~~~
          |                         |
          |                         void (*)(void)
    /__w/zephyr/zephyr/tests/kernel/mutex/sys_mutex/src/main.c:269:9: note: in expansion of macro 'CREATE_PARTICIPANT_THREAD'
      269 |         CREATE_PARTICIPANT_THREAD(05, 5);
          |         ^~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from /__w/zephyr/zephyr/include/zephyr/kernel.h:6102,
                     from /__w/zephyr/zephyr/subsys/testsuite/include/zephyr/tc_util.h:12,
                     from /__w/zephyr/zephyr/tests/kernel/mutex/sys_mutex/src/main.c:48:
    
    /__w/zephyr/zephyr/tests/kernel/sched/metairq/src/main.c:155:70: error: passing argument 4 of 'k_thread_create' from incompatible pointer type [-Werror=incompatible-pointer-types]
      155 |         CREATE_PARTICIPANT_THREAD(metairq_thread_id, K_PRIO_COOP(0), metairq_thread);
          |                                                                      ^~~~~~~~~~~~~~
          |                                                                      |
          |                                                                      void (*)(void)
    /__w/zephyr/zephyr/tests/kernel/sched/metairq/src/main.c:43:25: note: in definition of macro 'CREATE_PARTICIPANT_THREAD'
       43 |                         entry,                                                         \
          |                         ^~~~~
    In file included from /__w/zephyr/zephyr/include/zephyr/kernel.h:6102,
                     from /__w/zephyr/zephyr/tests/kernel/sched/metairq/src/main.c:6:
    /__w/zephyr/zephyr/twister-out/qemu_x86_64/tests/kernel/sched/metairq/kernel.scheduler.metairq/zephyr/include/generated/syscalls/kernel.h:59:131: note: expected 'k_thread_entry_t' {aka 'void (*)(void *, void *, void *)'} but argument is of type 'void (*)(void)'
       59 | static inline k_tid_t k_thread_create(struct k_thread * new_thread, k_thread_stack_t * stack, size_t stack_size, k_thread_entry_t entry, void * p1, void * p2, void * p3, int prio, uint32_t options, k_timeout_t delay)
          |                                                                                                                  ~~~~~~~~~~~~~~~~~^~~~~
    /__w/zephyr/zephyr/tests/kernel/sched/metairq/src/main.c:156:68: error: passing argument 4 of 'k_thread_create' from incompatible pointer type [-Werror=incompatible-pointer-types]
      156 |         CREATE_PARTICIPANT_THREAD(coop_thread1_id, K_PRIO_COOP(1), coop_thread1);
          |                                                                    ^~~~~~~~~~~~
          |                                                                    |
          |                                                                    void (*)(void)
    /__w/zephyr/zephyr/tests/kernel/sched/metairq/src/main.c:43:25: note: in definition of macro 'CREATE_PARTICIPANT_THREAD'
       43 |                         entry,                                                         \
          |                         ^~~~~
    /__w/zephyr/zephyr/twister-out/qemu_x86_64/tests/kernel/sched/metairq/kernel.scheduler.metairq/zephyr/include/generated/syscalls/kernel.h:59:131: note: expected 'k_thread_entry_t' {aka 'void (*)(void *, void *, void *)'} but argument is of type 'void (*)(void)'
       59 | static inline k_tid_t k_thread_create(struct k_thread * new_thread, k_thread_stack_t * stack, size_t stack_size, k_thread_entry_t entry, void * p1, void * p2, void * p3, int prio, uint32_t options, k_timeout_t delay)
          |                                                                                                                  ~~~~~~~~~~~~~~~~~^~~~~
    /__w/zephyr/zephyr/tests/kernel/sched/metairq/src/main.c:157:68: error: passing argument 4 of 'k_thread_create' from incompatible pointer type [-Werror=incompatible-pointer-types]
      157 |         CREATE_PARTICIPANT_THREAD(coop_thread2_id, K_PRIO_COOP(2), coop_thread2);
          |                                                                    ^~~~~~~~~~~~
          |                                                                    |
          |                                                                    void (*)(void)
    /__w/zephyr/zephyr/tests/kernel/sched/metairq/src/main.c:43:25: note: in definition of macro 'CREATE_PARTICIPANT_THREAD'
       43 |                         entry,                                                         \
          |                         ^~~~~
    
This was introduced by PR #62903

**Comment by benediktibk** [comment]
FYI: @jhedberg @henrikbrixandersen @carlescufi

**Comment by benediktibk** [comment]
An example of a PR with failed CI: #64570
