### PR TITLE
drivers: video: sw_generator: Fix 64-bit build error

### LINKED ISSUE #109740: drivers: video: video_sw_generator: format string mismatch causes build failure on 64-bit platforms
### Describe the bug

In `drivers/video/video_sw_generator.c` line 337, `LOG_ERR` uses `%u` for `frame_size` (`uint32_t`) while `vbuf->size` is `size_t` (`long unsigned int` on 64-bit platforms). This is caught by `-Werror` and causes a build failure on 64-bit targets such as `frdm_imx93/mimx9352/a55` (Cortex-A55).

```
drivers/video/video_sw_generator.c:337:17: error: format ‘%u’ expects argument of type ‘unsigned int’, but argument 3 has type ‘long unsigned int’ [-Werror=format=]
  337 |         LOG_ERR("Buffer too small (need %u, have %zu)", frame_size, vbuf->size);
cc1: all warnings being treated as errors
ninja: build stopped: subcommand failed.
```

### Regression

- [ x] This is a regression.

12782f1c9d7748357a79cd8dbb79b98baf5417c6 is the first bad commit
commit 12782f1c9d7748357a79cd8dbb79b98baf5417c6
Author: Kate Wang <yumeng.wang@nxp.com>
Date:   Tue Apr 28 11:33:48 2026 +0800

    drivers: video: sw_generator: Add JPEG and PNG format support
    
    Add support for JPEG and PNG compressed formats to the video software
    generator driver. This enables testing of compressed video formats
    without requiring actual camera hardware.
    
    The compressed frame buffers are included at compile time via
    generated header files, with configurable file names to support
    custom test patterns.
    
    Signed-off-by: Kate Wang <yumeng.wang@nxp.com>

### Steps to reproduce

```
west build -p -b frdm_imx93/mimx9352/a55 samples/subsys/usb/uvc
```

Or via twister:
```
scripts/twister -p frdm_imx93/mimx9352/a55 -T samples/subsys/usb/uvc --build-only
```

**Zephyr version:** `v4.4.0-3337-g07e34e68d340`

Also reproduced in NXP internal CI (`bitbucket_build_platform` build #9667).

### Root cause

`frame_size` is `uint32_t` but the format specifier `%u` is treated as `unsigned int`. On 64-bit platforms (Cortex-A55), `size_t` is `long unsigned int`, causing the compiler to flag the mismatch as an error via `-Werror=format=`.

### Suggested fix

Use `PRIu32` for portable `uint32_t` formatting:

```c
// drivers/video/video_sw_generator.c:337
// Before:
LOG_ERR("Buffer too small (need %u, have %zu)", frame_size, vbuf->size);

// After:
LOG_ERR("Buffer too small (need %" PRIu32 ", have %zu)", frame_size, vbuf->size);
```

### Related

- PR #85968 (`drivers: video: sw_generator: add more formats and try to simplify`) — last PR to touch `video_sw_generator.c`
- PR #92370 (`Video: Rework buffer management`) — open draft reworking buffer management types

### PR DESCRIPTION
**Pull request by Surya-Tumma**
Fix a build failure on 64-bit platforms like Cortex-A55. The compiler reports a format string error because the variable types and log specifiers do not match up perfectly.

Fixes : https://github.com/zephyrproject-rtos/zephyr/issues/109740

### CODE REVIEW

**Review by iuliana-prodan — DISMISSED** [review]

File: drivers/video/video_sw_generator.c [hunk 1]
```diff
@@ -334,7 +334,8 @@ static int video_sw_generator_fill_compressed(struct video_buffer *vbuf, bool hf
 
 	/* Check if buffer is large enough */
 	if (vbuf->size < frame_size) {
-		LOG_ERR("Buffer too small (need %u, have %zu)", frame_size, vbuf->size);
+		LOG_ERR("Buffer too small (need %u, have %lu)", (unsigned int)frame_size,
+			(unsigned long)vbuf->size);
```
Comment (ngphibang) [inline drivers/video/video_sw_generator.c]: Both `frame_size` and `vbuf->size` are `uint32_t`, why do we cast it differently ?

**Review by ngphibang — CHANGES_REQUESTED** [review]
Thanks for the fix.

File: drivers/video/video_sw_generator.c (hunk 1 above)
Comment (josuah) [reply drivers/video/video_sw_generator.c]: Minor detail, but an unwritten guideline is that when folding long log lines, the variables are on a different line than the print string, which can help with cross-checking the error string and associated variables.

```c
		LOG_ERR("Buffer too small (need %u, have %lu)",
			(unsigned int)frame_size, (unsigned int)vbuf->size);
```

But this is not blocking.

Thank you!

Comment (ngphibang) [reply drivers/video/video_sw_generator.c]: I think there was a mistake in the issue description, `vbuf->size` is actually an `uint32_t` not a `size_t`, so the simplest fix is just replace `%zu` by `%u`

Comment (Surya-Tumma) [reply drivers/video/video_sw_generator.c]: Thanks for the feedback @ngphibang and @josuah!
Good catch. I've updated the code to with PRIu32 for consistency across platforms!

Comment (ngphibang) [reply drivers/video/video_sw_generator.c]: I remember there was a discussion / debate on Zephyr about "should we use the simple %u or the cumbersome / ugly but correct PRI macro ?" but I don't know what the conclusion is for now and cannot find the link anymore

Comment (Surya-Tumma) [reply drivers/video/video_sw_generator.c]: Thanks for the context! 
Would you prefer I use the PRIu32 macro, or just keep it simple with matching (unsigned int) casts and %u?
Let me know what you prefer for this driver and I'll update it!

Comment (ngphibang) [reply drivers/video/video_sw_generator.c]: I am not sure. As PRI macros are not used at all in video code, maybe we can stick with %u then if we need a change, we can change all at once, what do you think @josuah ? BTW, there is "minor detail" left as mentioned by @josuah :-).

**Review by ngphibang — APPROVED** [review]

**Review by iuliana-prodan — APPROVED** [review]

**Review by aescolar — APPROVED** [review]

File: drivers/video/video_sw_generator.c (hunk 1 above)
Comment (josuah) [reply drivers/video/video_sw_generator.c]: I think there was a discussion about it on Discord/Github, offering to stick with C native types rather than PRI, but do not remember the conclusion of this...
