### PR TITLE
modules: uoscore-uedhoc: Update to the latest version 

### LINKED ISSUE #60235: Zephyr module uoscore-uedhoc sample `samples/zephyr_oscore/server` refers to tinycbor which no longer exists
**Describe the bug**
This file: https://github.com/zephyrproject-rtos/uoscore-uedhoc/blob/zephyr/samples/zephyr_oscore/server/CMakeLists.txt refers to tinycbor in zephyr, a module which no longer exists. It also uses the old `$ENV{ZEPHYR_BASE}` variable which should be replaced with `${ZEPHYR_BASE}`

**Expected behavior**
Issues to be addressed

**Impact**
Probably NIL since no one has reported this issue before so assuming no-one uses this codebase and/or sample

### PR DESCRIPTION
**Pull request by rlubos**
Update `uoscore-uedhoc` to the latest revision. Additionally, fix two issues encountered with the integration:
* mbed TLS dependencies broken after update to v3.3.0
* `testcase.yaml` missing from `oscore` tests (hence, above was not caught)

Fixes #60235

### CODE REVIEW

**Comment by carlescufi** [comment]
@rlubos can you please fix the compliance checks?

**Comment by rlubos** [comment]
@rajkan01 I can't add you as a reviewer, but since I'm touching the file you've modified lately, I'm asking for a review here. I'm talking specifically about this commit:
https://github.com/zephyrproject-rtos/zephyr/pull/60789/commits/ce8689efc8c60472bdb3e4dcd19970baf91b3344
Building that file with TFM enabled caused the linker to throw redefinition erros, as the functions the file provides are also defined in TFM crypto
> home/robert/repos/zephyrproject/zephyr/samples/hello_world/build/tfm/install/interface/src/tfm_crypto_api.c:32: multiple definition of `psa_open_key'; modules/mbedtls/libmbedTLSCrypto.a(psa_crypto_slot_management.c.obj):/home/robert/repos/zephyrproject/modules/crypto/mbedtls/library/psa_crypto_slot_management.c:498: first defined here

I've checked with @joerchan and according to him, other files should also be conditionally excluded when TFM is enabled, similarily to what was done in NCS `nrf_security` module:
https://github.com/nrfconnect/sdk-nrfxlib/blob/v2.4.0/nrf_security/src/core/builtin/CMakeLists.txt#L37C19-L37C19
Other files did not cause any trouble in this particular case but this likely is something to the TFM team to investigate.

**Review by joerchan — DISMISSED** [review]
@d3zd3z The other PSA files should also be excluded from the build, could you follow up on this?

**Review by joerchan — APPROVED** [review]
@rlubos I'm not sure why you dismissed my review, but the TLS changes I cannot really tell you if is right or not. I can tell you that they will not negatively affect us, but we may have to add additional changes to an existing noup patch.

**Comment by rlubos** [comment]
@joerchan I did not, it's GH who dismissed the review automatically on push (that's how the Zephyr repo is configured).

**Review by d3zd3z — APPROVED** [review]
