### PR TITLE
samples: fix dts missing in some NXP platforms

### LINKED ISSUE #85444: samples: accel_trig: mimxrt1040_evk: twr_ke18f: trigger mode will cause build error
**Describe the bug**

accel_trig build failure due the enable trigger mode. as the trigger gpio need rework board, and is disabled by dts by default.  

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?
 - mimxrt1040_evk
 - twr_ke18f
 - What have you tried to diagnose or workaround this issue?
 - code analysis
 - Is this a regression? If yes, have you been able to "git bisect" it to a
   specific commit?

```
d40eed43953550333d9b265358c85b5dd2d590a6 is the first bad commit
commit d40eed43953550333d9b265358c85b5dd2d590a6
Author: Hake Huang <hake.huang@oss.nxp.com>
Date:   Thu Dec 12 17:01:03 2024 +0800

    samples: sensor: enable sensor trigger

    1. enable sensor trigger.
    2. add a fixture for cases, as some platform need
       special rework.

    Signed-off-by: Hake Huang <hake.huang@oss.nxp.com>

```

**To Reproduce**

```
scripts/twister -p mimxrt1040_evk -T samples/sensor/accel_trig
```

**Expected behavior**

build pass

**Impact**

CI

**Logs and console output**

```
/home/jenkins/agent/workspace/zephyr_downstream_build_daily/zephyr/include/zephyr/device.h:96:41: error: '__device_dts_ord_DT_N_S_soc_S_i2c_403f8000_S_fxls8974_18_P_int2_gpios_IDX_0_PH_ORD' undeclared here (not in a function) 96 | #define DEVICE_NAME_GET(dev_id) _CONCAT(__device_, dev_id) | ^~~~~~~~~ /home/jenkins/agent/workspace/zephyr_downstream_build_daily/zephyr/include/zephyr/sys/util_internal.h:72:26: note: in definition of macro '__DEBRACKET' 72 | #define __DEBRACKET(...) __VA_ARGS__ | ^~~~~~~~~~~ /home/jenkins/agent/workspace/zephyr_downstream_build_daily/zephyr/include
```

**Environment (please complete the following information):**

 - OS: (e.g. Linux, MacOS, Windows)
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used: nxp-v4.0.0-12248-g638154ac8a5e

### PR DESCRIPTION
**Pull request by hakehuang**
fix the dts missed properties, as those need board rework.
also fix a naming issue in magn_trig fixture.

fixes: #85444

### CODE REVIEW

**Comment by hakehuang** [comment]
@erwango , I update the fixture naming for magn_trig in this pr.

**Review by yperess — DISMISSED** [review]

File: samples/sensor/accel_trig/boards/mimxrt1040_evk.overlay [hunk 1]
```diff
@@ -0,0 +1,5 @@
+&fxls8974 {
```
Comment (MaureenHelm) [inline samples/sensor/accel_trig/boards/mimxrt1040_evk.overlay:1]: New files need license/copyright headers

**Review by MaureenHelm — CHANGES_REQUESTED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Review by kartben — APPROVED** [review]
