### PR TITLE
manifest: mcuboot: include fixes for encrypted images and legacy RSA fields

### LINKED ISSUE #107149: regression: sysbuild with encrypted image fails to build
### Describe the bug

In v4.3.0 this build succeeds:
```
west build -b reel_board samples/hello_world --sysbuild -- -DSB_CONFIG_BOOTLOADER_MCUBOOT=y -DSB_CONFIG_BOOT_ENCRYPTION=y
```

In v4.4.0-rc3 it fails to compile with missing `mbedtls/aes.h` header:
```
In file included from /home/aaron/zephyrproject/bootloader/mcuboot/boot/bootutil/include/bootutil/crypto/aes_ctr.h:21,
                 from /home/aaron/zephyrproject/bootloader/mcuboot/boot/bootutil/include/bootutil/enc_key.h:33,
                 from /home/aaron/zephyrproject/bootloader/mcuboot/boot/bootutil/src/image_validate.c:54:
/home/aaron/zephyrproject/bootloader/mcuboot/boot/bootutil/include/bootutil/crypto/aes_ctr_mbedtls.h:17:10: fatal error: mbedtls/aes.h: No such file or directory
   17 | #include <mbedtls/aes.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
```

git bisect shows commit 66ee2d2304eea0c1fa4508763f0b978d6681cea0 where it fails to build, but that was for an unrelated header file that may have been fixed.

### Regression

- [x] This is a regression.

### Steps to reproduce

west build -b reel_board samples/hello_world --sysbuild -- -DSB_CONFIG_BOOTLOADER_MCUBOOT=y -DSB_CONFIG_BOOT_ENCRYPTION=y

### Relevant log output

```shell

```

### Impact

Functional Limitation – Some features not working as expected, but system usable.

### Environment

v4.4.0-rc3
sdk 1.0.0

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by valeriosetti**
- Do not access "ver" field in the RSA context structure because this has been removed from TF-PSA-Crypto.
- Add PSA_WANT for AES and CTR in order to support encrypted images.

Resolves #107149

### CODE REVIEW

File: modules/mbedtls/legacy_support.cmake [hunk 1]
```diff
@@ -33,6 +34,15 @@ if(CONFIG_MBEDTLS_DECLARE_PRIVATE_IDENTIFIERS)
...
 endif()
 
+if(CONFIG_MCUBOOT)
+  set(MBEDTLS_BUILTIN_SRC_PATH "${ZEPHYR_TF_PSA_CRYPTO_MODULE_DIR}/drivers/builtin/src")
+  set(legacy_headers
+    ${MBEDTLS_BUILTIN_SRC_PATH}/rsa_alt_helpers.h
+  )
+  file(COPY ${legacy_headers} DESTINATION ${CMAKE_BINARY_DIR}/legacy-mbedtls-headers/)
+  # target_include_directories() on "legacy-mbedtls-headers/" is already called above.
+endif()
```
Comment (tomi-font) [inline modules/mbedtls/legacy_support.cmake]: Put this inside `if(CONFIG_MBEDTLS_DECLARE_PRIVATE_IDENTIFIERS)` for clarity?

**Review by tomi-font — DISMISSED** [review]

File: modules/mbedtls/legacy_support.cmake (hunk 1 above)
Comment (valeriosetti) [reply modules/mbedtls/legacy_support.cmake]: Sure. Done ;)

**Review by tomi-font — DISMISSED** [review]

**Review by d3zd3z — APPROVED** [review]

**Review by nordicjm — APPROVED** [review]
