### ISSUE TITLE
 build failure of tests/subsys/llext with fvp_baser_aemv8r_aarch32_smp

### ISSUE THREAD

**Issue by FRASTM** [zephyrproject-rtos/zephyr#66382]
**Describe the bug**
Building the tests/subsys/llext  for the fvp_baser_aemv8r_aarch32_smp  target

` $ west build -p always -b fvp_baser_aemv8r_aarch32_smp tests/subsys/llext`

fails with 
```
$ZEPHYR_BASE/subsys/llext/llext.c: In function 'llext_link':
$ZEPHYR_BASE/subsys/llext/llext.c:784:25: warning: implicit declaration of function 'arch_dcache_flush_range'; did you mean 'arch_icache_flush_range'? [-Wimplicit-function-declaration]
  784 |                         arch_dcache_flush_range(ext->mem[i], ext->mem_size[i]);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~
      |                         arch_icache_flush_range

```

With that target, the #define CONFIG_CACHE_MANAGEMENT 1

This could be a regression coming from commit 173217753098d6b46cf3d510d0bda5c3dd2b51a8  of the PR https://github.com/zephyrproject-rtos/zephyr/pull/66144

**Impact**
CI failure

**Environment (please complete the following information):**
 - OS: (e.g. Linux, MacOS, Windows) ubuntu
 - Toolchain (e.g Zephyr SDK, ...)  SDK 0.16.3
 - Commit SHA b6d9ed095d7bc395be602072db2679d201735113

**Comment by teburd** [comment]
@pillo79 please take a look, might need some ifdefry or an empty default implementation for a weak symbol to deal with this.

**Comment by pillo79** [comment]
Thanks for the heads-up! It was actually the opposite :sweat_smile:: I used an arch-specific function while there was a globally defined equivalent mandated by the Cache API.
The linked PR fixes this and automatically defines `CACHE_MANAGEMENT` when appropriate.
